[stdlib] Use ephemeral string for substring comparison
swiftlang/swift pull request #10009
Opened 2017-05-31 21:25 UTC by airspeedswift

To avoid unnecessary copies. Also makes StringProtocol comparable and implements comparisons generically.

2017-05-31 21:26 UTC, airspeedswift commented
@swift-ci please test

2017-05-31 21:26 UTC, airspeedswift commented
@swift-ci please smoke benchmark

2017-05-31 21:40 UTC, moiseev approved these changes
LGTM

2017-05-31 21:41 UTC, moiseev commented
@swift-ci Please Test Source Compatibility

2017-05-31 22:32 UTC, airspeedswift commented
Oops, defining heterogenous `==` doesn't get us `!=` for free. Nor the other operators like `<=`, `>` etc.

2017-05-31 22:36 UTC, airspeedswift commented
Have fixed `!=` but I guess we'll have to define all of the other comparison operators as well.

2017-05-31 22:37 UTC, airspeedswift commented
@swift-ci please test

2017-05-31 22:49 UTC, moiseev commented
@airspeedswift if we had a `ComparableTo<T>`, then the derived operators could be possible in an extension.

2017-05-31 23:03 UTC, airspeedswift commented
Gah and skin tone emoji aren't working right on our Linux version of ICU so I need to adjust the test.

2017-05-31 23:07 UTC, airspeedswift commented
@swift-ci please test

2017-05-31 23:49 UTC, airspeedswift commented
@swift-ci please test

2017-06-01 12:24 UTC, dabrahams requested changes
If there are interesting speedups to be observed here it's most likely only through the `Equatable` and `Comparable` conformances, e.g.  `arrayOfStrings.index(of: someString)`.  You might want to make sure those cases are checked in the benchmarks

2017-06-01 12:24 UTC, dabrahams commented on stdlib/public/core/Substring.swift.gyb
> +  public static func ==<S: StringProtocol>(lhs: Self, rhs: S) -> Bool {
`R` or `RHS` would probably be a better generic parameter name.  There are enough `S`'s flying around here already

2017-06-01 14:30 UTC, airspeedswift commented
@swift-ci please smoke test

2017-06-01 19:41 UTC, airspeedswift commented
@swift-ci please smoke benchmark

2017-06-01 19:41 UTC, airspeedswift commented
@swift-ci please smoke test

2017-06-01 21:04 UTC, airspeedswift commented
@swift-ci please smoke test

2017-06-01 21:53 UTC, airspeedswift commented
@swift-ci please smoke benchmark

2017-06-03 01:22 UTC, airspeedswift commented
@swift-ci please smoke benchmark

2017-06-03 01:22 UTC, airspeedswift commented
@swift-ci please test

2017-06-03 18:20 UTC, merged