[NFC] Decompose function input types
swiftlang/swift pull request #10264
Opened 2017-06-14 22:18 UTC by CodaFi

Prepares the AST for future work to eliminate `getInput()` and perform function type argument matching in a less ad-hoc manner.

2017-06-14 22:19 UTC, CodaFi commented
@swift-ci please test

2017-06-15 03:03 UTC, CodaFi commented
@swift-ci please test macOS platform

2017-06-15 04:50 UTC, CodaFi commented
@swift-ci please test macOS platform

2017-06-15 06:03 UTC, CodaFi commented
@swift-ci please test macOS platform

2017-06-15 06:05 UTC, DougGregor requested changes

2017-06-15 06:05 UTC, DougGregor commented on include/swift/AST/Types.h
> +  bool HasDefaultArgument = false;
I commented on this on your other PR that builds on this... `HasDefaultArgument` really shouldn't be in the canonicalization. I don't think we can hoist `CallArgParam` up to the type system like this.

2017-06-15 06:05 UTC, DougGregor commented on include/swift/AST/Types.h
> +  const ArrayRef<CallArgParam> Input;
As noted before, we should use tail allocation to store the parameters and save ourselves the pointer/indirection.

2017-06-15 06:09 UTC, CodaFi commented on include/swift/AST/Types.h
> +  bool HasDefaultArgument = false;
We may need it for argument matching on overloads.

2017-06-15 06:17 UTC, CodaFi commented on include/swift/AST/Types.h
> +  const ArrayRef<CallArgParam> Input;
`llvm::TrailingObjects` requires this class be `final`.  I can manually tail-allocate if you still want it.

2017-06-15 06:21 UTC, DougGregor commented on include/swift/AST/Types.h
> +  bool HasDefaultArgument = false;
It doesn't belong in the type, though, and we don't want it to look like it has meaning there. I think `CallArgParam` needs to stay where it is, and we can introduce a `AnyFunctionType::Param` (or similar) that only captures what's actually in the type system.

2017-06-15 06:30 UTC, DougGregor commented on include/swift/AST/Types.h
> +  const ArrayRef<CallArgParam> Input;
Yeah, you'd need to do the `TrailingObjects` thing on the subclasses

2017-06-15 18:29 UTC, CodaFi commented
@swift-ci please test

2017-06-15 18:29 UTC, CodaFi commented
@swift-ci please test

2017-06-15 21:03 UTC, DougGregor approved these changes
I have minor comments, but this is looking great.

2017-06-15 21:03 UTC, DougGregor commented on include/swift/AST/Types.h
> +class alignas(AnyFunctionType::Param) FunctionType final :
But... fixing the alignment of `FunctionType` doesn't help the trailing objects be properly aligned. You don't need this `alignas` change.

2017-06-15 21:03 UTC, DougGregor commented on include/swift/AST/Types.h
> +  unsigned NumParams;
I guess this doesn't fit into `AnyFunctionTypeBitfields`, eh? ;)

2017-06-15 21:03 UTC, DougGregor commented on include/swift/AST/Types.h
> +  unsigned NumParams;
Sink `NumParams` down into `AnyFunctionType`?

2017-06-15 21:05 UTC, CodaFi commented on include/swift/AST/Types.h
> +class alignas(AnyFunctionType::Param) FunctionType final :
Same for `GenericFunctionType`?

2017-06-15 21:06 UTC, DougGregor commented on include/swift/AST/Types.h
> +class alignas(AnyFunctionType::Param) FunctionType final :
Right.

2017-06-15 21:11 UTC, CodaFi commented on include/swift/AST/Types.h
> +  unsigned NumParams;
Encode it in a pointer union and you've got a deal.

2017-06-15 21:11 UTC, CodaFi commented on include/swift/AST/Types.h
> +  unsigned NumParams;
👍

2017-06-15 21:14 UTC, CodaFi commented
@swift-ci please smoke test

2017-06-15 21:14 UTC, CodaFi commented
@swift-ci please smoke test

2017-06-15 21:33 UTC, CodaFi commented
⛵️

2017-06-15 21:33 UTC, merged