Let CodingKey inherit CustomStringConvertible for better debugging
swiftlang/swift pull request #10350
Opened 2017-06-17 06:00 UTC by inamiy

```swift
struct MyStruct: Codable {
    let test: String
}

let json = "{}".data(using: .utf8)!

do {
    let decoder = JSONDecoder()
    let decoded = try decoder.decode(MyStruct.self, from: json)
    print(decoded)
}
catch {
    print(error)
}
```

### Result

```
keyNotFound(CodableDemo.MyStruct.(CodingKeys in _CCD964A2735AA22BDC9F8350D8585760).test, Swift.DecodingError.Context(codingPath: [Optional(CodableDemo.MyStruct.(CodingKeys in _CCD964A2735AA22BDC9F8350D8585760).test)], debugDescription: "Key not found when expecting non-optional type String for coding key \"test\""))
```

Current `DecodingError` and `EncodingError` is hard to read when printing to the console, so I think `protocol CodingKey` should inherit `CustomStringConvertible` for better debugging.

2017-06-17 06:11 UTC, inamiy commented
@swift-ci please test

2017-07-14 20:03 UTC, itaiferber requested changes
Thanks for putting this together! If we're going to do this for debugging purposes, I think it would be helpful to conform to `CustomDebugStringConvertible` as well (which should definitely also display the `intValue`, even if it's `nil`).

2017-07-14 20:03 UTC, itaiferber commented on stdlib/public/core/Codable.swift
> +        return stringValue
If this has an `intValue` too, we should be printing that out as well.

2017-07-14 20:03 UTC, itaiferber commented on stdlib/public/core/Codable.swift
> +    public var description: String {
Please add a doc comment describing this (something like "A textual representation of this key." should suffice).

2017-07-16 03:47 UTC, inamiy commented on stdlib/public/core/Codable.swift
> +    public var description: String {
Added in 33582e6.

2017-07-16 03:50 UTC, inamiy commented on stdlib/public/core/Codable.swift
> +        return stringValue
Improved description in 33582e6 and 98ed5f9, e.g. `MyCodingKey(stringValue: "someKey", intValue: nil)`

2017-07-16 22:22 UTC, itaiferber approved these changes
Looks good to me! I'd just say that you can shorten the method for doing string interpolation in `description`, but looks good otherwise.

2017-07-16 22:22 UTC, itaiferber commented on stdlib/public/core/Codable.swift
> +        return "\(String(describing: type(of: self)))(stringValue: \"\(stringValue)\", intValue: \(intValue))"
You can just use `\(type(of: self))` instead of `\(String(describing: type(of: self)))`

2017-07-17 00:41 UTC, itaiferber commented on stdlib/public/core/Codable.swift
> +        return "\(String(describing: type(of: self)))(stringValue: \"\(stringValue)\", intValue: \(intValue))"
(After you change this, BTW, I will test and merge)

2017-07-17 03:14 UTC, inamiy commented on stdlib/public/core/Codable.swift
> +        return "\(String(describing: type(of: self)))(stringValue: \"\(stringValue)\", intValue: \(intValue))"
That's simpler! I fixed in e017508 :)

2017-07-17 03:49 UTC, itaiferber commented
@swift-ci Please test and merge

2017-07-20 21:11 UTC, milseman commented
@itaiferber it doesn't seem the merge took. Do you want to merge this?

2017-07-20 22:19 UTC, merged

2017-07-20 22:20 UTC, itaiferber commented
@milseman Thanks for letting me know!

2017-07-21 01:43 UTC, inamiy commented
Thanks for merge 😄

2017-07-21 17:43 UTC, jrose-apple commented
I'm not sure it makes sense for these to be CustomStringConvertible this way. CustomDebugStringConvertible makes sense, but CustomStringConvertible is the sort of thing you'd put into an interpolation. I'd expect just the `stringValue`, probably.

The fact that there's not an obvious right answer might mean this should be taken to swift-evolution.

2017-07-21 17:45 UTC, itaiferber commented
@jrose-apple This hasn't made its way to `swift-4.0-branch` yet, so we can tweak this and turn that off for now.