Fix a linked-list bug with the exclusivity runtime when accesses are not strictly nested
swiftlang/swift pull request #10452
Opened 2017-06-21 18:51 UTC by rjmccall

2017-06-21 18:51 UTC, rjmccall commented
@swift-ci Please test and merge.

2017-06-21 19:10 UTC, gottesmm commented
Hmmm... is it possible to write a unit test for this?

2017-06-21 19:10 UTC, gottesmm commented
Sorry read the commit stat wrong! Sorry for the noise!

2017-06-21 19:55 UTC, rjmccall commented
Actually, I can do much better than that as a unit test.

2017-06-21 19:56 UTC, rjmccall commented
@swift-ci Please test

2017-06-21 20:25 UTC, atrick approved these changes
👍

2017-06-21 20:30 UTC, atrick requested changes
Just these two typos...

2017-06-21 20:30 UTC, atrick commented on unittests/runtime/Exclusivity.cpp
> +    for (unsigned i = 0; i != n; ++i) begin(i);
`i != N`

2017-06-21 20:30 UTC, atrick commented on unittests/runtime/Exclusivity.cpp
> +    for (unsigned i = 0; i != n; ++i) end(i);
`i != N`

2017-06-21 20:39 UTC, rjmccall commented
Hazards of lazily shooting revisions off for the bots to handle.

2017-06-21 20:40 UTC, rjmccall commented
@swift-ci Please test.

2017-06-21 23:05 UTC, rjmccall commented
@swift-ci Please test.

2017-06-21 23:44 UTC, atrick approved these changes

2017-06-22 00:31 UTC, rjmccall commented
@swift-ci Please test OS X.

2017-06-22 04:10 UTC, merged

2017-06-22 06:24 UTC, atrick reviewed
👍 and🥇 for CCC.