[NFC] Reduce SIL's reliance on FunctionType::getInput
swiftlang/swift pull request #10568
Opened 2017-06-25 00:12 UTC by CodaFi

2017-06-25 00:13 UTC, CodaFi commented
@swift-ci please test and merge

2017-06-25 04:01 UTC, CodaFi commented
@swift-ci please smoke test

2017-06-26 17:43 UTC, slavapestov requested changes

2017-06-26 17:43 UTC, slavapestov commented on lib/AST/Type.cpp
> +void AnyFunctionType::substParams(const SubstitutionMap &substitutions,
I don't think this is necessary

2017-06-26 17:43 UTC, slavapestov commented on lib/SILGen/SILGenType.cpp
> +    reqtOrigTy->substParams(reqtSubMap, input);
Why not just reqtOrigTy->substGenericArgs(reqtSubMap)?

2017-06-26 17:43 UTC, slavapestov commented on lib/SILGen/SILGenType.cpp
> +    reqtOrigTy->substParams(reqtSubs, input,
Ditto

2017-07-11 22:10 UTC, CodaFi commented
#10889 and John's changes make this patch pretty useless.

2017-07-11 22:10 UTC, closed without merging