[gardening] Silence compiler warnings [NFC]
swiftlang/swift pull request #10785
Opened 2017-07-06 05:06 UTC by xwu

This PR focuses on some low-hanging fruit in terms of silencing compiler warnings. Specifically:

* One use of `swap(_:_:)` is replaced with `swapAt(_:_:)` to satisfy exclusivity rules.
* Four calls to `NSDecimal{Add|Subtract|Multiply|Divide}(_:_:_:_:)` are wrapped in `withUnsafeMutablePointer` to satisfy exclusivity rules.
* Two unused local variables are deleted (in `Data` and `StringCore`).
* Two arithmetic expressions are rewritten so that the inferred type of integer literals is such that operations are homogeneous, avoiding warnings about deprecated `Strideable` overloads.

2017-07-06 05:10 UTC, xwu commented on stdlib/public/core/Character.swift
> +    let minBitWidth = type(of: bits).bitWidth - bits.leadingZeroBitCount
As of SE-0104, `nonzeroBitCount` is now the name for popcount, so the name of this local variable is potentially confusing; I've renamed to aid comprehension.

2017-07-06 05:12 UTC, CodaFi commented on stdlib/public/SDK/Foundation/Decimal.swift
> +      return Decimal(_exponent: self._exponent, _length: self._length, _isNegative: 0, _isCompact: self._isCompact, _reserved: 0, _mantissa: self._mantissa)
Please (partially) restore the whitespace here.

2017-07-06 23:58 UTC, phausler reviewed
The Foundation overlay changes look good to me. The remainder should still be reviewed.

2017-07-06 23:58 UTC, phausler commented on stdlib/public/SDK/Foundation/Decimal.swift
> +      withUnsafeMutablePointer(to: &lhs) {
Thanks for taking care of these, they have been a thorn for a while now and possibly were causing some bugs.

2017-07-07 01:19 UTC, xwu commented
/cc @dabrahams for stdlib parts

2017-07-10 18:43 UTC, xwu commented
Sorry to ping again, @dabrahams, but would you mind reviewing the stdlib parts so that this can get merged? (I don’t have permissions to request reviewers.)

2017-07-10 18:58 UTC, dabrahams requested changes
Looks good; just a niggle

2017-07-10 18:58 UTC, dabrahams commented on stdlib/public/core/Character.swift
> +      _bitCount: UInt8(16 * Swift.max(1, (minBitWidth + 15) / 16))
If this can be done with a coercion instead of an `init()` that can trap, I'd prefer it.

2017-07-10 20:56 UTC, xwu commented on stdlib/public/core/Character.swift
> +      _bitCount: UInt8(16 * Swift.max(1, (minBitWidth + 15) / 16))
@dabrahams My preference too, but afaict not possible here. The problem isn’t the literals but the bit width, which is of type Int and needs to be converted and therefore may trap (unless you prefer a truncating conversion here).

2017-07-10 21:19 UTC, dabrahams commented on stdlib/public/core/Character.swift
> +      _bitCount: UInt8(16 * Swift.max(1, (minBitWidth + 15) / 16))
If you can prove to yourself that ordinary construction wouldn't have trapped, a truncating conversion is better.  We don't want to incur needless overheads in low-level code.

2017-07-10 22:05 UTC, xwu commented on stdlib/public/core/Character.swift
> +      _bitCount: UInt8(16 * Swift.max(1, (minBitWidth + 15) / 16))
You're right. Done.

2017-07-10 22:05 UTC, xwu commented
Ready to go, I hope. Thanks all.

2017-07-10 22:19 UTC, xwu commented
@phausler FYI, wrapping in `withUnsafeMutablePointer` results in the previously implicitly discardable result from `NSDecimal*` operations causing warnings; I have silenced that new warning with the requisite `_ =`.

2017-07-10 22:21 UTC, phausler commented
yea we were swallowing the failures there; that perhaps was a mistake.

2017-07-10 22:22 UTC, dabrahams approved these changes

2017-07-10 22:29 UTC, xwu commented
One day, maybe for Swift 5, I look forward to a holistic re-appraisal of Swift's floating point error handling mechanisms. There basically isn't one, as far as I'm aware, when it comes to `Float` and `Double`, so it's par for the course to discard these on `Decimal` as well, for now. But one day...

2017-07-11 16:28 UTC, CodaFi commented
@swift-ci please test

2017-07-11 16:28 UTC, CodaFi commented
@swift-ci please test

2017-07-12 03:34 UTC, xwu commented
Can I get a merge?

2017-07-12 06:13 UTC, dabrahams commented
Thanks @xwu!

2017-07-12 06:13 UTC, merged