Fix String.UTF8View.Index's conversion init
swiftlang/swift pull request #10971
Opened 2017-07-14 19:33 UTC by an0

String.UTF8View.Index's conversion init should check whether sourcePosition is already a utf8 index first. Otherwise it may return nil for a valid utf8 sourcePosition.

2017-07-14 19:46 UTC, an0 commented
I found this bug while reading code to understand SE-0180(https://twitter.com/an0/status/884524680123748352). Even now I still have some questions that I hope stdlib core members can help me with:

- On one hand, I believe SE-0180 makes string index universal: one can use any kind of index on any string view and it will just works because the necessary conversion will be done on the fly. If it is true then why still offer index conversion methods and initializers?
- On the other hand, the existence of index conversion methods and initializers makes me think that index conversion is still needed on the public API surface. If it is true then the loss of individual string index types caused by SE-0180 makes things less safe than before because the type safety while using index is gone.

These 2 thoughts are conflicting in my mind for the last week. Can someone help clear my mind? Thanks in advance.

2017-07-14 20:45 UTC, milseman commented
CC @dabrahams

2017-07-14 20:49 UTC, dabrahams commented
@swift-ci Please test

2017-07-14 20:53 UTC, dabrahams requested changes
Thank you for your contribution! It just needs a test in the test suite that would fail before this change is made

2017-07-14 21:15 UTC, dabrahams commented
@an0 There are two reasons to keep those APIs for Swift 4:

1. One still needs a way to detect whether an index is on, e.g., a Unicode scalar boundary.
2. The right APIs for doing \#1 above, and/or adjusting an index to be on a boundary in a given view, have not been designed yet 😄

2017-07-14 21:35 UTC, an0 commented
@dabrahams Thanks, that'll resolve my confusion.

Is it possible to improve the design of these API so that users won't be misled, just like I am, to think that manually conversion is still needed for using index on a different view? For example, for your 1st point, I suppose a pubic `isOnUnicodeScalarBoundary` method will be better than judging from the return value of conversion init. Just my 2 cents:p

2017-07-14 21:46 UTC, dabrahams commented
@an0 Yes, I agree that the right API design will prevent confusion.  The current one clearly does not.  

(I hope you noticed the changes requested in my review)

2017-07-14 21:53 UTC, an0 commented
@dabrahams could you point me to the right file to add this test?

2017-07-14 22:12 UTC, dabrahams commented
@an0 validation-test/stdlib/StringViews.swift seems like a good candidate.

2017-07-14 22:13 UTC, xwu commented on stdlib/public/core/StringUTF8.swift
> +        self.init(encodedOffset: sourcePosition.encodedOffset, transcodedOffset: sourcePosition._transcodedOffset, sourcePosition._cache)
Drive-by nit: this file uses two-space indents and 80-character lines; please re-indent and wrap :)

2017-07-15 17:18 UTC, an0 commented on stdlib/public/core/StringUTF8.swift
> +        self.init(encodedOffset: sourcePosition.encodedOffset, transcodedOffset: sourcePosition._transcodedOffset, sourcePosition._cache)
Thanks. I used Xcode to edit this single file. I am now using Emacs to fix it :p.

2017-07-15 17:36 UTC, an0 commented
@dabrahams thanks, tests are added.

2017-07-16 13:57 UTC, dabrahams approved these changes

2017-07-16 13:57 UTC, dabrahams commented
@swift-ci Please test

2017-07-16 13:58 UTC, dabrahams commented
@swift-ci Please test

2017-08-14 17:30 UTC, milseman commented
@dabrahams I think this PR might of slipped through the cracks. Do you still like this change as much today as a month ago?

2017-08-14 17:57 UTC, dabrahams commented
@milseman Unless you can add just the validation test part of this patch, and have the test pass without the other part, absolutely!

2017-08-14 21:59 UTC, merged