redundant load elimination for @in_guaranteed-only funcs
swiftlang/swift pull request #11040
Opened 2017-07-18 19:23 UTC by weissi

This adds _Redundant Load Elimination_ (RLE) across functions that only have `@in_guaranteed` parameters (which are read-only for the callee).

 - https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20170717/004934.html

Resolves [SR-5403](https://bugs.swift.org/browse/SR-5403).

2017-07-18 19:59 UTC, gottesmm commented
This needs FileCheck tests. Put them in ./tests/SILOptimizer/redundant_load_elim.sil.

2017-07-18 19:59 UTC, gottesmm commented
For information about FileCheck:

http://llvm.org/docs/CommandGuide/FileCheck.html

2017-07-18 20:08 UTC, eeckstein requested changes
Code changes LGTM.
But you have to add tests. I suggest that you add a test case in test/SILOptimizer/mem-behavior.sil.
And IMO it also makes sense to add an end-to-end test which checks that RLE really does its job.
Actually, it would also be nice to add test.swift from SR-5403 and check if the retain-release pair is really eliminated.

2017-07-18 20:08 UTC, eeckstein commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
>    } else {
nitpick: you can the 'else' with the following 'if' in one line to save one indentation level:
  } else if (...) {

2017-07-19 15:49 UTC, weissi commented
@gottesmm / @eeckstein Thanks very much for your help. I think I have addressed all your comments now.

2017-07-19 15:49 UTC, weissi commented
@swift-ci please test

2017-07-19 16:29 UTC, eeckstein commented
Looks good!
One more thing, which I missed on my first review: you can relax the condition. Instead of requiring that _all_ arguments must be an in_guaranteed of V, it's sufficient to have only _one_ such argument. in_guaranteed means that the callee promises not to modify that argument, even not through any potential aliases.

2017-07-19 16:32 UTC, eeckstein commented on test/SILOptimizer/mem-behavior.sil
> +  store %value to %0 : $*Int
For the purpose of this test you can omit these 3 lines

2017-07-19 16:32 UTC, eeckstein commented on test/SILOptimizer/mem-behavior.sil
> +  %r2 = apply %f_sink(%value_again) : $@convention(thin) (Int) -> ()
Also this 3 lines are not needed for this test

2017-07-19 16:38 UTC, eeckstein requested changes
A few more comments.

2017-07-19 16:38 UTC, eeckstein commented on test/SILOptimizer/redundant_load_elim.sil
> +sil @test_rle_in_guaranteed_entry : $@convention(thin) (@in Int) -> () {
A CHECK-LABEL is missing here

2017-07-19 16:38 UTC, eeckstein commented on test/SILOptimizer/mem-behavior.sil
> +// CHECK-NEXT:    %0 = argument of bb0 : $*Int                    // users: %6, %5, %3
nitpick: it's not needed to include the '// users:...' in the check expression

2017-07-19 16:38 UTC, eeckstein commented on test/SILOptimizer/redundant_load_elim.sil
> +  %r2 = apply %f_sink(%value_again) : $@convention(thin) (Int) -> ()
you should check that the apply argument is the 'struct $Int...' instruction.
You can do this by checking the struct-instructions with '[[VAL:%.*]] = struct...'

2017-07-20 12:59 UTC, weissi commented on test/SILOptimizer/mem-behavior.sil
> +// CHECK-NEXT:    %0 = argument of bb0 : $*Int                    // users: %6, %5, %3
thanks, fixed

2017-07-20 13:03 UTC, weissi commented on test/SILOptimizer/mem-behavior.sil
> +  %r2 = apply %f_sink(%value_again) : $@convention(thin) (Int) -> ()
thanks, fixed

2017-07-20 13:03 UTC, weissi commented on test/SILOptimizer/mem-behavior.sil
> +  store %value to %0 : $*Int
thanks, fixed

2017-07-20 13:05 UTC, weissi commented on test/SILOptimizer/redundant_load_elim.sil
> +sil @test_rle_in_guaranteed_entry : $@convention(thin) (@in Int) -> () {
thanks, fixed

2017-07-20 13:17 UTC, weissi commented on test/SILOptimizer/redundant_load_elim.sil
> +  %r2 = apply %f_sink(%value_again) : $@convention(thin) (Int) -> ()
oh yes, that makes a lot of sense, fixed

2017-07-20 14:56 UTC, weissi commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
> +  if (any_of(enumerate(AI->getArgumentOperands()),
@eeckstein so I think there's a bug here: it seems that I can't take the indices from `AI->getArgumentOperands()` and use them here `AI->getSubstCalleeType()->getParameters()[op.Index]`.

After this change this showed up whilst compiling the stdlib as 

```
Assertion failed: (Index < Length && "Invalid index!"), function operator[], file /Users/johannes/devel/llvm/include/llvm/ADT/ArrayRef.h, line 233.
0  swift                    0x000000010afecdc8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift                    0x000000010afebd26 llvm::sys::RunSignalHandlers() + 86
2  swift                    0x000000010afed38e SignalHandler(int) + 366
3  libsystem_platform.dylib 0x00007fff6e8d8f5a _sigtramp + 26
4  libsystem_platform.dylib 0x0000000100000008 _sigtramp + 2440196296
5  libsystem_c.dylib        0x00007fff6e703cea abort + 127
6  libsystem_c.dylib        0x00007fff6e6cbd40 basename_r + 0
7  swift                    0x00000001086ecf90 swift::SILVisitor<(anonymous namespace)::MemoryBehaviorVisitor, swift::SILInstruction::MemoryBehavior>::visit(swift::ValueBase*) + 7872
```

In other words it seems that there's not a 1:1 match of `AI->getSubstCalleeType()->getParameters()` and `AI->getArgumentOperands()`. Can you confirm that and what's the right way to go from an ApplyInst 'operand' to a parameter?

2017-07-20 16:12 UTC, eeckstein commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
> +  if (any_of(enumerate(AI->getArgumentOperands()),
Hm, I don't see anything obviously wrong here. Can you run the compiler in the debugger and dump the function and the apply instruction and op.Index?

2017-07-20 16:40 UTC, eeckstein commented on test/SILOptimizer/redundant_load_elim.sil
> +  // CHECK: [[VAL:%.*]] = struct $Int
that's not what I meant: you should put this at line 1204 and check for apply ([[VAL]]) here. You can find examples of this pattern in other functions in this test file.

2017-07-20 17:56 UTC, weissi commented on test/SILOptimizer/redundant_load_elim.sil
> +  // CHECK: [[VAL:%.*]] = struct $Int
@eeckstein 

 - `op.Index = 1`
 - `AI->...->getNumParams` = 1
 - `V` =   `%1 = argument of bb0 : $*AnyIterator<τ_0_0>    // user: %3`
 - `*AI` =  `%8 = apply %7<AnyIterator<τ_0_0>>(%0, %2) : $@convention(method) <τ_0_0 where τ_0_0 : Sequence, τ_0_0 == τ_0_0.Iterator> (@in_guaranteed τ_0_0) -> @out τ_0_0`

2017-07-20 17:58 UTC, weissi commented on test/SILOptimizer/redundant_load_elim.sil
> +  // CHECK: [[VAL:%.*]] = struct $Int
is it maybe the `@out` ?

2017-07-20 18:11 UTC, weissi commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
> +  if (any_of(enumerate(AI->getArgumentOperands()),
@eeckstein 

 - `op.Index = 1`
 - `AI->...->getNumParams` = 1
 - `V` =   `%1 = argument of bb0 : $*AnyIterator<τ_0_0>    // user: %3`
 - `*AI` =  `%8 = apply %7<AnyIterator<τ_0_0>>(%0, %2) : $@convention(method) <τ_0_0 where τ_0_0 : Sequence, τ_0_0 == τ_0_0.Iterator> (@in_guaranteed τ_0_0) -> @out τ_0_0`

is it maybe the `@out` getting its storage passed as an argument?

2017-07-20 18:30 UTC, eeckstein commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
> +  if (any_of(enumerate(AI->getArgumentOperands()),
Sorry, I didn't realize that this is not the right way to get the parameter convention. The SILFunctionType::getParameters() don't take the indirect results into account.
The correct way is to the the SILFunctionConventions with getSubstCalleeConv().
Then use getSILArgumentConvention(op.Index)

2017-07-21 13:07 UTC, weissi commented on test/SILOptimizer/redundant_load_elim.sil
> +  // CHECK: [[VAL:%.*]] = struct $Int
thanks, fixing that. Didn't quite appreciate how powerful this is.

2017-07-21 13:07 UTC, weissi commented on lib/SILOptimizer/Analysis/MemoryBehavior.cpp
> +  if (any_of(enumerate(AI->getArgumentOperands()),
thanks very much, that makes a lot of sense. Just compiling the fix 💯

2017-07-21 14:31 UTC, weissi commented
@swift-ci please test

2017-07-21 15:30 UTC, weissi commented
@swift-ci please test

2017-07-24 15:34 UTC, weissi commented
@swift-ci please test

2017-07-24 17:21 UTC, weissi commented
@eeckstein I think I finally addressed it all. Sorry about bringing the for loop back, I couldn't get it to compile on Linux with GCC's STL 👎

2017-07-24 17:23 UTC, weissi commented
@swift-ci please test

2017-07-24 19:49 UTC, eeckstein approved these changes

2017-07-24 19:50 UTC, eeckstein commented
@swift-ci Please smoke benchmark

2017-07-25 15:50 UTC, merged

2017-07-29 23:44 UTC, palimondo commented
I'm curious as to why this change had no visible effect on the benchmarks? The 2 improvements and 2 regressions reported above look like noise as to me. 
CC @eeckstein @dabrahams

2017-07-31 01:15 UTC, eeckstein commented
It seems that we don't have any benchmarks where this optimization can kick in. Most likely because we inline in most cases in performance critical code (i.e. in loops).

2017-07-31 01:36 UTC, palimondo commented
Don’t we need a benchmark for this? I have assumed that all performance optimizations should be accompanied by corresponding benchmarks. CC @dabrahams

2017-08-01 01:25 UTC, eeckstein commented
Not necessarily. IMO, for small things like this, a filecheck test is good enough to make sure that we don't regress.