Added sys/xattr.h to glibc modulemap
swiftlang/swift pull request #11117
Opened 2017-07-22 12:43 UTC by andybest

This adds sys/xattr.h to the glibc modulemap for Linux. This is needed to implement one of the last missing features for NSString in corelibs-foundation.

2017-07-22 18:02 UTC, compnerd commented on stdlib/public/Platform/glibc.modulemap.gyb
> +        header "${GLIBC_ARCH_INCLUDE_PATH}/sys/xattr.h"
Hmm, I don't see this include available for me.  Are you sure that this shouldn't be `${GLIBC_INCLUDE_PATH}/sys/xattr.h`?

2017-07-23 13:36 UTC, andybest commented on stdlib/public/Platform/glibc.modulemap.gyb
> +        header "${GLIBC_ARCH_INCLUDE_PATH}/sys/xattr.h"
Ahh, yes, you're right- wrong variable. My mistake. Looking at it, this would probably be better to go under the posix module anyway

2017-07-23 13:45 UTC, andybest commented
Moved it out of the sys module to posix.xattr and used the correct variable

2017-07-23 19:17 UTC, harlanhaskins commented
Would you mind adding a test that uses an xattr API on Linux?

2017-07-23 21:10 UTC, compnerd commented
@swift-ci please test

Should just pass, but, let's make sure that it can create the module on the buildbots.

2017-07-23 23:16 UTC, CodaFi requested changes
Blocking this on Harlan's review so we don't accidentally merge this

>Would you mind adding a test that uses an xattr API on Linux?

2017-07-23 23:16 UTC, CodaFi commented
@swift-ci please test Linux platform

2017-07-24 05:58 UTC, CodaFi commented
> /home/buildnode/jenkins/workspace/swift-PR-Linux@2/branch-master/buildbot_linux/swift-linux-x86_64/lib/swift/linux/x86_64/glibc.modulemap:430:16: error: header '///usr/include/sys/xattr.h' not found

2017-07-24 09:51 UTC, andybest commented
My original commit was correct- it needs to use ${GLIBC_ARCH_INCLUDE_PATH}, since xattr.h is located under /usr/include/x86_64-linux-gnu/sys on a 64 bit ubuntu. Changing it back and adding some tests.

2019-10-21 13:37 UTC, closed without merging