[stdlib] DoubleWidth refinements
swiftlang/swift pull request #11161
Opened 2017-07-25 04:05 UTC by natecook1000

This adds tests for masking bit shifts to `DoubleWidth` and addresses the feedback from @dabrahams here: https://github.com/apple/swift/pull/10131

2017-07-25 04:05 UTC, natecook1000 commented
@swift-ci Please test

2017-07-25 20:07 UTC, natecook1000 commented
@swift-ci Please test OS X platform

2017-07-26 16:55 UTC, natecook1000 commented
@swift-ci Please test OS X platform

2017-07-27 01:05 UTC, moiseev commented
Can we please wait till https://github.com/apple/swift/pull/11203 lands? Please?

2017-07-27 01:08 UTC, moiseev commented on stdlib/public/core/DoubleWidth.swift.gyb
> +    let t = Base.bitWidth > rhs._storage.low
`t` for temporary?

2017-07-27 01:11 UTC, moiseev requested changes
LGTM, apart from the `t` variable name. Maybe `newLow` and `newHigh` would read better?

2017-08-02 19:55 UTC, natecook1000 commented
@swift-ci Please smoke test

2017-08-02 20:04 UTC, moiseev approved these changes
:shipit:

2017-08-02 21:23 UTC, merged