Replicate NSAffineTransform logic for rotation to AffineTransform
swiftlang/swift pull request #11335
Opened 2017-08-03 21:42 UTC by phausler

AffineTransform was modified previously to alter the rotation logic, this unfortunately did not account for composition of matrices. This change replicates the logic in NSAffineTransform for rotation.

This addresses:
rdar://problem/33510242

2017-08-03 21:42 UTC, phausler commented
@swift-ci please test

2017-08-03 21:59 UTC, michael-lehew commented
lgtm

2017-08-03 22:27 UTC, jrose-apple commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> +// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
These header changes look wrong.

2017-08-03 23:15 UTC, itaiferber commented
Unrelated build failure on Linux, it looks like

2017-08-03 23:18 UTC, itaiferber reviewed
The content itself is good (although it's sort of lost in a sea of whitespace changes). The only comments I have are about that whitespace, where I think we've lost readability, which when it comes to diagrams, is important, IIRC. This is none-blocking for the fix, though.

2017-08-03 23:18 UTC, itaiferber commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> +     [ m11_T  m12_T  0 ] [ m11_M  m12_M  0 ]
I think we're losing readability on these comments, unfortunately; doesn't affect the code, of course, but this is a regression of sorts

2017-08-03 23:18 UTC, itaiferber commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> -               lhs.tX == rhs.tX && lhs.tY == rhs.tY
I think the indentation here should stay as-is

2017-08-03 23:18 UTC, itaiferber commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> +     [ -sin α   cos α  0 ]
Indentation here (and above)

2017-08-03 23:32 UTC, phausler commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> -               lhs.tX == rhs.tX && lhs.tY == rhs.tY
The indentation changes are from copy/paste from Xcode. Imho all overlay code should be 100% copy paste-able from the swift-corelibs-foundation Xcode project to the Foundation overlay.

2017-08-04 03:15 UTC, michael-lehew commented
I completely agree 

> On Aug 3, 2017, at 4:32 PM, Philippe Hausler <notifications@github.com> wrote:
> 
> @phausler commented on this pull request.
> 
> In stdlib/public/SDK/Foundation/AffineTransform.swift:
> 
> >      public static func ==(lhs: AffineTransform, rhs: AffineTransform) -> Bool {
>          return lhs.m11 == rhs.m11 && lhs.m12 == rhs.m12 &&
> -               lhs.m21 == rhs.m21 && lhs.m22 == rhs.m22 &&
> -               lhs.tX == rhs.tX && lhs.tY == rhs.tY
> The indentation changes are from copy/paste from Xcode. Imho all overlay code should be 100% copy paste-able from the swift-corelibs-foundation Xcode project to the Foundation overlay.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-04 03:45 UTC, xwu commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> +     [ -sin α   cos α  0 ]
Loss of indentation here and above has actual implications for the generated documentation, does it not? I thought that indentation is interpreted as block-level code?

2017-08-04 15:44 UTC, jrose-apple commented on stdlib/public/SDK/Foundation/AffineTransform.swift
> +     [ -sin α   cos α  0 ]
Yep. Copy/paste into an autoindenting environment shouldn't be a be-all, end-all goal because autoindent isn't perfect.

2017-08-04 16:06 UTC, phausler commented
@swift-ci please test

2017-08-04 16:48 UTC, jrose-apple requested changes
Marking as blocked until the indentation-in-doc-comment thing is figured out. (The source code indentation is Foundation's business, but the doc comments are important.)

2017-08-04 16:52 UTC, itaiferber commented
@jrose-apple The doc comments should block this. Documentation isn't generated from Foundation's doc comments.

2017-08-04 16:54 UTC, closed without merging

2017-08-04 17:06 UTC, jrose-apple commented
My understanding was that Quick Help still was, but I could be wrong.