Instrument NominalTypeDecl::lookupDirect
swiftlang/swift pull request #11521
Opened 2017-08-19 03:57 UTC by davidungar

Also implement RecursiveSharedTimer

Add counter and timer to NominalTypeDecl::lookupDirect. Also implement RecursiveSharedTimer.

2017-08-19 03:58 UTC, davidungar commented
@swift-ci Please smoke test

2017-08-21 21:25 UTC, graydon requested changes
Seems reasonable! Stylistic issues only:

  - Use an Optional<SharedTimer> with emplace() and reset(), rather than a separate heap allocation.
  - Use an RAII helper class to adjust the count, so users don't have to manually pair enter()/exit().

2017-08-23 00:51 UTC, gottesmm commented on include/swift/Basic/Timer.h
> +  private:
Private is the default with class.

2017-08-23 00:53 UTC, gottesmm reviewed
Quick drive by comment.

2017-08-23 00:53 UTC, gottesmm commented on include/swift/Basic/Timer.h
> +  // A SharedTimer for recursive routines.
This should be 3 slashes for it to be a doxygen comment ala LLVM style:

https://llvm.org/docs/CodingStandards.html#doxygen-use-in-documentation-comments

2017-08-23 21:51 UTC, davidungar commented
Revised to use better RAII scheme.

2017-08-23 21:56 UTC, davidungar commented
@swift-ci Please smoke test

2017-08-24 17:01 UTC, graydon approved these changes
LGTM thanks!

2017-08-24 17:11 UTC, merged