[4.0] Fix ambiguity between overlay inits and default inits for BNNS structs.
swiftlang/swift pull request #11625
Opened 2017-08-25 21:52 UTC by stephentyrone

Most of these are resolvable by simply switching over to inits without the previously-defaulted arguments, because the default args are all-or-nothing. In one case that doesn't make sense, so instead I've provided a dedicated static func to construct one class of object, and an init that doesn't match the importer-created one for the more common case.

resolves rdar://problem/33880553

[for swift-4.0-branch]
**Explanation:** Some inits in the BNNS overlay are not available due to ambiguity with the importer-created inits.
**Scope:** Local to the Accelerate/vecLib/BNNS module.
**Radar:** 33880553
**Risk:** Low. Only effects BNNS functions, and only really makes functionality available that is currently entirely broken.

2017-08-25 23:12 UTC, moiseev commented
@swift-ci Please test

2017-08-25 23:14 UTC, moiseev requested changes

2017-08-25 23:14 UTC, moiseev commented on test/stdlib/Accelerate.swift
> -// UNSUPPORTED: OS=watchos
This one caused [problems in master](https://github.com/apple/swift/pull/11580).

2017-08-26 00:13 UTC, moiseev approved these changes

2017-08-26 15:27 UTC, stephentyrone commented
@swift-ci Please test

2017-08-28 19:49 UTC, merged