Add OptionSet tests
swiftlang/swift pull request #11683
Opened 2017-08-29 22:27 UTC by lancep

Test our public OptionSet API

This adds validation tests for the public API of OptionSet.

2017-08-29 22:27 UTC, lancep commented
@swift-ci please smoke test

2017-08-29 22:45 UTC, moiseev requested changes
I don't remember whether we have the `SetAlgebra` conformance tests. But it would be nice to add a test for that too.

2017-08-29 22:45 UTC, moiseev commented on validation-test/stdlib/OptionSet.swift
> +  assert(s.rawValue == 32)
Here and everywhere why `assert`?

2017-08-29 22:45 UTC, moiseev commented on validation-test/stdlib/OptionSet.swift
> +  assert(s.rawValue == 32)
`expectEqual` or `expectTrue`.

2017-08-29 22:45 UTC, moiseev commented on validation-test/stdlib/OptionSet.swift
> +  expectEqual(member1, nil)
`expectNil`

2017-08-29 22:45 UTC, moiseev commented on validation-test/stdlib/OptionSet.swift
> +  expectEqual(member2, .monday)
`expectOptionalEqual`

2017-08-29 22:50 UTC, lancep commented
I have a separate bug for the SetAlgebra tests

2017-08-30 01:05 UTC, milseman approved these changes
LGTM

2017-08-30 04:14 UTC, lancep commented
@swift-ci please smoke test

2017-08-30 17:23 UTC, moiseev approved these changes

2017-08-30 17:23 UTC, merged