[CMake] Link static libraries as PUBLIC
swiftlang/swift pull request #11703
Opened 2017-08-31 02:42 UTC by modocache

## Summary

I noticed a curious thing when generating graphviz files based on Swift's CMake: graphs do not show a dependency from swiftDriver to swiftBasic, even though swiftDriver links in swiftBasic.

Using a "standalone" build configuration such as the one I describe in [SR-5778](https://bugs.swift.org/browse/SR-5778), I ran a `cmake --graphviz=` [command](https://gist.github.com/modocache/6f63a3185e54324a708e3c79ec1a9797) in order to generate a graph, as per the CMake documentation [here](https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html). The generated graph did not show a line extending from swiftDriver to swiftBasic, seemingly indicating that there is no dependency between these two libraries.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2F0v203w3p363X2m3c3v/swift-cmake-interface.png?X-CloudApp-Visitor-Id=543005)

In fact, the graph shows no lines pointing to swiftBasic at all, as if no libraries depend upon it.

It turns out that, while swiftDriver [does specify](https://github.com/apple/swift/blob/f2a1ffeb64631348db8d303f15c901376b9a9887/lib/Driver/CMakeLists.txt#L17-L20) `LINK_LIBRARIES swiftBasic` in order to link it in, the libraries themselves
are linked as `INTERFACE`.

[According to the CMake mailing list](https://cmake.org/pipermail/cmake/2016-May/063400.html):

> When A links in B as *INTERFACE*, it is saying that A does not use B in its implementation, but B is used in A's public API.

This does not appear to be the case, however, with swiftDriver. One trivial example would be `swift::Driver::printVersion`, which invokes swiftBasic's `getSwiftFullVersion`.

This commit changes the link keyword to `PUBLIC`, which again according to the mailing list means "that A uses B in its implementation and B is also used in A's public API."

It also means that graphs now show a dependency between libraries; notice that in the graph below, an arrow extends from swiftDriver connecting it to swiftBasic:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0b0S2W2x1v3T2i2q272w/swift-cmake-public.png?X-CloudApp-Visitor-Id=543005)

## Test plan

A clean build and test succeeds: `rm -rf /path/to/build && utils/build-script --test`

---

@jrose-apple, you mentioned someone had recently taken on some responsibilities with Swift CMake, could you point them here for their thoughts?

2017-08-31 02:50 UTC, modocache commented
@swift-ci please test

2017-08-31 03:55 UTC, gottesmm commented
@modocache Can you be sure to do clean tests with this.

@shahmishal Is there any possibility that we can get some sort of ability to force a clean after cmake builds. I am worried that cmake PRs are going to cause problems for other smoke tests.

2017-08-31 04:20 UTC, gottesmm commented
@modocache I think that @jrose-apple was talking about @Rostepher.

2017-08-31 06:02 UTC, shahmishal commented
> @shahmishal Is there any possibility that we can get some sort of ability to force a clean after cmake builds. I am worried that cmake PRs are going to cause problems for other smoke tests.

Yes, I will see if I can add this by end of September.

2017-08-31 16:10 UTC, jrose-apple requested changes
We deliberately don't do this to speed up builds. If you use PUBLIC instead of INTERFACE, each library would have to wait for the previous to finish linking before it could link. Additionally, if CMake actually took you at your word, you'd end up with multiple copies of swiftBasic, right?

On top of this, our intra-compiler dependencies are still pretty messed up. We still have circular dependencies, which leads to having libraries specified multiple times in executable and unit test targets. I'm not sure I believe anything about our dependency graph without dealing with that.

Regardless, these libraries aren't really meant to be treated as standalone entities. Since they're static libraries, INTERFACE is a perfectly good description of how to use them.

cc @llvm-beanz

2017-08-31 18:36 UTC, llvm-beanz commented
@jrose-apple's description is a really accurate and good description of the issue. We do this in LLVM as well. Basically any dependency of a `STATIC_LIBRARY` target should be an `INTERFACE` dependency because on every platform I'm aware of static libraries don't actually link in their dependencies, instead the dependencies are required to be listed on the link line of whatever uses the static library.

It is also worth noting that CMake's graph generation generates the build dependency graph, which is not the same as the code dependency graph. You can have code dependencies (like libSwiftDriver depending on libSwiftBasic) which are not actually build dependencies because ar will not read libSwiftBasic when generating libSwiftDriver.

2017-08-31 19:20 UTC, gottesmm commented
@llvm-beanz @jrose-apple Seems like something that should be written down somewhere. From what I understand @Rostepher is writing something up. @Rostepher, can you add this to your list of things to document?

2017-08-31 19:22 UTC, Rostepher commented
👍

2017-08-31 19:24 UTC, gottesmm commented
Thanks! = ).

2017-08-31 19:41 UTC, modocache commented
Ah OK, interesting, thanks for the info everybody, very educational!

> On top of this, our intra-compiler dependencies are still pretty messed up. We still have circular dependencies, which leads to having libraries specified multiple times in executable and unit test targets. I'm not sure I believe anything about our dependency graph without dealing with that.

@jrose-apple Is there a task for this? At my first glance it seemed like Swift's intra-compiler dependencies look very similar to Clang's. Are they both in need of improvement?

> It is also worth noting that CMake's graph generation generates the build dependency graph, which is not the same as the code dependency graph.

@llvm-beanz That's a really good point, thanks. One bit I'm still not understanding, though: shouldn't the build dependency graph, even when using `INTERFACE`, show a dependency between _something_ and swiftBasic? You mention that "ar will not read libSwiftBasic when generating libSwiftDriver", but wouldn't it read libSwiftBasic when generating the `swift` executable?

2017-08-31 19:56 UTC, jrose-apple commented
> > On top of this, our intra-compiler dependencies are still pretty messed up. We still have circular dependencies, which leads to having libraries specified multiple times in executable and unit test targets. I'm not sure I believe anything about our dependency graph without dealing with that.
>
> @jrose-apple Is there a task for this? At my first glance it seemed like Swift's intra-compiler dependencies look very similar to Clang's. Are they both in need of improvement?

[SR-1240](https://bugs.swift.org/browse/SR-1240) covers upward dependencies in swiftAST, but I don't know if we have anything for other libraries (or how bad a shape other libraries are in). I think the process is something like

1. Remove `#include`s that are layering violations.
2. Make the dependencies of static libraries sensible.
3. Make the dependencies of the tools, dylibs, and unit tests sensible (and order-independent).
4. Figure out some way to enforce it. I'm not sure if CMake already checks for *explicitly* making circular dependencies even in INTERFACE requirements, but we'd need some check on the built libraries to really get it to stick.

2017-08-31 21:23 UTC, llvm-beanz commented
@modocache, yes, you should see swiftc depending on libSwiftBasic. I do see that in my generated ninja file lib/libSwiftBasic.a is a dependency of the link action for bin/swift. Unfortunately because CMake gets weird about handling interface dependencies I'm not really sure if it does the right thing or not in generating the graphviz dependency graphs. This was part of why I wrote my own implementation of generating graphviz in CMake... I still need to see if I can find those patches...

2017-09-01 03:31 UTC, modocache commented
> I do see that in my generated ninja file lib/libSwiftBasic.a is a dependency of the link action for bin/swift.

Oh cool, yeah, I took a look and I see that as well.

> Unfortunately because CMake gets weird about handling interface dependencies I'm not really sure if it does the right thing or not in generating the graphviz dependency graphs. This was part of why I wrote my own implementation of generating graphviz in CMake... I still need to see if I can find those patches...

Yeah, I'll chalk this one up to some quirks in CMake graphviz, I guess. Please do send those patches my way if you can, I'd love to see them!

In any case it looks like this change isn't correct, so I'll close this pull request.

2017-09-01 03:31 UTC, closed without merging

2017-09-12 05:01 UTC, modocache commented
For anyone curious, here are the patches mentioned above: https://twitter.com/thegreatbeanz/status/903654270695653376