Updated argument parsing code to use a new OnOffAction with Enable an…
swiftlang/swift pull request #12005
Opened 2017-09-19 19:51 UTC by Rostepher

# Purpose

This PR resolves issue [SR-5911](https://bugs.swift.org/browse/SR-5911). My previous PR #11952 changed the internal 'destinations' for all the `--skip-build-*` and `--skip-test-*` flags from the form `skip_build_*` and `skip_test_*` to the affirmative `build_*` and `test_*`. When swapping those states I failed to account for the more advanced optional boolean behavior on each of these skip flags. It is possible for many flags to accept an optional boolean state to toggle them on or off manually, with skip flags it can be rather confusing since `--skip-build-benchmarks True` means that we should not build benchmarks. Before this fix the optional boolean was being directly set on these new inverted destinations, thus `--skip-build-benchmarks True` was setting the destination `build_benchmarks` to `True` rather than the expected `False`.

In addition to fixing the erroneous behavior I've also taken the liberty to revamp the testing suite again making a more clear distinction between flags that accept optional booleans, those that only toggle the state `True` or `False` and those that store constant values. The test suite now covers all these cases and has more strict testing for their edge cases.

A small note for reviewers, there's a lot of noise in the testing suite dealing with parsing arguments. To accurately test that each flag accepts the expected argument values and acts accordingly it was necessary to be able to parse flags without applying the defaults. Thus there's now the methods `parse_args` and `parse_default_args` on the main test case class.

2017-09-19 19:52 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 20:21 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 20:22 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:08 UTC, Rostepher commented
@gottesmm Would you mind giving this a quick once-over before I merge?

2017-09-19 21:09 UTC, Rostepher commented on utils/build_swift/driver_arguments.py
> +        print('not testing')
Whoops, left in a print statement. I'll remove that.

2017-09-19 21:27 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:27 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:28 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:29 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:35 UTC, gottesmm commented
@Rostepher give me a little bit. I am in some meetings today = (.

2017-09-19 21:41 UTC, Rostepher commented
@gottesmm No problem, just let me know when you've had a chance to look at it. Thanks!

2017-09-19 21:41 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-19 21:42 UTC, Rostepher commented
@swift-ci please smoke test os x

2017-09-19 21:43 UTC, Rostepher commented
@swift-ci please smoke test OS X

2017-09-19 23:54 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-20 00:02 UTC, gottesmm requested changes
A few remarks. Also can you split out the sorting/etc into a different commit. This should be just about fixing the specific bug. If you want to change the order/layout of things please do that in a different commit so that I can review only the important things via the diff.

2017-09-20 00:02 UTC, gottesmm commented on utils/build_swift/tests/expected_options.py
> +    pass
Question. Is pass supposed to be on this line according to flake8? I thought it was supposed to be right after the `"""`

2017-09-20 00:02 UTC, gottesmm commented on utils/build_swift/tests/expected_options.py
> +        kwargs['dest'] = kwargs.get('dest', None)
I still hate this. Can you just do this:

```
if 'dest' not in kwargs:
    kwargs['dest'] = None
```

2017-09-20 00:02 UTC, gottesmm commented on utils/build_swift/tests/expected_options.py
> +        kwargs['dest'] = kwargs.get('dest', None)
Same here.

2017-09-20 00:02 UTC, gottesmm commented on utils/build_swift/tests/expected_options.py
> +class EnableOption(_BaseOption):
Can you leave any shuffling to a different commit. This is going to be difficult to review.

2017-09-20 00:02 UTC, gottesmm commented
With my review, I stopped due to the moving around of code. Please fix that and then I will relook.

2017-09-26 19:06 UTC, shahmishal commented
@swift-ci test

2017-09-26 19:14 UTC, shahmishal commented
@swift-ci test Linux

2017-09-26 21:56 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-26 21:56 UTC, Rostepher commented
@swift-ci please test

2017-09-26 23:22 UTC, Rostepher commented
@swift-ci please smoke test

2017-09-27 18:08 UTC, Rostepher commented
@gottesmm Would you mind taking a look over this fix again. I've removed the test changes for now. I'll add those in a follow-up PR, I'd rather get this merged first to avoid any unexpected regressions.

2017-09-29 18:32 UTC, lplarson commented
LGTM

2017-09-29 19:06 UTC, merged