stdlib: fix build for non-ObjC targets
swiftlang/swift pull request #12350
Opened 2017-10-09 22:26 UTC by compnerd

When building the stdlib for Windows, we would see the following error:

  swift/stdlib/public/core/RuntimeFunctionCounters.swift:95:19: error: '(UnsafeRawPointer, Int64) -> Void' is not representable in Objective-C, so it cannot be used with '@convention(c)'
     @convention(c) (_ object: UnsafeRawPointer, _ functionId: Int64) -> Void
                    ^

Add a case around it to permit building the stdlib.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2017-10-09 22:26 UTC, compnerd commented
@swift-ci please test

2017-10-09 22:27 UTC, compnerd commented
CC: @jrose-apple

2017-10-09 22:48 UTC, jrose-apple requested changes
This is not correct; C and Swift have different calling conventions, and we really do want to support a C function here. I'm curious why UnsafeRawPointer, Int64, and Void aren't being treated as valid C types on Windows, though.

2017-10-09 22:56 UTC, compnerd commented
Yeah, they do have different conventions.  I think that we may want to alter the diagnostic emitted to make it more useful at some point.

```
error: '(UnsafeRawPointer, Int64) -> Void' is not representable in Objective-C, so it cannot be used with '@convention(c)'
```

That should be equivalent to `void ()(void *, long long int)` on Windows I believe.  Could it be the `long long` throwing something in the ClangImporter for a loop?

2017-10-09 23:26 UTC, jrose-apple commented
That code doesn't go through the importer at all; it's all in ASTContext::getForeignRepresentationInfo. Maybe CLongLong isn't defined correctly on Windows yet?

2017-10-10 04:33 UTC, compnerd commented
The types are in the stdlib ... so, I'm not sure about that.

```
// %swift -frontend -target x86_64-unknown-linux-gnu -parse-stdlib -S -o - %s
// %swift -frontend -target x86_64-unknown-windows-msvc -parse-stdlib -S -o - %s

public typealias Void = ()

public struct S {
}

public struct T {
  public typealias U = @convention(c) (_: S) -> Void
}
```

error: '(UnsafeRawPointer) -> Void' (aka '(UnsafeRawPointer) -> ()') is not representable in Objective-C, so it cannot be used with '@convention(c)'

2017-10-10 16:11 UTC, jrose-apple commented
That one's correct. Swift structs can't be used in `@convention(c)` functions.

The C types are indeed in the stdlib, but some of them need to be platform-specific. (Did you change CLong to be Int32 on Windows instead of Int64?) I wouldn't expect that to be the issue, though.

2017-10-10 16:27 UTC, compnerd commented
@jrose-apple hmm, but aren't `UnsafeRawPointer` and `Int64` technically structs?  They should be convertible obviously.  The mapping for `CLong` and `CLongLong` occurs in the `ASTContext` right?  That uses the size rather than the name AFAICT.  Am I looking at the wrong area?

2017-10-10 16:32 UTC, jrose-apple commented
Yes, they're all structs, but some structs are special-cased.

2017-10-10 16:34 UTC, jrose-apple commented
Whoops, I may have pointed you to the wrong place. `getForeignRepresentable` in Type.cpp is also relevant.

2017-10-10 18:16 UTC, jckarter commented
Some theories: If none of the `C*` defines correspond to `Int64` on Windows, there's a possibility we don't recognize it as representable in C. There's also the possibility of circularity issues when checking these traits in the standard library in particular; if we happen to be validating decls in a "wrong" order or not validating some of the `Int*` decls in a TU, we possibly wouldn't recognize them as being C compatible.

2017-10-10 18:59 UTC, compnerd commented
@jckarter well, I think you may be on to something.  I was just looking at the definitions of `CLong` and `CLongLong` and this gets confusing.

`CLong` -> `Int32`
`CLongLong` -> `Int`

`Int` is assumed to be `Int64`.

Mapping `CLongLong` to `Int64` doesn't work, as we no longer have the backwards mapping from `Int` to a `C*` type, which is needed for the stdlib build at least.

I'll double check if it is actually the `Int64` which is failing to be mapped.

2017-10-10 19:18 UTC, jckarter commented
It's possible that other code in the standard library will have to change to support an LLP64 platform. I'm not sure how pervasively we assume `long` is pointer-sized.

2017-10-10 19:19 UTC, jckarter commented
We may have to introduce and bless new typedefs for `CIntPtr`/`CUIntPtr`.

2017-10-10 19:26 UTC, compnerd commented
@swift-ci please test

2017-10-10 20:21 UTC, jrose-apple commented
For this specific case, we could also bless Int and UInt directly. CLongLong should probably just be Int64, not Int, even on LLP64 platforms.

2017-10-10 20:52 UTC, jckarter commented
We could try making `CLongLong` always be `Int64`. I wonder how much that breaks.

2017-10-10 20:53 UTC, compnerd commented
@jckarter @jrose-apple that triggers an assertion because its unable to map Int back to a clang type.  But, I agree, that would be much clearer.

2017-10-10 22:04 UTC, compnerd commented
@swift-ci please test linux platform

2017-10-10 23:34 UTC, jrose-apple approved these changes

2017-10-10 23:34 UTC, jrose-apple commented
Using `Int` here seems like an acceptable hackaround for now. Good thought.

2017-10-11 00:25 UTC, merged

2017-10-11 00:28 UTC, jrose-apple commented
By the way, if you don't plan to investigate the rest of it now, would you mind filing a bug so we get back to it later?

2017-10-11 03:30 UTC, compnerd commented
Yeah, I think that I want to try to get the Windows builds solid first.  I'll file a SR.