Cleaning up OSize and exposing more knobs for code size tuning
swiftlang/swift pull request #12636
Opened 2017-10-26 21:06 UTC by rajbarik

Improved Osize: 
(1) Use MinSize instead of OptForSize LLVM annotation; 
(2) Expose UnrollThreshold and Inline_Benefit_Reduction_Factor in the command line for automatic tuning of inlining and unrolling for code size; 
(3) Modify PassManager to enable Osize specific passes instead of current approach that checks for Osize inside individual passes

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2017-10-26 21:32 UTC, aschwaighofer requested changes
@rajbarik Thank you for improvements.

Can you rebase to a recent master?
Can you split the following functionality into two commits:

(1) Use MinSize instead of OptForSize LLVM annotation;
(2) Expose UnrollThreshold and Inline_Benefit_Reduction_Factor in the command line for automatic tuning of inlining and unrolling for code size;

We intend to add a function level attribute to enable "-O" like optimization when compiling at -Osize for a function. This would not work with a statically modified pass pipeline.

(3) Modify PassManager to enable Osize specific passes instead of current approach that checks for Osize inside individual passes


Code conventions:
http://llvm.org/docs/CodingStandards.html

A good way to following the without much effort is to use clang-format (it has bindings for emacs/vim/git)

https://github.com/apple/swift-clang/tree/stable/tools/clang-format

2017-10-26 21:32 UTC, aschwaighofer commented on lib/SILOptimizer/LoopTransforms/LoopUnroll.cpp
> +//static const uint64_t SILLoopUnrollThreshold = 250;
Remove this line?

2017-10-26 21:32 UTC, aschwaighofer commented on lib/SILOptimizer/LoopTransforms/LoopUnroll.cpp
> +  const uint64_t SILLoopUnrollThreshold = Loop->getBlocks().empty() ? 0 : (Loop->getBlocks())[0]->getParent()->getModule().getOptions().UnrollThreshold;
break the line at 80 chars.

2017-10-26 21:32 UTC, aschwaighofer commented on include/swift/AST/SILOptions.h
> +  /// Controls the aggressiveness of the performance inliner for Osize
Can you add a dot at the end of the line.

2017-10-26 21:32 UTC, aschwaighofer commented on include/swift/AST/SILOptions.h
> +  /// Controls the aggressiveness of the loop unroller
Can you add a dot at the end of the line.

2017-10-27 01:41 UTC, rajbarik commented
I created this: https://github.com/apple/swift/pull/12649 for part 1. Not sure if you still need part 2 that disables the optimizations at pass-pipeline level. Let me know.

2018-11-27 18:18 UTC, closed without merging