[WIP/Don't merge][Verifier] Verify we're loading initialized variables.
swiftlang/swift pull request #12670
Opened 2017-10-29 01:13 UTC by dcci

Initial step to fix: https://bugs.swift.org/browse/SR-6230

2017-10-29 20:30 UTC, gottesmm commented
I can't get into reviewing more of this (my schedule is tight). But this is a significantly more complex problem than just this small patch to even make the stdlib pass this. For instance you definitely need to handle out parameters. Before this can land, we would need to make sure that the stdlib/et al and a bunch of other things can build with this enabled.

IMO really you want a separate verifier separate from the SILVerifier ala the SILOwnershipVerifier since I imagine this will take a bit of code.

I am going to leave the real review of this though to @eeckstein.

2017-10-29 21:50 UTC, dcci commented
Yes, that's why it's a WIP. FWIW, I think this may get very complicated very fast.
It already breaks swift code when building the standard library, as you hinted.

```
SIL verification failed: possibly uninitialized load: !AllocInstSet.count(LI->getOperand())
Verifying instruction:
     %2 = load %1 : $*_Stderr                     // user: %4
->   return %2 : $_Stderr                         // id: %4
In function:
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %2, %3
  %2 = load %1 : $*_Stderr                        // user: %4
  dealloc_stack %1 : $*_Stderr                    // id: %3
  return %2 : $_Stderr                            // id: %4
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'
```

I posted this mainly so that this doesn't get lost. If the rule is that uninitialized values can't be loaded, and it wants to be enforced, it seems there's a non-zero amount of work to be done to even pass basic testcases as building swift itself, not talking about the large amount of codee out there. Unsure whether this is the correct time to bite the bullet.

2017-10-30 16:45 UTC, eeckstein requested changes

2017-10-30 16:45 UTC, eeckstein commented on lib/SIL/SILVerifier.cpp
> +        if (auto *SI = dyn_cast<StoreInst>(&I)) {
You don't need to handle StoreInst here because it's covered by the default (else) case below.

2017-10-30 16:45 UTC, eeckstein commented on lib/SIL/SILVerifier.cpp
> +        else {
Please add  a comment here that you conservatively assume that all uses of the alloc_stack either store to the location or let the address escape. Which means that the alloc_stack location is potentially initialized.

2017-10-30 16:45 UTC, eeckstein commented on lib/SIL/SILVerifier.cpp
> +    llvm::SmallSet<SILValue, 4> AllocInstSet;
I would rather make this a SmallSet<AllocStackInst, 4>

2017-10-30 16:45 UTC, eeckstein commented on lib/SIL/SILVerifier.cpp
> +  void verifyLoadInitialization(SILFunction *F) {
Please add a comment on the function which says what it does, e.g. catch trivial cases of not initialized alloc_stack locations.

2017-10-31 21:28 UTC, dcci commented
@eeckstein while I make the changes, here's the log of `-print-after-all` for that function, as you wanted to know which optimization generated the pattern.

```
*** SIL module before Guaranteed Passes transformation (0) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_box ${ var _Stderr }, var, name "self" // user: %2
  %2 = mark_uninitialized [rootself] %1 : ${ var _Stderr } // users: %5, %3
  %3 = project_box %2 : ${ var _Stderr }, 0       // user: %4
  %4 = load [trivial] %3 : $*_Stderr              // user: %6
  destroy_value %2 : ${ var _Stderr }             // id: %5
  return %4 : $_Stderr                            // id: %6
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL module after Guaranteed Passes Capture Promotion to Eliminate Escaping Boxes (capture-promotion) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_box ${ var _Stderr }, var, name "self" // user: %2
  %2 = mark_uninitialized [rootself] %1 : ${ var _Stderr } // users: %5, %3
  %3 = project_box %2 : ${ var _Stderr }, 0       // user: %4
  %4 = load [trivial] %3 : $*_Stderr              // user: %6
  destroy_value %2 : ${ var _Stderr }             // id: %5
  return %4 : $_Stderr                            // id: %6
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL module after Guaranteed Passes Access Enforcement Selection (access-enforcement-selection) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_box ${ var _Stderr }, var, name "self" // user: %2
  %2 = mark_uninitialized [rootself] %1 : ${ var _Stderr } // users: %5, %3
  %3 = project_box %2 : ${ var _Stderr }, 0       // user: %4
  %4 = load [trivial] %3 : $*_Stderr              // user: %6
  destroy_value %2 : ${ var _Stderr }             // id: %5
  return %4 : $_Stderr                            // id: %6
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL function after Guaranteed Passes Stack Promotion of Box Objects (allocbox-to-stack) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %4, %2
  %2 = mark_uninitialized [rootself] %1 : $*_Stderr // user: %3
  %3 = load [trivial] %2 : $*_Stderr              // user: %5
  dealloc_stack %1 : $*_Stderr                    // id: %4
  return %3 : $_Stderr                            // id: %5
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL module after Guaranteed Passes Prune Control Flow at No-Return Calls Using SIL unreachable (noreturn-folding) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %4, %2
  %2 = mark_uninitialized [rootself] %1 : $*_Stderr // user: %3
  %3 = load [trivial] %2 : $*_Stderr              // user: %5
  dealloc_stack %1 : $*_Stderr                    // id: %4
  return %3 : $_Stderr                            // id: %5
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL function after Guaranteed Passes Definite Initialization for Diagnostics (definite-init) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %2, %3
  %2 = load [trivial] %1 : $*_Stderr              // user: %4
  dealloc_stack %1 : $*_Stderr                    // id: %3
  return %2 : $_Stderr                            // id: %4
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

*** SIL module after Guaranteed Passes Eliminate Ownership Annotation of SIL (ownership-model-eliminator) (#1) ***
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %2, %3
  %2 = load %1 : $*_Stderr                        // user: %4
  dealloc_stack %1 : $*_Stderr                    // id: %3
  return %2 : $_Stderr                            // id: %4
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'

SIL verification failed: possibly uninitialized load: !AllocInstSet.count(LI->getOperand())
Verifying instruction:
     %2 = load %1 : $*_Stderr                     // user: %4
->   return %2 : $_Stderr                         // id: %4
In function:
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_stack $_Stderr, var, name "self"     // users: %2, %3
  %2 = load %1 : $*_Stderr                        // user: %4
  dealloc_stack %1 : $*_Stderr                    // id: %3
  return %2 : $_Stderr                            // id: %4
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'
```

2017-11-01 02:46 UTC, eeckstein commented
Oh, I see.
This is the initializer of _Stderr, which is an empty struct, i.e. it has no fields.
Only in this case we can end up with this code pattern.
I suggest you handle this special case of an empty struct/enum/tuple in the verifier.
The other possibility is to change SILGen to not emit this pattern at all for empty types.

2017-11-01 02:54 UTC, dcci commented
Thank you, @eeckstein. I may consider taking a look at SILGen, just for fun. Where should I look to begin with?

2017-11-01 03:18 UTC, eeckstein commented
I don't know much about silgen. @jckarter may help

2017-11-06 21:16 UTC, dcci commented
@jckarter Joe, thoughts on whether this can/should be fixed inside SILGen?

2017-11-06 21:32 UTC, jckarter commented
Can you be more specific about what you're trying to fix? It isn't clear from either the bug description or the patch here. Mind adding a test case?

2017-11-06 21:51 UTC, dcci commented
@jckarter Sure. The problem, as far as I can tell is that load of uninitialized values is invalid SIL, so I'm trying to add a verifier check to catch violations.

e.g. (test attached to the PR, but probably got lost in the noise)

```
import Builtin
import Swift

sil @patatino : $@convention(thin) (Builtin.Int32) -> Builtin.Int32 {
bb0(%0 : $Builtin.Int32):
  %4 = alloc_stack $Builtin.Int32
  %6 = load %4 : $*Builtin.Int32
  dealloc_stack %4 : $*Builtin.Int32
  return %6 : $Builtin.Int32
}
```

I hit a crash in the verifier when trying to compile the standard library, as stderr contains patterns like this:

```
// _Stderr.init()
sil @_T012SwiftPrivate7_StderrVACycfC : $@convention(method) (@thin _Stderr.Type) -> _Stderr {
bb0(%0 : $@thin _Stderr.Type):
  %1 = alloc_box ${ var _Stderr }, var, name "self" // user: %2
  %2 = mark_uninitialized [rootself] %1 : ${ var _Stderr } // users: %5, %3
  %3 = project_box %2 : ${ var _Stderr }, 0       // user: %4
  %4 = load [trivial] %3 : $*_Stderr              // user: %6
  destroy_value %2 : ${ var _Stderr }             // id: %5
  return %4 : $_Stderr                            // id: %6
} // end sil function '_T012SwiftPrivate7_StderrVACycfC'
```

@eeckstein explained this is because stderr has no fields (as far as I can tell, this is the exact code lowered pre optimizations). An alternative suggested was that of changing SILGen to not emit these patterns which would fail the verifier (as it's technically invalid SIL), and I wondered what were your thoughts/whether this was a good/feasible idea.

Thanks for your time!

2017-11-06 21:53 UTC, dcci commented
When I say "emit these patterns" I actually mean "lower to this sequence of instructions", FWIW.

2017-11-06 21:58 UTC, jckarter commented
For tuples and fragile structs, SIL allows elementwise initialization. Since empty structs have no fields, they can be "elementwise initialized" by doing nothing. The SIL is valid as currently emitted.

2018-07-25 21:03 UTC, closed without merging