[Mangling] Preserve all parameter flags in single parameter function mangling
swiftlang/swift pull request #12742
Opened 2017-11-03 08:11 UTC by xedin

Currently if function has a single parameter we'd skip mangling some of the
parameter flags e.g. __shared, `inout` still works because it's part of the
type itself (currently) but would be broken too if that were to change.

2017-11-03 08:11 UTC, xedin commented
@swift-ci please smoke test

2017-11-03 08:12 UTC, xedin commented
/cc @eeckstein please take a look.

2017-11-03 23:46 UTC, eeckstein requested changes
Can you please also update the Mangling.rst doc?

Otherwise lgtm!

2017-11-03 23:49 UTC, xedin commented
@eeckstein Will do, thanks!

2017-11-04 00:01 UTC, xedin commented
@swift-ci please smoke test and merge

2017-11-04 00:03 UTC, xedin commented
@swift-ci please smoke test and merge

2017-11-04 00:06 UTC, eeckstein approved these changes

2017-11-04 00:58 UTC, merged