[CMake] Localize a build hack
swiftlang/swift pull request #12880
Opened 2017-11-11 20:03 UTC by davezarzycki

The '-Wl,-z,defs' flag is useful, so let's disable it only where needed.

2017-11-11 20:03 UTC, davezarzycki commented
@swift-ci please test

2017-11-12 15:18 UTC, davezarzycki commented
The only failure in the full test was/is the known and unrelated `ModelIO.swift` failure. Let's smoke test this PR to bypass that problem and be merge ready.

@swift-ci please smoke test

2017-11-12 15:21 UTC, davezarzycki commented
@compnerd -- Does this patch look okay with you?

2017-11-13 01:24 UTC, compnerd requested changes
Why do you suspect that this only is an issue for the SwiftRemoteMirror?  I suspect that this breaks the tests too for Windows when cross compiling.  I’d say if you want -z defs, you should do this at a much deeper layer in swift_add_library with ELF style output.

2017-11-13 12:10 UTC, davezarzycki commented
Hi @compnerd – I thoughts and questions:
1) Do we agree that "-Wl,-z,defs" should be avoided as much as possible? As a reminder, it forces the linker to ignore missing definitions/symbols.
2) In my Linux ELF system testing, SwiftRemoteMirror is the only library that "needs" the flag, and I think even that case is fixable.
3) I don't have access to a Windows machine, nor are Windows machines a part of Swift's continuous integration, so any advice that isn't speculative would be helpful. Would you be open to trying this patch out? We can always revert it if Windows needs the flag in more scenarios.
4) At the very least, I'd like to make the top level removal of this flag conditional on platforms that need it. What do you think of this option?

2017-11-13 12:44 UTC, davezarzycki commented
On second thought, I'll just preserve the Windows behavior. Please consider reviewing #12895 instead. Thanks!

2017-11-13 12:44 UTC, closed without merging