Pop _JSONDecoder storage stack when throwing errors
swiftlang/swift pull request #12969
Opened 2017-11-16 18:50 UTC by zintus

`_JSONDecoder` internal state could be corrupted by trying to decode failing nested object. Fix this by ensuring storage stack pop after error throw.

Resolves [SR-6408](https://bugs.swift.org/projects/SR/issues/SR-6408).

2017-11-16 19:22 UTC, itaiferber requested changes
Thanks for putting this together! [SR-6408](https://bugs.swift.org/projects/SR/issues/SR-6408) is related to [SR-6078](https://bugs.swift.org/projects/SR/issues/SR-6078) — I've been meaning to put together the comprehensive fixes here but have not yet had the time. If we're going to fix this, do you mind please also addressing SR-6078 and applying these fixes to `PropertyListEncoder`/`PropertyListDecoder` as well?

Also, we'd want to introduce unit tests to ensure that this does what we think it does, and doesn't regress in the future.

2017-11-17 11:27 UTC, zintus commented
Now SR-6078 should be fixed too.

I didn't invest much time in setting up build/test environment, should work on it more

2019-11-14 19:32 UTC, CodaFi commented
Looks like this was covered by #13879.  If I'm wrong about that, please reopen this and rebase it to fix the merge conflicts.

2019-11-14 19:32 UTC, closed without merging

2019-11-19 10:10 UTC, zintus commented
Should be fixed by #13879, thanks for looking at it.