Batch mode for frontend subsystems 1/N
swiftlang/swift pull request #13413
Opened 2017-12-13 20:27 UTC by graydon

A bunch of work following @davidungar's work but further downstream in the compiler, altering the various subsystems called by FrontendTool (Sema/Serialization/SIL) to accept and work with multiple primary files. Theoretically NFC but see below.

You can't actually _use_ this without disabling a couple assertions upstream that the user only provided one primary, but that's an intentional part of @davidungar's plan :)

Passes swift tests but needs to be accompanied by a matching LLDB change.

There are a couple bits I'd like to see scrutinized in review here, each marked with a comment. The change to lib/SILGen/SILGenExpr.cpp is I _think_ NFC but I'm not 100% sure, and the FIXME-marked bit on line 793 of lib/FrontendTool/FrontendTool.cpp suggests we might have drifted to the point of having redundant logic that can be eliminated.

2017-12-13 23:55 UTC, davidungar reviewed
"notePrimarySourceFile" and its ilk could be more suggestive of multiple primaries. "noteAPrimarySourceFile"? or "noteAnotherPrimarySourceFile"? or "addThisFileToTheSetOfPrimaries"?

2017-12-13 23:58 UTC, davidungar approved these changes
The parts of this I know about--not all that much--look fine to me! Good stuff.

2017-12-14 17:11 UTC, jrose-apple requested changes
This is the wrong way to go. In order to keep supporting incremental builds, we need to keep emitting N swiftmodules, object files, and other auxiliaries when given N primary files as input.

2017-12-14 17:11 UTC, jrose-apple commented on include/swift/Frontend/Frontend.h
> +  void notePrimaryInputBuffer(unsigned BufID);
Naming nitpicks: "record" or "add" feels stronger than "note".

2017-12-14 17:11 UTC, jrose-apple commented on include/swift/Frontend/Frontend.h
> +  bool bufferIDIsAPrimaryInput(unsigned BufID) const {
Naming nitpicks: pulling the "is" up front makes it more obvious at the call site that this is a predicate: `isBufferIDAPrimaryInput`, `isBufferPrimaryInput` or even just `isPrimaryInput`.

2017-12-14 17:11 UTC, jrose-apple commented on include/swift/Subsystems.h
> +  /// Serializes a module and zero or more source files to the given output file.
This isn't right. We still need one swiftmodule per input file, or incremential compilation won't work.

2017-12-14 20:01 UTC, graydon commented
Ah, crumpets. Well good to find out early I guess! @jrose-apple do you think the non-Serialization parts are usable? I.e. the bits related to Sema and SILGen/SILOpt? Or do we need a separate AST ModuleDecl and SILModule per primary as well, if we're going to be emitting a separate .swiftmodule file per primary?

2017-12-14 21:31 UTC, jrose-apple commented
I think our goal was to have a combined AST ModuleDecl, but separate SILModules. That way we still save repeated type-checking work. The tricky bit was dealing with SILGen for "external declarations" i.e. "ClangImporter things that need SILGen"; for now the easiest thing is probably to just SILGen them all into every SIL module.

2017-12-14 21:32 UTC, jrose-apple commented
The frontendy things (the first and third commits) seem pretty much fine. I didn't take a close look at the second or fourth commits.

2017-12-14 21:56 UTC, graydon commented
K, will do. Sorry!

2017-12-19 00:42 UTC, graydon commented
Closing this out and opening new one with simpler / corrected multiplicity approach.

2017-12-19 00:42 UTC, closed without merging