[WIP] [ConstraintSystem] Finish up solver type cache implementation
swiftlang/swift pull request #13664
Opened 2018-01-01 20:29 UTC by xedin

Based on all of the great work @rudkx has done, solver should only apply _final_ types
to the expression tree when the solution is deduced. This patch makes it so and fixes
tests (mostly in IDE code completion) along the way.

2018-01-01 20:31 UTC, xedin commented
@rudkx There is one thing left which is going to fix 2 crashers related to explicit casts - we still use `getCastTypeLoc().setType` in CSGen to set opened generic type.

2018-01-02 08:23 UTC, rudkx commented
@xedin I didn't do any work on `TypeLoc` types yet. That seemed small enough to make it a separate task.

I haven't looked at this for a while, but I believe you also need to clear the type on the Expr when it is cached to ensure that we aren't accidentally reading it in places. That was the real hold up the last time I looked at this.

Can you hold off trying to merge this until I get done with the IUO changes. I suspect I've introduced some new `->getType()` and such that will need to be cleaned up with these changes in place, and I don't want to slow that work down at all.

2018-01-02 18:50 UTC, xedin commented
@rudkx Sure, there is no rush in merging this, just wanted to get it out since tests are fixed. I has planning to take care of `getCastTypeLoc` before merging anyway.

2018-01-07 06:48 UTC, xedin commented
@swift-ci please test

2018-01-07 06:48 UTC, xedin commented
@swift-ci please test source compatibility

2018-02-12 20:19 UTC, xedin commented
/cc @nathawes @benlangmuir

2018-02-13 00:37 UTC, xedin commented
/cc @rudkx

2018-02-13 01:31 UTC, rudkx requested changes
I'd like to have a better understanding of some of the changes and why we see behavioral changes here before we merge anything for this.

2018-02-13 01:31 UTC, rudkx commented on lib/Sema/CSDiag.cpp
> +      type = cs.getType(loc);
Why is this directly calling `loc.getType()` and then only if getting `null` calling `cs.getType(loc)`?

2018-02-13 01:31 UTC, rudkx commented on test/Compatibility/tuple_arguments.swift
> +  var d = (a, b)
It seems like there is something wrong if this is resulting in this type of diagnostic change.

2018-02-13 01:31 UTC, rudkx commented on test/IDE/complete_constructor.swift
> -// EXPLICIT_CONSTRUCTORS_3P-DAG: Decl[FreeFunction]/CurrModule/NotRecommended/TypeRelation[Invalid]: freeFunc()[#Void#]{{; name=.+$}}
So I am wondering how the code completion changes (which I haven't looked at closely) are related to the type cache. I would expect no behavioral changes from making the type checker store types in a different place.

2018-02-13 01:31 UTC, rudkx commented on lib/Sema/CSDiag.cpp
> +      expr->setType(type);
It's non-obvious why this is the right thing to do. This seems like an indication that something that should be reading from the type cache isn't.

2018-02-13 01:31 UTC, rudkx commented on lib/Sema/CSApply.cpp
> +          cs.setExprTypes(closure);
Under what circumstances do we need to do this? We should be type checking these bodies independently. They can refer to captured data, but that data should already have a type, right?

2018-02-13 02:08 UTC, rudkx approved these changes
We had a chance to sync up on this and everything looks okay for now. It definitely moves things forward re: fixing some crashers and no longer writing types all over the place. We still need to go back and clear expression types, etc. to finish this up.

2018-02-13 08:09 UTC, xedin commented
@swift-ci please test

2018-02-13 08:10 UTC, xedin commented
@swift-ci please test source compatibility

2018-02-14 04:26 UTC, xedin commented
@swift-ci please smoke test

2018-02-14 05:43 UTC, merged