Remove IUO nested inside other type from benchmark.
swiftlang/swift pull request #13749
Opened 2018-01-05 03:24 UTC by rudkx

SE-0054 disallowed nesting IUO types within other types. We currently
give a warning for this, but eventually we'll either emit an error or
interpret the '!' as '?' (a plain optional).

Either way, this particular benchmark doesn't test anything different
than the one that uses plain optionals, so we should be able to remove it.

2018-01-05 03:25 UTC, rudkx commented
@swift-ci Please smoke test

2018-01-05 15:33 UTC, eeckstein requested changes
I assume removing this part of the benchmark will affect the execution time. Can you rename the benchmark, e.g. to ArrayOfGenericPOD2, so that we treat it as a different benchmark.

2018-01-05 16:51 UTC, rudkx commented
@eeckstein Is this what you had in mind?

2018-01-05 17:23 UTC, rudkx commented
Oh you probably meant rename the registered string...one moment...

2018-01-05 17:29 UTC, rudkx commented
@eeckstein Okay I updated the name registered for the benchmark and added a comment. If you had something else in mind let me know.

2018-01-06 02:43 UTC, rudkx commented
@eeckstein Ping?

2018-01-06 06:17 UTC, rudkx commented
@swift-ci Please smoke test

2018-01-06 16:28 UTC, eeckstein approved these changes

2018-01-06 18:13 UTC, merged