[Foundation] Add benchmarks for Data APIs
swiftlang/swift pull request #13997
Opened 2018-01-17 23:59 UTC by phausler

This adds a number of benchmarks for Data

2018-01-17 23:59 UTC, phausler commented
@swift-ci please benchmark

2018-01-18 00:05 UTC, phausler commented
@swift-ci please smoke test

2018-01-18 02:54 UTC, xwu commented on benchmark/single-source/DataBenchmarks.swift
> +    BenchmarkInfo(name: "RepalceLargeBuffer", runFunction: run_RepalceLargeBuffer, tags: [.validation, .api, .Data]),
A few typos here with the word "Replace" misspelt.

2018-01-18 02:55 UTC, xwu commented on benchmark/utils/main.swift
> +import DataBenchmarks
Q: don't you also need to invoke `registerBenchmark` below?

2018-01-18 17:07 UTC, phausler commented
@swift-ci please benchmark

2018-01-18 17:07 UTC, phausler commented
@swift-ci please smoke test

2018-02-03 16:03 UTC, airspeedswift requested changes
I'm not sure what the situation is with sub-benchmark suites at the moment (it looks like all the string microbenchmarks that weren't intended to run by default on every PR are running). 

Need to be very careful to tune them to be stable when nothing changes, by doing enough iterations and also checking the min/max doesn't have too wide a variance.

2018-03-14 21:51 UTC, parkera commented
Closing in favor of #15221.

2018-03-14 21:51 UTC, closed without merging