[sil] When expanding aggregate instructions, do so consistently based…
swiftlang/swift pull request #14163
Opened 2018-01-25 19:19 UTC by gottesmm

… off the code-size hueristic.

We were expanding retain_value, release_value properly, but not
copy_addr/destroy_addr. This caused ARC invariants to break resulting in
miscompiles.

rdar://36509461

2018-01-25 19:21 UTC, gottesmm commented
@swift-ci test

2018-01-25 20:02 UTC, shajrawi requested changes
`include/swift/SIL/TypeLowering.h:  static TypeExpansionKind getLoweringStyle(bool shouldExpand) {` is no longer used after this change, can you please remove said function? Otherwise LGTM!

2018-01-25 20:10 UTC, gottesmm commented
**Explanation**: This commit ensures that when we canonicalize aggregate ARC operations on large structs, we do so consistently no matter the ARC operation that is used.
**Scope**: This is an important change since the inconsistent canonicalization can result in the ARC optimizer miscompiling. Additionally, this most likely caused us to lose code-size.
**Radar** (and possibly SR Issue): rdar://36509461
**Risk**: There is low risk to this change since we are just returning to our original consistency and the actual change in codegen is small. The risk to not taking this commit is high due to the possibility of ARC miscompiles.
**Testing**: I wrote compiler tests that validate that we are consistently expanded (or not) aggregate ARC operations.

2018-01-25 20:11 UTC, gottesmm commented
@shajrawi, @eeckstein asked me to make this as small as possible. I would rather just leave it in.

2018-01-25 20:53 UTC, gottesmm commented
Actually, I am going to come up with a test for the actual ARC failure as well for this PR. So I guess I can go through another test cycle.

2018-01-25 21:57 UTC, gottesmm commented
@swift-ci test

2018-01-25 21:57 UTC, gottesmm commented
@swift-ci test

2018-01-25 21:57 UTC, gottesmm commented
@swift-ci test

2018-01-25 21:57 UTC, gottesmm commented
@swift-ci test

2018-01-25 21:58 UTC, gottesmm commented
@swift-ci test

2018-01-25 21:58 UTC, shajrawi approved these changes

2018-01-25 22:00 UTC, gottesmm commented
@swift-ci test

2018-01-25 22:01 UTC, gottesmm commented
@shahmishal Is something wrong here? Or am I being impatient?

2018-01-25 22:01 UTC, gottesmm commented
nm. The bots are being upgraded.

2018-01-26 02:22 UTC, gottesmm commented
@swift-ci test

2018-01-26 02:22 UTC, gottesmm commented
@swift-ci test

2018-01-26 02:22 UTC, gottesmm commented
@swift-ci test

2018-01-26 02:23 UTC, gottesmm commented
@swift-ci test

2018-01-26 02:24 UTC, gottesmm commented
@swift-ci test

2018-01-26 02:26 UTC, shahmishal commented
Please wait for CI to catch up.

2018-01-26 03:30 UTC, gottesmm commented
Sorry for being so impatient Mishal!

2018-01-26 19:35 UTC, merged