Enable -Wall, -Wuninitialized, -Wunreachable-code for building runtime code.
swiftlang/swift pull request #14415
Opened 2018-02-05 21:57 UTC by tkremenek

2018-02-05 21:57 UTC, tkremenek commented
@swift-ci test

2018-02-05 21:58 UTC, jckarter commented
Thanks Ted! We should make sure to tag the `RemoteAST`, `Reflection` and `RemoteMirror` libraries with these flags too.

2018-02-05 22:38 UTC, gparker42 commented
Is #14417 a better place to change this? Does that cover the other libraries that Joe mentioned?

2018-02-05 23:25 UTC, dcci commented on stdlib/public/CMakeLists.txt
> +check_cxx_compiler_flag("-Wunreachable-code" CXX_SUPPORTS_UNINIT_WARNING)
Should this be `-Wuninitialized`?

2018-02-05 23:25 UTC, dcci commented on stdlib/public/CMakeLists.txt
> +  list(APPEND SWIFT_RUNTIME_CORE_CXX_FLAGS "-Wuninitialized")
I think that `-Wall` implies `-Wuninitialized` at least for clang and gcc.

2018-02-05 23:33 UTC, gparker42 requested changes
On hold. We want at most one of #14415 and #14417.

2018-02-06 02:52 UTC, tkremenek commented
I think #14417 is a better place for this.  However, I'd like to do an audit of what warnings are being enabled for various source files to see if anything is being missed.  I'll do that as a separate investigation.

2018-02-06 02:52 UTC, closed without merging