[wip] Bool toggle implementation
swiftlang/swift pull request #14586
Opened 2018-02-13 07:53 UTC by chriseidhof

This pull-request accompanies [SE-0199: Adding `toggle` to `Bool`](https://github.com/apple/swift-evolution/blob/master/proposals/0199-bool-toggle.md)

I don't know how to run the test suite and what the standards are for documentation. I'm happy to improve on the PR if someone with more knowledge can point things out.

2018-02-13 13:41 UTC, xwu commented
@swift-ci Please smoke test

2018-02-13 13:53 UTC, xwu reviewed
You'll need to add `public` :)

Seems like it'd make sense for this to be `_transparent` too.

2018-02-13 16:11 UTC, airspeedswift requested changes

2018-02-13 16:11 UTC, airspeedswift commented on stdlib/public/core/Bool.swift
> +  mutating func toggle() {
Needs to be public

2018-02-13 16:11 UTC, airspeedswift commented on stdlib/public/core/Bool.swift
> +  @_inlineable // FIXME(sil-serialize-all)
I think you can drop the `FIXME(sil-serialize-all)` for this one. It's truly legitimately inlineable.

2018-02-13 17:39 UTC, gottesmm commented
@chriseidhof We have in the docs directory information about the CI and testing. For the CI commands:

https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md

For the testing:

https://github.com/apple/swift/blob/master/docs/Testing.md

If you have any comments/improvements, they are welcome as always = ).

2018-03-08 19:21 UTC, airspeedswift commented
@swift-ci please test

2018-03-16 16:17 UTC, airspeedswift approved these changes

2018-03-16 16:17 UTC, merged

2018-06-05 00:07 UTC, ryanmaxwell commented
why no `func toggled() -> Self`as a pair with `mutating func toggle()`?