Revert "Mark the runtime's reimplementation of fixed_seed_override weak"
swiftlang/swift pull request #14867
Opened 2018-02-27 23:09 UTC by jrose-apple

Reverts apple/swift#14791. Apple policy doesn't allow libraries with weak definitions, so we can't use this solution, at least not unconditionally.

2018-02-27 23:09 UTC, jrose-apple commented
@swift-ci Please smoke test

2018-02-27 23:24 UTC, jckarter requested changes
There's no reason to revert this. The definition has hidden visibility, regardless of whether it ends up in a dylib or statically linked into an executable. Irrespective of that, Apple never internally statically links the Swift runtime, and Apple's internal build policies don't govern third-party builds.

2018-02-28 00:41 UTC, lattner commented
Jordan, why are you doing this?

2018-02-28 00:51 UTC, jrose-apple commented
Joe explained offline how the hidden visibility was sufficient, even for static linking, and that the problems with weak definitions are about dynamic linking in any case.

> Jordan, why are you doing this?

Because I legitimately thought there was a problem that hadn't been addressed. This wasn't a power play; it was not wanting to leave something broken in tree that could be problematic for users of the nightly toolchain.

2018-02-28 00:51 UTC, closed without merging

2018-02-28 01:55 UTC, lattner commented
Sorry for the misunderstanding.  The comment above the declaration was intended to address this possibility for confusion.  If it didn't work, please expand the comment.  Thanks!