utils: remove reference to swiftImageInspectionShared static library
swiftlang/swift pull request #14860
Opened 2018-02-27 19:30 UTC by bob-wilson

Even the name of this library shows that it is not a static library....
The static-stdlib-args.lnk file is generated by the
gen-static-stdlib-link-args script. The previous change for SR-7038
(PR 14772) only fixed the reference in the static-executable-args.lnk file.
rdar://problem/37710244

2018-02-27 19:34 UTC, bob-wilson commented
@swift-ci please test and merge

2018-02-27 19:56 UTC, jckarter commented
Can we add a regression test that attempts to link (and if `executable_test` is available, maybe execute) a statically-linked binary on Linux, so that this is less likely to regress again?

2018-02-27 22:27 UTC, jrose-apple commented
It looks like that's what Driver/static-stdlib-linux.swift is, since it just failed. My next question is how it passed before.

2018-02-28 00:58 UTC, compnerd requested changes
I'm not sure how this is supposed to work.  The swiftImageInspectionShared is what contains the runtime and the rest of the image inspection parts.  If this is being removed, which I'm fine with conceptually, we need to ensure that we do not remove ImageInspectionELF.cpp from the runtime sources.

2018-02-28 01:27 UTC, jrose-apple commented
The static standard library is supposed to be completely static. It doesn't get to link against `.so`s. Or am I missing something?

2018-02-28 18:32 UTC, compnerd commented
@jrose-apple okay, so that is what I would assume too.  However, there was linkage to the shared inspection component.  The way that we currently are handling the static build seems pretty complicated overall.

2018-02-28 18:42 UTC, jrose-apple commented
Who wrote this originally? Was it @jckarter?

2018-02-28 18:42 UTC, bob-wilson commented
I was just looking at this. The "Shared" library is actually built as a static library:

add_swift_library(swiftImageInspectionShared STATIC ....)

2018-02-28 18:48 UTC, jrose-apple commented
/me throws up hands, quits guessing about the problem without looking

2018-02-28 18:48 UTC, bob-wilson commented
I just downloaded the latest dev toolchain for Linux and there is no copy of that library installed. That would explain why we're getting link failures. This might just be a CMake problem.

2018-02-28 18:50 UTC, compnerd commented
@jrose-apple @spevans wrote that originally

2018-02-28 18:58 UTC, compnerd commented
I don't know the reason for the complexity, lets see what breaks on PR#14877.  Perhaps we have evolved enough to avoid a lot of the complexity that necessitated that back when it was introduced?

2018-02-28 18:58 UTC, spevans commented
I think the static linking needs to be reworked as I think it broke when the ELF section changes were reworked. The problem with adding a regression test for it was that it also relied on building a fully static libICU (the one that ships with ubuntu needs -ldl) so a test couldnt be added to reliably test it.
So removing the current broken reference is fine for now.

2018-02-28 18:59 UTC, jckarter commented
It used to be that we needed a different archive for the image inspection part of things because a static library doesn't have access to `libdl`, which is where some of the complexity arose. With @compnerd's changes we use a static constructor, which should work uniformly with or without a dynamic linker available.

2018-02-28 19:30 UTC, bob-wilson commented
See https://github.com/apple/swift/pull/14880. I'm going to close this PR

2018-02-28 19:30 UTC, closed without merging