[Parse] Refactor Lexer to unify logic into Trivia Lexer by using its comapibility
swiftlang/swift pull request #15081
Opened 2018-03-08 18:38 UTC by omochi

This PR refactor Lexer and simplify logic flow.

Currently, Lexer has many behavior variation and it makes logic complex.
There are 6 mode from 3 comment handling x 2 trivia handling.
So we need to care about some lexing logics orthogonality and dependency.

To resolve this, 3 modes without trivia are delegated to `WithTrivia` mode.
So we can stop to consider about `WithoutTrivia` behavior.

To give compatibility for these 3 modes to `WithTrivia` mode,
I add new `WithOnlyLeadingTrivia`.
This mode is almost same as `WithTrivia` except it does not lex trailing trivia.

And to make more stateless code,
I remove `LastCommentBlockStart` and `SeenComment` field.
Trivia information is sufficient to work what these fields did.

I think this PR drastically changes logic from before.
Please review carefully.
I checked that this passes validation-test locally.

2018-03-09 08:07 UTC, rintaro commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
I don't quite understand why this indirection is needed. Could you explain it?

2018-03-09 08:38 UTC, omochi commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
Its need to keep Lexer (outer) itself as its initialized.

For example, Lexer(NoComment, WithoutTrivia) must be always `CommentRetention == NoComment`, `TriviaRetention == WithoutTrivia`, `LeadingTrivia.size() == 0`, and `TrailingTrivia.size() == 0`. Inner Lexer is hided from these constraint.

Making new internal Lexer which has modified configuration from outer and all actually lexing process delegates to it, and we can hide its state from user of outer Lexer.
And internal Lexer implementation can discard consideration about which it is `WithTrivia` or `WithoutTrivia`.

To avoid making internal Lexer, we need more consideration about it.
For example, we need guard branch in `lexTrivia` to prevent store `TriviaPiece` to `LeadingTrivia` or `TrailingTrivia`.
In `ReturnAsToken` mode, need to clear `LeadingTrivia` and `TrailingTrivia` at end of `lexImpl` if we remove `LastCommentBlockStart` and `SeenComment` and unify to trivia lexing. In this PR, instead of these fields, I build `CommentLength` in `formToken` from trivias information.

In result of my PR, 
such a state based branching is very few.

- First direct or indirect branch in `initialize`.
- `isKeepingComment()` related branch. Its change comments to token or trivia, so Its need really another control flow.
- `WithOnlyLeadingTrivia` or `WithTrivia` branch at start of `lexTrivia`.

So I think its more simple than before.

2018-03-09 08:43 UTC, omochi commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
I say simply, this indirection gives us less branching.

2018-03-09 16:55 UTC, rintaro commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
Okey. You are trying to do 2 distinct things in this PR. Let me know if I'm wrong:

* Reduce branches caused by `TriviaRetention`, and simplify `case`s in `lexImpl`:
   By always lexing `LeadingTrivia`. To achieve this, construct private `Lexer` in `WithoutTrivia` mode, then propagate only `NextToken` and `CurPtr` to the outer Lexer.
* Eliminate `LastCommentBlockStart`/`SeenComment`:
  Instead, calculate `CommentLength` from `LeadingTrivia` in `formToken()`

First of all, could you to split the commit for them?

Also, as for reducing branches, your implementation has 3 major branches caused by `TriviaRetention` mode during single `lex()` call:
1. `if (!isWithTrivia())` in `lexImpl()`
2. `switch (TriviaRetention) {` in `lexTrivia(/*IsForTrailingTrivia*/false)`
3. `switch (TriviaRetention) {` in `lexTrivia(/*IsForTrailingTrivia*/true)`

Actually, I believe we can achieve this number of branches without the indirection. Consider:

* Always lex leading trivia.
* Only if `WithTrivia`, `lexTrivia(/*IsForTrailingTrivia*/true)` in `formToken()`
* Only if `WithoutTrivia`, Copy `Leading/TrailingTrivia` in `lex()`.

In this way, we can remove `if (TriviaRetention == TriviaRetentionMode::WithoutTrivia) return;` in `lexTrivia()`. As a result, the number of branches in this strategy are only two above (PoC code https://github.com/apple/swift/compare/master...rintaro:lexer-less-branches).

What do you think?

2018-03-09 16:56 UTC, rintaro requested changes
Preventing accidental merge.

2018-03-10 06:00 UTC, omochi commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
Your understand about what I want is exactly right.
Thanks to think deeply and comment in detail.

What you say to achieve same purpose without indirection is very good.
Certainly, we can filter `LeadingTrivia`, `TrailingTrivia` out from internal fields when we pass result to user in `lex`. I missed.

I want to resubmit PR with your idea.

But I have only one thing to consider.

In your PoC, no `WithOnlyLeadingTrivia` mode,
so `lexTrivia` always runs to end of **trailing trivia**.
The result from `lex` function is same,
but there is a one side effects from Lexer, diagnoses.

For example such source.

`aaa<SP>bbb<SP><\0><SP>ccc`

In first time of `lexImpl` in constructor, first token `aaa` is eaten.

Next, with your code, first call of `lex` occurs  diagnostic error about embedded nul character. (`aaa` as result token, `<SP>` as result trailing trivia,  `bbb` as `NextToken` internally, `<SP><\0><SP>` as `TrailingTrivia` internally).

But in original `WithoutTrivia` behavior,
this diagnostics come out from second call of `lex`.
Because Lexer position is stopped at end of **token**.

This difference of diagnostics changes order of diagnostics from Lexer and from Parser.

Actually I tried approach without `WithOnlyLeadingTrivia` in first time,
But this diagnostics shuffle was occur, and some test cases are failed.

Then I think. The order of them are trivia thing.
I retry with your idea, and fix to pass test case about only order of diagnostics.

Eliminating `LastCommentBlockStart` and `SeenComment` will split from PR.

2018-03-10 06:01 UTC, closed without merging

2018-03-10 06:13 UTC, omochi commented on lib/Parse/Lexer.cpp
> +        TriviaRetentionMode::WithOnlyLeadingTrivia, StartOffset, EndOffset));
Oh, sorry I misundestand.
Only if `WithTrivia`, we call `lexTrivia` in `formToken`,
Lexer stop at end of token but not end of trailing trivia.