[stdlib][SR-7136] Fast-path ad-hoc printing of Strings
swiftlang/swift pull request #15108
Opened 2018-03-09 16:27 UTC by darquro

I added dynamically checked whether something is a String and just print the string.

Resolves [SR-7136](https://bugs.swift.org/browse/SR-7136).

2018-03-09 16:32 UTC, darquro commented
@swift-ci Please smoke test

2018-03-09 16:59 UTC, jckarter requested changes

2018-03-09 16:59 UTC, jckarter commented on stdlib/public/core/OutputStream.swift
> +    _adHocPrint_unlocked(string, mirror, &target, isDebugPrint: false)
You can just do `target.write(string)`.

2018-03-09 17:00 UTC, jckarter commented
Thanks for looking into this! _adHocPrint is probably not going to be much faster in practice, though. You can use `TextOutputStream`'s `write` method directly since we know we have a string here.

2018-03-09 17:16 UTC, darquro commented
@jckarter Thank you for reviewing! I fixed it.

2018-03-09 17:21 UTC, jckarter commented
Awesome, thanks! I'll run the tests and merge.

2018-03-09 17:21 UTC, jckarter approved these changes

2018-03-09 17:21 UTC, jckarter commented
@swift-ci Please smoke test

2018-03-09 17:47 UTC, jckarter commented
Oh, `x as? String` will be true for `Optional<String>` as well, so this changes how Optional prints. I guess we'll have to move the `as? String` check after the `_isOptional` check below it.

2018-03-09 18:08 UTC, darquro commented
OK, I'll fix it again. 👍

2018-03-09 18:16 UTC, jckarter commented
@swift-ci Please smoke test

2018-03-09 19:05 UTC, milseman commented
@swift-ci please smoke benchmark

2018-03-09 19:06 UTC, milseman commented
Do we have anything to measure this speedup? I'm interested in detecting regressions and exploring further improvements here such as plumbing this higher up.

2018-03-09 21:51 UTC, milseman commented
(I suspect the string builders are noisy)

@swift-ci please benchmark

2018-03-12 23:07 UTC, milseman commented
@swift-ci please smoke benchmark

2018-03-12 23:08 UTC, milseman commented
@swift-ci please smoke test

2018-03-13 01:27 UTC, milseman commented
@swift-ci please smoke test

2018-03-16 00:03 UTC, milseman commented
@swift-ci please smoke test

2019-11-18 18:56 UTC, CodaFi commented
@swift-ci please smoke test

2019-11-18 18:56 UTC, CodaFi commented
@swift-ci please smoke benchmark

2019-11-18 19:52 UTC, jckarter commented
I suspect the primary benefit would be in startup time and memory usage, since this should make it so that `print("...")` doesn't warm up the conformance cache. I don't think our current benchmark suite measures that well, though.

2019-11-19 03:48 UTC, CodaFi commented
Hmph.  Yeah, this looks like noise.

2019-11-19 20:53 UTC, milseman commented
Do we have a benchmark (or should we write one) that will demonstrate the improvement?

2019-11-19 21:26 UTC, jckarter commented
We might be able to rig something up that captures the warmup time aspect. We could definitely do with more memory usage benchmarks, but that might need more infrastructure.

2020-02-10 06:05 UTC, futurejones commented
Can one of the admins verify this patch?

2020-04-10 22:28 UTC, CodaFi commented
I've filed https://bugs.swift.org/browse/SR-12572 about the benchmark infrastructure

@swift-ci test

2020-04-12 16:30 UTC, CodaFi commented
⛵

2020-04-12 16:30 UTC, merged