[SwiftSyntax] Add replace method SyntaxCollections
swiftlang/swift pull request #15331
Opened 2018-03-18 23:11 UTC by morozkin

I started working closely with SwiftSyntax and realized that I very often face with the situation where I need to replace one element in some kind of SyntaxCollection and for doing such operation we have to call two different methods: one for delete operation and one for insert operation.

This is a typical scenario where you need to update one element in the `ArrayExprSyntax`:
```arrayExpr.elements.removing(childAt: i).inserting(newArrayElement, at: i)```

Instead of this with the new method we can rewrite it in the following way:
```arrayExpr.elements.replacing(childAt: i, with: newArrayElement)```

2018-03-19 03:46 UTC, harlanhaskins reviewed
Thank you for this! If you could add a test, that’d be great!

2018-03-19 03:46 UTC, harlanhaskins commented on tools/SwiftSyntax/SyntaxCollections.swift.gyb
> +    newLayout.replaceSubrange(index...index, with: [syntax])
Should this be `newLayout[index] = syntax.raw`?

2018-03-19 23:02 UTC, morozkin commented
@harlanhaskins I added tests for all types of mutation methods of `SyntaxCollections`

2018-03-19 23:09 UTC, harlanhaskins requested changes

2018-03-19 23:09 UTC, harlanhaskins commented on test/SwiftSyntax/SyntaxCollections.swift
> +        SyntaxFactory.makeArrayElement(expression: SyntaxFactory.makeIntegerLiteral("0"), trailingComma: nil)
`makeIntegerLiteral` returns a `TokenSyntax`, not an `ExprSyntax`. Can you rewrite this to use `makeIntegerLiteralExpr`?

You might want to make a helper:

```swift
func integerLiteralElement(_ int: Int) -> ArrayElementSyntax {
  let literal = SyntaxFactory.makeIntegerLiteral("\(int)")
  return SyntaxFactory.makeArrayElement(
    expression: SyntaxFactory.makeIntegerLiteralExpr(digits: literal),
    trailingComma: nil)
}
```

That way you always know you're constructing a full `ArrayElementSyntax`.

2018-03-19 23:09 UTC, harlanhaskins commented
Structurally, the tests look great!

2018-03-20 01:51 UTC, harlanhaskins approved these changes
LGTM. Thank you so much!

2018-03-20 01:51 UTC, harlanhaskins commented
@swift-ci please smoke test

2018-03-20 05:35 UTC, harlanhaskins commented
@swift-ci please smoke test

2018-03-20 17:44 UTC, morozkin commented
@harlanhaskins I'm sorry for the quality of my previous commits. I had errors with compilation of the swift so I didn't run and check that my code compiles and runs well. But with my latest commit I compiled the swift with my changes and checked that all tests passed successfully

2018-03-20 17:46 UTC, harlanhaskins commented
No need to apologize 😊

I’ll re-run the tests now and we can hopefully get this merged!

@swift-ci please smoke test

2018-03-20 18:03 UTC, nkcsgexi commented
@morozkin there's no need to feel bad. People rely on CI to find build errors all the time 😄

2018-03-20 18:05 UTC, harlanhaskins commented
I certainly do!

2018-03-20 18:58 UTC, harlanhaskins commented
:boat:

2018-03-20 18:58 UTC, merged

2018-03-20 18:58 UTC, harlanhaskins commented
Thank you, @morozkin!