Merge getRuntimeLibraryPath and getRuntimeStaticLibraryPath
swiftlang/swift pull request #15388
Opened 2018-03-21 00:19 UTC by lanza

These two functions are duplicates except for one string. Merge them and
add an argument for whether we want static or shared.

2018-03-21 00:25 UTC, lanza commented
@compnerd smoke test and merge please

2018-03-21 14:36 UTC, compnerd requested changes

2018-03-21 14:36 UTC, compnerd commented on lib/Driver/ToolChains.cpp
> +    }
I think this is better as a ternary:

    llvm::sys::path::append(runtimeLibpath, "lib", shared ? "swift" : "swift_static");

2018-03-21 14:36 UTC, compnerd commented on lib/Driver/ToolChains.cpp
> +  getRuntimeLibraryPath(LibPath, Args, TC, true);
Please add a comment:

    getRuntimeLibraryPath(LibPath, Args, TC, /*Shared=*/true);

Similar throughout.

2018-03-22 08:19 UTC, lanza commented on lib/Driver/ToolChains.cpp
> +  getRuntimeLibraryPath(LibPath, Args, TC, true);
Gross, if only there was a language with functions with named arguments.

2018-03-22 16:48 UTC, compnerd commented
@swift-ci please test and merge

2018-03-22 16:48 UTC, compnerd approved these changes

2018-03-22 18:15 UTC, compnerd commented
@swift-ci please test and merge

2018-03-22 20:39 UTC, merged