SWIFT_MODULE_DEPENDS_DARWIN
swiftlang/swift pull request #15657
Opened 2018-03-31 18:36 UTC by compnerd

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2018-03-31 18:37 UTC, compnerd commented
CC: @jrose-apple @shahmishal @Rostepher @gottesmm

2018-03-31 18:37 UTC, compnerd commented
@swift-ci please test

2018-03-31 19:30 UTC, gottesmm commented
@compnerd since these are automatically updated, I imagine whatever thing is used to update them must be updated as well. @Rostepher @zisko: how is this working now?

2018-03-31 23:34 UTC, compnerd commented
@gottesmm yeah, I was hoping that one of you guys would know how that is being handled.

2018-04-02 16:14 UTC, jrose-apple commented
The updates are computed by utils/find-overlay-dependencies.sh and friends, though there are some additional complexities around Apple-internal only content that, well, stinks for us at Apple.

I'm going to abstain from this one and let Ross and Jacob decide whether it's a good change.

2018-04-02 16:41 UTC, compnerd commented
@jrose-apple the second change in this set is something that is more of a clean up, and if it ends up being painful for the internal only content, then we can drop it.  Saw the opportunity, so whipped up a patch :-)

2018-05-04 19:13 UTC, compnerd commented
CC: @Rostepher @zisko

2018-06-04 01:57 UTC, compnerd commented
@gottesmm - anyone other than @zisko and @Rostepher that can decide what we want to do with this?

2018-06-04 03:12 UTC, Rostepher commented on cmake/modules/AddSwift.cmake
> +        API_NOTES_NON_OVERLAY
I don't think we should use this PR as a means to re-format these arguments. I'd much prefer if we kept whitespace changes in separate, non-functional PRs if possible. Makes it not only easier to review, but also distills PRs such as this one down to just the functional changes.

2018-06-04 03:15 UTC, Rostepher commented on cmake/modules/AddSwift.cmake
> +                        "${SWIFTLIB_options}"
Standard CMake styling does not require that arguments are "visually" indented (like in Python) to the same column as the first argument. In fact, the standard style in this project is all subsequent lines are to be indented 2 spaces. These sorts of whitespace changes and re-stylings add a lot of diff churn and potential merge conflicts.

2018-06-04 03:16 UTC, Rostepher commented on stdlib/public/SDK/CoreAudio/CMakeLists.txt
> +                    ${SWIFT_SDK_OVERLAY_LIBRARY_BUILD_TYPES}
Same here, we should indent 2 spaces on subsequent lines.

2018-06-04 03:19 UTC, Rostepher requested changes
This sort of functional change should not also include all these whitespace/formatting changes. In particular the indentation in the various overlays is not in keeping with the standard formatting style.

Can we move those changes to separate "gardening" PRs and slim this one down? And as @jrose-apple mentioned, these arguments are automagically updated by a few scripts in the `utils` directory. It's likely those will also need to be updated to know about these shared dependencies.

2018-06-05 22:47 UTC, compnerd commented
@Rostepher - yeah, I want to figure out if this is something that you think is helpful/valuable or not.  This needs to be rebased which will remove all the other stuff around it - the commits were broken up accordingly to that anways.

The idea here is that you are unifying the commonality of the iOS/tvOS/watchOS/macOS dependency tree.  There are so many cases where you find checks to see if the build is of that type and then perform a behaviour.  It just seems that this simplifies some of that logic.

2018-06-14 18:41 UTC, compnerd commented
@Rostepher - ping?

2018-09-05 16:03 UTC, compnerd commented
Seems that there is no interest from Apple on this ...

2018-09-05 16:03 UTC, closed without merging