Re-adding the test suite for checking constant propagation phase
swiftlang/swift pull request #15697
Opened 2018-04-03 01:06 UTC by ravikandhadai

This commit enables some parts of the test suite `diagnostic_constant_propagation.swift`. It enables all test cases that pass under the latest swift implementation. It also has some false negatives, which should ideally be reported as an error but currently  pass the diagnostics phase. The commit also separate tests that have diverging behavior in Swift 3 and Swift 4.

2018-04-03 01:07 UTC, ravikandhadai commented
@swift-ci Please smoke test

2018-04-03 05:39 UTC, devincoughlin requested changes
Thanks for splitting this up. It is great to see so many tests re-enabled! (Some of which have been disabled for a *long* time).

This looks pretty good. I've made several minor comments inline.

One thing, however, is that you should make sure that your editor is using two spaces for tabs. Because of all the whitespace changes, this diff changes many more lines than those whose functionality changed. We really like to keep whitespace changes to a minimum since they obscure the history of the file and make for larger diffs that are harder to review.

Can please you update the patch to use two spaces per tab for the lines where you have added/changed things and to leave the spacing as it is (even if it is inconsistent) on lines whose functionality didn't change in your patch.

I generally do a 'git diff' before submitting a PR to make sure the patch includes only changes to the lines I expect.

2018-04-03 05:39 UTC, devincoughlin commented on test/SILOptimizer/diagnostic_constant_propagation.swift
> +// <rdar://problem/19508336> Extend test/SILOptimizer/diagnostic_constant_propagation.swift to 32-bit platforms
We should probably leave the FIXME in place here since we haven't added 32-bit tests yet.

2018-04-03 05:39 UTC, devincoughlin commented on test/SILOptimizer/diagnostic_constant_propagation.swift
> +    var _ = Int8(126) + Int8(1+1) // FIXME: flase negative: overflow that is not caught by diagnostics (see also <rdar://problem/39120081>).
Nit: Typo 'flase'.

2018-04-03 05:39 UTC, devincoughlin commented on test/SILOptimizer/diagnostic_constant_propagation.swift
> +// TODO: There is a radar related to these: <rdar://problem/15735295>. But, everything seem to work as expected. Is the problem fixed?
Yes, it looks like it is. You can remove the TODO. Thanks for re-enabling these!

2018-04-03 05:39 UTC, devincoughlin commented on test/SILOptimizer/diagnostic_constant_propagation.swift
> +    _ = intConversionWrapperForUSCheckedConversion(255, 30) // FIXME: false negative: uncaught overflow error. See the function `intConversoin..` definition (see also <rdar://problem/39120081>).
Nit: typo 'intConversoin' ?

2018-04-03 06:05 UTC, devincoughlin commented
Some other, super nit-picky drive by style nits: 

We try to use the imperative mood for commit message titles and we often prefix commit messages with the affected subsystem. So, for example, for your commit message we would idiomatically write: "[Tests] Re-add the test suite for checking constant propagation phase" This way someone scanning commit messages to try to understand a regression will know based on the prefix whether they need to dig into your commit or can skip it and move on.

We also try to include necessary background for understanding the motivation for a commit in the commit message. I would suggest adding an explanation of the reason the tests were disabled and and a description of why we have the false negatives in the commit message. This will help future maintainers understand why some but not all of the tests were re-enabled.

2018-04-03 18:32 UTC, moiseev commented on test/SILOptimizer/diagnostic_constant_propagation.swift
> +    return x + y
Please use 2 spaces for indentation.

2018-04-03 18:34 UTC, moiseev reviewed
It is really hard to see what exactly has changed in `diagnostic_constant_propagation.swift` due to, I believe, changed indentation that the diff highlighter is unable to process properly. So please can you update the PR with a 2-space indentation.

2018-04-03 19:19 UTC, ravikandhadai commented
This new commit fixes the indentation, typos and code convention changes that were requested.

2018-04-03 19:20 UTC, ravikandhadai commented
@swift-ci Please smoke test

2018-04-03 21:46 UTC, devincoughlin approved these changes

2018-04-03 21:46 UTC, devincoughlin commented
LGTM. Thanks!!

2018-04-06 20:26 UTC, ravikandhadai commented
@moiseev Hi max, does it look good to you and should I merge it.

2018-04-06 21:12 UTC, moiseev commented
@ravikandhadai yeah. I gave a 👍 on your comment above expressing agreement =)

2018-04-06 21:16 UTC, ravikandhadai commented
@swift-ci Please smoke test and merge

2018-04-06 22:02 UTC, ravikandhadai commented
@swift-ci Please smoke test and merge

2018-04-06 22:06 UTC, shahmishal commented
@swift-ci Please smoke test and merge

2018-04-06 22:36 UTC, merged