Basic: record layering violation for linking
swiftlang/swift pull request #15746
Opened 2018-04-04 21:40 UTC by compnerd

When linking on Linux, we would fail with unresolved symbol references
to  `swift::FrontendStatsTracer::getTraceFormatter<T>`.  The use of the
types, which are defined in swiftSIL occur in swiftBasic.  To avoid the
circular dependency, introduce interface link dependencies.  This allows
the consumers of swiftBasic to also link against swiftSIL at the right
time, resolving the symbol.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2018-04-04 21:40 UTC, compnerd commented
CC: @gottesmm @jrose-apple

2018-04-04 21:40 UTC, compnerd commented
@swift-ci please test

2018-04-04 21:42 UTC, gottesmm commented
@compnerd why doesn't this happen on Darwin?

2018-04-04 22:59 UTC, jrose-apple submitted a review, later dismissed
Basic is the bottom of the library hierarchy; this really is a circular dependency. We'll have to find another answer.

2018-04-04 23:00 UTC, jrose-apple commented
@gottesmm: ld64 doesn't pay attention to dependencies between static libraries, so none of this happens on Darwin. If we built dylibs we'd see all of these problems.

(This is hardly the only circularity but it's a particularly egregious one because it involves Basic.)

2018-04-05 05:06 UTC, graydon requested changes
Yeah no this isn't right. The slightly subtle arrangement of declaring swift::FrontendStatsTracer::getTraceFormatter<T> instances in Basic, against forward-declared higher-level types, and then only defining those in the higher-layer libraries, is specifically done to avoid linking errors and circular dependency. If that is somehow failing, I made a mistake or something. Can you post the exact error you're getting? (I develop on 50/50 linux and darwin and this is not happening on my end).

2018-04-05 16:44 UTC, gottesmm commented
@jrose-apple that wasn't clear to me. It could have also been due to ld64 not iterating. I guess I should have been more specific with my question.

2018-04-05 16:46 UTC, gottesmm commented
*erm ld64 iterating and gold not doing so in the case of linking in a dylib. I didn't see it was an issue with static libraries. This reminds me of crazy ideas I have had in the past for identifying layering violations via something in lld. But that is an idea for another time.

2018-04-05 21:37 UTC, compnerd commented
@graydon it just gives a bunch of unresolved symbol errors when building with gold.  The next time I do a full build, Ill try to grab the error message.

2018-04-06 20:39 UTC, AndrewSB commented
Here's the error:

```
--- Building tests for swift ---
+ /usr/bin/cmake --build /home/asb/Developer/swift/build/Ninja-DebugAssert/swift-linux-x86_64 -- -j24 SwiftUnitTests
[4/9] Linking CXX executable unittests/Driver/SwiftDriverTests
FAILED: unittests/Driver/SwiftDriverTests
: && /usr/bin/clang++   -Wno-unknown-warning-option -Werror=unguarded-availability-new -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wdelete-non-virtual-dtor -Wstring-conversion -fcolor-diagnostics -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -g  -latomic -fuse-ld=lld unittests/Driver/CMakeFiles/SwiftDriverTests.dir/DependencyGraphTests.cpp.o  -o unittests/Driver/SwiftDriverTests -L/home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/./lib -Wl,-rpath,/home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/./lib /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSupport.a -lpthread /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libgtest_main.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libgtest.a -lpthread lib/libswiftDriver.a -lpthread lib/libswiftFrontend.a lib/libswiftMigrator.a lib/libswiftIDE.a lib/libswiftFrontend.a lib/libswiftMigrator.a lib/libswiftIDE.a lib/libswiftParseSIL.a lib/libswiftSIL.a lib/libswiftSema.a lib/libswiftSerialization.a lib/libswiftClangImporter.a lib/libswiftParse.a lib/libswiftIndex.a lib/libswiftAST.a lib/libswiftMarkup.a /home/asb/Developer/swift/build/Ninja-DebugAssert/cmark-linux-x86_64/src/libcmark.a lib/libswiftSyntax.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMDebugInfoDWARF.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86CodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86AsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86Desc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86AsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86Disassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86Info.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMX86Utils.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMAsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMDisassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMDesc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMAsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMInfo.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMARMUtils.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64CodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMGlobalISel.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64AsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64Disassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64Desc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64AsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64Info.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAArch64Utils.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCAsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCDesc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCAsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCDisassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPowerPCInfo.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZAsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZDisassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZDesc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZAsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSystemZInfo.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMDebugInfoCodeView.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMDebugInfoMSF.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMSelectionDAG.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsAsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsDesc.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsAsmPrinter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsDisassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMCDisassembler.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMMipsInfo.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libclangFrontendTool.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libclangCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMCoroutines.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMCoverage.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMLTO.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMObjCARCOpts.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMPasses.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMipo.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMIRReader.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAsmParser.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMInstrumentation.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMLinker.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMCodeGen.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMBitWriter.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMScalarOpts.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMInstCombine.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMVectorize.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMTransformUtils.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMTarget.a /home/asb/Developer/swift/build/Ninja-DebugAssert/llvm-linux-x86_64/lib/libLLVMAnalysis.a /home/asb/Developer/swift/ [...]

2018-04-06 21:58 UTC, graydon commented
@compnerd & @AndrewSB If I had to guess, I would think that the not-lld linker I tested with (I guess ld64) is deciding the various `FrontendStatsTracer::FrontendStatsTracer` constructor overloads in Statistic.cpp are dead symbols before it tries to resolve their calls to the forward-declared (and defined in higher-level libraries) `getTraceFormatter<>` specializations, whereas lld is deciding the constructor overloads are not-dead and then trying to resolve them. Or perhaps they wind up as weak references or something. I don't know what's formally correct here but clearly I botched making it portable, and will post a fix as soon as I can reproduce what you're seeing.

(I _suspect_ solving it is therefore just a matter of moving those one-liner constructors from Statistic.cpp to inlines in Statistic.h, so they don't get codegen'ed _at all_ when not in use; but there might be other approaches that work too. If you want to try a short term fix ahead of me, try that?)

2018-04-10 00:41 UTC, compnerd commented
@swift-ci please test

2018-04-10 00:59 UTC, jrose-apple commented on include/swift/Basic/Statistic.h
> +// emissions.  We cannot force the inling by defining them in the declaration
Typo: "inling".

2018-04-10 00:59 UTC, jrose-apple commented
If this new patch fixes the issue I see no problems with it.

2018-04-10 17:38 UTC, compnerd commented
Yeah, it fixes the issue.  I'll update it for the typo.  *sigh* typing is hard.

2018-04-10 17:41 UTC, compnerd commented
@swift-ci please test and merge

2018-04-10 18:19 UTC, jrose-apple commented
Please wait for @graydon.

2018-04-10 20:01 UTC, graydon approved these changes

2018-04-10 20:02 UTC, graydon commented
Looks good to me (though I assumed you'd just put the constructors _in_ the class definition, rather than declaring in the class and defining as inlines immediately outside the class; but I don't especially care). Sorry for the delay in replying!

2018-04-10 20:03 UTC, graydon commented
Ah never mind, stopped to actually read the comment re "We cannot force the inlining by defining them in the declaration". That's fine then!

2018-04-10 23:05 UTC, jrose-apple commented
@swift-ci please test

2018-04-10 23:06 UTC, jrose-apple commented
@swift-ci Please test

2018-04-12 05:04 UTC, merged