[stdlib] De-gyb Arrays.swift.gyb
swiftlang/swift pull request #16230
Opened 2018-04-28 00:18 UTC by lancep

Split up Array, ArraySlice and ContiguousArray into one file each, with an ArrayShared file for common stuff.

2018-04-28 05:34 UTC, gottesmm requested changes
+1 on less gyb! Found some nits.

2018-04-28 05:34 UTC, gottesmm commented on stdlib/public/core/ArrayShared.swift
> +//===--- Arrays.swift.gyb -------------------------------------*- swift -*-===//
Wrong file name.

2018-04-28 05:34 UTC, gottesmm commented on stdlib/public/core/ArraysCommon.swift
> +// ###sourceLocation(file: "/Users/lanceparker/Development/swift-source/swift/stdlib/public/core/Arrays.swift.gyb", line: 1)
Bad title and ### source location. You should probably grep for these.

2018-04-28 05:34 UTC, gottesmm approved these changes

2018-04-28 05:35 UTC, gottesmm commented
(sorry I just meant to leave comments, not approve/disapprove)

2018-05-30 18:15 UTC, lancep commented
@swift-ci please test

2018-05-30 18:40 UTC, lancep commented
@swift-ci please test

2018-05-30 18:40 UTC, lancep commented
@swift-ci please test

2018-05-30 21:11 UTC, merged