[Testing] NFC: pipe_round_robin.swift.gyb is too scheduler sensitive
swiftlang/swift pull request #16574
Opened 2018-05-12 11:48 UTC by davezarzycki

If a background compile job is running on my Linux box, this test will sometimes fail.

2018-05-12 11:48 UTC, davezarzycki commented
@swift-ci please smoke test

2018-05-12 15:49 UTC, davezarzycki commented
@swift-ci please smoke test linux

2018-05-13 19:49 UTC, davezarzycki commented
@swift-ci please smoke test

2018-05-13 19:58 UTC, davezarzycki commented
@swift-ci please clean test linux

2018-05-13 21:58 UTC, davezarzycki commented
@swift-ci please smoke test macos

2018-05-16 11:13 UTC, davezarzycki commented
@graydon – Might you please review this? Thanks!

2018-05-16 20:48 UTC, graydon requested changes
While I appreciate that increasing the buffer size makes the buffered reading more efficient, it also potentially defeats the way this test works, since we're testing the read-to-poll ratio and each read now consumes 64x as much data.

Can you check to be sure that the read-to-poll ratio is still very high (hundreds-to-thousands) when running the preimage of the commit this test was added for, with an increased read-buffer size? Otherwise the test is no longer meaningful as-is, and needs some further refinement.

2018-05-16 22:28 UTC, davezarzycki commented
I don't want to get sucked into cleaning up `lib/Basic/Unix/TaskQueue.inc`, so I removed the performance improvement.

@swift-ci please smoke test

2018-05-18 16:52 UTC, graydon approved these changes

2018-05-18 16:53 UTC, graydon commented
Looks good, thanks!

2018-05-18 16:53 UTC, merged