[Gardening] Update alloc_stack documentation in SIL.rst
swiftlang/swift pull request #16589
Opened 2018-05-14 06:54 UTC by kitasuke

As of Swift 4.0, `alloc_stack` always uses stack which means it's now guaranteed that the allocated memory is really located on the stack since this change below.
https://github.com/apple/swift/commit/cd1037b799402f4d68322011ef1b196f94281cea

2018-05-14 07:05 UTC, CodaFi commented
@swift-ci please smoke test

2018-05-14 18:19 UTC, slavapestov commented
@swift-ci Please smoke test Linux

2018-05-14 18:58 UTC, aschwaighofer approved these changes
looks good

2018-05-14 19:18 UTC, gottesmm requested changes
Can you add the current behavior. I think this is important behavior to call out specifically and explicitly.

2018-05-15 16:06 UTC, kitasuke commented
Added the current behavior. Let me know if that doesn't make sense!

2018-05-15 21:59 UTC, gottesmm commented
That isn't what I meant. I meant what do we do today if we have a runtime sized stack allocated thing. IIRC we use a dynamic alloca or something like that. @aschwaighofer did I get that right?

2018-05-21 16:43 UTC, aschwaighofer commented
Yes, if the type is runtime sized we use a dynamic alloca which will allocate memory on the stack.

2019-11-18 23:05 UTC, CodaFi commented
@swift-ci please smoke test

2019-12-02 18:34 UTC, CodaFi commented
⛵️

2019-12-02 18:34 UTC, merged