Add ExistentialToGeneric mangling and demangling code
swiftlang/swift pull request #16603
Opened 2018-05-14 19:23 UTC by rajbarik

Add a new mangler/demangler option 'e' for ExistentialToGeneric needed for 
https://github.com/apple/swift/pull/13991

2018-05-14 19:44 UTC, eeckstein requested changes
Can you please also update docs/ABI/Mangling.rst

2018-05-14 20:16 UTC, slavapestov commented on lib/Demangling/Remangler.cpp
> +        Buffer << 'e';
It seems weird that this is an if/else if construct that duplicates some of the cases here. Can you instead redo this as a series of independent ifs instead?

2018-05-14 22:30 UTC, rajbarik commented
@eeckstein please see the updated doc

2018-05-14 23:20 UTC, eeckstein approved these changes

2018-05-15 03:56 UTC, slavapestov commented on lib/Demangling/Remangler.cpp
> +        Buffer << 'e';
Ok. It seems strange that the first letter is lower case and the rest are upper case, for each of the different argument kinds. But I guess that’s what we have today already.

2018-05-15 16:13 UTC, slavapestov commented
@swift-ci Please smoke test

2018-05-15 17:11 UTC, merged