[AST] Add XFAIL test for extra inhabitant logic for reference storage types
swiftlang/swift pull request #16861
Opened 2018-05-27 14:43 UTC by davezarzycki

Optional reference storage types have broken extra inhabitant logic. Right now, this problem is limited to optional unmanaged nodes created by the clang importer because the formal language does not allow optional unowned/unmanaged.

Please note that GitHub pull request #16237 contains a general solution to this problem, but without changing the formal user facing policy.

2018-05-27 14:44 UTC, davezarzycki commented
@swift-ci please smoke test

2018-05-29 21:03 UTC, rjmccall requested changes
This test has a lot of unnecessary stuff in it.  Could you refine it down to something that just has a `copy_addr` of an `Optional<S>` or something?

2018-05-29 22:07 UTC, davezarzycki commented
I've shrunk the SIL test down as far as I could go without crashing the compiler.

@swift-ci please smoke test

2018-05-29 23:45 UTC, davezarzycki commented
@swift-ci please smoke test

2018-05-29 23:46 UTC, davezarzycki commented
@swift-ci please smoke test

2018-05-31 18:49 UTC, rjmccall approved these changes
LGTM now, thanks.

2018-05-31 19:17 UTC, merged