[don't merge!Use depth and index to lookup type metadata artificial variables
swiftlang/swift pull request #16937
Opened 2018-06-01 00:48 UTC by adrian-prantl

Use depth and index to lookup type metadata artificial variables  …
instead of using name and decl context.

The advantages of this approach are three-fold:
- This is necessary to support inlined generic functions.
- We can retire the debugger-specific type name manfgling mode for archetypes.
- This saves 270kb of debug information in the x86_64 libSwiftCore.dylib alone.

<rdar://problem/38306256>

2018-06-04 16:41 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-04 20:23 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-04 20:24 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-04 23:36 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-04 23:36 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-07 20:47 UTC, dcci requested changes
Some comments inline. I'll try to review more carefully in the next hours.

2018-06-07 20:47 UTC, dcci commented on lib/IDE/TypeReconstruction.cpp
> +static void VisitNodeDependentMember(ASTContext *ast,
We should really add a `lldb-moduleimport-test` test for this.

2018-06-07 20:47 UTC, dcci commented on lib/IRGen/DebugTypeInfo.cpp
> +
Spurious newline I assume?

2018-06-12 21:20 UTC, adrian-prantl commented
@dcci: Can you take another look?

2018-06-12 21:20 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-12 23:41 UTC, dcci approved these changes
LGTM

2018-06-12 23:46 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test platform Linux

2018-06-12 23:46 UTC, adrian-prantl commented
test with https://github.com/apple/swift-lldb/pull/671
@swift-ci test

2018-06-13 01:56 UTC, merged