Better error message for 'class func/var' usage in protocols
swiftlang/swift pull request #16965
Opened 2018-06-02 19:31 UTC by Moximillian

Clarify how to use protocols in relation to class funcs. This has been discussed in https://forums.swift.org/t/class-constrained-protocols-dont-allow-for-class-methods/13031

2018-06-02 20:40 UTC, xwu commented
I don't think this is an appropriate fix when the usage being diagnosed is in an `enum`, for example. It should be restricted to usage in protocol declarations only.

Consider perhaps also reworking the wording to omit unnecessary text (such as "keyword") and to clarify what's actually being advised (e.g., "use 'static' to declare a requirement fulfilled by either a class or static method").

2018-06-02 21:36 UTC, CodaFi requested changes

2018-06-02 21:36 UTC, CodaFi commented on include/swift/AST/DiagnosticsCommon.def
> +      "use 'static' to declare a requirement fulfilled by either a class or static method", ())
"requirement" is the language one uses in the context of protocol members.  I think the confusion in the thread stems from the `class` requirement on protocols not emitting a more refined diagnostic.  You should look into specializing this for exactly that case.

2018-06-02 21:44 UTC, Moximillian commented
@xwu updated the error text as a separate error, so that protocols can have different text than structs and enums. Only protocol related tests have changes, other tests are unchanged.
Tried to apply the protocol specific error in ParseDecl.cpp. Does TypeCheckDecl.cpp need to be changed too?

2018-06-02 22:00 UTC, CodaFi commented
I still think this isn't *quite* what the original thread intended.  OP seemed confused that a `class` bound on a protocol would emit a diagnostic that, the right light, implies classes wouldn't be able to conform to the protocol because `class` members aren't `static` members.  I don't think the original diagnostics need updating, I think we need a new diagnostic to address that head on.

2018-06-02 22:12 UTC, Moximillian commented
Apparently extension parsing/type checking happens in TypeCheckDecl.cpp, so for protocol extensions, the appropriate error is not yet produced.

2018-06-02 22:14 UTC, CodaFi commented
```swift
protocol MyProtocol: class {
    static func a() -> Self // Compiles.
    class func b() -> Self // Doesn't compile.  "Class methods are only allowed within classes; use 'static' to declare a static method"
}
```

This is the original.  It isn't about the conformances, it's about the protocol requirements.

2018-06-02 22:27 UTC, CodaFi commented
>  It's not obvious for new users.

Okay, I'll re-review under this new specification.

2018-06-02 22:28 UTC, CodaFi commented on include/swift/AST/DiagnosticsCommon.def
> +      "use 'static' to declare a requirement fulfilled by either a class or static method", ())
When diagnostics are related by only a snippet of text, as this one is to its neighbors to the north, you should parametrize the diagnostic.  [For example](https://github.com/apple/swift/blob/master/include/swift/AST/DiagnosticsSema.def#L305-L306)

2018-06-02 22:29 UTC, CodaFi commented on lib/Parse/ParseDecl.cpp
> +        diagnose(Tok, Flags.contains(PD_InProtocol) ? diag::class_var_not_in_class_protocol : diag::class_var_not_in_class)
Nit: This line should be wrapped to 80 characters.  You can pull out diagnostic selectors as variables or parametrize the diagnostic.  Either one would shorten the line.

2018-06-02 22:29 UTC, CodaFi commented on lib/Parse/ParseDecl.cpp
> +        diagnose(Tok, Flags.contains(PD_InProtocol) ? diag::class_func_not_in_class_protocol : diag::class_func_not_in_class)
Nit: ditto.

2018-06-02 22:37 UTC, xwu commented on include/swift/AST/DiagnosticsCommon.def
> +      "use 'static' to declare a requirement fulfilled by either a class or static property", ())
The last diagnostic in this file begins: “Generic requirement...” I doesn’t strike me as unfriendly.

2018-06-02 22:42 UTC, Moximillian commented
@CodaFi thanks for the review, I'll work on this...

2018-06-02 22:46 UTC, CodaFi commented on include/swift/AST/DiagnosticsCommon.def
> +      "use 'static' to declare a requirement fulfilled by either a class or static property", ())
Whoops, grep'ed too hard in the wrong directory.  Striking this.

2018-06-02 22:47 UTC, CodaFi commented
Dropped my comments about the wording so we're just down to the nits then, @Moximillian.  I'll take this once those are resolved.

2018-06-03 06:58 UTC, Moximillian commented on include/swift/AST/DiagnosticsCommon.def
> +      "use 'static' to declare a requirement fulfilled by either a class or static property", ())
Just for the sake of completeness:
**Protocols**
“A protocol defines a blueprint of methods, properties, and other *requirements* that suit a particular task or piece of functionality. ”

Excerpt From: Apple Inc. “The Swift Programming Language (Swift 4).” iBooks.

2018-06-03 08:18 UTC, Moximillian commented
@xwu @CodaFi parametrized the error, using 80 columns for the code and implemented error for the protocol extensions too (& tests for it)

2018-06-03 13:08 UTC, xwu commented
The error message doesn’t make sense to me for protocol extensions: you cannot declare requirements in an extension, only statically dispatched protocol extension methods, so the original error message is correct.

2018-06-03 19:19 UTC, Moximillian commented
@xwu you are correct. Updated the protocol extensions to use the original version of the error.

2018-06-03 21:10 UTC, xwu commented
@swift-ci Please smoke test

2018-06-04 06:05 UTC, Moximillian commented
Test failures have been fixed

2018-06-04 14:07 UTC, xwu commented
@swift-ci Please smoke test

2018-06-04 16:28 UTC, CodaFi approved these changes

2018-06-04 16:28 UTC, CodaFi commented
⛵️

2018-06-04 16:29 UTC, merged

2018-06-07 11:12 UTC, AnthonyLatsis commented
Leaving out the error message as a whole, I am still not happy with the `fulfilled by either a class or static method`. It's read as if the "or" is between a class and a static method rather than between a class method or a static method.

2018-06-07 13:40 UTC, xwu commented
That reading is syntactically possible but semantically absurd; I suppose we could reverse the order and write "static or class method" but I'm doubtful this is a problem. I'm not familiar with the phrase "type method" in the context of Swift diagnostics.

2018-06-07 20:53 UTC, Moximillian commented
I tend to agree with switching the static/class in the error (even if it's just so tiny change). Created a new PR for it.