Documentation: improve instructions for Windows cross compiling
swiftlang/swift pull request #17012
Opened 2018-06-06 01:02 UTC by sparkasaurusRex

I wanted to help clarify and improve the instructions for cross compiling for windows. On Linux, the cmake options were not correct so I added the correct options. Also, the cmake options should be comma separated with no spaces between options.

2018-06-06 01:03 UTC, sparkasaurusRex commented
@compnerd Who else should I tag?

2018-06-06 14:34 UTC, xwu commented on docs/WindowsCrossCompile.md
> +From the build directory we can build the windows standard libraries using
Please capitalize Windows. Also, this is known as the _Swift_ runtime and standard library (for Windows), not the "Windows standard libraries." (And "standard library" isn't capitalized for Swift.)

2018-06-07 17:55 UTC, compnerd requested changes

2018-06-07 17:55 UTC, compnerd commented on docs/WindowsCrossCompile.md
> +-DSWIFT_WINDOWS_ICU_UC=<path to ICU UC lib>
These should also use the ARCH specific variables.

2018-06-07 21:38 UTC, compnerd commented
@sparkasaurusRex - for future changes, I think that these could've been collapsed into a single commit.

2018-06-07 21:38 UTC, compnerd commented
@swift-ci please test and merge

2018-06-07 21:38 UTC, compnerd approved these changes

2018-06-07 21:38 UTC, compnerd commented
@swift-ci please test and merge

2018-06-08 01:09 UTC, merged