Removed the tf_tensor_to_i1 magic function
swiftlang/swift pull request #17821
Opened 2018-07-07 21:02 UTC by mhong

This function appears only needed to appease SILVerifier, which requires that the `cond` operand of `cond_br` be a `Builtin.i1` type. Removing this function helps simplify the logic in the TF partition, device partition and lowering passes.

Added a field to SILFunction indicating if it's a accelerator (TF) function, so that we can customize SILVerifier behavior accordingly (and possibly other code related to SILFunction down the road).

2018-07-07 21:02 UTC, mhong commented
@swift-ci please test tensorflow

2018-07-07 22:52 UTC, lattner commented
@swift-ci please test tensorflow

2018-07-07 22:52 UTC, lattner commented
@swift-ci please test tensorflow

2018-07-07 22:54 UTC, lattner commented
I appreciate what you're going for here, but we will never be able to upstream this patch: it is too invasive to expand the definition of conditional branch to work on other types.

2018-07-07 22:55 UTC, lattner commented
Also, there is a semantic issue here with this approach: you can't branch on just any old Tensor<Bool>, it has to be a zero-d tensor of bool.  Having an operation that converts from Tensor to i1 makes this more explicit.  Even MLIR will require such a thing.

Perhaps there is a better way of expressing this than we are currently doing it though, I agree the special case is grotty...

2018-07-07 23:24 UTC, rxwei requested changes
Thanks for the work plumbing through it!

I actually think the existing solution is entirely reasonable and does have precedents within stdlib (alternatively, we could even use `@_semantics("tf.tensor_to_i1")`).

*Even if* the community decided that there could be an customization point that allowed user-defined control flow condition types (highly unlikely), such features would be implemented generically over custom user defined types instead of ad-hoc compiler special cases to avoid the complexity such ad-hoc cases impose on the semantics.

2018-07-08 04:47 UTC, mhong commented
Some reasons for making the change in SILFunction and SILVerifier are:

1. we are defining a new type of SIL function (for TF execution), which is not expected to go through (much of) optimization passes, and will not be executed in Swift runtime. 
2. As such, it seems reasonable to expect that it conforms to a different set of rules as set by the existing verifier, including control flow rules. e.g. the `builtin.i1` constraint for `cond_br` seems mainly motivated by some ARC optimization passes (https://github.com/mhong/swift/blob/0db0a1e8d84f38b9a1a048ac04df611af5f8ac56/lib/SIL/SILVerifier.cpp#L41070), which are not relevant to the new SIL function type.
3. Even for existing SIL functions to be executed by Swift runtime, the existing constraint on builtin.i1 appears too restrictive. Say if we want to vectorize the boolean comparison, do we want to express "a vector of bool values" at the SIL level to feed `cond_br`, instead of (I'm guessing) having LLVM IR reverse engineer such vectorization during IRGen or later?

#3 above is related to @lattner's point below:

> Also, there is a semantic issue here with this approach: you can't branch on just any old Tensor, it has to be a zero-d tensor of bool. Having an operation that converts from Tensor to i1 makes this more explicit.

It sounds plausible that someone will want to extend TF to make cond_br over a 1D Tensor<Bool> array work in the future, say in the context of "auto batching" for efficient execution of control flow over a batch of input examples (e.g. NLP sentences).

2018-07-09 00:49 UTC, rxwei commented
First, I understand the pain points here: SIL and TensorFlow have different control flow semantics. TensorFlow graph is arguably not a good control flow model here - 1) it uses `Tensor` with runtime-known size as the control flow condition, 2) the type system does not have separate a scalar type, and 3) the protocol that TFPartition and TFLowerGraph made is to make "SIL accelerator functions" correspond to a TensorFlow graph.

Since we are dealing with two different IRs, there are tradeoffs in what we do to translate one IR to another. If two systems are tightly integrated, then we then have the option to bend one IR to another, which partly is what this patch is doing here. But with TensorFlow support, pattern-matching control flow conditions (wrapping/unwrapping) during TFLowerGraph is low-cost and guarantees the semantic correctness of SIL. Earlier @lattner even discussed running optimization passes on accelerator functions because they are all valid SIL programs. This patch is changing the core semantics (thus invasive), and if we were to run optimizations on these SIL programs later on, some will be considered ill-formed by other passes. Then the obvious fix would be patching `isAcceleratorFn`-checks everywhere in the compiler, violating separation of concerns.

> Even for existing SIL functions to be executed by Swift runtime, the existing constraint on builtin.i1 appears too restrictive. Say if we want to vectorize the boolean comparison, do we want to express "a vector of bool values" at the SIL level to feed cond_br, instead of (I'm guessing) having LLVM IR reverse engineer such vectorization during IRGen or later?

They are "restrictive" because it's an IR with canonical control flow constructs. The condition of a branch is always a boolean value in a program. What would "making the branch condition a vector" achieve here? What would a "vector condition" mean in operational semantics? Could you provide a concrete case where you believe a vector condition would be semantically valid and be useful?

> It sounds plausible that someone will want to extend TF to make cond_br over a 1D Tensor array work in the future, say in the context of "auto batching" for efficient execution of control flow over a batch of input examples (e.g. NLP sentences).

I don't think this is a valid use case. While autobatching is certainly something we want to support in the future, it has nothing to do with "using a 1D tensor to represent control flow condition". In the loop case, autobatching works by vectorizing loops over single examples. In either batched programs or non-batched programs, control flow conditions are **always** a boolean, as this is a fundamental property of control flow.

2018-07-09 19:33 UTC, mhong commented
Thanks @rxwei for your input. I also had a discussion with @lattner. We will abandon this PR for now.

Some updated notes:
1. Indeed we are conceptually defining a new IR for accelerator functions, with its own instruction set (e.g. GraphOpInst) and rules/invariants. The most pragmatic infra for us is still SIL along with its transformation and verifier code though. 

So even though some of the optimization passes and associated invariants will not be applicable to accelerator functions (e.g. Arc optimization), none of such code (e.g. in verifier) is causing us much trouble. If some invariants being checked by verifier affect us down the road, we can revisit at that time what to do (e.g. selectively turn off code in verifier).

2. An example of vectorized condition check is that in CUDA programming, we can check if a vector of 32 bool values are true in a thread block, and for those cases that are true, process those elements (with a bit mask), and run some other code for the cases that are false as well (also with a bit mask). This is referred to as "divergent control flow".

In LLVM IR (and SIL), such vectorized logic is not expressed in the IR level -- presumably doing so would introduce too much change to the IR, such as the operand of cond_br. One option is to introduce new inst types like a `pcond_br` to do such vectorized condition evaluation.

As such, it's best not to change/extend `cond_br` for this.

3. If we want to extend SILFunction with custom info, we'll want to use attributes, instead of adding more member fields to its already large collection.

Thank you both again for the discussion!

2018-07-09 19:33 UTC, closed without merging

2018-07-10 00:30 UTC, mhong commented
Also, one option is to change the magic tf_tensor_to_i1 to a graph op inst (which needs to return a bool instead of a tensor result), so that we need less special-case code to deal with it.