[swiftSyntax] Fix issue where swiftc was not found when swiftSyntax is build via Xcode
swiftlang/swift pull request #18673
Opened 2018-08-13 16:06 UTC by ahoppen

`swiftSyntax` finds `swiftc` based on the directory layout of the build folder. However, that layout is different if `swiftSyntax` is built via Xcode than if it's built with Ninja. 

For Ninja: 
```
- bin/
  - swiftc
- lib/
  - swift/
    - ${target}/
      - libswiftSwiftSyntax.[dylib|so]
```

For Xcode:
```
- bin/
  - swiftc
- lib/
  - swift/
    - macosx/
      - x86_64/
        - libswiftSwiftSyntax.[dylib|so]
```

Allow `swiftSyntax` to find `swiftc` by traversing up to the `lib` folder and then moving to `bin/` instead of hardcoding the nesting level of `libswiftSwiftSyntax.dylib` inside `lib`.

2018-08-13 16:06 UTC, ahoppen commented
@swift-ci Please smoke test

2018-08-13 16:46 UTC, harlanhaskins commented on tools/SwiftSyntax/SwiftcInvocation.swift
> +    // Traverse the path up until we find the
Nitpick: unfinished comment

2018-08-13 17:05 UTC, harlanhaskins commented
This is definitely an improvement, thanks!

2018-08-13 17:16 UTC, ahoppen commented
@swift-ci Please smoke test and merge

2018-08-13 17:40 UTC, compnerd commented
Hmm, is there a reason to not try to make the layout uniform across the two builds?  It seems that it only complicates things to have the different layouts.  Making the code more robust anyways is probably a good idea.

2018-08-13 17:54 UTC, harlanhaskins commented
@compnerd I think this is the correct answer -- this library is going to be somewhere under `lib/` on all platforms, so walking up to `lib/` and then to `bin/` seems like a good way to support all layouts.

I agree that the layouts should match across platforms, but that's a more invasive change.

2018-08-13 17:56 UTC, ahoppen commented
@swift-ci Please smoke test and merge

2018-08-13 18:57 UTC, compnerd commented
@harlanhaskins - also would be interesting to consider windows :-)

2018-08-13 19:09 UTC, compnerd commented
Sorry @ahoppen about causing the conflicts.  Should be relatively easy to get these changes moved on top of the changes that I had.

2018-08-13 19:52 UTC, harlanhaskins commented
@compnerd Ah, yes! Apologies -- I am admittedly entirely uninformed of Windows library structure. What does the layout currently look like on Windows?

2018-08-13 20:08 UTC, ahoppen commented
@swift-ci Please smoke test

2018-08-13 21:33 UTC, jrose-apple requested changes
Yeah, this is incorrect, sorry. For Apple platforms, both Ninja and Xcode build into the architecture-specific directories first, but then lipo together all the architectures into the platform directory. If Xcode's not doing that for you we either have a CMake bug or you're building the wrong target.

2018-08-15 15:56 UTC, jrose-apple approved these changes

2018-08-15 18:09 UTC, merged