IDE: refactor USR generation to request evaluator model.
swiftlang/swift pull request #19005
Opened 2018-08-27 23:16 UTC by nkcsgexi

This patch adds a new TypeID zone for IDE usage, which contains
request kinds to answer IDE-interested questions. As a proof-of-concept,
we refactor the existing USR generation code to use the request evaluator
model. Most part of this patch is NFC, however a slight difference is
using this model allows us to cache the calculated USRs in the evaluator.

2018-08-27 23:16 UTC, nkcsgexi commented
@swift-ci please smoke test

2018-08-27 23:30 UTC, jrose-apple commented
Where does the name "TypeID" come from?

2018-08-27 23:39 UTC, DougGregor requested changes
I don't think there's any reason that this code (the IDE requests or their implementation) have to live in the AST library. Can you put all of it in the IDE library instead?

2018-08-27 23:39 UTC, DougGregor commented on lib/AST/USRGeneration.cpp
> +bool ide::printDeclUSR(const ValueDecl *D, raw_ostream &OS) {
It seems like this belongs in the IDE library.

2018-08-28 18:07 UTC, nkcsgexi commented
Talked with @DougGregor offline about this PR. Since the API `printDeclUSR` is used by `Serialization/ModuleFile.cpp` too, moving them entirely to IDE seems to be difficult. Instead, we drop the IDE requests ID zone for now and move the USR generation request to type checker requests.

2018-08-28 18:07 UTC, nkcsgexi commented
@swift-ci please smoke test

2018-08-28 18:33 UTC, nkcsgexi commented
The linux failure seems to be unrelated. @swift-ci Please clean test Linux platform

2018-08-28 23:26 UTC, nkcsgexi commented
@swift-ci Please clean test Linux platform

2018-08-29 00:17 UTC, nkcsgexi commented
all tests passed. @DougGregor OK to merge?

2018-08-29 17:49 UTC, merged