test: enable IRGen.generic_casts on all targets
swiftlang/swift pull request #19126
Opened 2018-09-04 21:44 UTC by compnerd

Adjust the test for ELF and COFF targets as well.  This allows us to get
additional test coverage and reduces the number of failing tests on Windows.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2018-09-04 21:44 UTC, compnerd commented
@swift-ci please test

2018-09-04 21:49 UTC, jrose-apple requested changes
We don't want to be testing ObjC details on non-ObjC-supporting platforms. That makes it harder for us to update any of this when it needs to be changed.

2018-09-05 16:44 UTC, compnerd commented
@jrose-apple I don't think that the changes required here are particularly onerous to maintain, and they are easy to verify against what clang does already.

2018-09-05 17:01 UTC, jrose-apple commented
Sure, but there's no point in enabling it either. It's not "additional test coverage" if it's testing an environment that can't happen.

2018-09-05 17:03 UTC, jrose-apple commented
(To me, it's a little different from the other tests you've turned on with `-enable-objc-interop`. It's good to make it easier for someone on non-macOS to check if they've broken ObjC interop. But that's only worth a certain amount of maintenance effort.)

2019-02-25 18:38 UTC, closed without merging