[Changelog] Add SE-0202 to 4.2
swiftlang/swift pull request #19383
Opened 2018-09-19 02:54 UTC by Azoy

2018-09-21 04:01 UTC, Azoy commented
cc: @natecook1000

2018-10-05 20:21 UTC, harlanhaskins commented
ping: @natecook1000

2018-10-05 20:53 UTC, natecook1000 requested changes
Ah, thanks! Looks good, with some minor points here.

2018-10-05 20:53 UTC, natecook1000 commented on CHANGELOG.md
> +  safe random number generator on each platform. All the randomization functions
Can you hyphenate "thread-safe"?

2018-10-05 20:53 UTC, natecook1000 commented on CHANGELOG.md
> +  let newGreetings = greetings.shuffled(using: &mt) // ["hola", "hi", "hey", "hello"]
I don't think we need to repeat all these here — maybe just one example of using `mt`?

2018-10-05 20:53 UTC, natecook1000 commented on CHANGELOG.md
> +      // Algorithm stuff here
`// implementation` instead?

2018-10-05 20:53 UTC, natecook1000 commented on CHANGELOG.md
> +  function.
"...introduce a new static method that creates a random value."

2018-10-05 20:53 UTC, natecook1000 commented on CHANGELOG.md
> +  There are also a couple of collection additions included as well.
"There are also additions to select a random element from a collection or shuffle its contents."

2018-10-05 21:20 UTC, natecook1000 approved these changes

2018-10-05 21:20 UTC, natecook1000 commented
LGTM, thanks @Azoy!

2018-10-05 21:20 UTC, natecook1000 commented
@swift-ci Please smoke test and merge

2018-10-05 21:59 UTC, natecook1000 commented
@swift-ci Please smoke test and merge

2018-10-05 23:00 UTC, merged