Add support for using Dispatch in lit tests on Linux
swiftlang/swift pull request #19836
Opened 2018-10-11 20:27 UTC by kubamracek

Today, several lit tests use and test Dispatch, but this is only available on macOS/iOS and gated behind `REQUIRES: objc_interop`. This PR introduces a different flag, `REQUIRES: dispatch` and makes it available on Linux (if you use build-script with --libdispatch). The individual pieces:

- In build-script, when building libdispatch on Linux, copy the resulting libdispatch.so and swiftmodule files to the right location in the Swift resource directory.
- In lit, detect whether the build has libdispatch.so, and add `dispatch` as an available feature. On macOS, this is always available.
- Change a few tests to use `REQUIRES: dispatch` instead of `REQUIRES: objc_interop`
- Remove the Dispatch module from mock SDKs.

2018-10-11 20:29 UTC, kubamracek commented
@swift-ci please test

2018-10-12 00:39 UTC, compnerd commented on test/lit.cfg
> +      if os.path.exists(make_path(config.swift_lib_dir, "swift", "linux", "libdispatch.so")):
Do we ever test with the static variant of the runtime?  We may have those enabled, so we need to check both :-(.

2018-10-12 00:39 UTC, compnerd commented on test/stdlib/DispatchData.swift
> +#endif
OMG, this is beautiful!  I ended up doing some more ... intensive refactoring in swift-syntax to deal with the autoreleasepool.

2018-10-12 00:39 UTC, compnerd commented on utils/build-script-impl
> +                  continue
Woah, I do not understand this magic at all.  Why can we not use the normal build/install rules?

2018-10-12 16:14 UTC, vlm approved these changes

2018-10-23 00:06 UTC, jrose-apple requested changes

2018-10-23 00:06 UTC, jrose-apple commented on test/Inputs/clang-importer-sdk/usr/include/dispatch.h
> -#import <objc/NSObject.h>
This seems suspect to me. test/Inputs/clang-importer-sdk is a fake SDK under the control of the tests, which means anything depending on this should *not* be using the real Dispatch.

2019-05-13 23:36 UTC, closed without merging