Add `(rhs: Self, lhs: Self)` function to `==` and `<` operators.
swiftlang/swift pull request #19917
Opened 2018-10-16 19:28 UTC by MrLotU

While conforming a custom type to `BinaryInteger`, I found in the docs that for all binary comparison operators except for `==` and `<`, there are 2 functions, one with arguments `(lhs: Self, rhs: Self)` and one with arguments `(lhs: Self, rhs: Other)` with `Other being a generic parameter that conforms to `BinaryInteger` (see the docs [here](https://developer.apple.com/documentation/swift/binaryinteger/2884492) and [here](https://developer.apple.com/documentation/swift/binaryinteger/2886190) for both versions of the `>` operator).

For consistency reasons, I felt like both methods should be there for all operators, not excluding two at (seemingly) random.

2018-10-16 19:28 UTC, tanner0101 approved these changes

2018-10-16 19:32 UTC, joscdk approved these changes

2018-10-16 19:43 UTC, MrLotU commented
@swift-ci Please test

2018-10-16 23:05 UTC, moiseev commented on stdlib/public/core/Integers.swift
> +    return lhs == rhs
This invocation will result in an infinite recursion.

2018-10-16 23:11 UTC, xedin requested changes
@MrLotU Thanks for the patch! The biggest problem here is that new members are going to be self-recursive just like this example:

```swift
protocol P {
  func foo(_ b: Self) -> Bool
}

extension P {
  func foo(_ b: Self) -> Bool {
    return self.foo(b)
  }
}

struct S : P {}

let a: S = S()
let b: S = S()

a.foo(b)
```

/cc @moiseev

2018-10-16 23:24 UTC, xwu requested changes
The methods `==(Self, Self)` and `<(Self, Self)` don't have default implementations because they are the two methods that must be implemented, on the basis of which all others are defined. It is not an arbitrary omission.

2018-10-17 10:03 UTC, xwu commented
Every comparison operator has homogeneous and heterogeneous implementations. None are missing. However, you can’t have default implementations of all of them—that would cause infinite recursion. A concrete type needs to implement _something_. In Swift, that something is the concrete homogeneous ‘==‘ and ‘<‘ operators. Therefore, they don’t have default implementations.

2019-11-15 19:31 UTC, natecook1000 commented
Closing this. @MrLotU, if you'd like to continue the discussion, feel free to re-open or start a discussion on the forums!

2019-11-15 19:31 UTC, closed without merging