Syntax: correct implementation for `removing`
swiftlang/swift pull request #19972
Opened 2018-10-21 22:14 UTC by compnerd

`llvm::ArrayRef<T>` does not define `erase`.  However, since the intent
here is to remove the last n elements, we can use `drop_back` instead.
Furthermore, replace the direct use of `Layout` with `getLayout()`.
This was identified by gcc 8.2.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2018-10-21 22:14 UTC, compnerd commented
CC: @bitjammer

2018-10-21 22:14 UTC, compnerd commented
@swift-ci please test

2018-10-22 10:22 UTC, rintaro requested changes
The intent here is to remove an element at `i`.
E.g. given `[A, B, C, D]`, `removing(2)` returns `[A, B, D]`.

2018-10-22 15:53 UTC, compnerd commented
@rintaro - bleh, yes, I see your point now that I look at it again.  The model that I had in mind was that of an erase from iterator as in the STL.

2018-10-23 17:05 UTC, compnerd commented
@swift-ci please test

2018-10-24 09:07 UTC, rintaro commented on include/swift/Syntax/SyntaxCollection.h
> +    std::advance(iterator, i - 1);
I'm not sure `i - 1` is correct. What if i == 0?
Also, could you add test cases in `unittests/Syntax/SyntaxCollectionTests.cpp`?

2018-10-26 00:31 UTC, compnerd commented
@swift-ci please test

2018-10-29 04:04 UTC, rintaro commented
@swift-ci please test

2018-10-29 05:51 UTC, rintaro commented on unittests/Syntax/SyntaxCollectionTests.cpp
> +  llvm::raw_svector_stream OS(Scratch);
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/swift/unittests/Syntax/SyntaxCollectionTests.cpp:272:27: error: expected ';' after expression
23:37:50   llvm::raw_svector_stream OS(Scratch);
23:37:50                           ^
23:37:50                           ;
```
I guess:
```suggestion
  llvm::raw_svector_ostream OS(Scratch);
```

2018-10-29 20:19 UTC, compnerd commented
@swift-ci please test

2018-10-30 02:37 UTC, rintaro approved these changes
Thank you!

2018-10-30 02:37 UTC, merged