[silgen] When emitting a top level error, destroy the error after we …
swiftlang/swift pull request #20033
Opened 2018-10-25 03:14 UTC by gottesmm

…have logged it.

This is not strictly necessary since we are going to be exiting the program, but
the ownership verifier thinks that the error is leaked otherwise.

rdar://29791263

2018-10-25 03:15 UTC, gottesmm commented
@swift-ci smoke test

2018-10-25 15:33 UTC, jrose-apple commented
Can we put the destroy after the call to `errorInMain`? Or make `errorInMain` return `Never`?

2018-10-25 16:17 UTC, gottesmm commented
@jrose-apple the destroy is after the call to errorInMain... This is an error path so I am not sure if it is worth optimizing out the destroy. That being said, I could use an end_lifetime and we could just leak it using that.

2018-10-25 16:28 UTC, jrose-apple commented
Oops, not sure how I misread that! Okay, so we're not paying the run time cost…but we might still be paying in code size.

2018-10-26 01:18 UTC, gottesmm commented
Ok. I can make that change. I don't think the code-size impact is large... but why not save some if we can.

2018-10-26 01:34 UTC, gottesmm commented
@swift-ci smoke test and merge

2018-10-26 01:34 UTC, gottesmm commented
@swift-ci smoke test and merge

2018-10-26 01:34 UTC, gottesmm commented
@swift-ci smoke test and merge

2018-10-26 01:34 UTC, gottesmm commented
@swift-ci smoke test and merge

2018-10-26 16:35 UTC, gottesmm commented
@swift-ci smoke test os x platform

2018-10-26 16:35 UTC, gottesmm commented
@swift-ci smoke test os x platform

2018-10-26 17:12 UTC, jckarter requested changes
Can we encode that the program is ending in SIL somehow instead?

2018-10-26 17:32 UTC, gottesmm commented
@jckarter That feels like a larger design question to me. I think the simplest way that one could do that is to have a privileged return value. But I think we would need to discuss that and I am not sure if that should hold up this PR.

2018-10-29 21:39 UTC, gottesmm commented
I talked with @jckarter offline. He is ok with my merging this and filing an SR with his enhancement proposal. It is here: https://bugs.swift.org/browse/SR-9114.

2018-10-29 21:39 UTC, merged