[Exclusivity] Remove dominated access checks with no nested conflict.
swiftlang/swift pull request #20053
Opened 2018-10-25 22:22 UTC by shajrawi

Radar rdar://problem/42789656

General case:

—
begin_access A (may or may not have no_nested_conflict)
load/store
end_access

apply // may have a scoped access that conflicts with A

begin_access A [no_nested_conflict]
load/store
end_access A
—

The second access scope does not need to be emitted.

NOTE: KeyPath access must be identified at the top-level, non-inlinable stdlib entry point.
As such, The sodlib entry pointed is annotated by a new @_semantics that is equivalent to inline(never)

2018-10-25 23:28 UTC, shajrawi commented
@swift-ci Please test OS X

2018-10-26 02:48 UTC, shajrawi commented
@swift-ci Please test

2018-10-26 02:48 UTC, shajrawi commented
@swift-ci Please test

2018-10-26 02:51 UTC, shajrawi commented
@eeckstein I have added a new commit that makes the changes we discussed offline - mainly bailing out when encountering unpaired accesses and the new recursive walk that avoids explicitly checking for proper dominance:

I went with a small vector of `(begin_access, storage location)` that only keeps track of distinct storage locations that can be optimized (which should be a tiny set no matter the size of the function or number of begin_access instructions in it)

This vector keeps track of the first `(begin_access, storage location)` seen in the dominator (sub)tree.

When encountering a `begin_access` instruction we just have to see if its `storage location` is in said vector or not - iterating over a handful of unique storage locations at the most

When we are done with a sub-tree, we just have to remove the new elements in the small vector, which are the last entries we pushed back, this is efficiently implemented of course.

2018-10-26 06:41 UTC, shajrawi commented
@swift-ci Please test OS X

2018-10-26 15:29 UTC, shajrawi commented
@swift-ci Please smoke test OS X

2018-10-26 15:29 UTC, shajrawi commented
@swift-ci Please smoke test OS X

2018-10-26 16:29 UTC, eeckstein requested changes
the basic algorithm looks good.

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +// restrictions Such as key-path or unpaired begin access We only traverse the
typo: missing "." after "access"

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +// we bail to Simplify the code instead of handling unpaired accesses
typo "simplify"

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +  auto newNumOfElems = visitedDomAccessesToStorageInfo.size();
please inline this expression into the assert. Otherwise you'll get a warning in the release build

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +bool DominatedAccessRemoval::visitInstruction(
Please add a comment what the boolean return value means

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +  KeyPathEntryPointsSet keypathEntries;
Any reason you are not handling the key path calls like unpaired accesses?

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +  DomPairSet domPairs;
This doesn't need to be a pair. You don't care about the first begin_access instruction. It's sufficient to just keep a list of begin_accesses to set the static flag. Also, "Set" is a bad name for it as it is a vector

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +    if (!callee->hasSemanticsAttr("_keyPathEntryPoint"))
Is this the right check? Isn't it a decl attribute and not a semantic attribute?

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +    keypathEntries.insert(fullApply.getInstruction());
Why not just return false here (and treat it like unpaired accesses)?

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +    return !currStorage.isDistinctFrom(storage);
I think is is the wrong check. AFAIK, !isDistinct is not the inverse of locations being equal. And the equal-check is needed to be able to optimize the access.

2018-10-26 16:29 UTC, eeckstein commented on test/SILOptimizer/access_dom.sil
> +}
Please add a test with a key path

2018-10-26 16:29 UTC, eeckstein commented on lib/SILOptimizer/Transforms/AccessEnforcementDom.cpp
> +    AccessedStorageInfo &visitedDomAccessesToStorageInfo) {
It's okay that AccessedStorageInfo is a vector - assuming that it's small in the common case.
But you have to add a bail-out check if it gets larger than a certain limit, to avoid quadratic compile time in corner cases.

Also, you have to add a maximum-recursion-depth check because for very large functions, with lot of control flow, you can run into a stack overflow here.

2018-10-26 18:02 UTC, shajrawi commented
@swift-ci Please smoke test

2018-10-26 18:03 UTC, shajrawi commented
@swift-ci Please smoke test

2018-10-26 18:03 UTC, shajrawi commented
@eeckstein I’ve done all the changes in the review, including adding recursion and quadratic compile time bail-outs, new key path test and bug-fix for the equal-check of accesses. I also changed the new attribute from a decl attribute to a semantic attribute

2018-10-26 18:23 UTC, eeckstein approved these changes
LGTM!

2018-10-26 20:22 UTC, merged