[stdlib] Remove a bunch of unused public inlinable functions from Runtime
swiftlang/swift pull request #20223
Opened 2018-11-01 19:08 UTC by moiseev

2018-11-01 19:08 UTC, moiseev commented
@swift-ci Please benchmark

2018-11-01 19:08 UTC, moiseev commented
@swift-ci Please test

2018-11-01 21:18 UTC, moiseev commented
@milseman can you take a look if this removes something UTF-8 uses?

2018-11-01 22:20 UTC, moiseev commented
@swift-ci Please test macOS platform

2018-11-02 18:23 UTC, milseman requested changes
Pretty much all of these annotations should go away, not be approved for inclusion in our ABI

2018-11-02 18:31 UTC, milseman commented on stdlib/public/core/Runtime.swift.gyb
>  public final class _stdlib_AtomicInt {
Agreed

2018-11-02 19:09 UTC, moiseev commented
@swift-ci Please test

2018-11-02 19:09 UTC, moiseev commented
Updated the PR to just removing the unused functions.

2018-11-02 21:15 UTC, lorentey approved these changes
The removals look good!

2018-11-02 21:43 UTC, moiseev commented
@swift-ci Please test macOS platform

2018-11-05 19:03 UTC, moiseev commented
Resolved the conflicts.
@swift-ci Please smoke test

2018-11-05 23:08 UTC, milseman approved these changes
LGTM

2018-11-06 02:04 UTC, merged