Updated SwiftPrivate.swift using String Interpolation
swiftlang/swift pull request #20243
Opened 2018-11-02 15:34 UTC by arguiot

I updated /stdlib/private/SwiftPrivate/SwiftPrivate.swift using String Interpolations, so the code is more readable and more "Swifty". I also updated the copyright to 2018.

This PR doesn't resolve any bugs or issue.

2018-11-02 15:47 UTC, arguiot commented
@swift-ci Please smoke test

2018-11-02 18:01 UTC, harlanhaskins commented on stdlib/private/SwiftPrivate/SwiftPrivate.swift
> -  return "[ " + x.lazy.map { asHex($0) }.joined(separator: ", ") + " ]"
Can you change these indentations back to 2 spaces? The Swift standard library prefers 2-space indentation.

2018-11-02 20:04 UTC, lorentey requested changes
We prefer to use 2 spaces for indentation; otherwise the change looks good to me!

2018-11-04 23:19 UTC, arguiot commented
@xwu I applied your changes

2018-11-06 19:16 UTC, moiseev commented
@swift-ci Please smoke test

2018-11-06 19:17 UTC, moiseev approved these changes
:shipit:

2018-11-06 19:19 UTC, lorentey approved these changes
Looking good!

2018-11-06 22:49 UTC, merged