Runtime: add UnknownObject on non-ObjC builds
swiftlang/swift pull request #20309
Opened 2018-11-04 01:06 UTC by compnerd

The UnknownObject type is used for the block convention block pointers.
This is used in libdispatch and we cannot build for Windows without it.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2018-11-04 01:06 UTC, compnerd commented
CC: @jckarter @mikeash

2018-11-04 01:06 UTC, compnerd commented
@swift-ci please test

2018-11-04 02:44 UTC, jckarter commented
This shouldn't be necessary. How does libdispatch work on Linux?

2018-11-04 02:45 UTC, jckarter requested changes
This shouldn't be necessary. How does libdispatch work on Linux? You may need the *value witness table*, but the type should not have to exist.

2018-11-04 02:56 UTC, compnerd commented
@jckarter pretty sure that it is getting away since not all symbols need to be fulfilled by default on ELF (`-z defs` is not the default).

2018-11-04 03:09 UTC, troughton commented
FWIW, when I built the Swift Dispatch overlays on Windows against [DrPizza's libdispatch port](https://github.com/DrPizza/libdispatch) I didn't need to make any compiler changes, although I did need to enable support for and link in the Blocks runtime to the libdispatch library. I'm not sure what's different to cause you to need changes here.

2018-11-04 04:17 UTC, compnerd commented
@troughton this is specifically the SDK overlay which is not part of that port I believe.

@jckarter btw, this is a smaller reduced case:

```
class C {
  var _block: @convention(block) () -> Void
  init(block: @escaping @convention(block) () -> Void) {
    self._block = block
  }
}
```

You're correct in that Linux for some reason does not generate that reference!  The reference is generated in the type metadata completion function for C.  I don't see that being generated on Linux for some reason?

2018-11-04 04:57 UTC, troughton commented
If it helps to narrow down the problem:

By the Dispatch overlays I mean that [these files](https://github.com/troughton/SwiftFrameGraph/tree/master/Sources/WindowsOverlays/Dispatch), along with the C stubs reimplemented in https://github.com/troughton/SwiftFrameGraph/blob/d008724c7fdc8af525d484ee074d855c2017676b/Sources/WindowsOverlays/CFoundationExtras/DispatchStubs.cc.

When linked against the Windows SDK and built for x64 Windows this did not require any compiler changes against a Swift 4.1 toolchain.

2018-11-04 05:50 UTC, compnerd commented
@jckarter I wonder if this is a result of the lazy initialized metadata ... which may now emit the completion function for the initialization?

2018-11-04 16:04 UTC, jckarter commented
@compnerd Are you sure it's not only looking for the value witness table?

2018-11-04 18:05 UTC, jckarter approved these changes

2018-11-04 18:05 UTC, jckarter commented
I see. It would be nice to only include the value witness table, but that's splitting hairs a bit.

2018-11-05 00:08 UTC, compnerd commented
@swift-ci please test macOS platform

2018-11-05 01:30 UTC, compnerd commented
@swift-ci please clean test macOS platform

2018-11-05 04:04 UTC, merged