Finish removing -swift-version 3
swiftlang/swift pull request #20409
Opened 2018-11-07 22:40 UTC by slavapestov

Fixes <rdar://problem/43101816>.

2018-11-07 22:40 UTC, slavapestov commented
@swift-ci Please test

2018-11-07 22:40 UTC, slavapestov commented
@swift-ci Please test source compatibility

2018-11-07 22:41 UTC, slavapestov commented
@swift-ci Please test

2018-11-07 22:41 UTC, slavapestov commented
@swift-ci Please test source compatibility

2018-11-07 23:14 UTC, dnadoba requested changes

2018-11-07 23:14 UTC, dnadoba commented on include/swift/Basic/Version.h
>    static std::array<StringRef, 4> getValidEffectiveVersions() {
Array size should be 3 instead of 4
```suggestion
   static std::array<StringRef, 3> getValidEffectiveVersions() {
```

2018-11-07 23:39 UTC, benrimmington commented
See also #20374

2018-11-08 01:41 UTC, slavapestov commented
Oops, I didn't realize we made the same change here. @tkremenek The only significant difference I see is that I removed the swift3 lit substitutions from lit.cfg, and XFAILd the offending tests. Do you want to take over?

2018-11-09 21:50 UTC, tkremenek commented
Yeah I'll take over.

2018-11-14 01:41 UTC, slavapestov commented
Thanks Ted!

2018-11-14 01:41 UTC, closed without merging