Disable really large Data tests that take a bit too long to run
swiftlang/swift pull request #20411
Opened 2018-11-07 23:04 UTC by phausler

The benchmarks for Data are a bit harsh for CI to run. This disables the really big ones.

2018-11-07 23:04 UTC, phausler commented
@swift-ci please smoke test

2018-11-07 23:44 UTC, eeckstein requested changes
Please also disable DataCountLarge

2018-11-07 23:44 UTC, eeckstein commented on benchmark/single-source/DataBenchmarks.swift
>      BenchmarkInfo(name: "DataCountLarge", runFunction: run_CountLarge, tags: [.validation, .api, .Data]),
Can you also disable this one. It also takes long.

2018-11-07 23:49 UTC, phausler commented
@swift-ci please smoke test and merge

2018-11-08 00:06 UTC, airspeedswift commented
While we're looking, `IterateData` is very noisy – it appears in about half of my benchmark runs.

2018-11-09 22:48 UTC, phausler commented
@swift-ci please smoke test

2018-11-09 22:48 UTC, eeckstein approved these changes

2018-11-10 00:14 UTC, merged

2018-11-10 20:33 UTC, gottesmm commented
@phausler just a suggestion. Maybe we should have a .long tag or something like that (and maybe run them during the long test?) not sure.

2018-12-20 10:52 UTC, palimondo commented
@airspeedswift Re: noisy `IterateData`. With what benchmark running method are you seeing this?