[stdlib] Fixed for Cygwin
swiftlang/swift pull request #20482
Opened 2018-11-09 22:46 UTC by tinysun212

- Cygwin uses Newlib (https://en.wikipedia.org/wiki/Newlib) as the C runtime library.
  In Cygwin, Newlib was called Glibc. Newlib can now be called Newlib.
- COFF image inspection code patched for Cygwin (and MinGW).
- VarArgs, RefCount and other minor patches

2018-11-12 18:28 UTC, compnerd requested changes

2018-11-16 21:53 UTC, tinysun212 commented on stdlib/public/Platform/newlib.modulemap.gyb
> +  // link directive doesn't work in the submodule yet.
The link directive function seems to depend on the clang library. This comment was copied from the `glibc.modulemap.gyb` file.

2018-11-17 00:09 UTC, tinysun212 commented on stdlib/public/SwiftShims/RefCount.h
> +//   In MinGW and Cygwin, we force SideTableRefCountBits object align to 16 bytes and prevent crash.
Fixed it and amended commit.

2018-11-17 00:10 UTC, tinysun212 commented on stdlib/public/SwiftShims/RefCount.h
> +//   When __atomic_load() accepts 16 bytes object, it should be aligned 16 bytes or will be crashed.
Replaced

2018-11-17 00:10 UTC, tinysun212 commented on stdlib/public/SwiftShims/RefCount.h
> +#else
Removed the conditional

2018-11-17 00:11 UTC, tinysun212 commented on stdlib/public/core/VarArgs.swift
> +// On the 64bit Windows, the va_list structure is similar to the one defined
Replaced

2018-11-17 00:11 UTC, tinysun212 commented on stdlib/public/runtime/SwiftRT-COFF.cpp
> +  __attribute__((section("." #name "$A"))) static uintptr_t __start_##name = 0; \
Modified

2018-11-17 00:13 UTC, tinysun212 commented on stdlib/public/runtime/SwiftRT-COFF.cpp
> +#else
It worked without this. Removed the `pSwiftImageConstructor` declaration.

2018-11-17 00:15 UTC, tinysun212 commented on stdlib/public/stubs/LibcShims.cpp
> +#if !defined(_MSC_VER)
Removed this patch. It was not needed.

2018-11-17 00:20 UTC, tinysun212 commented
@compnerd I modified the files and amended the commit. Thanks for your review.

2018-11-19 04:05 UTC, compnerd commented on stdlib/public/Platform/newlib.modulemap.gyb
> +  // link directive doesn't work in the submodule yet.
Does it really apply to newlib?

2018-11-19 18:49 UTC, tinysun212 commented on stdlib/public/Platform/newlib.modulemap.gyb
> +  // link directive doesn't work in the submodule yet.
Yes, It does. Newlib in Cygwin is very similar to Glibc in Linux, but not equal to.

2019-11-14 20:57 UTC, CodaFi commented
@tinysun212 Could you please rebase this pull request so we can re-test these changes?

2020-02-10 06:03 UTC, futurejones commented
Can one of the admins verify this patch?

2020-04-10 22:25 UTC, CodaFi commented
Alright, it's been quite a while and this patch hasn't seen much activity in a few years now. I'm going to close this out. Thanks!

2020-04-10 22:25 UTC, closed without merging