Make sure the code completion takes both private imports and testable
swiftlang/swift pull request #20525
Opened 2018-11-12 22:55 UTC by aschwaighofer

imports into account separately.

2018-11-12 22:55 UTC, aschwaighofer commented
@swift-ci Please test

2018-11-13 16:10 UTC, aschwaighofer commented
@swift-ci Please test

2018-11-13 16:13 UTC, aschwaighofer commented
@swift-ci Please test

2018-11-13 20:14 UTC, benlangmuir requested changes
Please add a test case in test/IDE/complete_cache.swift. There's one for `@testable` that you could base it on.  Otherwise, LGTM!

2018-11-13 20:14 UTC, benlangmuir commented on include/swift/AST/Module.h
> +    /// Return the resuls for testable or private imports.
typo: missing "t" in results.

2018-11-14 14:29 UTC, aschwaighofer commented
@swift-ci Please smoke test

2018-11-14 15:25 UTC, benlangmuir approved these changes

2018-11-14 15:51 UTC, merged