Add a test for a compiler crasher with -O -whole-module-optimization -sanitize=address
swiftlang/swift pull request #21385
Opened 2018-12-17 22:06 UTC by kubamracek

Add a test for <https://github.com/apple/swift-llvm/pull/133>.

2018-12-17 22:11 UTC, rjmccall commented on test/Interpreter/asan-globals-overwrite.swift
> +// RUN: %target-run %t
I think this is `%target-run-simple-swift(-O -whole-module-optimization -sanitize=address)`.

2019-11-18 21:54 UTC, CodaFi commented
Still good to have this test

@swift-ci please smoke test

2020-02-10 06:03 UTC, futurejones commented
Can one of the admins verify this patch?

2020-02-10 17:42 UTC, yln commented on test/Interpreter/asan-globals-overwrite.swift
> +// REQUIRES: objc_interop
`REQUIRES: foundation`

2020-02-11 17:42 UTC, danliew-apple commented
Interesting this looks like an old PR that didn't get merged.

2020-02-11 17:45 UTC, ghost requested changes
I don't know why this test is in `test/Interpreter/`, we aren't using the interpreter in this test are we?
It sound probably be in `test/Sanitizers` with the other sanitizer test cases.

2020-02-11 17:45 UTC, danliew-apple commented on test/Interpreter/asan-globals-overwrite.swift
> +// REQUIRES: objc_interop
Probably needs `REQUIRES: asan_runtime` if we are actually going to run.

2020-04-14 22:48 UTC, CodaFi commented
Merged in #31008.

2020-04-14 22:48 UTC, closed without merging