AST: Cache ProtocolDecl::getInheritedProtocols() [5.0]
swiftlang/swift pull request #21971
Opened 2019-01-18 02:09 UTC by slavapestov

Fixes <rdar://problem/47371754>.

2019-01-18 02:09 UTC, slavapestov commented
@swift-ci Please test

2019-01-18 04:08 UTC, DougGregor requested changes

2019-01-18 04:08 UTC, DougGregor commented on include/swift/AST/Decl.h
> +    InheritedProtocolsValid : 1,
You need to set this to `false` in the constructor!

2019-01-18 04:21 UTC, slavapestov commented
@swift-ci Please test

2019-01-18 04:22 UTC, DougGregor approved these changes

2019-01-18 05:36 UTC, slavapestov commented
@swift-ci Please test

2019-01-18 21:42 UTC, slavapestov commented
@swift-ci Please test

2019-01-19 00:32 UTC, AnnaZaks approved these changes

2019-01-19 00:33 UTC, merged