Refactor the mandatoryOpt pipeline for use in LLDB
swiftlang/swift pull request #22303
Opened 2019-02-01 20:44 UTC by bgogul

Refactor some of the mandatoryOpt pipeline code for use in LLDB. (See https://github.com/apple/swift-lldb/pull/1268)

2019-02-01 20:45 UTC, bgogul commented
@swift-ci please test tensorflow

2019-02-01 21:09 UTC, dan-zheng reviewed
Is the underlying problem that generated primal/adjoint/jvp/vjp functions don't have the right "qualified ownership"-ness?
If so, changing that and doing raw stage serialization seems like a more robust fix. It'd look like:
```diff
   vjp = fb.createFunction(linkage, vjpName, vjpType, vjpGenericEnv,
                           original->getLocation(), original->isBare(),
                           IsNotTransparent, original->isSerialized(),
                           original->isDynamicallyReplaceable());
-  vjp->setUnqualifiedOwnership();
+  if (!original->hasQualifiedOwnership())
+    vjp->setUnqualifiedOwnership();
// Same for primal/adjoint/jvp.
```

2019-02-01 21:09 UTC, dan-zheng commented on lib/SILOptimizer/PassManager/Passes.cpp
> +
minor: extra newline

2019-02-01 21:14 UTC, marcrasi requested changes
I have an idea for a less-invasive change that will be easier to keep in sync with upstream. Not totally sure if it will work.

Three pieces:
1. Add a `SerializeForDifferentiation` to `class SILOptions`.
2. In `addMandatoryOptPipeline`, add `if (Options.SerializeForDifferentiation) { P.addSerializeSILPass() }`
3. I think that the SerializeSILPass works by calling a serialization callback that has been registered on the SILModule. So you'll have to refactor the LLDB code to do the serialization in a closure, and then register that closure with `sil_module->setSerializeSILAction()`.

2019-02-01 21:19 UTC, marcrasi commented
I like this overall approach of running all the pre-differentiation passes before serializing in LLDB, because it pretty much guarantees that when LLDB tries to load a function and differentiate it, the differentiation pass will see the exact same SIL in the body that it would have seen if it had decided to differentiate it in the first place. This will make it a lot more likely to always work, even if there are even more problems with differentiating raw SIL that we don't know about yet.

If you add a `SerializeForDifferentiation` option, that would be a nice place to put a comment explaining this reasoning.

2019-02-01 22:02 UTC, bgogul commented
> I like this overall approach of running all the pre-differentiation passes before serializing in LLDB, because it pretty much guarantees that when LLDB tries to load a function and differentiate it, the differentiation pass will see the exact same SIL in the body that it would have seen if it had decided to differentiate it in the first place. This will make it a lot more likely to always work, even if there are even more problems with differentiating raw SIL that we don't know about yet.
> 
> If you add a `SerializeForDifferentiation` option, that would be a nice place to put a comment explaining this reasoning.

Nice. I did think about adding an option to SILOptions and may be messing around with the mandatory pipeline. However, your suggestion of adding a call-back for serialization seems much cleaner and much less invasive.

2019-02-02 00:55 UTC, bgogul commented
This is much cleaner now. Thanks, Marc. PTAL.

2019-02-02 01:00 UTC, marcrasi approved these changes
Yay!

2019-02-03 00:21 UTC, rxwei approved these changes

2019-02-04 19:29 UTC, merged