Generate CodeView by deafult for Windows
swiftlang/swift pull request #22625
Opened 2019-02-14 22:51 UTC by lanza

llvm, lldb and swift combine to offer better support for PDBs on
Windows than it does DWARF. Default to generating PDBs on Windows.

2019-02-14 22:51 UTC, lanza commented
After #22624 goes in this would be the most sane default.

2019-02-14 22:52 UTC, compnerd commented
Please add a driver level test to ensure that we do this.

2019-02-14 22:52 UTC, compnerd commented
CC: @dcci

2019-03-12 20:49 UTC, lanza commented
@compnerd This fails to build on Windows due to the pdb gen bug you hit. WIP

2019-11-18 22:04 UTC, CodaFi commented
Let's see what happens

@swift-ci please smoke test

2019-11-18 22:04 UTC, CodaFi commented
@swift-ci please test Windows platform

2019-12-04 17:54 UTC, compnerd commented
welp, thats going to destroy the test suite on Windows; I think that we should ensure that those work before merging this

2019-12-04 18:01 UTC, dcci requested changes
Agree. Also it feels like a bug to me that Windows failing doesn't prevent the PR from being merged.

2019-12-05 04:54 UTC, CodaFi commented
@lanza I think we can merge this if you XFAIL or fix these tests:

```
    Swift(windows-x86_64) :: IRGen/condfail_message.swift
    Swift(windows-x86_64) :: DebugInfo/variables.swift
    Swift(windows-x86_64) :: DebugInfo/tuple.swift
    Swift(windows-x86_64) :: DebugInfo/top_level_code.swift
    Swift(windows-x86_64) :: DebugInfo/shadowcopy-linetable.swift
    Swift(windows-x86_64) :: DebugInfo/scopes.swift
    Swift(windows-x86_64) :: DebugInfo/return.swift
    Swift(windows-x86_64) :: DebugInfo/prologue.swift
    Swift(windows-x86_64) :: DebugInfo/patternmatching.swift
    Swift(windows-x86_64) :: DebugInfo/linetable.swift
    Swift(windows-x86_64) :: DebugInfo/line-directive.swift
    Swift(windows-x86_64) :: DebugInfo/letstring.swift
    Swift(windows-x86_64) :: DebugInfo/iteration.swift
    Swift(windows-x86_64) :: DebugInfo/inlinedAt.swift
    Swift(windows-x86_64) :: DebugInfo/inlinescopes.swift
    Swift(windows-x86_64) :: DebugInfo/implicitreturn.swift
    Swift(windows-x86_64) :: DebugInfo/gsil.swift
    Swift(windows-x86_64) :: DebugInfo/foreach.swift
    Swift(windows-x86_64) :: DebugInfo/fnptr.swift
    Swift(windows-x86_64) :: DebugInfo/enum.swift
    Swift(windows-x86_64) :: DebugInfo/columns.swift
    Swift(windows-x86_64) :: DebugInfo/closure-args.swift
    Swift(windows-x86_64) :: DebugInfo/basic.swift
    Swift(windows-x86_64) :: DebugInfo/bool.swift
    Swift(windows-x86_64) :: DebugInfo/any.swift
    Swift(windows-x86_64) :: DebugInfo/alloca-init.swift
    Swift(windows-x86_64) :: DebugInfo/NestedTypes.swift
    Swift(windows-x86_64) :: DebugInfo/Imports.swift
    Swift(windows-x86_64) :: DebugInfo/ImportsStdlib.swift
    Swift(windows-x86_64) :: DebugInfo/EagerTypeMetadata.swift
```

2019-12-05 17:58 UTC, dcci commented
I wouldn't really XFAIL these tests. It means that there are potentially big holes in CodeView Windows support and merging this patch would lead to false expectations of what works and what doesn't (or maybe tests just need to be updated and everything works fine, in which case, well, we should do it sooner rather than later).

2020-02-10 06:02 UTC, futurejones commented
Can one of the admins verify this patch?

2020-04-14 23:28 UTC, CodaFi commented
@lanza I'm going to close this out since it seems like this needs to be handled incrementally to avoid disrupting the Windows build.

2020-04-14 23:28 UTC, closed without merging