SILGen: Short-cut bind_optional_exprs that are used by objective-c pr…
swiftlang/swift pull request #22728
Opened 2019-02-19 23:04 UTC by aschwaighofer

…operty and method calls

obj?.method() // We may just forward the value of obj to method()

Objective-C's message send returns nil for a message send to nil so we
can skip the enum switch on the optional value and use it as is.

rdar://48007302

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2019-02-19 23:05 UTC, aschwaighofer commented
@swift-ci Please test

2019-02-20 01:13 UTC, slavapestov requested changes
I really don’t like this change. Please redo it as a SIL optimizer pass as John points out below.

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenExpr.cpp
> +    MarkBindOptionalShortCut shortCut(SGF, E);
This is for a member access that is a type, eg something like type(of: value).SomeNestedClass. This doesn’t apply here.

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenExpr.cpp
> +    B.createBranch(loc, someBB);
You don’t need the basic block at all in this case I think. It should be enough to just bitcast the optional to its payload type.

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenLValue.cpp
> +                     .getObjectType()
I don’t think the getObjectType() is necessary

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenExpr.cpp
> +  auto hasAcceptableOuputType = [](Expr *expr) -> bool {
Typo: Ouput not Output

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenExpr.cpp
> +    if (!func->getDecl()->isObjC())
isObjC() is not the same as “called via objc_msgSend”

2019-02-20 01:13 UTC, slavapestov commented on lib/SILGen/SILGenExpr.cpp
> +BindOptionalExpr *SILGenFunction::maySkipSwitchInBindOptionalSubExpr(Expr *E) {
All the checks here are duplicating existing logic elsewhere in SILGen that tries to determine if a method is dispatched via objc_msgSend(). This is going to be a source of latent bugs.

2019-02-20 01:15 UTC, slavapestov commented
We should instead do this at the ArgumentSource level when lowering a call to a method or accessor. We already know at that point if it’s an Objective C message send.

2019-02-20 01:36 UTC, rjmccall commented
This is not generally semantically valid; ?-chains that short-circuit are required to bypass the evaluation of all expression to the right of the `?` operator within the chain, including call arguments.

I would recommend applying this optimization at the SIL level, where it will also avoid complicating an already over-complex bit of code in SILGen.

2019-02-20 01:38 UTC, rjmccall commented
Doing it at the SIL level would also let you optimize other syntactic forms of short-circuiting, like `guard let`.

2019-02-20 09:34 UTC, closed without merging