Update README.md
swiftlang/swift pull request #23862
Opened 2019-04-08 17:54 UTC by compnerd

Add Windows to the CI list.  This is different in that it is hosted on Azure, but, we can at least monitor the build status.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2019-04-08 17:54 UTC, compnerd commented
CC: @shahmishal @Rostepher @tkremenek

2019-04-08 17:54 UTC, compnerd commented
@swift-ci please smoke test

2019-04-08 18:28 UTC, shahmishal commented
@compnerd We would like to use this list for nodes on ci-external.swift.org. Can you add a node to ci-external.swift.org?

2019-04-08 18:29 UTC, shahmishal requested changes
We should hold off from adding to this list until it's on ci-external.swift.org

2019-04-08 18:46 UTC, compnerd commented
@shahmishal - I think that its still going to be a while (as that requires moving over build-script-impl into python.  In the mean time, it would be nice to make it easier for others to see the current state.

2019-04-08 18:54 UTC, shahmishal commented
@compnerd We can setup the job by converting [yml file](https://dev.azure.com/compnerd/windows-swift/_git/windows-swift?path=%2Fazure-pipelines.yml&version=GBmaster) into Jenkins job. So, we are not blocked on build-script-imple. 

I can help create a new script which would handle this build.

2019-04-08 20:19 UTC, compnerd commented
That sounds great to me @shahmishal!  How would we setup the connection?  AIUI, these agents wouldn't be able to accept the SSH connection as they are Windows hosted.  @drodriguez would be able to help get the machines into the cluster though.

2019-04-08 20:26 UTC, drodriguez commented
To be clear, the SSH connection should be possible, but I might need a little more time to figure out the setup and it will be a trial and error. I found a way to install an SSH server and direct it to `cmd.exe` some months ago. But I don’t know if the SSH plugin being used will like `cmd.exe`.

2019-04-09 00:28 UTC, shahmishal commented
@drodriguez If it makes it easier, we can meet up (online or in person) and get this working.

2019-04-09 18:50 UTC, drodriguez commented
@shahmishal: glad to meet up. Let's move this conversation to better medium, though. I will send you an email explaining the setup. Cheers!

2019-05-13 23:15 UTC, compnerd commented
This is now merged.

2019-05-13 23:15 UTC, closed without merging