Unvail the Darwin.abs function to avoid collisions with Swift.abs
swiftlang/swift pull request #23956
Opened 2019-04-11 17:46 UTC by stephentyrone

Also marks M_PI etc obsoleted instead of merely deprecated (which they have been since Swift 3.0).

Fixes <rdar://problem/44044108>

2019-04-11 17:46 UTC, stephentyrone commented
@swift-ci please test

2019-04-11 17:46 UTC, stephentyrone commented
@swift-ci please test source compatibility

2019-04-12 00:36 UTC, compnerd commented
Shouldn't a similar change be done in the Windows SDK overlay?

2019-04-12 01:25 UTC, stephentyrone commented
> Shouldn't a similar change be done in the Windows SDK overlay?

Probably, but I know nothing about what APIs Windows does (or should) provide, so I will leave that to someone else.

2019-04-12 01:29 UTC, jrose-apple commented
These versions are language versions, and there is no "Swift 5.1" language version. I'm afraid you can't do this conditionally.

2019-04-12 01:29 UTC, jrose-apple commented
(I mean, you can, but it won't have any effect until we get a `-swift-version 6` or something.)

2019-04-12 01:40 UTC, stephentyrone commented
@jrose-apple bad news for the obsoletion of flatMap, too:

>   @available(swift, deprecated: 4.1, obsoleted: 5.1, renamed: "compactMap(_:)"

2019-04-12 01:42 UTC, jrose-apple commented
I remember mentioning this there too, and getting the response that it was okay since it would *eventually* have an effect. That's different from trying to avoid collisions, though.

(Are the collisions actually a problem? I thought we said the standard library is always shadowed by what's in other libraries when there's a perfect overload.)

2019-04-12 01:46 UTC, stephentyrone commented
@jrose-apple The collision is a problem because `fabs` is deprecated `renamed: abs`, but if someone has `Darwin.fabs`, the fixit replaces it it with `Darwin.abs` and turns a deprecation warning into a compile error (because `Darwin.abs` has the signature `(Int32) -> Int32`). A better fix would be the ability to do `renamed: Swift.abs` and get the right fixit, but we don't need `Darwin.abs` sitting around anyway.

2019-04-12 01:48 UTC, stephentyrone commented
>  I thought we said the standard library is always shadowed by what's in other libraries when there's a perfect overload

This is often not ideal for the specific case of the platform overlay. We want the stdlib to be shadowed by *user* libraries, but in the case of Platform, we are actively trying to provide more of that functionality in the stdlib, so more often than not we would prefer the stdlib versions to get picked up.

2019-04-12 02:50 UTC, jrose-apple commented
The platform overlay currently isn't treated specially by the compiler, and I don't think this would be sufficient reason to do so.

2019-04-12 10:12 UTC, stephentyrone commented
I agree, hence the removals.

2019-04-12 16:21 UTC, jrose-apple commented
…ugh. I misread the patch from the beginning, and thought you were using `obsoleted` to do the removals. Carry on.

2019-04-15 13:15 UTC, Coeur requested changes
Please leave it to the human readable form `squareRoot` instead of the cryptic `sqrt` name (_squirt_?) as it's not following the [Swift guidelines](https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage). Or address this renaming in a separate pull request.

2019-04-15 13:36 UTC, stephentyrone commented
@Coeur `sqrt` is a sanctioned name of the operation per SE-0246, and per the swift naming guidelines:

> Embrace precedent. Don’t optimize terms for the total beginner at the expense of conformance to existing culture.

We'll have both `squareRoot` and `sqrt` going forward, and both are perfectly acceptable. We may *eventually* deprecate one of them, but that would be another SE proposal.

2019-04-15 13:45 UTC, Coeur commented
@stephentyrone well, I just noticed that [you did replace](https://github.com/apple/swift/pull/3454/files) `_swift_stdlib_squareRootf` with `_swift_stdlib_sqrtf` some three years ago, and [you did ask in 2017](https://github.com/apple/swift/pull/6786) some 2 years ago if `sqrt(2)` wasn't better than `2.squareRoot()`. So you're clearly more experienced than I am on the naming here. But while there are two forms currently acceptable, I don't see what would be the benefit to flip the recommendation here.

2019-04-15 14:11 UTC, stephentyrone commented
@Coeur What changed is SE-0246. Prior to that the only spelling provided by stdlib was `.squareRoot()` (`sqrt(x)` came from the platform overlays). We have always intended to expose a global free function as well, but hadn't decided how it would be spelled in the standard library, so I didn't want to recommend something that might not be the real name. We now know what the spelling of that free function is, and can recommend using it.

2019-04-15 18:03 UTC, Coeur commented
OK, I've just read the proposal SE-0246 and the review, and nobody ever mentioned `squareRoot` once. :(
Too bad, but oh well, not a big issue.

2019-04-15 18:04 UTC, Coeur approved these changes

2019-06-13 18:55 UTC, stephentyrone commented
We're punting on this until we have an actual language version to tie it to.

2019-06-13 18:55 UTC, closed without merging