[benchmark] Fix: Set.*.Box use identity everywhere
swiftlang/swift pull request #24570
Opened 2019-05-07 14:20 UTC by palimondo

Consistently apply the `identity` in `Box` variants of benchmarks for `subtracting` and `intersection` to guard against future sufficiently smart compiler that could hoist the constant expression out of the loop. This pattern is used in all other variants and was explained by @lorentey in https://github.com/apple/swift/pull/18928#discussion_r212722518.

2019-05-07 14:20 UTC, palimondo commented
@swift-ci please benchmark

2019-05-07 15:00 UTC, palimondo commented
OK, this matches my local results, because the negligible performance changes in `SetIntersectionBox0`, `SetIntersectionBox25`, `SetSubtractingBox0`, `SetSubtractingBox25` flew under the radar.

The I'm pretty sure there will be legitimate performance changes in `Set.subtracting.Empty.Box` and `Set.subtracting.Box.Empty` when #21300 lands, so I suggest we land this fix at the same time and avoid the need to come up with new name for these benchmarks. What do you think @eeckstein?

2019-05-07 16:02 UTC, eeckstein requested changes
Can you add a legacyFactor for this change?
If https://github.com/apple/swift/pull/21300 improves performance we want to see that in the results. If both changes land together we cannot tell how much the https://github.com/apple/swift/pull/21300 improved performance.

2019-05-07 16:25 UTC, palimondo commented
This fix *increases* the runtime and because `legacyFactor` is currently an *integer* multiplier, it can only inflate the reported time and cannot be used to work around this as is.

I've triggered the CI benchmark in #21300 to be sure, but without fixing this, the runtime dips too low in these two cases (`Set.subtracting.Empty.Box`, `Set.subtracting.Box.Empty`) and we would have to adjust the multipliers anyway.

2019-05-07 17:12 UTC, palimondo commented
Erm, I misspoke, those two cases regress according to [benchmark report](https://github.com/apple/swift/pull/21300#issuecomment-490154938) (0.15x & 0.29x), but these are marginal cases with 1000x workload multipliers — so this means subtracting the empty set takes 152 ns and 158 ns.

2019-05-07 17:19 UTC, palimondo commented
With this fix, these will be even a bit higher, because the loop will have to deal with `identity`, but I really wouldn't stress that case at all. As I said, this fix as well as #21300 change the runtime of those two test (both increase), so if we land around the same time, we can pretend this minor regression is all caused by #21300 and we would not need to burn the good benchmark names just to fix this `identity` omission. Would you agree, @eeckstein?

2019-05-07 22:30 UTC, palimondo commented
@swift-ci please smoke test

2019-05-10 21:24 UTC, palimondo commented
@eeckstein @lorentey Assuming #21300 is ready to be merged, I propose we coordinate the landing of these 3 PRs in following order:

1. #24156 [benchmark] Variants for Set Sequence Methods
2. #24570 [benchmark] Fix: Set.*.Box use identity everywhere (this one)
3. #21300 [stdlib] Optimize some Set operations

2020-02-10 05:59 UTC, futurejones commented
Can one of the admins verify this patch?

2020-10-01 06:59 UTC, shahmishal commented
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

2020-10-05 21:30 UTC, closed without merging