Add Identifiable protocol to the standard library
swiftlang/swift pull request #26022
Opened 2019-07-09 15:20 UTC by anandabits

This PR implements SE-0261.  It will be updated with any changes after the core team makes a final decision.  Please let me know if it should target a different branch.

2019-07-09 18:36 UTC, airspeedswift commented on stdlib/public/core/Identifiable.swift
> +public protocol Identifiable {
This (and the implementation) will need an `@available` annotation

2019-07-09 18:37 UTC, airspeedswift requested changes

2019-07-09 18:37 UTC, airspeedswift commented on stdlib/public/core/Identifiable.swift
> +  @inlinable
Are we _certain_ this is definitively the implementation we'll want forever? If not, leaving off `@inlinable` may be a better choice, at least at first.

2019-07-09 18:48 UTC, Azoy commented on stdlib/public/core/Identifiable.swift
> +/// A class of types whose instances hold the value of an entity with stable identity.
This also needs the big copyright comment before anything else.

2019-07-09 18:57 UTC, anandabits commented on stdlib/public/core/Identifiable.swift
> +  @inlinable
I'm fine with removing it for now.  I'm curious though - what other implementation options do you have in mind?

2019-07-09 20:09 UTC, airspeedswift commented on stdlib/public/core/Identifiable.swift
> +  @inlinable
¯\_(ツ)_/¯

Mostly just making sure we've asked that question and are certain of the answer.

2019-07-26 23:33 UTC, anandabits commented
@airspeedswift now that this has been accepted I’ll get the PR rebased on the latest master.  Are there any other changes that need to happen before it is ready to merge?  Additional documentation as mentioned in the review rationale?

2019-07-26 23:47 UTC, lorentey commented
@anandabits Let's land the code as is -- we can figure out the docs later.

2019-07-26 23:49 UTC, lorentey approved these changes

2019-07-26 23:49 UTC, lorentey commented
@swift-ci please smoke test

2019-07-27 00:38 UTC, merged