Move SourceFile::LookupCache to header file
swiftlang/swift pull request #26042
Opened 2019-07-09 22:52 UTC by save-buffer

Moves `SourceFile::LookupCache` to header file to resolve errors with incomplete types when `Module.h` is included in external projects.

2019-07-09 23:29 UTC, compnerd commented
Please fix up the commit message.  I think clarifying that this is due to the use of the `std::unique_ptr` which will create a `std::default_deleter` which requires a complete definition is useful.

2019-07-09 23:33 UTC, compnerd commented
CC: @jrose-apple

2019-07-09 23:33 UTC, compnerd commented
@swift-ci please test

2019-07-09 23:34 UTC, compnerd commented
@swift-ci please test

2019-07-09 23:50 UTC, jrose-apple requested changes
Please don't do this. Instead, you can force SourceFile's destructor to be defined out of line (by declaring it in the header file and then defining it with `= default` in the .cpp file).

2019-07-10 17:14 UTC, save-buffer commented
OK. I'll close this one. The new one is in PR #26059

2019-07-10 17:14 UTC, closed without merging