Remove legacyFactor and adopt blackHole where appropriate in Diffing and Myers benchmarks
swiftlang/swift pull request #26104
Opened 2019-07-12 02:18 UTC by numist

Per post-merge feedback in https://github.com/apple/swift/pull/25808

2019-07-12 02:18 UTC, numist commented
@swift-ci please benchmark

2019-07-12 02:19 UTC, numist commented
@swift-ci please smoke test

2019-07-12 04:12 UTC, palimondo commented
The benchmark validation on CI runs only for the newly added tests, so we don’t see those results here now. Could you please also post your local result from running `Benchmark_Driver check -f Diff -f Myers --format markdown`? Otherwise LGTM.

2019-07-12 04:25 UTC, palimondo requested changes
Could you please refactor to use a shared run function, parametrized with the workload String? You should probably also touch the lazily initialized global constants in setUpFunction using the blackHole, too. See AngryPhonebook benchmarks for an example of this.

2019-07-12 20:34 UTC, numist commented
✅  | Benchmark Check Report
---|---
⚠️⏱ | `Myers` execution took at least 8040 μs. <br><sub> Decrease the workload of `Myers` by a factor of 16 (10), to be less than 1000 μs.
⚠️Ⓜ️ | `Myers` has very wide range of memory used between independent, repeated measurements. <br><sub> `Myers` mem_pages [i1, i2]: min=[2140, 2672] 𝚫=532 R=[1074, 569]

After touching the globals and adjusting the inputs of `Myers` to match `Diffing.Similar` in 16087175b7:

✅  | Benchmark Check Report
---|---
⚠️Ⓜ️ | `Myers` has very wide range of memory used between independent, repeated measurements. <br><sub> `Myers` mem_pages [i1, i2]: min=[35, 43] 𝚫=8 R=[20, 41]

Not sure why `Myers` would exhibit this problem and not `Diffing.Similar` as the two are practically identical (until I land further perf improvements to `Collection.difference(from:)`, anyway).

As an aside, could you help me understand why everything gets `blackHole`d? I understand why you'd want to mask out setup and the like, but AngryPhoneBook even blackholes the work that is supposed to be benchmarked so it seems like I don't have the right idea around what it's for.

2019-07-12 21:01 UTC, palimondo commented
As I understand it, the`blackHole` is used as barrier to prevent sufficiently smart future compiler from eliminating calls with unused results as dead code. But thinking about this particular case… the `let _ = ` should guarantee the same thing, right? 🤔 @lorentey, @eeckstein?

We started to use it in `setUpFunction`s to pre-initialize lazy globals that take significant time, so that their initialization does not spoil the first sample.

2019-07-12 21:07 UTC, numist commented
Sounds reasonable. Regardless, there's value in conforming to the existing patterns.

2019-07-12 21:07 UTC, numist commented
@swift-ci please test

2019-07-12 21:08 UTC, palimondo commented
> `Myers` mem_pages [i1, i2]: min=[35, 43] 𝚫=8 R=[20, 41]

This seems fine to me. The memory heuristic is quite sensitive.

2019-07-13 04:40 UTC, palimondo requested changes
Scott, I apologize for the being skittish in my review… I’m on the road and doing all  this on a phone.

Could you please also change the naming of these benchmarks to follow the [Naming Convention](http://bit.ly/BenchmarkNaming)? I think the benchmark family name here is clearly `Diff`, so putting a period after that would we a good first step. If I understand this correctly, Myers is an alternative diffing algorithm. In your last commit, you’ve changed the workloads in `Myers` to match those in `DiffSimilar`. Therefore it would make sense to try and make the results directly comparable by also applying the concept of variants from the benchmark naming convention.  Could you also please:

* change the variable names of workloads  in Myers.swift to match those from Diffing.swift, so that it is clearer it is the same workload,
* rename the file Myers.swift to DiffingMyers.swift or DiffMyers.swift,
* rename `Myers` benchmark to `Diff.Similar.Myers`, to make it clear it is a variant of the same workload, using a different algorithm.

2019-07-13 04:59 UTC, palimondo commented
Tiny nitpick: I’d declare the reversed workloads like this:
````swift
let alphabetsReversed = Array(alphabets.reversed())
let loremReverse = Array(loremIpsum.reversed())
````
…and probably call the latter <code>loremReverse<strong>d</strong></code>… 😜

2019-07-15 23:08 UTC, numist commented
@swift-ci Please test

2019-07-16 04:35 UTC, palimondo commented
The changes in `DiffingMeyers` and `Diffing` look great, but something went very wrong during the merge. It now has 148 changed files instead of 3.

2019-07-16 21:39 UTC, numist commented
Something was extremely broken with my fork. Should be fixed now.

2019-07-16 21:46 UTC, palimondo commented
@swift-ci please benchmark

2019-07-16 21:49 UTC, palimondo approved these changes
LGTM. Thank you for your patience Scott!

2019-07-16 21:49 UTC, palimondo commented on benchmark/single-source/DiffingMyers.swift
> +// The DiffingMyers test benchmarks Swift's performance running the algorithm
Thanks for adding this explanation!

2019-07-16 21:50 UTC, palimondo commented
@swift-ci please benchmark

2019-07-16 21:50 UTC, palimondo commented
@swift-ci please smoke test

2019-07-16 21:50 UTC, palimondo commented
@swift-ci please smoke test

2019-07-17 00:13 UTC, merged

2019-07-17 17:48 UTC, numist commented
How did @swift-ci come up with zero run time for the diffing benchmarks after the local benchmark check report indicated everything was fine?

2019-07-17 17:49 UTC, numist commented
Ohhh, I bet it was not actually appropriate to use `blackHole` around the work function.

2019-07-17 20:48 UTC, lorentey commented
At worst, `blackHole` should slow things down, not speed things up. The use of `blackHole` in the `run_` functions seems entirely appropriate to me. 

(It looks somewhat out of place in the setup closures, but it won't cause harm there, either.)

2019-07-17 20:53 UTC, lorentey commented
What's likely happening is that the optimizer is clever enough to recognize that the same input is repeatedly passed to the same pure function, and it moves the function call outside the loop. If so, the `identity` helper should prevent that:

```
blackHole(diff(identity(arg1), identity(arg2))
```

2019-07-17 20:59 UTC, lorentey commented
This highlights an interesting point -- since the Myers algorithm is implemented internal to the benchmark, it has an unfair advantage over the stdlib: it can be specialized to the concrete element type, which can considerably speed things up.

2019-07-18 03:52 UTC, palimondo commented
I’m pretty sure the zero runtimes are caused by CI machines running on stable macOS 10.14 and not the 10.15 Beta, so it is the expected result of the availability checks we’ve been discussing in  #25808.

2019-07-18 05:17 UTC, numist commented
Oh I see, the `blackHole` function prevents code elimination by the compiler.

> This highlights an interesting point -- since the Myers algorithm is implemented internal to the benchmark, it has an unfair advantage over the stdlib: it can be specialized to the concrete element type, which can considerably speed things up.

I think this is ok since the Myers benchmark measures Swift vs the Diffing benchmark, which measures `Collection.difference()`

> I’m pretty sure the zero runtimes are caused by CI machines running on stable macOS 10.14 and not the 10.15 Beta, so it is the expected result of the availability checks we’ve been discussing in #25808.

That makes sense, especially since that I got no such warnings from `Benchmark_Driver check` on a 10.15 system. We could put the `BenchmarkInfo` instances inside an availability check to omit them from the results, or just revisit this once 10.15 has GMed if the zeroes aren't hurting anything.

2019-07-18 06:24 UTC, palimondo commented
The zeros are not hurting anything directly, it’s just that these benchmarks also provide no value here until the machines upgraded to 10.15. So I still question the way we do the availability checks in these benchmarks. 

What @lorentey explained in #25808 makes sense for app developers using the new diffing API, but I’m not convinced it applies equally to these benchmarks. I think the Swift Benchmark Suite’s use and usefulness outside of guarding compiler and stdlib development is rather theoretical and should not be used as argument to hamper this primary use case.

Can we please re-examine this issue? CC @eeckstein @jrose-apple