stdlib: prevent static builds on Darwin
swiftlang/swift pull request #26210
Opened 2019-07-18 03:40 UTC by compnerd

Static builds of the standard library and the SDK overlay are
unsupported post ABI stability.  Disallow building of the standard
library and SDK overlay statically for Darwin platforms.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2019-07-18 03:40 UTC, compnerd commented
@swift-ci please test

2019-07-18 03:41 UTC, compnerd commented
CC: @shahmishal @brentdax @Rostepher @gottesmm @jrose-apple

2019-07-18 16:17 UTC, DougGregor requested changes

2019-07-18 16:17 UTC, DougGregor commented on stdlib/CMakeLists.txt
> +  if(building_dawin_sdks)
Typo here "building_dawin_sdks" vs. "building_darwin_sdks".

2019-07-18 16:17 UTC, DougGregor commented on stdlib/public/Darwin/CMakeLists.txt
> +  if(building_dawin_sdks)
Same typo.

2019-07-18 20:17 UTC, compnerd commented
@swift-ci please test

2019-07-18 20:17 UTC, compnerd commented
@swift-ci please test

2019-07-18 21:43 UTC, brentdax commented
Funny, I just filed a bug for this. https://bugs.swift.org/browse/SR-11157

2019-07-19 04:03 UTC, compnerd commented
Yes, it does make that impossible, but, really, that is already pretty badly broken.  The current model doesn't really work (CMake just is not designed that way) - e.g. `-install_name` being used on ELF and `-soname` being used for MachO?!  We have a ton of hacks in place and we keep piling more on.  I think that we need to just change to proper cross-compilation (nearly all the pieces are now in place).  At that point, that will have different CMake sub-builds for each one.  This is better long term.

2019-07-19 15:06 UTC, compnerd commented
@swift-ci please test

2019-07-19 15:06 UTC, compnerd commented
@swift-ci please test

2019-07-19 21:06 UTC, brentdax commented
I think @shahmishal needs to be part of this conversation, because if we can't use the same presets on Darwin and other platforms, that's going to impact the way CI is configured.

2019-07-19 21:17 UTC, shahmishal commented
@brentdax @compnerd Thanks for bring this to my attention, if we see build failures on CI because we are still using the flag on macOS please let me know and I will update the preset.

2019-07-19 21:27 UTC, brentdax commented
Looking at build-presets.ini, the following apparently-Darwin presets still use this flag:

* mixin_buildbot_trunk_base
* buildbot,tools=RA-flto,stdlib=RDA
* LLDB_Swift_DebugAssert_with_devices
* LLDB_Swift_ReleaseAssert_with_devices

We should probably remove the flag from these.

2019-07-20 01:45 UTC, compnerd commented
Beyond the update of the presets, the question is, should we even permit building the standard library/SDK overlay for Darwin in static mode?

2019-07-21 19:40 UTC, brentdax commented
We think not permitting it is fine. Mishal says that we (should) always use separate presets for Linux, so preset sharing isn't a concern.

2019-07-22 16:29 UTC, compnerd commented
@swift-ci please test macOS platform

2019-07-23 23:06 UTC, compnerd commented
@swift-ci please test macOS platform

2019-07-24 02:22 UTC, compnerd commented
Sounds like all the concerns have been addressed, I'm going to go ahead and merge this.  As @shahmishal said, if we run into cases where the preset is using static builds, we will update the preset and sharing is not a concern.

2019-07-24 02:22 UTC, merged

2019-07-25 00:40 UTC, shahmishal commented
https://github.com/apple/swift/pull/26343