[Diagnostics] Port the "extra address of argument" diagnostic to the new framework.
swiftlang/swift pull request #26697
Opened 2019-08-16 20:11 UTC by hborla

2019-08-16 20:11 UTC, hborla commented
@swift-ci please smoke test

2019-08-16 20:25 UTC, xedin requested changes
We already have a ConstraintFix/FailureDiagnostic for this - `RemoveAddressOf`/`InvalidUseOfAddressOf` looks like we just need to extend its use.

2019-08-16 23:03 UTC, hborla commented
@swift-ci please smoke test

2019-08-17 00:17 UTC, xedin commented on lib/Sema/CSFix.h
> -  RemoveAddressOf,
Although this is a contextual failure, let's keep it's special kind since we know what it is.

2019-08-17 00:17 UTC, xedin commented on lib/Sema/CSFix.cpp
> +bool RemoveAddressOf::diagnose(Expr *root, bool asNote) const {
Is it necessary to move stuff in `cpp` it same way as in the header?

2019-08-17 00:17 UTC, xedin commented on lib/Sema/CSDiagnostics.cpp
> +SourceLoc InvalidUseOfAddressOf::getLoc() const {
Same thing as in `CSFix.cpp` I think it should be left in place, it might make it more difficult to blame the changes later on.

2019-08-17 01:01 UTC, hborla commented
@swift-ci please smoke test

2019-08-17 01:11 UTC, xedin approved these changes
Looks great, thank you!

2019-08-17 02:33 UTC, merged