[Source Tooling] Refactoring action to convert if statement to switch
swiftlang/swift pull request #26719
Opened 2019-08-19 18:09 UTC by Regno

Implement action to convert if statements from:
  ```
var e = E.case1
  if e == .case1 {}
  else if e == .case2 {}
  else {}
```
to
```
  var e = E.case1
  switch e {
  case .case1: break
  case .case2: break
  default: break
  }
```

Resolves [SR-5741](https://bugs.swift.org/browse/SR-5740).

@nkcsgexi

2020-01-07 06:30 UTC, Regno commented
@nathawes Could you review this PR please?

2020-01-08 00:23 UTC, nathawes requested changes
Looking good so far! I thought of a few edge cases that might need handling and some tests to add while looking over it. I mentioned some potential enhancements to make it applicable in more situations in case you're interested in working on them, but those can certainly be left for a future PR too.

2020-01-23 18:52 UTC, closed without merging

2020-02-02 09:57 UTC, Regno commented
I can't reopen this PR after force push to branch. So I create new one: https://github.com/apple/swift/pull/29596

2020-02-02 10:00 UTC, Regno commented on lib/IDE/Refactoring.cpp
> +    auto FirstArgument = dyn_cast<DeclRefExpr>(ConditionArguments->getElement(0));
I added test cases to check such situation:
```
func checkInverseCondition(e: E) {
   if .first == e {
     print("first")
   } else if .second == e {
     print("second")
   } else {
     print("default")
   }
 }
```
and
```
func checkMultipleOrConditions(e: E) {
   if e == .first || e == .second || e == .third {
     print("1-3")
   } else if e == .fourth { 
     print("4")
   } else { 
     print(">4")
   }
 }
```

https://github.com/apple/swift/pull/29596/files#diff-25cfa169a425e3d40c7c27e0135e3d58

2020-02-02 10:03 UTC, Regno commented on lib/IDE/Refactoring.cpp
> +    auto ConditionArguments = ConditionExpr->getArg();
I added check to allowed functions names like `==` and `~=`.

2020-02-02 10:04 UTC, Regno commented on test/refactoring/ConvertToSwitchStmt/basic.swift
> +}
Added regression test:
```
func checkMultipleWithUnrelatedCondition(e: E, x: Int) {
   if e == .first || x > 0 {
     print("e is the first or x is positive")
   } else { 
     print("Shouldn't convert to switch")
   }
 }
```

2020-02-02 10:05 UTC, Regno commented on lib/IDE/Refactoring.cpp
> +    auto IfBody = dyn_cast_or_null<BraceStmt>(If->getThenStmt());
Added test with empty `If` statement body:

```
func checkEmptyBody(e: E) {
   if e == .first {}
   else if e == .second {
     print("second")
   }
 }
```

2020-02-02 10:06 UTC, Regno commented on lib/IDE/Refactoring.cpp
> +      OS << tok::kw_switch << Space << FirstArgumentValue->getNameStr().str() << Space << tok::l_brace << NewLine;
Also added this case. Take a look at line 81 `checkLabeledCondition`.

2020-02-02 10:08 UTC, Regno commented on lib/IDE/Refactoring.cpp
> +      return false;
I added such test cases too.

But I don't check that type conforms to the `Equatable` protocol. I just suppose that user will try to convert a valid `if` statement.

2020-02-07 18:03 UTC, nathawes commented on lib/IDE/Refactoring.cpp
> +    auto IfBody = dyn_cast_or_null<BraceStmt>(If->getThenStmt());
The case I was thinking of was more if the user hasn't actually written the braces at all yet:
```
if e == .first || e == .second // stopped typing here to convert to switch
```
But no need to change it.