[windows] Force a downcast to make VC++ happy.
swiftlang/swift pull request #27072
Opened 2019-09-06 23:03 UTC by drodriguez

For some reason VC++ is not seeing that ClassDecl is a subtype of
NominalTypeDecl, and failing to compile this new code.

As a workaround, one can force a downcast to the parent type, and it
seems to compile and pass the ClangImporter tests.

I don't completely like the solution, if anyone has some better idea or workaround, I will be happy to apply it.

The Windows builds have been broken since this midday because of this since the introduction of #27008 (see https://ci-external.swift.org/job/oss-swift-windows-x86_64/1243/)

/cc @gmittert @compnerd @varungandhi-apple

2019-09-06 23:04 UTC, drodriguez commented
@swift-ci please test Windows platform

2019-09-07 01:31 UTC, drodriguez commented
@swift-ci please smoke test

2019-09-07 02:24 UTC, varungandhi-apple submitted a review, later dismissed
I hope we don't keep running into such issues in the future. Unnecessary work for you due to compiler bugs :-/.

2019-09-07 02:30 UTC, jrose-apple requested changes
I'm sorry to say it, but please figure out what's going wrong rather than just leaving it at "for some reason". Otherwise we'll end up with un-idiomatic code across the codebase and no one will remember what it's there fore.

2019-09-07 05:22 UTC, drodriguez commented
I will try to find a better solution next week (I don't have access to my Windows machine during the weekend). I wanted to have something up in case we needed it, and also to get it through the Windows CI to check it. I will "Dismiss" Varun review so nobody should be able to merge this (in any case, Varun, thanks for looking into this).

2019-09-09 17:32 UTC, gmittert commented
Fixed by https://github.com/apple/swift/pull/27079

2019-09-09 17:32 UTC, closed without merging