Fail early if getExtendedNominal is called before extension has been bound.
swiftlang/swift pull request #27313
Opened 2019-09-23 23:11 UTC by davidungar

Trip an assertion if code in the compiler directly or indirectly attempts to `getExtendedNominal` too soon (i.e. before the extension has been bound).

2019-09-23 23:12 UTC, davidungar commented
@slavapestov @CodaFi Hasn't been tested yet, but thought you might want to get a jump on the review. Thanks.

2019-09-23 23:13 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-23 23:33 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-24 00:00 UTC, CodaFi requested changes
This infrastructure change doesn't seem quite right.  Do you want to assert `extension->alreadyBoundToNominal()`?

2019-09-24 04:43 UTC, davidungar commented
@CodaFi How would `alreadyBoundToNominal` work in the case where the code is illegal because there is no nominal to bind the extension to?

2019-09-24 05:14 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-24 05:16 UTC, davidungar commented
@CodaFi I did change `ExtendedNominalRequest::getCachedResult` because it seems that the operation must be repeated if it fails, or else Swift.o won't build, as per your comment in the code.

2019-09-24 05:58 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-24 07:01 UTC, davidungar commented
@CodaFi Don't have time to push a fix now, but I see that the assertion must include something more as a disjunct to handle non-top-level extensions which never get attempted to be bound. The problem I see with `isInvalid() || alreadyBoundToNominal()` is the window between `bindExtensions()` and `validateDecl`. In that window, the assertion should succeed for an extension of a nonexistent nominal, but `isInvalid` won't be true yet. It's too late to mess with this now; I'll try a specific-to-not-top-level fix tomorrow (really later today).

2019-09-24 18:15 UTC, slavapestov approved these changes
This is great, thanks! I only have a few minor nitpicks, feel free to merge without more review (assuming nobody else has objections)

2019-09-24 18:15 UTC, slavapestov commented on include/swift/AST/Decl.h
> +  llvm::PointerIntPair<NominalTypeDecl *, 1, bool> ExtendedNominal = {nullptr,
PointerIntPair is default-initialized

2019-09-24 20:30 UTC, davidungar commented on include/swift/AST/Decl.h
> +  llvm::PointerIntPair<NominalTypeDecl *, 1, bool> ExtendedNominal = {nullptr,
Cool, tx!

2019-09-24 20:30 UTC, davidungar commented on lib/AST/NameLookupRequests.cpp
> +  // Without this recomputation, building Swift.o fails.
Edited the comment. Better?

2019-09-24 20:31 UTC, davidungar commented on lib/AST/Decl.cpp
> +  return getParent()->getContextKind() != DeclContextKind::FileUnit;
As discussed offline, also need to catch `struct S { extension E {} }`

2019-09-24 20:32 UTC, davidungar commented on include/swift/AST/Decl.h
> +  /// in order to fail fast when type checking work is attempted before extension binding has taken place.
Thanks for the catch!

2019-09-26 19:31 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-26 21:40 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-26 23:35 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-26 23:40 UTC, davidungar commented
@swift-ci please clean smoke test os x platform

2019-09-28 21:06 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-28 21:07 UTC, davidungar commented
@swift-ci please smoke test os x platform

2019-09-28 21:07 UTC, davidungar commented
@swift-ci please smoke test linux platform

2019-09-28 22:57 UTC, davidungar commented
Please test with following pull request:
https://github.com/apple/swift-lldb/pull/2021

@swift-ci please smoke test os x platform

2019-09-29 00:10 UTC, davidungar commented
@swift-ci please smoke test linux platform

2019-09-29 00:32 UTC, davidungar commented
Please test with following pull request:
apple/swift-lldb#2021

@swift-ci please smoke test linux platform

2019-09-30 15:37 UTC, merged