[OSLogOptimization] Improve the OSLogOptimization pass so that it can fold constant arrays and closure literals
swiftlang/swift pull request #28168
Opened 2019-11-09 01:02 UTC by ravikandhadai

This PR enhances the OSLogOptimization pass so that it can fold constant arrays and closure literals that are inferred by the constant evaluator while evaluating os log calls. The main changes of this PR are mostly confined to the function `emitCodeForSymbolicValue` of the `OSLogOptimization` pass.  In addition to adding support for array and closure folding, this PR also contains a fix to a (minor) bug in the code that manages the lifetime of the folded value.  For perspicuity, this PR is split into 3 self-contained commits as described below: 

 * Commit  9b57208 fixes a bug in the code that replaces a guaranteed value by an owned (constant) value. It also slightly improves the replacement logic for non-OSSA (which is meant to be phased out soon once OSSA is enabled in the mandatory pipeline) so that it can handle the folding of arrays and closures introduced in this PR.  This commit updates `OSLogPrototypeCompileTest.sil` test suite to reflect these changes.

* Commit fa0ec3d adds support for folding constant arrays. It also adds SIL tests for testing array folding logic to the file: `OSLogPrototypeCompileTest.sil`.

* Commit f7b489e adds support for folding symbolic closures, which are representations of closure literals in the constant evaluator. It also adds SIL tests for testing the closure folding logic. Importantly, this commit updates the `OSLogPrototypeCompileTest.swift` to check whether the "array of closures" used by the new OSLog overlay is folded.

2019-11-09 01:02 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-11 19:29 UTC, ravikandhadai commented
@swift-ci Please test Linux Platform

2019-11-12 18:21 UTC, atrick requested changes
Generally looks good. A couple of comments are inline.

2019-11-13 01:15 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-13 01:20 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-13 01:21 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-13 01:23 UTC, ravikandhadai commented
@atrick Thanks for the comments. I have pushed a commit that addressed the comments. I have also added test `testNoFoldingOfArrayLiterals` in `OSLogPrototypeCompileTest.sil`  that checks that array literals are not folded.

2019-11-13 02:39 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-13 02:43 UTC, ravikandhadai commented
@swift-ci Please test

2019-11-13 18:30 UTC, merged