Minimize Make-Style Dependencies
swiftlang/swift pull request #28696
Opened 2019-12-11 04:05 UTC by CodaFi

When -emit-dependencies is switched on, the Frontends are each tasked
with emitting Make-style dependencies files describing the full Swift
compilation graph and any external dependencies picked up by the Clang
Importer. Each output path was given a make target, and each target was
given a full copy of the dependencies of the swift compilation session.

This is a tremendous amount of duplication of a tremendous amount of
dependencies.  There can often be hundreds of dependencies for a single
target, and each output file's target would recieve its own copy. This
puts a significant strain on the build system, which is parsing a linear
number of these dependency files in incremental mode. (Given the build
system operates at the level of driver invocations, it's questionable
whether we even need to emit these files with content at all, but that's
a separate issue). When each output file adds all of its dependencies,
that means we have a quadratic increase in the parsing load.

Aim to compress these make-style dependency files by nominating
a primary output as a most-preferred target that recieves the entire
compilation graph.  The remaining targets, rather than copy the build
dependencies, simply depend on that target being rebuilt.

This allows us to cut down the size of make-style dependencies by
(1/# of outputs).  When multiplied by the number of files in a large
incremental codebase, as in SR-11927, the savings can be as much as
50% of incremental build time.

We can reduce this further by nominating a single frontend job to be the
Blessed One That Emits The Dependencies since Make requires we emit
a complete graph (as in K^n) so everybody sees the same internal
dependencies, and there's no way for a user to customize
individual frontend invocations as with Clang so everybody should see
the same external dependencies.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

2019-12-11 04:05 UTC, CodaFi commented
@swift-ci please test

2019-12-11 04:05 UTC, CodaFi commented
@swift-ci please test source compatibility

2019-12-11 04:11 UTC, CodaFi commented
Uh oh, this is gonna fail a Driver test.  I'll get to it tomorrow.

2019-12-11 04:53 UTC, davidungar requested changes
Very nice! Great idea, done very quickly. The one comment I feel strongly about is that the one large function be broken up. Take or leave the rest. Thanks in advance!

2019-12-11 04:53 UTC, davidungar commented on lib/FrontendTool/FrontendTool.cpp
> +    }
I find this easier to read when the short branch, here the else case, comes first. That way I don't have to match up the brace before the "else" with the appropriate "if".

2019-12-11 04:53 UTC, davidungar commented on lib/FrontendTool/FrontendTool.cpp
> +}
This function takes up almost the whole of my screen height (40") without the comment. Could it be broken up into about three pieces? Your excellent comments illustrate that each piece does have a cogent separable thought to it.

2019-12-11 04:53 UTC, davidungar commented on lib/FrontendTool/FrontendTool.cpp
> +  const std::string *const firstNonEmptyTarget(*it);
Nice "consting", BTW.

2019-12-11 04:53 UTC, davidungar commented on test/Driver/minimal_make_dependencies.swift
> +// Try WMO - we need to emit targets for each primary object file.
Would be nice to add a comment at the top of the file summarizing what is being tested.

2019-12-11 04:53 UTC, davidungar commented on lib/FrontendTool/FrontendTool.cpp
> +static void forEachMinimalMakeStyleTarget(
I like the structure of using a functional interface here.

2019-12-11 04:54 UTC, DougGregor commented
@swift-ci please test Windows

2019-12-11 05:54 UTC, CodaFi commented
@swift-ci please test windows

2019-12-11 05:54 UTC, CodaFi commented
@swift-ci please test windows

2019-12-11 05:54 UTC, CodaFi commented
@swift-ci please test windows

2019-12-11 05:54 UTC, CodaFi commented
@swift-ci please test

2019-12-11 05:55 UTC, CodaFi commented
@swift-ci please test

2019-12-11 05:55 UTC, CodaFi commented
@swift-ci please test windows

2019-12-11 08:01 UTC, CodaFi commented
Hmph, need to update the check line to make Windows happy...

2019-12-11 08:04 UTC, CodaFi commented
@swift-ci please smoke test

2019-12-11 08:04 UTC, CodaFi commented
@swift-ci please smoke test

2019-12-11 08:04 UTC, CodaFi commented
@swift-ci please test Windows

2019-12-11 08:04 UTC, CodaFi commented
@swift-ci please test Windows

2019-12-11 08:04 UTC, CodaFi commented
@swift-ci please test Windows

2019-12-11 08:08 UTC, CodaFi commented
@swift-ci please test Windows

2019-12-12 22:50 UTC, CodaFi commented
@swift-ci please smoke test

2019-12-12 22:50 UTC, CodaFi commented
@swift-ci please smoke test

2019-12-22 03:01 UTC, closed without merging

2019-12-22 07:17 UTC, davidungar commented
If this were still open I would approve it. Looks better!