[NFC] Better document DeclNameRef
swiftlang/swift pull request #28763
Opened 2019-12-13 02:40 UTC by brentdax

Improves the documentation of `DeclName` and `DeclNameRef` to explain when each one should be used.

2019-12-13 02:41 UTC, brentdax commented
@swift-ci please smoke test

2019-12-13 03:39 UTC, varungandhi-apple commented
I had something different in mind when I wrote the comment. Something like: (in your words)

```
// (haven't checked the line widths)

// [DeclName-vs-DeclNameRef]
// Consider the following snippet of code:
//
//     struct Foo: Bar.Baz { ... }
//
// Bar and Baz should be represented by DeclNameRefs because
// they refer to types declared elsewhere, while Foo should be represented
// by a DeclName since it is the place where that declaration's name is actually defined.
//
// This notion is carried beyond the parser and AST themselves and into places
// where we're processing information about the AST. For example, the type checker
// should use DeclNameRef to refer to names extracted from the expression it's
// type checking and DeclName to refer to names of overloads it's trying to match to them.
// (In practice, there are a few workarounds in the type checker that we need to
//  address. See also [type-checker-use-DeclNameRef].)

/// $[Stuff you already wrote...]
///
/// See also [DeclName-vs-DeclNameRef].
class DeclName

/// $[Stuff you already wrote...]
///
/// See also [DeclName-vs-DeclNameRef]
class DeclNameRef
```

Also, if you think it is possible/easy, it might be worth adding FIXMEs with `[type-checker-use-DeclNameRef]` (and that last sentence in the comment I suggested) in the places where you think the change needs to be made, even if you don't make the changes right away. For an example, here is how I've done stuff before: https://github.com/apple/swift/search?q=%5Bclang-function-type-serialization%5D&unscoped_q=%5Bclang-function-type-serialization%5D

---

Aside: you were mentioning that `getFullName()` is perhaps not such a good name. I concur. Maybe we should rename it to `getDeclName()` in a different PR. My mental model of a DeclName is

```
DeclNameRef := [Optional Module Name] [DeclName]
DeclName := [DeclBaseName] [Optional argument labels]
```

2019-12-13 03:42 UTC, varungandhi-apple requested changes
I think this is good (and probably more detailed compared to the average in the compiler), but I think we would benefit from having a concrete example and some more discussion, as you showed in your forum post.

2020-02-10 05:52 UTC, futurejones commented
Can one of the admins verify this patch?

2020-10-01 07:00 UTC, shahmishal commented
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

2020-10-05 21:30 UTC, closed without merging