[WIP] [requires-evolution] Support whitespace and punctuation for escaped identifiers
swiftlang/swift pull request #28966
Opened 2019-12-29 15:11 UTC by adellibovi

Hello everyone 👋 
This is a working in progress prototype for a new evolution pitch about adding support for whitespace and punctuation for escaped identifiers.

In few words this would enable us to do something like:
```swift
func `test object returns true when validation succeed`() { ... }
```

For more details, the discussion is currently being held at: https://forums.swift.org/t/pre-pitch-whitespaces-and-punctuation-for-methods-declarations/32073

2019-12-29 21:47 UTC, CodaFi approved these changes
Approach LGTM.  I’d appreciate more regression tests but I’m not gonna block on it.  In particular
- A semantic test for (overloaded) declrefs of declarations with these names
- A syntactic test that exercises typo correction
- A syntactic test that hits the disallowed ranges in the new predicates

2019-12-29 21:48 UTC, CodaFi commented
Let’s see what’s up

@swift-ci please test

2019-12-29 21:48 UTC, CodaFi commented
@swift-ci please build toolchain

2019-12-30 03:49 UTC, allevato requested changes
> more regression tests

I mentioned it in the [forum thread](https://forums.swift.org/t/whitespaces-and-punctuation-for-escaped-identifiers/32073/22?u=allevato), but one area that still needs work is `SILPrinter`. It currently only checks identifiers against the list of keywords to determine escaping, so the following:

```swift
func `foo bar baz`() {}
```

would get written out by `-emit-sil(gen)`, I believe, as

```swift
func foo bar baz()
```

and then would fail to parse if someone passed that SIL back as input to the compiler.

So it would be good to have some tests that take a file with some escaped identifiers, compile it to SIL, and then compile that, to verify the functionality that still needs to be implemented.

2019-12-30 21:50 UTC, adellibovi commented
Thanks @CodaFi for the review, I had to push few more commits, if you feel like that requires another review of the PR I will be happy to receive your feedbacks 😊 Can I kindly ask you to execute the tests and the tool chain again? Thanks!

2020-01-03 00:23 UTC, rintaro commented on lib/Parse/Lexer.cpp
> +  if (c == '\r' || c == 'n' || c == '`')
Did you mean `'\n'`?

2020-01-03 00:25 UTC, adellibovi commented on lib/Parse/Lexer.cpp
> +  if (c == '\r' || c == 'n' || c == '`')
oops, yes, pushed the fix :)

2020-01-13 22:46 UTC, jckarter commented
@swift-ci Please build toolchain

2020-01-24 22:04 UTC, nonsensery commented
Not sure if this has been fixed in the mean time, but I think I encountered a bug in toolchain dc087f5.

When I write this code:

```swift
func `some weird method`(`argument one`: Int, `argument two`: Int) -> Int {
    `argument one` + `argument two`
}

`some weird method`(`argument one`: 1, `argument two`: 2)
```

I get warnings that the arguments don't need to be escaped, If I apply the fixit, it removes the backticks and the code won't compile.

![Screen Shot 2020-01-24 at 2 03 03 PM](https://user-images.githubusercontent.com/238323/73107295-52a70600-3eb2-11ea-9a6c-d6644eafe5c7.png)

2020-01-28 19:54 UTC, adellibovi commented
Closing as the proposal got rejected, thanks for the PR review anyway!

2020-01-28 19:54 UTC, closed without merging