[stdlib] Backport withContiguousStorageIfAvailable to SubString.UTF8View to 5.2
swiftlang/swift pull request #29380
Opened 2020-01-23 14:39 UTC by Lukasa

This is a back port of #29146 to the 5.2 branch. I don't see any particular reason for this wart to persist in Swift 5.2, and the patch is straightforward enough that I think its risk is low, so I'd like to propose we take this back port.

2020-01-24 00:15 UTC, kylemacomber requested changes
I know this is a really low risk change, but it seems pretty late to me to be landing this in 5.2.

2020-01-24 15:33 UTC, Lukasa commented
@kylemacomber I understand that concern, though it's a shame. How negotiable is that stance? 😁

2020-01-24 22:59 UTC, lorentey commented
IIUC, this change depends on https://github.com/apple/swift/pull/28883, but that change hasn't been cherry-picked to 5.2. There is no point in taking this one without the other.

Both of these are low-risk changes but they also seem to have relatively low impact. As such, we wouldn't normally cherry-pick them to a release branch (this is why #28883 is missing from 5.2 -- it wasn't an accidental omission).

If you have a specific use case that bumps the impact of these, then of course you should insist on merging both these changes. There is a bit of ceremony involved: you'll need to fill out the nomination template (as described in the [5.2 release process](https://swift.org/blog/5-2-release-process/) announcement); the Explanation field there would be a good place to describe the reason for the urgency.

2020-01-24 23:05 UTC, lorentey commented
@swift-ci test

2020-02-10 05:50 UTC, futurejones commented
Can one of the admins verify this patch?

2020-04-02 22:30 UTC, tkremenek commented
@swift-ci clean test

2020-04-03 15:18 UTC, tkremenek commented
Is there a reason to leave this PR open?

2020-04-03 16:15 UTC, Lukasa commented
I don't think so, I think its time has passed.

2020-04-03 16:15 UTC, closed without merging