CI: stylistic changes to simplify script
swiftlang/swift pull request #29671
Opened 2020-02-06 06:28 UTC by compnerd

Use CMake more effectively to both build and change the working
directory.  This simplifies the number of steps and reduces possible
error points.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

2020-02-06 06:29 UTC, compnerd commented
@swift-ci please clean test windows platform

2020-02-06 06:29 UTC, compnerd commented
CC: @drodriguez

2020-02-06 06:41 UTC, drodriguez requested changes
I think LLDB is missing the build directory, otherwise looks good.

2020-02-06 06:41 UTC, drodriguez commented on utils/build-windows.bat
> +cmake^
Missing `-B`?

2020-02-06 16:56 UTC, compnerd commented on utils/build-windows.bat
> +cmake^
mechanical changes are difficult!

2020-02-06 17:23 UTC, compnerd commented
@swift-ci please clean test Windows platform

2020-02-06 17:24 UTC, compnerd commented
@swift-ci please clean test Windows platform

2020-02-07 16:12 UTC, compnerd commented
@swift-ci please clean test Windows platform

2020-02-07 16:39 UTC, drodriguez approved these changes

2020-02-07 19:04 UTC, compnerd commented
@swift-ci please clean test Windows platform

2020-02-07 21:04 UTC, compnerd commented
@swift-ci please smoke test

2020-02-07 23:04 UTC, merged