[Parse] Add an attribute for typeEraser.
swiftlang/swift pull request #29775
Opened 2020-02-12 00:41 UTC by hborla

This will be used for compiler-driven type erasure for dynamic replacement of functions with an opaque return type. For now, just parse the attribute and ignore it.

2020-02-12 00:41 UTC, hborla commented
@swift-ci please smoke test

2020-02-12 00:50 UTC, xedin approved these changes

2020-02-12 01:21 UTC, DougGregor requested changes

2020-02-12 01:21 UTC, DougGregor commented on lib/Serialization/Serialization.cpp
> +      TypeEraserDeclAttrLayout::emitRecord(S.Out, S.ScratchRecord,
Hmm. I suggest removing the serialization code here, since this will be `NotSerialized`.

2020-02-12 01:21 UTC, DougGregor commented on include/swift/AST/Attr.def
> +  ABIStableToAdd | ABIBreakingToRemove | APIStableToAdd | APIBreakingToRemove,
I suggest tagging this as `NotSerialized` for now, so it's completely ignored.

2020-02-12 01:38 UTC, hborla commented
@swift-ci please smoke test

2020-02-12 08:44 UTC, omochi commented
Is not spelling `typeErasure` ?

I found a word `type erasure` in this document.

> Prefixes and Suffixes
> Any is used as a prefix to denote "type erasure," e.g. AnySequence<T> wraps any sequence with element type T, conforms to SequenceType itself, and forwards all operations to the wrapped sequence. When handling the wrapper, the specific type of the wrapped sequence is fully hidden.

https://github.com/apple/swift/blob/master/docs/StdlibAPIGuidelines.rst#prefixes-and-suffixes

2020-02-12 16:36 UTC, hborla commented
@omochi The spelling "type eraser" is intentional to describe the type that implements type erasure. For example, the protocol `Sequence` could specify that its type eraser is `AnySequence`
```swift
@_typeEraser(AnySequence)
protocol Sequence {
```

2020-02-12 17:14 UTC, omochi commented
@hborla Sorry for my ambiguous sentences.
I talk about spelling is whether `erasure` or `eraser`.

2020-02-12 17:17 UTC, hborla commented
@omochi Yes, the spelling is intentional. The type _eraser_ is the type that implements type _erasure_.

2020-02-12 17:58 UTC, merged

2020-02-13 01:47 UTC, omochi commented
@hborla 

> The type eraser is the type that implements type erasure.

I finally understand what you say 🙂
Thank you.