Fixing build breaks for master-next against latest llvm.org.
swiftlang/swift pull request #29799
Opened 2020-02-12 23:21 UTC by plotfi

There were changes due to the StringRef to std::string conversion, changes in the Debug Info DIBuilder::createModule API, and a drop in the using for PointerUnion4 since PointerUnion is now a variadic template and will do in its place.

2020-02-12 23:21 UTC, plotfi commented
@compnerd @smeenai @JDevlieghere

2020-02-12 23:22 UTC, compnerd requested changes
The changes beyond `IRGenDebugInfo.cpp` should go to master

2020-02-13 21:55 UTC, JDevlieghere approved these changes

2020-02-14 01:36 UTC, plotfi commented
@compnerd can I get a test run and an approve?

2020-04-14 05:30 UTC, CodaFi commented
Looks like Raphael got this one in 728e8a1bde9b5e2ae219427dca70ff689e2f200a. Thanks!

2020-04-14 05:30 UTC, closed without merging