[NFC] Update required CMake version in README.md
swiftlang/swift pull request #29891
Opened 2020-02-17 21:19 UTC by MaxDesiatov

Currently, when building on Ubuntu, the system installed version (which is older than 3.15.1) is not sufficient, the required version should be specified explicitly.

2020-02-18 00:52 UTC, compnerd approved these changes

2020-02-18 00:53 UTC, compnerd requested changes
I think that we should make this clearer.  3.4.3 is sufficient - we *can* build CMake 3.15 with that and will do so.  This happens via build-script already.  If you are building without build-script, you are responsible for knowing the details of what happens in the implementation.

2020-02-19 20:55 UTC, MaxDesiatov commented
@compnerd I've clarified the text mentioning both versions and in which cases these requirements are applicable.

2020-02-19 21:07 UTC, compnerd approved these changes

2020-02-19 21:07 UTC, compnerd commented
@swift-ci please smoke test

2020-02-24 13:43 UTC, MaxDesiatov commented
@compnerd I don't think OS X failure is related. Can this be merged yet?

2020-03-02 15:50 UTC, MaxDesiatov commented
@compnerd ping

2020-03-13 10:14 UTC, MaxDesiatov commented
@compnerd would you have another look please? Is there anything that prevents this from being merged?

2020-04-01 10:30 UTC, MaxDesiatov commented
Closing as subsumed by #30695

2020-04-01 10:30 UTC, closed without merging