[Tests] Mark some CrossImport tests as unsupported on Windows
swiftlang/swift pull request #29962
Opened 2020-02-20 18:25 UTC by devincoughlin

Unblock Windows testing by marking some CrossImport tests as
unsupported on Windows.

2020-02-20 18:26 UTC, devincoughlin commented
@swift-ci please smoke test and merge

2020-02-20 18:48 UTC, compnerd requested changes
Please don't mark this as unsupported on Windows.  It should be treated as a failure on macOS.

2020-04-18 21:25 UTC, compnerd commented
The underlying issues here were addressed right?  Is this still useful @devincoughlin?

2020-10-01 06:56 UTC, shahmishal commented
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

2020-10-05 21:31 UTC, closed without merging