removed scalar from test string as it is logically invalid/undefined …
swiftlang/swift pull request #30282
Opened 2020-03-08 02:10 UTC by rnantes

Removes a scalar from test input that was logically invalid.

As discussed in this  [`forum post`](https://forums.swift.org/t/is-this-a-bug-in-swift-stdlib-character-isuppercase/34385/6) the generated string used in this test includes a scalar in the character L̥̖͎͓̪̫ͅ that is logically invalid. With this scalar it is undefined if this character is in fact uppercase. With this PR the scalar is removed from the character in the test strings.

2020-03-08 21:35 UTC, xwu commented
Note: As was stated in the forum post, it is very much defined whether this character is uppercase (it is not). What's ambiguous is what one would expect any case transformation operation to do with it as part of encoding or decoding JSON.

2020-03-09 04:08 UTC, rnantes commented
> Note: As was stated in the forum, it is very much defined whether this character is uppercase (it is not), and there's nothing "logically invalid" about the character. What's ambiguous is what one would expect any case transformation operation to do with it as part of encoding or decoding JSON, and the rationale for removal would be that there's no need to ensure what should occur in those causes because there's no realistic use case that would exercise this behavior.

Yes that is correct. Poor choice of words on my part.

2020-03-10 17:09 UTC, CodaFi requested changes
Could you please amend the commit message to expand on what @xwu said and perhaps add a comment above this test about this case. At some point, somebody is going to come across this code and have the same question you did about why this state of affairs exists.

2020-03-22 18:37 UTC, rnantes commented
@CodaFi I have amended the commit. Let me know if this suits the change or if you would like it to be reworded further thanks!

2020-03-22 20:25 UTC, xwu commented
As @CodaFi mentioned, it would be nice to have more explanation in the test than just "because Itai wanted to test this."

2020-04-15 01:23 UTC, CodaFi commented
Apologies for the delay

> Removed scalar from test string because it is ambiguous as to what the correct funcionality for the snake case conversion should be and there is no expectation that this behaviour is needed in this use case

This tells me what, it does not tell me *why*. Could you be a little more descriptive than this?

2020-10-01 06:56 UTC, shahmishal commented
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

2020-10-05 21:31 UTC, closed without merging