Add swiftcc attribute for runtime functions called from Swift
swiftlang/swift pull request #30938
Opened 2020-04-10 01:30 UTC by kateinoigakukun

This change marks all functions called using swiftcc as swiftcc attribute.

On most of architectures, C calling convention functions can be invoked using swiftcc.
 However on WebAssembly, swiftcc invocation strictly requires callee function is swiftcc to match the number of parameters with arguments.

Reference: https://reviews.llvm.org/D76049

2020-04-10 01:39 UTC, compnerd commented
Doesn't this break backwards compatibility on macOS?

2020-04-10 01:43 UTC, kateinoigakukun commented
@compnerd As far as I know, C calling convention is compatible with swiftcc when not using swiftself or swifterror, so this doesn't break backward compatibility.

2020-04-12 16:09 UTC, jckarter requested changes
This absolutely breaks ABI compatibility even if you aren't using the special registers. Aside from using the special self and error registers, Swift functions have a higher threshold for number of return registers, and divide aggregates differently from the C calling convention. It is not generally safe to mix the Swift and C calling conventions. Why do you want to make this change?

2020-04-12 16:30 UTC, omochi commented
@jckarter @kateinoigakukun 

It's interesting.

Some swift code in standard library import runtime function by using `@_silgen_name` like here.

https://github.com/apple/swift/blob/0c9c901c94e7aa9c3df0c68b8825fc55d46f043e/stdlib/public/core/DebuggerSupport.swift#L261-L262

In my understanding, all name only declared functions are considered as swiftcc in swift compiler.

So, are these implementations generally unsafe currently?

Instead of defining runtime function as swiftcc,
we should introduce a way that declare functions as c convention in swift side.

Example:

```swift
@_silgen_name("swift_retainCount") @convention(c)
public func _getRetainCount(_ Value: AnyObject) -> UInt
```

2020-04-12 16:48 UTC, jckarter commented
Yes, it is a bug to use `@_silgen_name` to call a function with the C calling convention. C functions can be declared by importing the C declaration from a C header. In this case, it looks like `_getRetainCount` is only used in tests, so I would try removing the `_getRetainCount` declaration and updating the test to import `swift_getRetainCount` with a C header.

2020-04-12 17:14 UTC, jckarter commented
cc @dcci who added those `_retainCount` declarations. Are those used by the debugger or other tools in addition to stdlib tests?

For functions like `swift_retainCount` with only one register-size argument and return, changing them to swiftcc might be harmless if we need to keep the API around. I'd hesitate to change the calling convention more generally than that, though.

2021-09-18 14:25 UTC, MaxDesiatov commented
Per our discussion in https://forums.swift.org/t/calling-convention-mismatch-violations-between-runtime-stdlib-and-emitted-code/51975, it seems that this could still proceed? Or is there anything else that needs to be addressed?

2021-09-18 14:25 UTC, MaxDesiatov commented
@swift-ci please smoke test

2021-09-18 14:26 UTC, MaxDesiatov commented
Requesting a review from @meg-gupta as someone who recently edited these files and I had to resolve conflicts with those edits.

2021-09-28 11:45 UTC, MaxDesiatov commented
@swift-ci please smoke test

2021-09-28 18:39 UTC, MaxDesiatov commented
@swift-ci please smoke test macOS platform

2021-09-29 08:37 UTC, MaxDesiatov commented
@kateinoigakukun could you have a look at the failing macOS test? That seems to persist after re-running CI

2021-10-01 17:16 UTC, kateinoigakukun commented
This PR contains some types of changes and is obsolete now. I'm splitting this into small PRs, so close this for now.
e.g. https://github.com/apple/swift/pull/39119 https://github.com/apple/swift/pull/39546

2021-10-01 17:16 UTC, closed without merging