[stdlib] Fix for objc_copyClassList broken since snapshot 2019-08-27
swiftlang/swift pull request #31128
Opened 2020-04-18 20:38 UTC by johnno1962

Hi Apple,

Quick fix for AutoreleasingUnsafeMutablePointer when you are using it with an array of AnyClass objects (for example when using `objc_copyClassList()` from Swift).

Since Xcode 11.4/11.4.1, the following code crashes:
```
var nc: UInt32 = 0
if let classes = objc_copyClassList(&nc) {
    for i in 0 ..< Int(nc) {
        _ = "\(classes[i])"
    }
    free(UnsafeMutableRawPointer(classes))
}
```
With an error along the lines of
```
2020-04-18 22:26:49.986732+0200 SwiftTwaceApp[78749:972902] *** NSForwarding: warning: object 0x7fff87ba8ba8 of class 'JSExport' does not implement methodSignatureForSelector: -- trouble ahead
2020-04-18 22:26:49.987066+0200 SwiftTwaceApp[78749:972902] *** NSForwarding: warning: object 0x7fff87ba8ba8 of class 'JSExport' does not implement doesNotRecognizeSelector: -- abort
```

Seems to be an ownership issue related to the refactoring in #26760 that doesn't take into account the array could contain `AnyClass` instances (as conceded in a TODO for the struct.) This patch uses the old implementation for the `.pointee` getter if `Pointee.self == AnyClass.self`. Seems to resolve the problem for the code above for me.

Resolves [SR-12344](https://bugs.swift.org/browse/SR-12344).

2020-04-18 21:21 UTC, johnno1962 commented
Can anybody think of a workaround until the toolchain is fixed?

2020-04-18 23:10 UTC, CodaFi requested changes
A strong load will happen to work here in a lot of cases, but is still not correct with respect to the ownership semantics implied by `AutoreleasingUnsafeMutablePointer`. It seems like the bridged return type for `objc_copyClassList` might be to blame instead.

2020-04-18 23:20 UTC, CodaFi commented
Though, I'm not really sure what we can do about this. Declaring the pointee `__strong` on libObjC's side won't actually change the behavior of the importer.

2020-04-18 23:26 UTC, CodaFi commented
Actually, isn't this behavior intended? What you're seeing is that you cannot reliably print root classes because you only have an `AnyObject`, not an `NSObject` bound here.

2020-04-18 23:43 UTC, CodaFi commented
Yup, that's what this is

```
// BridgingHeader.h
OBJC_ROOT_CLASS @interface MyRootClass
@end
```

```
// Test.swift
print(MyRootClass.self)
```

> 2020-04-18 16:42:35.585496-0700 Reproducer[92523:5665605] *** NSForwarding: warning: object 0x1002cc248 of class 'MyRootClass' does not implement methodSignatureForSelector: -- trouble ahead
> 2020-04-18 16:42:35.585543-0700 Reproducer[92523:5665605] *** NSForwarding: warning: object 0x1002cc248 of class 'MyRootClass' does not implement doesNotRecognizeSelector: -- abort

2020-04-19 00:06 UTC, CodaFi commented
In fact, you won't be able to load `AnyClass` instances because we emit a `strong_copy_unmanaged_value` as a consequence of the access to the class list. This expands to a `swift_unknownObjectRetain` that tries to send `retain` to the object. A terrible, awful workaround would be to manipulate the class list with an UnsafeRawPointer instead. There, you'll only have raw-yet-typed loads that won't involve ARC traffic. Another terrible, awful solution on our end would be changing the return type of `objc_copyClassList` to involve `Unmanaged`.

2020-04-19 00:34 UTC, CodaFi commented
Give this a shot instead

```
var nc: UInt32 = 0
if let classes = objc_copyClassList(&nc) {
  let ptr = UnsafePointer<AnyClass>(classes)
  for i in 0 ..< Int(nc) {
    print(ptr[i])
  }
  free(UnsafeMutableRawPointer(classes))
}
```

2020-04-19 01:40 UTC, CodaFi commented
Note that this "works" by convincing the compiler we have the appropriate `__strong` references to the metaclasses in this buffer, so it doesn't need to defensively retain on the access. This is a lie that has very bad consequences in optimized code. The most correct answer is to do what `AutoreleasingUnsafeMutablePointer` is trying to do for you here and recast the ponter to `UnsafePointer<Unmanaged<AnyClass>>`.

2020-04-19 09:41 UTC, johnno1962 commented
Thanks for the work-around @CodaFi. I’m Up up and running again with [these changes](https://github.com/johnno1962/SwiftTrace/commit/c7b76dad214403caed44492a27d01789e2709a0f) to the project that was causing the problem. I’ll leave this PR as is until others have had a chance to comment. It would be a shame if `objc_copyClassList()` no longer worked from Swift.

2020-04-19 18:21 UTC, CodaFi commented
It’s not that it no longer works. This is intended behavior given the return type of this function - the mismatch comes from AUMP being used instead of a plain pointer, which may stem from mistakenly translating ObjC code.  When invoked from Objective-C, the result is a buffer of Class pointers, and accesses to that buffer are typed loads without involving ARC.  In Swift, we bridge the buffer’s contents to an ARC-aware type. So in order to recover the intended semantics, you need to avoid sending ANY messages to these metaclasses, just as in ObjC.

2020-04-21 05:25 UTC, johnno1962 commented
Problem seems to be these root classes as I’m seeing similar crashes in Objective-C:
```
NSArray<Class> *objc_classArray() {
    unsigned nc;
    NSMutableArray<Class> *array = [NSMutableArray new];
    if (Class *classes = objc_copyClassList(&nc))
        for (int i=0; i<nc; i++)
//            if (class_getSuperclass(classes[i]))
                [array addObject:classes[i]]; // crashes here
    return array;
}
```
If you uncomment the `class_getSuperclass` line you can avoid the crash and this works in Swift (argument is marked as unretained).
```
        if let classes = objc_copyClassList(&nc) {
            for i in 0 ..< Int(nc) {
                if class_getSuperclass(classes[i]) == nil {
                    continue
                }
                callback(classes[i], &stopped)
                if stopped {
                    break
                }
            }
            free(UnsafeMutableRawPointer(mutating: classes))
        }
```

2020-04-22 18:40 UTC, mikeash commented
It's not quite root classes, but classes that don't support basic operations like `retain` and `release`. It just so happens that such classes are mostly root classes. There could potentially be a subclass of one of those which would also fail.

The right way to handle this is to whitelist certain class hierarchies and check for membership using a technique that doesn't require any functionality in the class itself. For example, you might limit yourself to `NSObject` subclasses by using `class_getSuperclass` to see if its root class is `NSObject`. Rejecting anything unknown will help avoid problems.

Even this isn't completely safe, as it's entirely possible for someone to implement an `NSObject` subclass that doesn't like to be messaged. If at all possible, restrict your search to subclasses of your own class, or implementors of a particular protocol. Or better yet, avoid the dynamism and manually register your classes; it's not quite as cool, but it usually works out more nicely in the end.

As far as this fix goes, I don't think special-casing `AnyClass` on `AutoreleasingUnsafeMutablePointer` is the right approach. Really, it's a bad import of the API; the return type should be `UnsafePointer<AnyClass>` but the importer doesn't have enough info to determine that. I'd like to apply a fix in the overlay instead.

In the meantime, you can emulate this fix and work around the problem in your own code by converting the return value to an `UnsafePointer` before you use it:

```
var n: UInt32 = 0
let l = UnsafePointer(objc_copyClassList(&n)!)
for i in 0 ..< Int(n) {
    _ = NSStringFromClass(l[i])
}
```

2020-05-12 13:55 UTC, johnno1962 commented
I’m closing this as someone seems to have picked up the ball and is running with it, in a different direction :)

2020-05-12 13:55 UTC, closed without merging