Remove -force-single-frontend-invocation
swiftlang/swift pull request #31621
Opened 2020-05-07 15:32 UTC by davezarzycki

This option predates -whole-module-optimization and is no longer needed.

2020-05-07 15:32 UTC, davezarzycki commented
@swift-ci please smoke test

2020-05-07 15:36 UTC, harlanhaskins requested changes

2020-05-07 15:36 UTC, harlanhaskins commented on include/swift/Option/Options.td
> -def force_single_frontend_invocation :
I’m fine with removing the flag but let’s leave this option here as an alias for -whole-module-optimization. We have existing clients passing -force-single-frontend-invocation and we can’t break them.

2020-05-07 16:10 UTC, CodaFi requested changes
Thanks for the cleanup! I agree with Harlan's assessment: Let's leave behind an alias for now. You can even warn in the Driver about the flag being an alias. Any non-experimental flags in the driver are supposed to be considered part of a stable interface.

2020-05-07 16:20 UTC, compnerd commented
I think that the option alias is a requirement ... that is a driver flag.  Only the frontend flags can be removed, driver flags need to be maintained for compatibility.

2020-05-07 16:20 UTC, compnerd commented
@swift-ci please test Windows platform

2020-05-08 10:42 UTC, davezarzycki commented
I added the old flag alias back.

@swift-ci pleas smoke test

2020-05-08 10:42 UTC, davezarzycki commented
@swift-ci please test Windows platform

2020-05-08 14:07 UTC, harlanhaskins approved these changes

2020-05-08 14:18 UTC, davezarzycki commented
@swift-ci please smoke test

2020-05-08 16:48 UTC, CodaFi approved these changes

2020-05-08 16:48 UTC, merged