Ignore conflicting debug variables for same function argument.
swiftlang/swift pull request #31682
Opened 2020-05-09 21:49 UTC by zoecarver

It's possible to have two debug variables for the same function argument when [one function is inlined into the other](https://swift.godbolt.org/z/5uuWRp) so, we shouldn't crash. 

I'm not entirely sure this is the right fix. Maybe, instead, we should update the linliner to remove argument debug variables.

This is not only nice for debugging but also necessary for round-trip sil testing (read and dump sil between all passes).

2020-05-10 20:32 UTC, CodaFi commented on lib/SIL/Verifier/SILVerifier.cpp
> +          while (DebugVars.size() <= ArgNo) {
Seems like you could express this as a conditional/std::max-ified `DebugVars.resize()`?

2020-05-10 20:34 UTC, CodaFi commented
@adrian-prantl is the authority here, but it seems like we should be fixing the passes that cause this situation instead of silencing the verifier. It certainly seems like we should RAUW those argument debug_values.

2020-05-10 20:53 UTC, zoecarver commented
@CodaFi Removing them when we inline a function wouldn't be difficult. That's a good solution which I'm happy with (I can update the patch if that's what we decide on). We do leave normal debug_values, though. So It seems like we should keep these too. Or maybe just remove the argument number. 

Also, what does "RAUW" mean?

2020-05-10 20:57 UTC, gottesmm commented
@adrian-prantl is the person to review this for sure. RAUW means replace all uses with.

2020-05-11 19:58 UTC, adrian-prantl requested changes
> It's possible to have two debug variables for the same function argument when one function is inlined into the other so, we shouldn't crash.

This statement sounds like there might be a misunderstanding of how variable debug info is represented in SIL.

A source variable referenced by a `debug_value`, `debug_value_addr`, or `alloc_stack` instruction is uniquely identified through its combination of name and scope. You can visualize this by passing -Xllvm -sil-print-debuginfo -emit-sil to the compiler:

`debug_value %0, $Int, let, name "x", argno 1, loc "file.swift":23, scope 1`

The scope serves two purposes:
1. it tells which function the variable belongs to
  e.g., `sil_scope 1 { loc "file.swift":20 parent @$s3fooF ` ...
2. the inlineAt filed tells us which inlined **instance** of the function the variable belongs to
  ... `inlinedAt 2 }`
  `scope 2 { loc bar.swift:100 parent 3 }`, etc ...

Most likely there is an optimization pass that is accidentally dropping the inline info and thus you end up with two copies of the variable ending up in the same scope. That's what you want to look for. If you just disable the verifier, like in this patch, you will run into a similar verifier failure / assertion / crash at the LLVM level, that is going to be even harder to trace back to the root cause.

2020-05-11 20:55 UTC, zoecarver commented
@adrian-prantl that's very good to know. Thank you for all the information. 

It looks like all the scope information is present. I don't think that's the issue. It looks like the verifier doesn't check the scope, though. I'll update the verifier to require that the debug var names are different _or_ the scope is different, WDYT?

Unfortunately, when sil is dumped the scope information is lost. So, we still have the issue for round-tripping sil. Any ideas about the best way to solve that? Maybe we should not dump debug instructions with a scope outside the current function. I can't think of a scenario where we'd need that information in raw-text sil.

2020-05-11 21:24 UTC, adrian-prantl commented
> @adrian-prantl that's very good to know. Thank you for all the information.
> 
> It looks like all the scope information is present. I don't think that's the issue. It looks like the verifier doesn't check the scope, though. I'll update the verifier to require that the debug var names are different _or_ the scope is different, WDYT?

I don't think that it true. The block you were modifying in this patch is nested inside an `if (!DS->InlinedCallSite) {`, which means that it only applies to variables/arguments without inline info.

> 
> Unfortunately, when sil is dumped the scope information is lost. So, we still have the issue for round-tripping sil. Any ideas about the best way to solve that? 

Can you elaborate what you mean? Textual .sil is lossy in terms of debug info, but scope info should not be a problem (see my example from my previous reply). Or are you saying that it is not serialized in binary SIL?

> Maybe we should not dump debug instructions with a scope outside the current function. I can't think of a scenario where we'd need that information in raw-text sil.

All the test cases for SIL debug info and inlining in the compiler are relying on this feature.

2020-05-11 21:33 UTC, zoecarver commented
> I don't think that it true. The block you were modifying in this patch is nested inside an if (!DS->InlinedCallSite) {, which means that it only applies to variables/arguments without inline info.

You're right. I didn't look close enough. 

> Can you elaborate what you mean? Textual .sil is lossy in terms of debug info, but scope info should not be a problem (see my example from my previous reply). Or are you saying that it is not serialized in binary SIL?

No, I'm talking about textual .sil. The issue is when I dump sil with `-emit-sil` or `.dump()` I don't get scope / inline information. The information is there, because when I pass swift `-Xllvm -sil-print-debuginfo` (as you suggested) it works great: 
```
sil_scope 4 { loc "run.swift":3:13 parent @$s3run5entry1yS2i_tF : $@convention(thin) (Int) -> Int }
sil_scope 5 { loc "run.swift":3:35 parent 4 }
sil_scope 6 { loc "run.swift":4:12 parent 5 }
sil_scope 7 { loc "run.swift":1:13 parent @$s3run3fooyS2iF : $@convention(thin) (Int) -> Int inlined_at 6 }

// entry(y:)
sil @$s3run5entry1yS2i_tF : $@convention(thin) (Int) -> Int {
// %0 "y"                                         // users: %3, %2, %1
bb0(%0 : $Int):
  debug_value %0 : $Int, let, name "y", argno 1, loc "run.swift":3:19, scope 4 // id: %1
  debug_value %0 : $Int, let, name "x", argno 1, loc "run.swift":1:19, scope 7 // id: %2
  return %0 : $Int, loc "run.swift":4:5, scope 5  // id: %3
} // end sil function '$s3run5entry1yS2i_tF'
```

But, without that (just `swift run.swift -emit-sil`), I get:
```
// entry(y:)
sil @$s3run5entry1yS2i_tF : $@convention(thin) (Int) -> Int {
// %0 "y"                                         // users: %3, %2, %1
bb0(%0 : $Int):
  debug_value %0 : $Int, let, name "y", argno 1   // id: %1
  debug_value %0 : $Int, let, name "x", argno 1   // id: %2
  return %0 : $Int                                // id: %3
} // end sil function '$s3run5entry1yS2i_tF'
```

Which doesn't have the inline information. So,  when I parse and verify that function (as a .sil input file) I get an error.

2020-05-11 22:46 UTC, adrian-prantl commented
> No, I'm talking about textual .sil. The issue is when I dump sil with -emit-sil or .dump() I don't get scope / inline information. 

I see what you mean now. You're saying that you can't do `swiftc -emit-sil -o - | swiftc -verify` without also passing `-Xllvm -sil-print-debuginfo`. That's a valid complaint. My personal opinion is that `-sil-print-debuginfo` should be the default and instead we should have a `-Xllvm -sil-hide-debuginfo`. The reason why we felt this option was necessary at all is that contrary to LLVM IR, in SIL the source location information is not optional, but present regardless of whether you are compiling with or without `-g`, so having a less verbose output option was seen beneficial.

My main concern with stripping the debug_values / locations from SIL by default is that it will make it easier for optimization authors to forget handling them and that that will lead to more issues like the one you are investigating here.

2020-05-11 23:02 UTC, zoecarver commented
> You're saying that you can't do swiftc -emit-sil -o - | swiftc -verify without also passing -Xllvm -sil-print-debuginfo. 

Exactly. Well-put. 

> My personal opinion is that -sil-print-debuginfo should be the default and instead we should have a -Xllvm -sil-hide-debuginfo.

I'd also be happy with this but I suspect that would be a larger change that would require more discussion. 

> My main concern with stripping the debug_values / locations from SIL by default is that it will make it easier for optimization authors to forget handling them and that that will lead to more issues like the one you are investigating here.

It's a bit of a paper-over fix but, what do you think about stripping the argument number when dumping a debug instruction that has a scope associated with a different function? That way the debug instruction would still be there so tests would still work and optimization passes would still have to care about it but, it would resolve the error I bring up in the PR and allow for round-tripping textual sil.

2020-05-11 23:13 UTC, vedantk commented
Hm, but stripping out just the argument number may actually change the behavior (i.e. hide bugs) in subsequent passes.

Imo it's a bit of an unforced error to hide parts of the IR when dumping it out. If there's a test or workflow that depends on round-tripping SIL that contains debug info, all of the pertinent debug info really ought to be dumped out.

Sometimes seeing the debug info isn't necessary for what pass authors need to do. In those cases, we can borrow a solution from llvm: just explicitly run -strip-debug on the IR.

2020-05-12 01:39 UTC, zoecarver commented
@vedantk That's a fair point. It might make the most sense to either dump all (or none of) the debug info when round-tripping. I don't see any reason that wouldn't work.

2020-05-12 01:40 UTC, zoecarver commented
I'll go with that for now. Feel free to post other solutions, though.

2020-05-12 01:40 UTC, closed without merging