[SymbolGraph] Show get/set on protocol requirement full declarations
swiftlang/swift pull request #31903
Opened 2020-05-20 00:08 UTC by bitjammer

But don't show them in subheading contexts.

rdar://63233897

2020-05-20 00:08 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-20 00:13 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-20 21:02 UTC, jackhl requested changes
Can you add a test that a `let` stored property gets a `{get}` and a `var` stored property gets a `{get set}`?

2020-05-20 21:11 UTC, bitjammer commented on lib/SymbolGraphGen/SymbolGraph.cpp
> +  // we don't want to show these for even for protocol requirements
That's some good copy pasta :).

2020-05-20 21:17 UTC, bitjammer commented on lib/SymbolGraphGen/SymbolGraph.cpp
> +  // we don't want to show these for even for protocol requirements
Fixed, thanks.

2020-05-20 21:17 UTC, bitjammer commented
Stored properties don't show `{ get set }` -- see https://developer.apple.com/documentation/coregraphics/cgpoint/1456040-x.

2020-05-20 21:18 UTC, bitjammer commented
@swift-ci Please smoke test.

2020-05-20 22:24 UTC, bitjammer commented
Looks like an unrelated swift-driver failure. Will try again in a little while.

2020-05-22 16:48 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-22 17:52 UTC, bitjammer commented
Windows bot is out of space.

2020-05-22 18:08 UTC, bitjammer commented
@swift-ci Please test Windows platform

2020-05-22 18:24 UTC, bitjammer commented
@swift-ci Please test Windows platform

2020-05-26 18:04 UTC, merged