[SymbolGraph] Look for @_spi on extensions
swiftlang/swift pull request #31985
Opened 2020-05-22 23:30 UTC by bitjammer

Consider declarations inside `@_spi` extensions to be internal.

Clean up the "implicitly private" check to work for `Decl` and not just
`ValueDecl`, allowing it to be used directly on extensions instead of having to
look for extensions everywhere.

rdar://63361634

2020-05-22 23:30 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-26 18:06 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-26 19:09 UTC, jackhl requested changes
This generally looks good, just a few small comment/name change suggestions.

2020-05-26 19:09 UTC, jackhl commented on lib/SymbolGraphGen/SymbolGraph.h
> +  bool isImplicitlyPrivate(const Decl *VD,
```suggestion
  bool isImplicitlyPrivate(const Decl *D,
```

2020-05-26 19:09 UTC, jackhl commented on lib/SymbolGraphGen/SymbolGraph.h
>    /// the context of the symbol to determine whether it is implicitly private.
Are all `Decl`s symbols or just `ValueDecls`? If `Decl`s include more than just symbols (e.g. extensions) then this comment should change.

```suggestion
  /// the context of the declaration to determine whether it is implicitly private.
```

2020-05-26 19:09 UTC, jackhl commented on lib/SymbolGraphGen/SymbolGraphASTWalker.cpp
>      // Ignore effecively private decls.
```suggestion
    // Ignore effectively private decls.
```

2020-05-26 20:32 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-26 22:58 UTC, bitjammer commented
@swift-ci Please smoke test Linux Platform

2020-05-27 23:09 UTC, bitjammer commented
@swift-ci Please smoke test

2020-05-28 16:46 UTC, bitjammer commented
@swift-ci Please smoke test Linux Platform

2020-05-28 19:54 UTC, merged