Ignore onFastPath builtin while looking for valid static initializer of a global variable
swiftlang/swift pull request #32319
Opened 2020-06-11 17:22 UTC by meg-gupta

The presence of this builtin has no effect while optimizing initializers of global variables.

2020-06-11 17:23 UTC, meg-gupta commented
@swift-ci smoke test

2020-06-12 00:27 UTC, meg-gupta commented
@swift-ci smoke test OS X

2020-06-12 06:45 UTC, meg-gupta commented
@swift-ci Please smoke test OS X platform

2020-06-12 06:45 UTC, meg-gupta commented
@swift-ci Please smoke test Linux platform

2020-06-12 09:33 UTC, eeckstein requested changes
You need to handle this builtin also in IRGen's emitConstantValue().
It would make sense to add a run command line with -emit-ir to test/SILOptimizer/optionset.swift, so that this is also tested.

2020-06-15 08:48 UTC, meg-gupta commented
@eeckstein I can't seem to write a test where the builtin needs to be handled in IRGen's emitConstantValue. Looks like onFastPath builtin is generated with no users during SILGen, so the static initializer will not have the onFastPath builtin. Additionally, we never seem to call emitConstantValue for an empty type.

2020-06-15 09:07 UTC, eeckstein approved these changes
@meg-gupta okay, thanks for checking. If it compiles, then it's fine.

2020-06-15 17:23 UTC, merged