[WIP] workarounds for regression SR-12831 on master/5.3 toolchains since Feb 7th
swiftlang/swift pull request #32484
Opened 2020-06-21 09:55 UTC by johnno1962

Hi Apple,

OK, so it’s a busy week but I thought I’d file a quick workaround I’ve had to use to get one of my repos [johnno1962/SwiftTrace](https://github.com/johnno1962/SwiftTrace) to be able to compile with a toolchain built from master & 5.3 branch. At the moment you get a `Segmentation fault: 11` during module merge due to dereferencing a nullptr as detailed in [the ticket](https://bugs.swift.org/browse/SR-12831).  I've bisected the various recent downloadable toolchains and this dates back to commits on February 7th and looking at where it crashes it seems to be related to [this new functionality](https://github.com/apple/swift/pull/29670) cc: @rjmccall.

The problem declaration is [this](https://github.com/johnno1962/SwiftTrace/blob/master/SwiftTrace/SwiftSwizzle.swift#L93) which is `@convention(c)` but actually a SwiftDecl:
```Swift
       static var onEntry: @convention(c) (_ swizzle: Swizzle, _ returnAddress: UnsafeRawPointer,
           _ stackPointer: UnsafeMutablePointer<UInt64>) -> IMP? = {
               (swizzle, returnAddress, stackPointer) -> IMP? in
               // etc...
```
If I remove the `@convention(c)` it will compile but give an error at runtime. I need to store a pointer to a C function in a static. This has been compiling fine previously.
 
Works around [SR-12831](https://bugs.swift.org/browse/SR-12831).

2020-06-22 19:37 UTC, CodaFi commented on lib/IRGen/GenType.cpp
> +// avoids error: "<unknown>:1:1: Cannot read '/usr/lib/swift/layouts-x86_64.yaml'"
The proper way to work around these is to ensure that your resource directory is properly formed. If you have built a custom toolchain, you will need to verify that these layout back-compat files are present under `My-Custom-Toolchain.xctoolchain/usr/lib/swift`.

2020-06-22 19:38 UTC, CodaFi commented on lib/IRGen/GenType.cpp
> +// avoids error: "<unknown>:1:1: Cannot read '/usr/lib/swift/layouts-x86_64.yaml'"
Please also note that these paths are subject to VFS remapping, and are sensitive to the `-resource-dir` flag.

2020-06-22 19:40 UTC, CodaFi requested changes
Your original crash is in Clang. I suspect you are having trouble with the coherency of a generated clang module if the AST reader is unable to parse something. You could try removing the module cache and rebuilding. But turning off huge portions of the deserialization code is not the right answer.

2020-06-23 07:28 UTC, johnno1962 commented
Thanks for triaging this @CodaFi, I’ve downloaded the Xcode 12 beta and cannot reproduce this problem. I’ll keep an eye on it and file a radar if it makes it into Xcode 12. Sorry for the noise ☺️.

2020-06-23 07:28 UTC, closed without merging