[NFC] Make StringRef to std::string conversions explicit.
swiftlang/swift pull request #32899
Opened 2020-07-15 10:00 UTC by varungandhi-apple

2020-07-15 10:00 UTC, varungandhi-apple commented
https://github.com/apple/llvm-project/pull/1461

@swift-ci please test

2020-07-15 11:36 UTC, gribozavr approved these changes

2020-07-15 16:19 UTC, varungandhi-apple commented
https://github.com/apple/llvm-project/pull/1462

@swift-ci please smoke test

2020-07-15 17:37 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test

2020-07-15 18:55 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test

2020-07-15 20:47 UTC, CodaFi requested changes
To be forwards-compatible, we need to use `StringRef::str()` here. It looks like these constructor calls are still going through the removed conversion operator.

2020-07-15 21:06 UTC, varungandhi-apple commented
Not sure what you mean. I still see the explicit conversion operator on llvm's master branch and apple/llvm's apple/master branch, which is what this patch is using. Where do you see it being removed?

2020-07-15 21:27 UTC, CodaFi approved these changes

2020-07-15 21:27 UTC, CodaFi commented
Absolutely right. Sorry, I was looking at the wrong diffs there.

:sail

2020-07-15 22:53 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test

2020-07-15 23:49 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test Linux platform

2020-07-16 00:44 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test Linux platform

2020-07-16 02:30 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test Linux platform

2020-07-16 03:20 UTC, varungandhi-apple commented
apple/llvm-project#1462

@swift-ci please smoke test Linux platform

2020-07-16 03:31 UTC, varungandhi-apple commented
Given that the rebranch has already started: let's just merge this, unblock the Swift master -> master-next automerger and wait for LLVM's `swift/master` to be updated with the rebranch.

@swift-ci please test

2020-07-16 05:07 UTC, varungandhi-apple commented
Closing this PR. Instead, let's just make the changes to master-next directly (https://github.com/apple/swift/pull/32897), like we've been doing so far. I talked to Mishal about how we should handle this; we can fix stuff on master before the rebranch in case more issues are introduced in the next ~2 weeks.

2020-07-16 05:07 UTC, closed without merging