[stdlib] Preserve random-access Mirror.children inside AnyCollection
swiftlang/swift pull request #33319
Opened 2020-08-05 20:49 UTC by airspeedswift

#32041 unintentionally lost the random-access nature of some collections. While the returned type is `AnyCollection`, you could restore random-access via `AnyRandomAccessCollection(mirror.children)`, but this now returned `nil` for some children. This PR restores this.

2020-08-05 20:49 UTC, airspeedswift commented
@swift-ci please test

2020-08-05 23:09 UTC, airspeedswift commented
@swift-ci please test

2020-08-06 16:26 UTC, airspeedswift commented
@swift-ci please test

2020-08-18 06:48 UTC, HoustonDuane requested changes

2020-08-18 06:48 UTC, HoustonDuane commented on test/stdlib/Mirror.swift
> +  expectTrue(c2?.first?.label as? Int == 42)
Shouldn't this be expectTrue(c2?.first?.**value** as? Int == 42)?

2020-08-18 06:48 UTC, HoustonDuane commented on test/stdlib/Mirror.swift
> +  expectTrue(c1?.first?.label as? Int == 1)
Shouldn't this be expectTrue(c1?.first?.**value** as? Int == 1)?

2020-08-18 06:56 UTC, HoustonDuane commented
@airspeedswift Hi, please review my comments regarding the two arguably copy errors 🧐

2020-10-01 06:54 UTC, shahmishal commented
Please update the base branch to `main` by Oct 5th otherwise the pull request will be closed automatically. 

* How to change the base branch: ([Link](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request))
* More detail about the branch update: ([Link](https://forums.swift.org/t/updating-branch-names/40412/))

2020-10-05 21:31 UTC, closed without merging