Re-implement DebuggerContextChange using a new mechanism
swiftlang/swift pull request #33795
Opened 2020-09-03 20:21 UTC by slavapestov

Expression evaluation in lldb wraps the entire user-written expression
in a new function body, which puts any new declarations written by the
user in local context.

There is a mechanism where declarations can get moved to the top level,
if they're only valid at the top level (imports, extensions etc), or
if the name of the declaration begins with '$'. This mechanism used to
actually add the declaration to the SourceFile's TopLevelDecls list,
which would break ASTScope invariants about source ranges being
monotonically increasing and non-overlapping.

Instead, we use the new 'hoisted' flag to mark the declarations as
hoisted, which leaves them syntactically in their original location
in the AST, but treats them as top level in SILGen and IRGen.

Part of <rdar://problem/53971116>.

2020-09-03 20:22 UTC, slavapestov commented
@swift-ci Please smoke test

2020-09-03 20:32 UTC, DougGregor approved these changes

2020-09-03 20:35 UTC, davidungar requested changes
This is great stuff! I'd like to see the invariant about the hoisting bit and the hoisted list factored out and also reified with an assertion.

2020-09-03 20:35 UTC, davidungar commented on include/swift/AST/Decl.h
> +    /// lldb.
Excellent!

2020-09-03 20:35 UTC, davidungar commented on lib/Parse/ParseDecl.cpp
> +        getDebuggerClient()->didGlobalize(D);
There is an invariant here, I'm guessing that these three always go together. If so, how about factoring this out, and lines 118-121 into a separate function? I'm guessing you've also added assertions for the invariant.

2020-09-03 20:35 UTC, davidungar commented on lib/Sema/TypeChecker.cpp
> +      visitTopLevelDecl(D);
This might be the place for the consistency-checking assertion.

2020-09-03 22:50 UTC, slavapestov commented
I discussed the suggested improvements with @davidungar offline. We both agree they’re good but I’m going to apply them to a follow-up PR since I have more cleanups in this area and I don’t want to run PR tests again.

2020-09-03 22:50 UTC, merged

2020-09-04 01:49 UTC, davidungar commented
Works for me! Thanks, @Slava -- this is great stuff!