Add a SWIFT_STDLIB_HAS_DARWIN_LIBMALLOC flag to allow/disallow uses of Darwin libmalloc APIs (malloc_default_zone, malloc_zone_malloc, etc.)
swiftlang/swift pull request #33812
Opened 2020-09-04 23:56 UTC by kubamracek

2020-09-04 23:56 UTC, kubamracek commented
@swift-ci please test

2020-09-05 04:00 UTC, kubamracek commented
@swift-ci please test

2020-09-05 17:01 UTC, kubamracek commented
@swift-ci please test stdlib with toolchain

2020-09-08 14:05 UTC, mikeash requested changes

2020-09-08 14:05 UTC, mikeash commented on include/swift/Runtime/Concurrent.h
> +        defined(SWIFT_STDLIB_HAS_DARWIN_LIBMALLOC)
You'll want this to just be `SWIFT_STDLIB_HAS_DARWIN_LIBMALLOC` (no `defined()` around it) to handle the case where it's `0`.

2021-08-23 20:54 UTC, kubamracek commented
@swift-ci please test

2021-08-23 21:15 UTC, mikeash approved these changes

2021-08-24 02:37 UTC, merged