Copy sources from Differentiation before building
swiftlang/swift pull request #34193
Opened 2020-10-05 22:00 UTC by edymtt

This is needed since the generation of files from gyb templates gets
confused when trying to use files in parent directories.
Symlinks are likely not an option since they could not be available
under a Windows build environment

Take this chance to add the proper header to the file

Addresses rdar://69953208

2020-10-05 22:00 UTC, edymtt commented
@swift-ci please smoke test

2020-10-05 22:05 UTC, rxwei approved these changes

2020-10-06 05:39 UTC, compnerd requested changes
I think that it makes more sense to just push this down to the same directory.  Your current change wont work with incrementals as the copy will only occur once at configure time.

2020-10-23 17:03 UTC, edymtt commented
Turns out that I did not need to introduce this implementation of Differentiation in the first place.

Closing this PR and tracking removal in #34409

2020-10-23 17:03 UTC, closed without merging