update and unify the "please file a bug report" message
swiftlang/swift pull request #34376
Opened 2020-10-21 12:10 UTC by eeckstein

The new message is:
"Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace."

1. In crash logs we used to print a message which points to the llvm bug tracking page. Now it points to the swift.org bug tracking guidelines.
2. Use the same message in all compiler diagnostics which ask the user to file a bug report.

rdar://problem/70488534

2020-10-21 12:11 UTC, eeckstein commented
@swift-ci smoke test

2020-10-22 18:04 UTC, brentdax requested changes
I like the concept, but this doesn't match our diagnostic style.

2020-10-23 10:01 UTC, eeckstein commented
@brentdax I pushed a new version

2020-10-23 10:01 UTC, eeckstein commented
@swift-ci smoke test

2020-10-28 21:26 UTC, brentdax approved these changes
Looks great, thanks!

2020-10-29 07:37 UTC, merged