[Runtime] Define GOT equivalents for Linux for BuiltinProtocolConformances
swiftlang/swift pull request #34457
Opened 2020-10-27 06:24 UTC by Azoy

Some Linux archs+platforms don't support relocations like `@GOTPCREL` which is what we defaulted to using on ELF platforms. Create a GOT equivalent for indirect symbols we reference for ELF (mirroring what the Swift compiler currently does). This should fix external CI testing platforms.

2020-10-27 06:24 UTC, Azoy commented
@swift-ci Please test

2020-10-27 10:28 UTC, xwu commented
@swift-ci Please test

2020-10-27 14:33 UTC, xwu commented
@swift-ci Please test OS X platform

2020-10-27 16:26 UTC, gottesmm commented
@lhames what are your thoughts on this?

2020-10-27 17:26 UTC, jckarter commented
ELF assemblers do support GOT relative references, but the syntax is different. `@GOT` should work.

2020-10-27 17:36 UTC, jckarter commented
Maybe it would be more portable to write the assembly as a `.ll` file? LLVM ought to be able to generate the proper relocations for all of our target platforms.

2020-10-27 22:33 UTC, drodriguez commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +  "  .long (" SYMBOl ")\n" \
Minor: lowercase `l` at the end of `SYMBOl`.

2020-10-27 23:13 UTC, drodriguez commented
So with this patch applied, and the fix for the lowercase `l`, I get to the following error, which seems related:

```
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSQ2eeoiySbx_xtFZTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSHSQTb', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSH9hashValueSivgTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSH4hash4intoys6HasherVz_tFTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSH13_rawHashValue4seedS2i_tFTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSLSQTb', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSL1loiySbx_xtFZTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSL2leoiySbx_xtFZTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSL2geoiySbx_xtFZTq', defined in lib/swift/linux/x86_64/libswiftCore.so
/usr/bin/ld.gold: error: stdlib/public/runtime/CMakeFiles/swiftRuntime-linux-x86_64.dir/BuiltinProtocolConformances.cpp.o: cannot make copy relocation for protected symbol '$sSL1goiySbx_xtFZTq', defined in lib/swift/linux/x86_64/libswiftCore.so

> swift-demangle
$sSQ2eeoiySbx_xtFZTq
method descriptor for static Swift.Equatable.== infix(A, A) -> Swift.Bool
$sSHSQTb
base conformance descriptor for Swift.Hashable: Swift.Equatable
$sSH9hashValueSivgTq
method descriptor for Swift.Hashable.hashValue.getter : Swift.Int
$sSH4hash4intoys6HasherVz_tFTq
method descriptor for Swift.Hashable.hash(into: inout Swift.Hasher) -> ()
$sSH13_rawHashValue4seedS2i_tFTq
method descriptor for Swift.Hashable._rawHashValue(seed: Swift.Int) -> Swift.Int
$sSLSQTb
base conformance descriptor for Swift.Comparable: Swift.Equatable
$sSL1loiySbx_xtFZTq
method descriptor for static Swift.Comparable.< infix(A, A) -> Swift.Bool
$sSL2leoiySbx_xtFZTq
method descriptor for static Swift.Comparable.<= infix(A, A) -> Swift.Bool
$sSL2geoiySbx_xtFZTq
method descriptor for static Swift.Comparable.>= infix(A, A) -> Swift.Bool
$sSL1goiySbx_xtFZTq
method descriptor for static Swift.Comparable.> infix(A, A) -> Swift.Bool
```

(the usage of `ld.gold` is because it is the one available in the Android NDK, which is the setup the Android CI builders use).

I will try AArch64 next to see if the same error is generated. The fix seems to at least avoid the compilation problem. Thanks a lot for it. I would not have been able to figure out the changes necessary.

2020-10-28 02:04 UTC, Azoy commented
Can we even use LLVM IR though? From a quick search it seems that we don't always build with clang, sometimes we build with msvc and I don't believe it can compile ll files (maybe that's just for when building clang? I'm not sure).

Yeah I've been looking at LLVM source and found the assert when its checking the relocation for aarch64 ELF, and it seems to only support an absolute symbol or a `@PLT` relocation which I don't believe is the same thing. With the new issue you're seeing @drodriguez I found that  this seems to be an issue with gold and the fact that we can't PC-relative reference stdlib symbols in the runtime at compile time (which is why we have to go through GOT for these symbols in the first place).

2020-10-28 15:45 UTC, drodriguez commented
> Can we even use LLVM IR though?

The Windows build prefers MSVC for compiling (it's faster on Windows), but builds large parts of LLVM. I don't see `llc` explicitly listed in https://github.com/apple/swift/blob/main/utils/build-windows.bat#L199, but it might be possible to change the build slightly to compile and use that tool. I suppose that @compnerd might know if there's a chance of a `.ll` file working for this problem across platforms.

> With device tests, does that include Interpreter tests?

I don't think `Interpreter` tests are possible for cross-compiled targets, or I think they never have run in Android. I might be wrong. What I mean by "device tests" is those tests marked as `executable_test`, which need to execute the results of a compilation into the target device.

> If it doesn't that means the runtime test for this feature passed using @PLT no?

Yes. That's what I wanted to say with that disclaimer. I only run half of the tests. I would expect `@PLT` to make some noise in the device tests. Setting those up is a little bit complicated and takes long time. That's why I didn't do it.

2020-10-28 17:33 UTC, jckarter commented
> Can we even use LLVM IR though? From a quick search it seems that we don't always build with clang, sometimes we build with msvc and I don't believe it can compile ll files (maybe that's just for when building clang? I'm not sure).

The runtime can only be built with the just-built Clang, because upstream clang and msvc do not support the Swift calling convention. It should be fine to use LLVM IR.

2020-10-29 15:56 UTC, compnerd commented
@jckarter - it can also be built with a host compiler as long as the host compiler supports the SwiftCC.

2020-10-29 15:59 UTC, compnerd requested changes

2020-10-29 15:59 UTC, compnerd commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +#if defined(__arm__) && !defined(__aarch64__)
PPC uses the `%` sigil as well

2020-10-29 15:59 UTC, compnerd commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +  "  .size .Lgot." SYMBOL ", 8\n"
I think you might want to have a level of indirection here.  The `.L` not guaranteed to the assembler local prefix.

2020-10-29 15:59 UTC, compnerd commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +#if defined(__x86_64__) || defined(__aarch64__)
PPC64?

2020-10-29 15:59 UTC, compnerd commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +  "  .size .Lgot." SYMBOL ", 4\n"
Similar here to the 8-byte case.

2020-10-29 15:59 UTC, compnerd commented on stdlib/public/runtime/BuiltinProtocolConformances.cpp
> +    "  .type .Lgot." SYMBOL ", " TYPE_OBJECT "\n" \
I think that you should create another macro to generate the name rather than use the `.Lgot." SYMBOL"` in multiple locations.

2020-10-29 16:31 UTC, compnerd commented
The copy relocation against a protected symbol has had issues in the past.  Dropping the visibility to default should work, or alternatively, I think that looking into R_*_GOTPCRELX might be useful.  Depending on the context in which it is used, we should be able to use the GOTPCREL variant of the symbol.

2020-10-29 17:22 UTC, jckarter commented
@compnerd We should never copy Swift symbols, and we really do want them to be `protected`.

2020-10-29 17:25 UTC, jckarter commented
> @jckarter - it can also be built with a host compiler as long as the host compiler supports the SwiftCC.

AFAIK that still implies some variation of Clang. If we tweak the swiftcc lowering, or the way the swiftcc maps into runtime C++, we're going to want to make the change to swift-clang in lockstep with swift itself, so using any other compiler is going to be brittle. However, we could use `llc` from the just built LLVM to compile `.ll` files if we don't want to rely on the runtime compiler being the just-built Clang.

2020-10-29 17:40 UTC, compnerd commented
Oh, assuming that the compiler that is used for building the runtime supports the correct thing is reasonable.  I don't think that we should be relying on `llc` as upstream officially deems it as an internal tool and provides no guarantees on it.  I think that just using out-of-line assembly might really be a significantly easier to maintain solution here.

2020-10-29 18:10 UTC, jckarter commented
I thought so too, but it looks like the correct assembly syntax for emitting the kinds of relocations we want is pretty tempermental and varies between platforms quite a bit. As far as portable options, C can't express relative references, but LLVM IR can.

If we don't want to ship a .ll file, or rely on llc or clang being part of the build toolchain, another kinda-gross option might be to just add code to IRGen that generates the necessary LLVM IR while building the standard library.

2020-10-29 18:12 UTC, Azoy commented
I was just about to mention moving this back to IRGen to solve lots of these issues. Is there any particular reason you consider that solution kinda-gross?

2020-10-29 18:15 UTC, jckarter commented
I guess it just seems kind of unfortunate for the compiler to have code in it that's only ever used to build the standard library to me.

2021-02-10 21:46 UTC, closed without merging