Make the compiler understand what StringRef is.
swiftlang/swift pull request #34622
Opened 2020-11-07 13:18 UTC by gevorgyana

This commit makes the header ready for stand-alone usage.

2020-11-09 17:19 UTC, harlanhaskins commented on include/swift/Syntax/TokenKinds.h
> +#incldue "llvm/ADT/StringRef.h"
Typo here:

```suggestion
#include "llvm/ADT/StringRef.h"
```

2020-11-09 23:32 UTC, CodaFi requested changes
Thanks for the change. We'll also need `#include "llvm/Support/raw_ostream.h"`

2020-11-13 15:26 UTC, gevorgyana commented
@swift-ci Please smoke test

2020-11-13 15:32 UTC, gevorgyana commented
@swift-ci please smoke test

2020-11-13 17:13 UTC, CodaFi commented
@gevorgyana CI privileges requires you have write permissions to this repo - for security purposes.

@swift-ci smoke test

2020-11-13 17:14 UTC, CodaFi approved these changes

2020-11-13 18:59 UTC, harlanhaskins approved these changes

2020-11-13 21:36 UTC, CodaFi commented
@swift-ci smoke test

2020-11-14 04:54 UTC, CodaFi commented
@swift-ci smoke test

2020-11-14 10:46 UTC, gevorgyana commented
Could you please point at what the problem may be with?

2020-11-14 23:01 UTC, CodaFi commented
@swift-ci clean test

2020-11-19 04:17 UTC, CodaFi commented
@swift-ci smoke test

2021-01-13 05:44 UTC, CodaFi commented
@swift-ci smoke test

2021-01-13 07:14 UTC, CodaFi commented
@swift-ci smoke test Linux

2021-01-14 02:09 UTC, CodaFi commented
@swift-ci clean smoke test Linux

2021-01-14 05:56 UTC, CodaFi commented
⛵

2021-01-14 05:56 UTC, merged