Add 'Fingerprint' Currency Type... And Serialize It!
swiftlang/swift pull request #34808
Opened 2020-11-18 19:18 UTC by CodaFi

* Add a new `Fingerprint` currency type that centralizes a bunch of hashing invariants and gives me some room to try to experiment with different hashing regimes.
* Push the `Fingerprint` type as a refinement of the `std::string`-ified interface we had there previously.

There's lots of plumbing here. The most fiddly bits are in the new serialization code. We'll be serializing fingerprints in a side table for swiftmodules. This ensures that fingerprints are preserved for cross-module dependencies so we can properly take advantage of type body fingerprints.

Finally, migrate the "fingerprints" in some hand-written tests. These tests were using fingerprints name 'after', 'before' and 'same', which are far too short to resemble a fingerprint value, which must be 32-bytes. Migrate these files so that

'after' -> 'afterachangewasmadetoswiftsource'
'before' -> 'beforechangewasmadetoswiftsource'
'same' -> 'sameasiteverwassameasiteverwassa'

There is otherwise no change to the contents of these files.

rdar://71343649

2020-11-18 19:19 UTC, CodaFi commented
@swift-ci test

2020-11-18 19:31 UTC, CodaFi commented
@swift-ci test source compatibility

2020-11-18 20:20 UTC, CodaFi commented
@swift-ci test

2020-11-18 20:21 UTC, CodaFi commented
@swift-ci test

2020-11-18 21:59 UTC, CodaFi commented
@swift-ci test

2020-11-18 22:43 UTC, CodaFi commented on lib/Driver/Driver.cpp
> +      versionValid = CompilationRecordSwiftVersion.equals(version::getSwiftFullVersion(version::Version::getCurrentLanguageVersion()));
N.B. This is a mistake. I will revert this after the tests pass.

2020-11-19 00:05 UTC, davidungar requested changes
This is great stuff, and I want to just approve it. But, from my reading of the comment for the `Fingerprint` type, you and I disagree on whether a fingerprint reflects identity. Since I believe that a fingerprint reflects state, and that it is useful to think of a declaration has having an identity independent of its state (e.g. adding a method to a struct does not change the struct's identity), I don't think that the comment as-is is accurate.

But, maybe I'm wrong, or there is a better framing I don't see. Perhaps it would help to talk offline?

2020-11-19 00:50 UTC, davidungar reviewed
Spoke offline, there will be a wording change to the one comment, and a change to the "000..." part.

2020-11-19 01:12 UTC, davidungar approved these changes
LGTM!

2020-11-19 01:13 UTC, CodaFi commented on include/swift/Basic/Fingerprint.h
> +/// A \c Fingerprint represents a stable point of identity for a piece of data
Spoke about this offline, we chose to use `stable summary of the contents...`

2020-11-19 01:13 UTC, CodaFi commented
@swift-ci test

2020-11-19 05:35 UTC, CodaFi commented
⛵

2020-11-19 05:35 UTC, merged