SILOptimizer: treat a `destroy_addr` as modification
swiftlang/swift pull request #35235
Opened 2020-12-28 18:57 UTC by compnerd

When performing the r-value elimination pass repeatedly, we may have
inserted a `destroy_addr` of the source value.  In such a case, it is
important to treat the `destroy_addr` as a modification (as you may not
use the value any longer).  This seems to match the behaviour observed
on macOS (and theoretically Windows).  Although this appears to extra
copy, it does not misuse memory.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

2020-12-28 18:57 UTC, compnerd commented
@swift-ci please benchmark

2020-12-28 18:58 UTC, compnerd commented
SR-13985, rdar://problem/72614608

2020-12-28 21:55 UTC, compnerd commented
CC: @gottesmm @eeckstein

2020-12-29 00:13 UTC, compnerd commented
@swift-ci please test

2020-12-29 06:09 UTC, atrick commented
This fix looks correct. To be clear, the problem was the assumptions that a `destroy_addr` modifies memory of the value being destroyed. It does not. However, the TempRValue code does need to check for either a modification of the source value or the end of the source value's lifetime.

2020-12-29 16:49 UTC, compnerd commented
@atrick my assumption was the latter part of the statement - that `destroy_addr` has marked the memory as being "invalid" (that is no guarantees can be made about the state of the memory).  Further use after the instruction is UB.  Based upon that, I made the assumption that it is okay to treat the `destroy_addr` as a load (which is what I feel like is the grey area - because its technically not a load).

However, thank you for verifying that this is a correct change!

2020-12-31 01:49 UTC, atrick approved these changes

2021-01-04 11:57 UTC, eeckstein reviewed
Hm, this doesn't make sense.
`destroy_addr` is modeled as a memory-write (see https://github.com/apple/swift/blob/949b0c0cc3632b0c278a33a4022dd280cf31215a/include/swift/SIL/SILInstruction.h#L379) and there shouldn't be a need for treating it specially.
`aa->mayWriteToMemory` should catch that it's a source modification.

2021-01-05 00:41 UTC, gottesmm commented
Also, I would like a SIL test case for this.

2021-01-05 02:58 UTC, compnerd commented
Yes, I do have a SIL test case that I will of course add.

2021-01-05 05:10 UTC, atrick requested changes
It looks like I approved this prematurely.

@eeckstein I thought someone recently fixed this `destroy_addr` behavior, which caused the problem. But that must have been `destroy_value`. I have no idea what this bug is.

This is pretty confusing because deinitialization can actually write to any escaping object *except* the one being deinitialized, unless we analyze the destructor. It's usually convenient to handle deinitialization like a write, but that's no excuse to be imprecise about it in the side-effect API.

I'm still not sure what the real intention of the `mayWrite` APIs are, but if we're going to make these kind of assumptions, that intention needs to be specified in the API. It's not good enough just look at how it's currently implemented. That doesn't tell you the API's intention, what assumptions clients may have been made, and how the implementation may change in the future:
https://github.com/apple/swift/pull/35261/files

2021-01-05 13:10 UTC, eeckstein commented
@atrick There is a good documentation of this at the line which I mentioned in my previous comment: https://github.com/apple/swift/blob/949b0c0cc3632b0c278a33a4022dd280cf31215a/include/swift/SIL/SILInstruction.h#L379

Though, it's probably a bit hidden. I added references to this comment in the comments of the API functions: https://github.com/apple/swift/pull/35262

2021-01-05 13:11 UTC, eeckstein commented
@compnerd This is an interesting bug. Even the SIL test case only reproduces on linux, but not on MacOS. I'll take a look.

2021-01-05 14:00 UTC, eeckstein commented
I found the problem. This is something completely different. I'll put up a PR with a fix.

2021-01-05 16:48 UTC, compnerd commented
Thanks @eeckstein!

2021-01-05 16:48 UTC, closed without merging