Fix a couple of crash-on-invalid situations with local variables defined inside result builders  [5.4]
swiftlang/swift pull request #35827
Opened 2021-02-08 18:39 UTC by slavapestov

5.4 cherry-pick of https://github.com/apple/swift/pull/35812.

2021-02-08 18:39 UTC, slavapestov commented
@swift-ci Please test

2021-02-08 18:55 UTC, Bo886 commented
n

2021-02-08 18:55 UTC, Bo886 approved these changes
n

2021-02-08 18:55 UTC, Bo886 approved these changes

2021-02-08 18:56 UTC, Bo886 approved these changes

2021-02-08 18:56 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -            return patternBinding->isExplicitlyInitialized(index);
-

2021-02-08 18:56 UTC, Bo886 approved these changes

2021-02-08 18:56 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -    // If any of the entries lacks an initializer, don't handle this node.
-

2021-02-08 18:57 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -    // If any of the entries lacks an initializer, don't handle this node.
-

2021-02-08 18:57 UTC, Bo886 approved these changes

2021-02-08 18:57 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -        unhandledNode = patternBinding;
-

2021-02-08 18:57 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -    if (!llvm::all_of(range(patternBinding->getNumPatternEntries()),
-

2021-02-08 18:57 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -    if (!llvm::all_of(range(patternBinding->getNumPatternEntries()),
-

2021-02-08 18:57 UTC, Bo886 commented on lib/Sema/BuilderTransform.cpp
> -    // If any of the entries lacks an initializer, don't handle this node.
-

2021-02-08 18:57 UTC, Bo886 approved these changes

2021-02-08 18:58 UTC, Bo886 approved these changes

2021-02-08 18:58 UTC, Bo886 approved these changes

2021-02-08 19:02 UTC, Bo886 requested changes
n

2021-02-08 19:05 UTC, Bo886 approved these changes

2021-02-09 04:03 UTC, slavapestov commented
@swift-ci Please test macOS

2021-02-09 22:21 UTC, tkremenek approved these changes

2021-02-09 23:19 UTC, merged