Skip adding alias targets when they don't exist
swiftlang/swift pull request #36782
Opened 2021-04-06 21:40 UTC by porglezomp

The CMake uses the concept of a "primary variant" which isn't necessarily aligned with either the host or target. In some cases, like cross-compiling an iOS compiler toolchain for `macosx-arm64`, the expected "primary variant" target will be missing and so CMake will fail. We can skip adding the alias since `build-script` will call the more specific target anyway.

2021-04-06 21:54 UTC, porglezomp commented
@swift-ci please smoke test

2021-04-06 22:32 UTC, edymtt requested changes

2021-04-06 22:32 UTC, edymtt commented on stdlib/CMakeLists.txt
> +  if(TARGET ${name}${SWIFT_PRIMARY_VARIANT_SUFFIX}${variant})
I believe a more readable check would be

```suggestion
  if(SWIFT_PRIMARY_VARIANT IN_LIST SWIFT_SDKS)
```

2021-04-06 22:32 UTC, edymtt commented on stdlib/CMakeLists.txt
> +    message(WARNING "Primary variant is not being built, target ${name}${SWIFT_PRIMARY_VARIANT_SUFFIX}${variant} does not exist, not creating ${name}${variant} alias target.")
If we decide to change the check, we could improve on this message as well, e.g.

```suggestion
    message(WARNING "Primary variant ${SWIFT_PRIMARY_VARIANT} is not being built, not creating ${name}${variant} alias target for it.")
```

2021-04-06 22:32 UTC, edymtt commented on stdlib/CMakeLists.txt
> +    message(WARNING "Primary variant is not being built, target ${name}${SWIFT_PRIMARY_VARIANT_SUFFIX}${variant} does not exist, not creating ${name}${variant} alias target.")
(Optional) would it be possible to add some tests for this scenario?

2021-04-06 23:02 UTC, edymtt approved these changes

2021-04-06 23:58 UTC, porglezomp commented
@swift-ci please smoke test

2021-04-06 23:59 UTC, porglezomp commented
I'm also rebuilding locally against a preset that I'm sure exercises cross-compilation

2021-04-07 00:32 UTC, porglezomp commented
@swift-ci please smoke test macOS Platform

2021-04-07 00:44 UTC, porglezomp commented
@swift-ci please smoke test macOS Platform

2021-04-07 15:05 UTC, edymtt commented on stdlib/CMakeLists.txt
> +  if(SWIFT_PRIMARY_VARIANT IN_LIST SWIFT_SDKS)
I fat fingered a variable name in my previous suggestion, this should be the correct one

```suggestion
  if(SWIFT_PRIMARY_VARIANT_SDK IN_LIST SWIFT_SDKS)
```

2021-04-07 15:11 UTC, edymtt requested changes

2021-04-07 15:11 UTC, edymtt commented on stdlib/CMakeLists.txt
> +    message(WARNING "Primary variant ${SWIFT_PRIMARY_VARIANT} is not being built, not creating ${name}${variant} alias target for it.")
```suggestion
    message(WARNING "Primary variant ${SWIFT_PRIMARY_VARIANT_SDK} is not being built, not creating ${name}${variant} alias target for it.")
```

2021-04-07 18:31 UTC, compnerd approved these changes
I believe that this should be safe.

2021-04-07 18:50 UTC, edymtt approved these changes

2021-04-08 06:51 UTC, porglezomp commented
Just squashing the two review fixup commits and improving their commit message.

2021-04-08 08:23 UTC, porglezomp commented
@swift-ci please smoke test and merge

2021-04-08 12:26 UTC, porglezomp commented
@swift-ci please smoke test and merge

2021-04-08 18:35 UTC, porglezomp commented
@swift-ci please smoke test macOS Platform and merge

2021-04-08 18:35 UTC, porglezomp commented
@swift-ci please smoke test macOS Platform

2021-04-08 20:08 UTC, porglezomp commented
@swift-ci please smoke test macOS Platform

2021-04-08 23:04 UTC, merged