Teach TypeLayout the Different Types of References
swiftlang/swift pull request #37116
Opened 2021-04-28 20:22 UTC by gmittert

As part of SR-14273, the type layout infrastructure needs to be able to be able
to differentiate between types of scalars so it knows how to release/retain
appropriately. Right now, for example, to destroy a scalar, it blindly calls
into typeInfo's irgen functions which means it's not able to generate any of
the needed information for itself.

This patch adds a field to ScalarTypeLayout to allow them to know what kind of
reference they are and strings through the machinery to provide the information
to set it.

This also moves ScalarTypeLayout::destroy to use the new information.

2021-05-14 15:40 UTC, aschwaighofer requested changes
This is great!

I am only worried about the one case mentioned inline (multi payload enum generation) that we would generate slightly worse code and I think we should address as mentioned inline.

---

While reviewing and playing with generated code I noticed an opportunity for improvement (independent of the code in this PR).


```
public class MyClass {}

public enum SinglepayloadEnum {
    case some(MyClass)
    case none
}

public func copySinglepayloadEnum(_ from: inout SinglepayloadEnum) {
    var to = from
}
```

If you look at the code we generate in the copy value witness for the enum at `-O` vs `-Onone`, surprisingly at `-Onone` the code is arguably be better (at least in terms of code size). That is because we use the TypeInfo based code generation at `-Onone` that has an optimization for this case vs the TypeLayout based generation at `-O` that misses it.

```
define internal %swift.opaque* @"$s1A17SinglepayloadEnumOwcp"(%swift.opaque* noalias %dest, %swift.opaque* noalias %src, %swift.type* %SinglepayloadEnum) #6 {
entry:
  %0 = bitcast %swift.opaque* %dest to %T1A17SinglepayloadEnumO*
  %1 = bitcast %swift.opaque* %src to %T1A17SinglepayloadEnumO*
  %2 = bitcast %T1A17SinglepayloadEnumO* %0 to %swift.refcounted**
  %3 = bitcast %T1A17SinglepayloadEnumO* %1 to %swift.refcounted**
  %4 = load %swift.refcounted*, %swift.refcounted** %3, align 8
  %5 = call %swift.refcounted* @swift_retain(%swift.refcounted* returned %4) #2
  store %swift.refcounted* %4, %swift.refcounted** %2, align 8
  %6 = bitcast %T1A17SinglepayloadEnumO* %0 to %swift.opaque*
  ret %swift.opaque* %6
}

vs (-O)
define internal %swift.opaque* @"$s1A17SinglepayloadEnumOwcp"(%swift.opaque* noalias returned %dest, %swift.opaque* noalias nocapture readonly %src, %swift.type* nocapture readnone %SinglepayloadEnum) #7 {
entry:
  %0 = bitcast %swift.opaque* %src to i64*
  %1 = load i64, i64* %0, align 8
  %2 = and i64 %1, -4294967295
  %3 = icmp ne i64 %2, 0
  %4 = and i64 %1, 8589934590
  %5 = icmp eq i64 %4, 8589934590
  %6 = or i1 %3, %5
  %7 = inttoptr i64 %1 to %T1A7MyClassC*
  br i1 %6, label %payloadBlock, label %noPayloadBlock

payloadBlock:                                     ; preds = %entry
  %8 = bitcast %swift.opaque* %dest to %T1A7MyClassC**
  %9 = getelementptr %T1A7MyClassC, %T1A7MyClassC* %7, i64 0, i32 0
  store %T1A7MyClassC* %7, %T1A7MyClassC** %8, align 8
  %10 = tail call %swift.refcounted* @swift_retain(%swift.refcounted* returned %9) #6
  br label %12

noPayloadBlock:                                   ; preds = %entry
  %11 = bitcast %swift.opaque* %dest to i64*
  store i64 %1, i64* %11, align 8
  br label %12

12:                                               ; preds = %payloadBlock, %noPayloadBlock
  ret %swift.opaque* %dest
}
```

The TypeInfo based generation has a special case that recognizes if you have a single payload enum with one non payload case and just uses a retain/release instead of switching on the payload and then releases. This is valid because the non payload case is going to be represented as `0` which retain/release can handle.

2021-05-14 15:41 UTC, aschwaighofer commented on lib/IRGen/GenEnum.cpp
> +        return IGM.typeLayoutCache.getOrCreateResilientEntry(T);
This adds the overhead of loading the value witness in code emission of e.g `copy_addr`. Something like:

```
  copy_addr %3 to [initialization] %2 : $*MultipayloadEnum  
```

Is going to call to the value witness functions (which requires loading the value witness table).


I think, instead we should introduce something like a `TypeInfoBasedTypeLayoutEntry` which is implemented like `ScalarTypeLayoutEntry` before this patch. We can use it until `ScalarTypeLayoutEntry` grows the full ability of TypeInfo based lowering (e.g handle spare bits computations).

2021-05-17 21:31 UTC, gmittert commented
Added a "TypeInfoBasedTypeLayout" for Layouts that don't have everything implemented yet and moved the CXXStructs and multi enums to use it.

Since we have the information in scalar layouts now, I added a case in the enum destroy to just release the payload if it's a nullable refcounted pointer.

2021-05-17 21:32 UTC, gmittert commented
@swift-ci please test

2021-05-20 18:16 UTC, gmittert commented
@swift-ci please smoke test

2021-06-09 16:47 UTC, gmittert commented
Moving GenStruct to produce Aligned Type layouts inflates code size a ton because it computes an alignment for each field using and/add instead of doing a single gep. Going to split that out into a different PR and try to tackle that there.

2021-09-29 22:25 UTC, gmittert commented
@swift-ci please test

2021-09-29 22:25 UTC, gmittert commented
@swift-ci please smoke test

2021-10-04 17:02 UTC, aschwaighofer commented
@swift-ci Please benchmark

2021-10-05 18:41 UTC, aschwaighofer commented
@swift-ci Please benchmark

2021-10-05 20:12 UTC, aschwaighofer approved these changes
Lgtm

2021-10-05 20:12 UTC, aschwaighofer commented
@swift-ci Please smoke test

2021-10-06 00:20 UTC, gmittert commented
preset=buildbot,tools=RA,stdlib=RD,test=non_executable
@swift-ci Please test with preset macOS

2021-10-06 21:00 UTC, merged