Fix for a crash due to performLocalReleaseMotion
swiftlang/swift pull request #38150
Opened 2021-06-29 07:07 UTC by meg-gupta

In low level LLVMARCOptimizer, during canonicalization we don't rauw the result of RT_Retain with its arg similarly to RT_ObjCRetain and RT_BridgeRetain.
And during performLocalReleaseMotion, we assert that we have canonicalized RT_Retain.
In a release compiler, if we optimize such an RT_Retain with a RT_Release, then this can result in a compiler crash

Fixes rdar://79238115

2021-06-29 07:08 UTC, meg-gupta commented
@swift-ci test

2021-06-29 17:25 UTC, meg-gupta commented
@swift-ci test

2021-06-29 20:33 UTC, atrick requested changes
Can you explain why we don't need RAUW for the `RT_UnknownObjectRetain` case?

2021-06-29 20:33 UTC, atrick commented on lib/LLVMPasses/LLVMARCOpts.cpp
> +        // Use the arg directly instead of the RC identity `ArgVal` here
The comment used below is more explanatory
```
        // Do not get RC identical value here, could end up with a
        // crash in replaceAllUsesWith as the type maybe different.
```

2021-06-29 21:28 UTC, meg-gupta commented
@atrick The same issue can also happen with RT_UnknownObjectRetain. Fixed it. Thanks

2021-06-29 21:29 UTC, meg-gupta commented
@swift-ci test

2021-06-29 23:21 UTC, meg-gupta commented
@swift-ci test Linux Platform

2021-06-30 01:01 UTC, atrick approved these changes
Excellent. Thanks!

2021-06-30 02:13 UTC, meg-gupta commented
Trying again... @swift-ci test Linux Platform

2021-06-30 07:03 UTC, meg-gupta commented
@swift-ci test Linux Platform

2021-06-30 17:39 UTC, meg-gupta commented
Another flaky error. Trying again... @swift-ci smoke test Linux Platform

2021-06-30 18:47 UTC, meg-gupta commented
@swift-ci clean smoke test Linux Platform

2021-06-30 22:40 UTC, merged