Fix use-after-free in DestroyHoisting
swiftlang/swift pull request #38965
Opened 2021-08-19 21:48 UTC by meg-gupta

Due to mismatch in the instructions handled in DestroyHoisting::getUsedLocationsOfInst
and MemoryLocations::analyzeLocationUsesRecursively, certain users of addresses
were not considered and the destroys were hoisted before valid uses causing use-after-frees.

2021-08-19 21:48 UTC, meg-gupta commented
@swift-ci test

2021-08-19 21:49 UTC, meg-gupta commented
@swift-ci benchmark

2021-08-19 22:05 UTC, meg-gupta commented
@swift-ci test

2021-08-19 22:05 UTC, meg-gupta commented
@swift-ci benchmark

2021-08-19 22:07 UTC, meg-gupta commented
I found a real bug due to unhandled cases with `switch_enum_addr`. Other instructions I handle in this PR like `witness_method` etc are dead and will be cleaned up by DCE later on. But the fix is needed to have a valid SIL after this pass, unless we decide to clean up such instructions in this pass.

2021-08-20 08:00 UTC, eeckstein requested changes
Thanks for fixing this.

Basically LGTM, I just have one change request.

2021-08-20 17:51 UTC, meg-gupta commented on lib/SILOptimizer/Transforms/DestroyHoisting.cpp
> +    case SILInstructionKind::StructElementAddrInst:
Thanks, that makes sense

2021-08-20 17:52 UTC, meg-gupta commented
@swift-ci test

2021-08-20 21:48 UTC, meg-gupta commented
@swift-ci test

2021-08-23 06:33 UTC, eeckstein approved these changes
thanks, LGTM!

2021-08-26 01:29 UTC, merged