ClangImporter: teach clang importer to import Clang SPI symbols and model them similarly as Swift SPIs
swiftlang/swift pull request #39068
Opened 2021-08-27 00:02 UTC by nkcsgexi

For clang symbols marked with SPI_AVAILABLE, we add SPIAccessControlAttr to them so they will be considered as SPIs in the AST. To be able to use all these symbols, we also add an implicit SPI import statement for all clang modules. All clang SPIs belong to the same SPI group named `<objc>` because clang currently doesn't support custom SPI group.

rdar://73902734

2021-08-27 19:54 UTC, xymus approved these changes
This looks good!

Should we wait for library-level inference in the build system to land before we integrate this? I'm worried that as such it will raise false positive on SPI use in private frameworks.

2021-08-27 20:37 UTC, adrian-prantl requested changes
As discussed offline, the change in debug info behavior is a regression.

2021-08-28 00:56 UTC, adrian-prantl approved these changes
Looks like you were able fix the missing ImportDecls, thanks!

2021-08-28 02:41 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 02:53 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 05:01 UTC, nkcsgexi commented on test/ClangImporter/availability_spi_as_unavailable.swift
> +public let d: SPIInterface2 // expected-error{{cannot use class 'SPIInterface2' here; it is an SPI imported from 'SPIContainer'}}
That's a great idea. Added.

2021-08-28 05:01 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 15:57 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 16:16 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 18:12 UTC, nkcsgexi commented
@swift-ci please smoke test

2021-08-28 21:20 UTC, nkcsgexi commented
@xymus @adrian-prantl Thanks for taking a look! All tests passed. Merging.

2021-08-28 21:20 UTC, merged