Make it clear that arr[n] panics rather than throws
swiftlang/swift pull request #39185
Opened 2021-09-06 07:12 UTC by vandadnp

I've always thought that the documentation for subscripts of arr where an index is received should mention that the code panics if the index is out of bounds.

This PR is inspired by the Rust documentation on `Vec` where in the [indexing section](https://doc.rust-lang.org/std/vec/struct.Vec.html#indexing) it is clearly stated that the code panics if index is out of bounds.

I am not a native English speaker so the wording here could need some polishing!

Does not resolve a bug, purely a documentation update.

2021-09-07 14:24 UTC, xwu commented
Many standard library functions will trap when preconditions are violated; it wouldn't be tenable to put this description into each summary sentence. However, where the parameter `index` is documented with a "must," it may be reasonable to point out the consequences of violating that "must."

/cc @natecook1000

2021-09-07 15:02 UTC, vandadnp commented
@xwu thank you or your reply

In my opinion anything affecting the public interface of an API has to be clearly documented. A trap, which is pretty much unhandlable by a programmer should for sure be mentioned somewhere so that users of the public interface of this API are aware of using it with invalid indices. But again, that's just my opinion ✌🏻

2021-09-08 11:19 UTC, vandadnp commented
@swift-ci please test

2021-11-08 21:48 UTC, amartini51 commented
I agree that it's valuable to call out the behavior if the index is out of bounds.  However, let's not add that information to the abstract — the abstract describes the expected behavior, and the discussion section talks about things like when a method throws an error.  Likewise, let's avoid the word "panic", which isn't used elsewhere in the stdlib to describe throwing a fatal error at run time.

How about adding this to the discussion section instead:  "Accessing an index that's out of range is a fatal error."

2021-11-17 21:01 UTC, amartini51 requested changes
Let's revise based on the comments I wrote previously.

(Added myself as a reviewer so I can mark this as needing changes before being merged.)

2021-11-18 06:00 UTC, vandadnp commented
@amartini51 hi and thank you for your valuable time.

To re-iterate, a public API crashing an application, which this does, is so important to document that it should be almost the first line of documentation for Array subscript function. I've personally never read the documentation for Array.Index and can say that many other fellow Swift developers never have and never will.

Putting this critical information in Array.Index documentation is certainly not ideal. I wouldn't be happy with that contribution personally so it's perhaps best for me to close this PR and let the Swift team take care of that.

Thank you again for your time.

2022-04-21 07:37 UTC, closed without merging