[Benchmarks][stdlib] Adding an extra benchmark for set isDisjoint for disjoint sets of different size
swiftlang/swift pull request #39265
Opened 2021-09-12 00:19 UTC by LucianoPAlmeida

As for the improvement on #39263 we can really see much improvement because sets are same size.
So this adds a new smaller disjoint set and a benchmark for 0 overlap (disjoint) using those sets. And also make the benchmark run to run `a.isDisjoint(b)` and `b.isDisjoint(a)` to give a better overview of benchmarks with different size sets.

2021-09-12 00:20 UTC, LucianoPAlmeida commented
@swift-ci Please benchmark

2021-09-13 00:03 UTC, lorentey reviewed
Looks good! 

One of these days we'll need to take a long, hard look at how an innocent addition like this can trigger such large swings in unchanged code paths within the same module.

2021-09-13 00:07 UTC, lorentey requested changes
We'll need to leave the existing benchmarks as is -- changing them would interfere with performance tracking.

(The new code is great for the new benchmarks, though!)

2021-09-13 00:55 UTC, LucianoPAlmeida commented
> Argh, my bad, I missed that this changes those paths. (Reviewing PRs on my phone is not a good idea. 🙈)

No worries, Thanks for the review!

2021-09-13 01:00 UTC, LucianoPAlmeida commented
> We'll need to leave the existing benchmarks as is -- changing them would interfere with performance tracking.
> 
> (The new code is great for the new benchmarks, though!)

Just fixed!
Created new benchmark function to run disjoint sets of different sizes, so let me know if this is good :)

2021-09-13 01:19 UTC, LucianoPAlmeida commented
@swift-ci Please benchmark

2021-09-13 14:09 UTC, LucianoPAlmeida commented
@swift-ci Please smoke test

2021-09-14 16:00 UTC, LucianoPAlmeida commented
@lorentey, friendly ping :)
To know if there is any other change or it is good to land?

2021-09-14 19:40 UTC, lorentey commented
> Just for curiosity, in this on the how to read: `Unexpected regressions which are marked with '(?)' are probably noise.` what it is exactly this `noise` and generally what causes such results? 

It's a heuristic that puts the mark on (almost) all results that are overlapping with the old run. Here is the logic behind it:

```python
        # Indication of dubious changes: when result's MIN falls inside the
        # (MIN, MAX) interval of result they are being compared with.
        self.is_dubious = (old.min < new.min and new.min < old.max) or (
            new.min < old.min and old.min < new.max
        )
```

I believe this will tend to shame benchmarks that have a high variability. (I'm not nearly good enough with statistics to tell if it's a good one, but it seems to be working relatively well!)

2021-09-14 19:45 UTC, lorentey approved these changes
Looks good, thank you for working on this.

> **Regression**                        | **OLD** | **NEW** | **DELTA** | **RATIO**
> :---                                  | ---: | ---: | ---:   | ---:     
> Set.isDisjoint.Box25                  | 355  | 515  | +45.1% | **0.69x (?)**
> Set.isDisjoint.Int25                  | 262  | 344  | +31.3% | **0.76x (?)**

I wonder if the nondeterministic hashing config was lost from the benchmarking environment. This could also be an instruction cache artifact from the functions getting slightly bumped in the emitted binary. Well, it's an investigation for another day. :-/

2021-09-14 19:45 UTC, merged

2021-09-14 20:26 UTC, LucianoPAlmeida commented
> It's a heuristic that puts the mark on (almost) all results that are overlapping with the old run. Here is the logic behind it:

Ah interesting, thank you for the explanation!

> I believe this will tend to shame benchmarks that have a high variability. (I'm not nearly good enough with statistics to tell if it's a good one, but it seems to be working relatively well!)

Variability would be across multiple runs with same input values? I guess that given that most of the methods being benchmarked are deterministic, variability across multiple runs may come from hardware state e.g. variability of CPU cache hits and misses in different runs... 
Sorry for to many questions and pings, I guess benchmarking at some is very complicated because is to many variables :)

2021-09-15 04:02 UTC, lorentey commented
> Variability would be across multiple runs with same input values?

Yep -- the benchmarks are measured over multiple iterations, scaled so that each measurement take some fixed amount of time/ I believe this is set to discourage/prevent context switches in the middle of a benchmark, but measuring over multiple iterations also reduces some of the noise by averaging it out.

Then iirc these measurements are repeated multiple time to collect a nice sample. The min/max/avg/stddev values reported come from these samples.

(Beware I'm sure I got at least some of these details wrong -- the truth is in the code. 😅 )

2021-09-15 11:00 UTC, LucianoPAlmeida commented
Interesting to know, Thanks :)