Ensure that we only depend on a small expected set of external symbols in the freestanding stdlib
swiftlang/swift pull request #39401
Opened 2021-09-22 21:07 UTC by kubamracek

2021-09-23 00:16 UTC, compnerd requested changes
I like the idea here, but I think that this is better implemented as a python script.  That should also allow for this to extend into other OSes.  There are definitely cases of symbols which are Darwin specific here.  We do have some tests that run python scripts - that would also make the test a bit less reliant on the host tools.

2021-09-23 01:00 UTC, kubamracek commented
👍 All sounds good, will tweak the PR.

Yes, the current list is for Darwin. I actually have a "plan" to keep shrinking this list down so that all Darwin APIs are completely gone (with the exception of one dyld API to enumerate loaded modules, see the discussion we had in the other PR).

2021-09-24 22:37 UTC, kubamracek commented
@swift-ci please test

2021-09-25 03:48 UTC, kubamracek commented
@swift-ci please test

2021-09-25 15:21 UTC, kubamracek commented
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

2021-09-29 19:22 UTC, compnerd approved these changes

2021-09-29 19:22 UTC, compnerd commented on utils/check_freestanding_dependencies.py
> +    lines = subprocess.check_output(["nm", "--undefined-only", args.library]) \
Would be nice to have this be a parameter so we can pass it `%llvm-nm`.

2021-09-29 19:26 UTC, kubamracek commented on utils/check_freestanding_dependencies.py
> +        fail = True
Note to self, this shouldn't set fail = True. It should be just a warning.

2021-09-30 02:55 UTC, kubamracek commented
@swift-ci please test

2021-09-30 02:55 UTC, kubamracek commented
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

2021-09-30 15:26 UTC, gottesmm commented
I am for this and think it is reasonable/important to make sure mistakes to sneak in. The only question I have is if this is a BuildSystem unit test or a stdlib unit test. I am fine in either place though.

2021-09-30 15:31 UTC, kubamracek commented
Ah, forgot to explain: The reason I put it into test/stdlib/ is to make it actually run in the "minimal" buildbot we have on ci.swift.org. Because that bot only builds the runtime+stdlib and not the compiler, it only runs tests from a subset of lit tests.

If you're okay with that, then I'd like to keep the test in test/stdlib/, and perhaps figure our if there other sub-folders of tests that we should be running later.

2021-09-30 16:03 UTC, gottesmm commented
@kubamracek SGTM. Can you put in a big comment explaining that? I just don't want someone to move it by mistake.

2021-10-01 14:15 UTC, kubamracek commented
@swift-ci please test

2021-10-01 14:16 UTC, kubamracek commented
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

2021-10-01 14:54 UTC, kubamracek commented
@swift-ci please test

2021-10-01 14:55 UTC, kubamracek commented
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

2021-10-01 16:14 UTC, kubamracek commented
@swift-ci please test Windows platform

2021-10-01 21:59 UTC, kubamracek commented
@swift-ci please test Windows platform

2021-10-01 21:59 UTC, kubamracek commented
preset=stdlib_S_standalone_minimal_macho_x86_64,build,test
@swift-ci please test with toolchain and preset

2021-10-01 23:43 UTC, merged