runtime, WebAssembly: add ImageInspectionWasm.cpp
swiftlang/swift pull request #39483
Opened 2021-09-28 13:44 UTC by MaxDesiatov

This change adds a stub for `swift::lookupSymbol` for the WebAssembly platform.

Related to SR-9307.

2021-09-28 13:45 UTC, MaxDesiatov commented
@swift-ci please smoke test

2021-09-28 13:46 UTC, MaxDesiatov commented
CC @kateinoigakukun

2021-09-28 15:19 UTC, MaxDesiatov commented
@swift-ci please smoke test

2021-09-28 18:24 UTC, compnerd reviewed
Is there something that prevents symbol lookup on WASM?  Why a stub rather than an implementation?

2021-09-29 04:31 UTC, kateinoigakukun commented
@compnerd Currently, Wasm doesn't have a standard stable ABI for exporting `address <-> symbol`  table for now.
It's currently working in progress. And also, there is no API to access such information from Wasm binary side. https://github.com/WebAssembly/tool-conventions/blob/main/DynamicLinking.md
So it's reasonable for me to use a stub for now.

2021-09-29 15:27 UTC, compnerd requested changes
Please add the context that @kateinoigakukun mentioned into the file as a comment.

2021-10-08 04:04 UTC, kateinoigakukun approved these changes
There is no change request from my side.

2021-10-12 00:54 UTC, compnerd approved these changes
It's not really using a stub - its adding a placeholder for an implementation.  This means that any `fatalError` is going to be useless under any configuration or build.

2021-10-12 13:04 UTC, merged