[cxx-interop] Implement foreign reference types.
swiftlang/swift pull request #39605
Opened 2021-10-06 01:18 UTC by zoecarver

This is an experimental feature to allow an attribute, `import_as_ref`, to import a C++ record as a non-reference-counted reference type in Swift.

2021-10-06 20:22 UTC, rjmccall requested changes

2021-10-06 20:22 UTC, rjmccall commented on lib/ClangImporter/ImportDecl.cpp
> +          if (selfIsInOut && !isa<ClassDecl>(dc)) {
Maybe `selfIsInOut` should just be false when we import as a reference type.

2021-10-06 20:22 UTC, rjmccall commented on lib/IRGen/GenCall.cpp
> +
We shouldn't see this.

2021-10-13 17:42 UTC, zoecarver commented
@rjmccall this should be ready for re-review now. I think I addressed all your comments. Let me know what you think.

Note: I still need to fix the issue with optionals (unless some macro tells us otherwise, we should be importing foreign reference types as optionals). I'll do that shortly, but I think the rest of the PR can still be reviewed without that change.

2021-10-15 20:51 UTC, zoecarver commented on lib/SIL/Verifier/SILVerifier.cpp
> +        operandType.getClassOrBoundGenericClass()->getClangDecl() &&
But thanks for catching that!

2021-10-22 00:13 UTC, zoecarver commented
@swift-ci please smoke test.

2021-11-20 00:17 UTC, zoecarver commented on include/swift/AST/Decl.h
> +      const_cast<ClassDecl *>(this)->isForeignReferenceType();
This is not ideal, but I think it's OK because we never construct a const decl, right?

2021-11-20 00:48 UTC, zoecarver commented
@swift-ci please smoke test.

2021-11-29 20:58 UTC, zoecarver commented
@swift-ci please smoke test.

2021-11-29 21:11 UTC, zoecarver commented
@rjmccall friendly ping :)

2021-12-04 01:23 UTC, zoecarver commented on include/swift/AST/DiagnosticsIRGen.def
> +ERROR(foreign_reference_types_unsupported,none,
@rjmccall and @beccadax I need to add a test for this new error, but other than that, this should be ready for re-review.

2021-12-05 19:02 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-05 19:18 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-05 19:18 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-06 08:21 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-06 16:32 UTC, zoecarver commented
@swift-ci please smoke test Linux.

2021-12-06 22:26 UTC, zoecarver commented
@swift-ci please smoke test Linux.

2021-12-06 22:28 UTC, zoecarver commented
@swift-ci please smoke test Linux.

2021-12-08 10:18 UTC, zoecarver commented
@swift-ci please smoke test Linux.

2021-12-08 12:01 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-08 15:35 UTC, zoecarver commented
@swift-ci please smoke test.

2021-12-08 18:26 UTC, hyp commented on lib/AST/Type.cpp
> +  if (auto *classDecl = getPointer()->lookThroughAllOptionalTypes()->getClassOrBoundGenericClass())
Looks like you duplicate the logic here. Can you call `getPointer()->isForeignReferenceType()` instead?

2021-12-08 19:26 UTC, zoecarver commented on test/Interop/Cxx/foreign-reference/not-any-object.swift
> +test(Empty.create()) // expected-error {{type of expression is ambiguous without more context}}
Add a test for casting explicitly to any object.

2021-12-08 19:33 UTC, hyp approved these changes

2021-12-08 19:33 UTC, merged