Don't include support for old mangling in runtimes without ObjC interop
swiftlang/swift pull request #39675
Opened 2021-10-10 15:26 UTC by kubamracek

This saves a surprising amount of codesize in the runtime (~25 kB on x86_64).

2021-10-10 17:40 UTC, compnerd approved these changes
I could see an argument for this being something that you could control rather than associating this with the stable ABI.  Id like to see Windows aim for a stable ABI at some point, and wouldn't want to include the old decoration schemes since it pre-dated the cut point.  I don't think that adding in the option needs to hold up this change though.

2021-10-11 14:47 UTC, mikeash approved these changes
Can we make this conditional on ObjC interop rather than the stable ABI? ObjC is why we keep the old mangling around, so that would probably make more sense. I'm fine with adjusting that later if you prefer, though.

2021-10-13 00:06 UTC, compnerd commented
Well, the interesting thing is that ObjC interop is not a build time constant - it is a runtime value (`-enable-objc-interop` or `-disable-objc-interop`).

2021-10-13 00:09 UTC, compnerd requested changes

2021-10-13 00:09 UTC, compnerd commented on lib/Demangling/CMakeLists.txt
> +  SUPPORT_OLD_MANGLING=1)
Can you please rename this to `SWIFT_SUPPORT_OLD_MANGLING`?

2021-10-13 00:09 UTC, compnerd commented on stdlib/CMakeLists.txt
> +# Only Darwin platforms have ObjC interop.
Can you change this please?
```suggestion
# Only Darwin platforms enable ObjC interop by default.
```

2021-10-13 00:09 UTC, compnerd commented on stdlib/CMakeLists.txt
> +       "${SWIFT_STDLIB_OBJC_INTEROP_default}")
Oh, this is a good idea!  I didn't even think of this.  What do you think of `SWIFT_STDLIB_ENABLE_OBJC_INTEROP` instead?

2021-10-13 04:43 UTC, kubamracek commented
@swift-ci please test Windows platform

2021-10-13 18:01 UTC, compnerd commented
@mikeash yes, and I think that this change moves to actually clean that up.  The sinking of the option to the stdlib makes this better.  The demangler is in lib/ rather than stdlib/ which is what I think is making me uncomfortable.

2021-10-13 18:02 UTC, compnerd approved these changes

2021-10-13 18:39 UTC, mikeash approved these changes

2021-10-14 02:47 UTC, merged