[Concurrency] set queue width on all non-apple platforms, not just linux
swiftlang/swift pull request #39765
Opened 2021-10-15 02:00 UTC by ktoso

**Description:** We recently made setting the queue width also happen on linux; but rather, it should be for "non apple platforms". 
**Risk:** Low
**Review by:** @DougGregor @rjmccall 
**Testing:** Ci testing
**Original PR:** https://github.com/apple/swift/pull/39764 and the previous one https://github.com/apple/swift/pull/39742
**Radar:** rdar://79907041

2021-10-15 02:01 UTC, ktoso commented
@swift-ci please test

2021-10-16 16:19 UTC, compnerd requested changes, later dismissed

2021-10-16 16:19 UTC, compnerd commented on stdlib/public/Concurrency/GlobalExecutor.cpp
> +#if defined(SWIFT_CONCURRENCY_BACK_DEPLOYMENT) || !defined(__apple__)
```suggestion
#if defined(SWIFT_CONCURRENCY_BACK_DEPLOYMENT) || !defined(__APPLE__)
```

2021-10-16 16:19 UTC, compnerd commented on stdlib/public/Concurrency/GlobalExecutor.cpp
> +#if defined(SWIFT_CONCURRENCY_BACK_DEPLOYMENT) || !defined(__apple__)
```suggestion
#if defined(SWIFT_CONCURRENCY_BACK_DEPLOYMENT) || !defined(__APPLE__)
```

2021-10-19 21:51 UTC, DougGregor approved these changes

2021-10-19 21:52 UTC, merged