Add Builtin.ifdef_<FLAGNAME> as a facility to peek at -D flag that client code is building with
swiftlang/swift pull request #39797
Opened 2021-10-17 16:12 UTC by kubamracek

2021-10-17 16:12 UTC, kubamracek commented
@swift-ci please test

2021-10-19 06:58 UTC, eeckstein requested changes
nice!
Just a few comments.
And: please add a test.

2021-10-19 06:58 UTC, eeckstein commented on lib/IRGen/GenBuiltin.cpp
> +    llvm_unreachable("Ifdef not constant folded");
nitpick: I'd prefer a error message describing the root cause: "Builtin.ifdef can only be used in @_alwaysEmitIntoClient functions"

2021-10-19 06:58 UTC, eeckstein commented on lib/SILOptimizer/Utils/ConstantFolding.cpp
> +        if (!inst->getModule().isStdlibModule()) {
This should depend on `FrontendOptions::ParseStdlib` and not on the module name.
Either you'll add `ParseStdlib` to SILOptions or just use `SILOptions::DisableReplacement` (which is used for the assert configuration).

2021-10-19 06:58 UTC, eeckstein commented on lib/SILOptimizer/Utils/ConstantFolding.cpp
> +        if (constantFoldIfdef(cast<BuiltinInst>(I), val)) {
`constantFoldIfdef` never returns an invalid SILValue

2021-10-19 06:58 UTC, eeckstein commented on lib/SILOptimizer/Utils/ConstantFolding.cpp
> +static SILValue constantFoldIfdef(BuiltinInst *BI, bool value) {
nitpick: maybe call this function `replaceWithIntOne`? Or just inline it

2021-10-19 06:58 UTC, eeckstein commented on stdlib/public/core/Builtin.swift
> +private func _ifdefFooBar() -> Bool {
Please don't add this function to the stdlib. You can create a test it by compiling a file with `-parse-stdlib` and explicitly `import Swift`.

2021-10-19 23:50 UTC, kubamracek commented
@eeckstein comments should be addressed now!

2021-10-20 14:29 UTC, kubamracek commented
@swift-ci please test

2021-10-20 14:59 UTC, eeckstein approved these changes
lgtm!

2021-10-21 22:36 UTC, merged