Avoid including unistd.h and replace write(STDERR) with fputs(stderr)
swiftlang/swift pull request #40177
Opened 2021-11-13 23:42 UTC by kubamracek

2021-11-13 23:42 UTC, kubamracek commented
@swift-ci please test

2021-11-14 02:03 UTC, kubamracek commented
@swift-ci please test Windows platform

2021-11-14 20:08 UTC, compnerd requested changes
The removal of unistd is fine, but this is subtly different.  `write` is just a wrapper over the syscall, `fputs` may buffer.  This needs a `fflush` at least.

2021-11-14 23:06 UTC, kubamracek commented
@swift-ci please test

2021-11-14 23:06 UTC, kubamracek commented
Added fflush calls.

2021-11-15 05:48 UTC, compnerd approved these changes

2021-11-15 14:46 UTC, mikeash approved these changes

2021-11-15 18:28 UTC, kubamracek commented
@swift-ci please test

2021-11-15 19:44 UTC, kubamracek commented
@swift-ci please test Linux platform

2021-11-15 19:45 UTC, kubamracek commented
@swift-ci please test Windows platform

2021-11-16 02:41 UTC, merged

2021-11-17 15:55 UTC, al45tair commented on stdlib/public/runtime/Errors.cpp
> +  fflush(stderr);
FWIW, `stderr` is normally unbuffered by default, so the `fflush()` is probably not necessary. It won't hurt though.