Remove spurious rethrows from Async[Throwing]PrefixWhileSequence
swiftlang/swift pull request #40246
Opened 2021-11-18 22:58 UTC by GeorgeLyon

The `rethrows` marker is unnecessary in these two locations.

Resolves [SR-15494.](https://bugs.swift.org/browse/SR-15494)

2021-12-07 06:40 UTC, DougGregor commented
@swift-ci please smoke test

2021-12-10 19:59 UTC, DougGregor requested changes
The failure that's showing up here is because removing `rethrows` is an ABI change, which that test (`api-digester/stability-concurrency-abi.test`) verifies. This PR will need to do something akin to https://github.com/apple/swift/pull/39707 to make the change (which is a good one!) without breaking the existing ABI.

2021-12-10 20:16 UTC, GeorgeLyon commented
If I'm understanding correctly, the solution is to have the new, non-throwing function have the same symbol name as the old, rethrowing function. I'm not sure what the best way to get this name is, any hints?

2022-02-18 01:42 UTC, phausler commented
oof that is definitely a mistake that slipped past. Can we perhaps use an overload here and then mark the existing one as deprecated and disfavored overload?

2023-03-23 00:31 UTC, closed without merging