libswift: replace use of `std::string` with `char *`
swiftlang/swift pull request #40299
Opened 2021-11-26 17:14 UTC by compnerd

This replaces the use of C++ interop with C bindings for the string
bridging.  This change ensures that the interop can be used on all
platforms, including those where the ABI concerns with C++ have not yet
been addressed.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

2021-11-26 17:14 UTC, compnerd commented
CC: @eeckstein @zoecarver

2021-11-26 17:14 UTC, compnerd commented
@swift-ci please test

2021-11-26 18:49 UTC, eeckstein commented
Why not just revert f063701f8465905084eaa2ce3c6156b19e8595d7

2021-11-26 19:06 UTC, zoecarver requested changes
Please do not merge this PR before we have a proper discussion about whether this is the right path to resolve the issues you're discussing. 

What specific ABI issues are you seeing with `std::string` on Windows? For both ctors (which are not used in libSwift) and copy-ctors, we ask clang for the function signature/ABI to ensure that we match that and emit a thunk where needed. 

----
If we're going to do this, I agree with Erik, let's use what was there before, it's much better (matches the other string bridging and is platform agnostic).

2021-12-15 19:28 UTC, compnerd commented
Okay, but we need to get this sorted out for now.  Lets revert the other change for now.

2021-12-17 13:06 UTC, eeckstein commented
I have a PR for the revert (which is also need for unblocking CMO work): https://github.com/apple/swift/pull/40607

2021-12-17 13:39 UTC, zoecarver commented
> Okay, but we need to get this sorted out for now. Lets revert the other change for now.

Sorry, I somehow missed this comment. @compnerd can you please explain the issue you're running into. I'd really like to avoid reverting this change.

2021-12-21 14:51 UTC, closed without merging