Unclear word
swiftlang/swift pull request #40874
Opened 2022-01-16 16:58 UTC by philipturner

I don't understand why it says "currency", which means money. There might be some Swift data type for money, but I haven't heard of it yet. Also, the explanation misses that the entire document just covers built-in Swift types. Did you mean "concurrency"?

2022-01-16 21:16 UTC, CodaFi requested changes
There is a difference here!

The compiler understands `Builtin` types like `Builtin.NativeObject`, and it understands much higher-level common user types like `String`. The types in the standard library are not considered builtins - they're built atop builtins more often than not. The document linked here describes optimization opportunities exposed by annotations and structures attached these higher-level types and associated operations.

"Currency" (often also "vocabulary") types are types that one reaches for in most common usages of the language. Do you want to manipulate a string - pick String, not `UnsafeMutableBufferPointer<CChar>`. Do you want a pack of unique elements - pick `Set<T>`!

2022-01-16 23:13 UTC, philipturner commented
Then could the documentation clarify what "currency" means? I didn't see it in `Lexicon.md`, and from the point of view of someone who doesn't know what it means, it looks like a misspelling of "Concurrency".

2022-01-17 08:35 UTC, WowbaggersLiquidLunch commented
also relevant answer on the forums: https://forums.swift.org/t/what-does-currency-type-mean/41065/2

2022-01-17 11:18 UTC, philipturner commented
The definition for currency still needs to be refined, could anyone help me here?

2022-01-17 17:41 UTC, CodaFi commented on docs/Lexicon.md
> +## currency
```suggestion
## currency type
```

2022-01-17 17:41 UTC, CodaFi commented on docs/Lexicon.md
> +Aa type that's meant to be commonly passed around and stored, like `Array`, as opposed to a type that's useful for temporary/internal purposes but which you wouldn't normally use in an external inter
Nit: Could you reflow this text to 80(-ish) columns?

2022-01-17 17:45 UTC, CodaFi commented on docs/README.md
> +    operations on [currency](/docs/Lexicon.md#currency) data types and optimizes accordingly.
This link needs to be updated as well.

2022-01-17 17:45 UTC, philipturner commented on docs/README.md
> +    operations on [currency](/docs/Lexicon.md#currency) data types and optimizes accordingly.
```suggestion
    operations on [currency](/docs/Lexicon.md#currency-types) data types and optimizes accordingly.
```

2022-01-17 17:48 UTC, CodaFi approved these changes
Thanks

⛵

2022-01-17 17:48 UTC, CodaFi commented
Note to self: manually squash this

@swift-ci smoke test

2022-01-18 05:08 UTC, xwu commented on docs/README.md
> +    operations on [currency](/docs/Lexicon.md#currency-types) data types and optimizes accordingly.
Link's not quite correct.

```suggestion
    operations on [currency](/docs/Lexicon.md#currency-type) data types and 
    optimizes accordingly.
```

2022-01-18 11:33 UTC, philipturner commented
@CodaFi you may need to retest this because of a one-character change.

2022-01-18 14:08 UTC, xwu commented
@swift-ci smoke test

2022-01-18 18:37 UTC, merged