[cxx-interop] Add a basic test for using stdlib iterator_traits
swiftlang/swift pull request #41290
Opened 2022-02-09 02:42 UTC by cabmeurer

Add a basic test for using `std::iterator_traits`

Ref: #41166

2022-02-09 02:42 UTC, cabmeurer commented on test/Interop/Cxx/stdlib/Inputs/std-iterator_traits.h
> +inline IteratorTraits initIterator() { return {}; }
idk if this is the correct way for this...

2022-02-09 03:11 UTC, cabmeurer commented on test/Interop/Cxx/stdlib/Inputs/std-iterator_traits.h
> +inline IteratorTraits initIterator() { return {}; }
i dont think this is the right way to do this...

2022-02-09 03:19 UTC, cabmeurer commented
I thought I would give it a go and try to add some tests here, let me know if these is even needed and/or what I should fix

2022-02-10 18:24 UTC, hyp commented
@swift-ci please test

2022-02-11 00:45 UTC, cabmeurer commented
@swift-ci please test

2022-02-11 00:50 UTC, cabmeurer commented
> **Build failed** [Swift Test OS X Platform](https://ci.swift.org/job/swift-PR-macos/31106/) Git Sha - [265b8f2](https://github.com/apple/swift/commit/265b8f229daded8609875d85d73f6fce60ac8920)

Pushed a change that should resolve this failure

2022-02-18 18:26 UTC, cabmeurer commented
@zoecarver when you get a chance, could you merge this for me?

2022-02-18 23:22 UTC, zoecarver requested changes
I'm sorry, I don't think that this really makes sense to test. If we are able to construct an object, it won't be nil. It might be interesting to see if we can import `iterator_traits` (a module interface test) but honestly, I'm not even sure how valuable that would be. I don't think people will be using traits like this very often in Swift. 

What would be really helpful is some tests for `std::next` and `std::prev` (if you have time, `std::distance`, and `std::advance` might be interesting too) because I anticipate those will be used very frequently. Could you update this PR to test those instead (or make a new PR)?

I really appreciate you spending time writing tests! So, I'm sorry if this is disappointing :(

2022-02-18 23:23 UTC, zoecarver commented
I should also mention that these tests look 100% correct, so really well done for your first PR! It's just the thing you're testing doesn't really make sense.

2022-02-18 23:45 UTC, closed without merging