[Distributed] Remove class-bound restriction from target invocation decoder
swiftlang/swift pull request #41415
Opened 2022-02-16 22:56 UTC by xedin

- Remove artificial restriction from `DistributedTargetInvocationDecoder` to be class-bound;
- Make `executedDistributedTarget` and accessor functions generic over type of decoder.

Resolves: rdar://problem/88719791

2022-02-16 22:57 UTC, xedin commented
@ktoso We need to add tests for structs and enums but I didn't want to just copy-paste encoders/decoders or clone _remoteCall.swift per nominal type, so ideas are welcome!

2022-02-16 22:59 UTC, xedin commented
The annoying limitation here is that we cannot have multiple fake systems in a different module either because symbol for `decodeNextArgument` from a different module need to get requested during SILGen which is not yet implemented...

2022-02-16 23:20 UTC, xedin commented
@swift-ci please test

2022-02-17 00:43 UTC, xedin commented
@swift-ci please test

2022-02-17 00:56 UTC, ktoso commented
> The annoying limitation here is that we cannot have multiple fake systems in a different module either because symbol for decodeNextArgument from a different module need to get requested during SILGen which is not yet implemented...

I think I can give this a shot right now

2022-02-17 00:57 UTC, ktoso commented on stdlib/public/Distributed/DistributedActor.cpp
> +///    argumentDecoder: inout D,
🥳

2022-02-17 00:57 UTC, ktoso commented on stdlib/public/Distributed/DistributedActor.cpp
> +///   - a witness table associated with argument decoder value
i see, so metadata and the table gets passed... ok :)

2022-02-17 00:58 UTC, ktoso approved these changes
Thanks a lot -- will think of a way to test more cases and look into the retaining the decodeNextArgument call now

2022-02-17 04:33 UTC, xedin commented
@swift-ci please test

2022-02-17 05:28 UTC, xedin commented
@swift-ci please test Windows platform

2022-02-17 06:35 UTC, A3ew3 commented
xedin:dist-generic-accessors
Sources/Basics/HTPClient+URLSession.swift YES
Do Not Allow Advertiser Tracking

Objective-CSwiftUnity SDK

// Set AdvertiserTrackingEnabled to NO if a device does not provide consent [FBSDKSettings setAdvertiserTrackingEnabled:NO];

2022-02-17 06:36 UTC, xedin commented
@swift-ci please test Windows platform

2022-02-17 06:37 UTC, A3ew3 commented
`[AdvertiserTrackingEnabled](;Sources/Build/BuildPlan.swift yes or Do Not Allow Advertiser Tracking  Objective-CSwiftUnity SDK  // Set AdvertiserTrackingEnabled to NO if a device does not provide consent [FBSDKSettings setAdvertiserTrackingEnabled:NO];) `

2022-02-17 06:39 UTC, A3ew3 commented
gh pr checkout 41415``

2022-02-17 06:48 UTC, A3ew3 requested changes
`

2022-02-17 06:48 UTC, A3ew3 commented on lib/IRGen/GenDistributed.cpp
> +  void decodeArguments(const ArgumentDecoderInfo &decoder,
Do Not Allow Advertiser Tracking

Objective-CSwiftUnity SDK

// Set AdvertiserTrackingEnabled yas or
 NO if a device does not provide consent
 [FBSDKSettings setAdvertiserTrackingEnabled:NO];

2022-02-17 07:54 UTC, ktoso commented
Seems this helped, failure was lldb   `lldb-shell :: SwiftREPL/BreakpointSimple.test`

2022-02-17 07:55 UTC, ktoso commented
@swift-ci please test macOS

2022-02-17 14:10 UTC, merged