[AutoDiff] Change decorators on derivatives of `FloatingPoint` functions
swiftlang/swift pull request #41414
Opened 2022-02-16 22:20 UTC by philipturner

The `@_transparent` modifier appears nowhere else in the `_Differentiation` module, even on functions that are generic or non-generic. Also, no other AutoDiff functions are force-inlined like `@_transparent` does. This PR makes FloatingPointDifferentiation.swift.gyb consistent with the rest of the stdlib.

2022-02-16 23:14 UTC, compnerd commented
I think that this would need benchmarking across macOS, Linux, Windows, and android.  If the inliner is now at the point where we could actually remove the attribute, this might be interesting.  At the very least we would want a wide coverage of different model sizes (e.g. perhaps an implementation of GPT-3 and BERT with this) on a reasonably sized corpus.  There is the other aspect of potentially breaking existing clients due to emission behaviour, but that can be a secondary axis of investigation.

2022-02-16 23:41 UTC, philipturner commented
> I think that this would need benchmarking across macOS, Linux, Windows, and android. 

`@inline(__always)` would solve this problem and make it consistent with the rest of the `_Differentiation` module. If the only reason it was `@_transparent` originally was performance, this makes perfect sense. If it's about performance, we should also add `@inline(__always)` to SIMD vectors, which are native just like Float and Double.

> (these were carefully analyzed and put in strategically to deal with code-size and perf ratios).

I've looked, but I haven't found any citation of the initial reason for forcing the inlining. Since profiling is something scientific, we need hard evidence linked in this PR to justify whether and what we force-inline.

> (e.g. perhaps an implementation of GPT-3 and BERT with this)

I don't think the reference to machine learning is particularly suitable here. I recently got S4TF working on macOS (so existing crashes can be debugged and isolated) and [with TF 2.8](https://github.com/philipturner/swift-for-tensorflow/commit/5794ef766e45122a9eb8278bd5c73318cfdbe5bc), but it's still crashing on release. Otherwise, there are no Swift ML frameworks that use AutoDiff and can provide such benchmarks.

Furthermore, ML doesn't use AutoDiff on Swift's native types. It operates on `Tensor<Float>`, using custom derivatives that are not from the Swift stdlib. The overhead of calling into `CTensorFlow` is also quite high, and could dwarf the cost of not inlining one function.

> There is the other aspect of potentially breaking existing clients due to emission behaviour,

Correct me if I'm wrong, but this is a reference to ABI stability of AutoDiff. If we were to make inlining optional, it would break binary compatibility with existing compiled code. AutoDiff is not ABI stable yet (SR-15577), so we are free to change its binary interface.

2022-02-17 00:38 UTC, philipturner commented
If we do go forward with keeping `@_transparent` or `@inlinable @inline(__always)`, then we will use that convention for the future `FloatingPoint` members that were made differentiable in #41099. Is this correct?

2022-02-17 01:59 UTC, compnerd requested changes
I'm not convinced that this doesn't have consequences that are important.  The benchmarking is important.  I agree that the benchmarking doesn't need to be ML specific, however, that is what was used in the past.  Something which exercises the codepaths for forward and backwards differentiation aggressively in a hotpath would likely suffice (though would need before and after comparisons).

All I can share about the previous performance analysis is that it was done across a variety of CPUs/GPUs/... and OS environments and that these were identified through profiling to be considerably important to get the proper code generation.  It is important that we do not hastily drop these attributes without the due investigation.

2022-02-17 02:10 UTC, philipturner commented
> All I can share about the previous performance analysis is that it was done across a variety of CPUs/GPUs/... and OS environments

I don't see how it's possible to benchmark Swift's native CPU types on a GPU. But, your statement is sufficient evidence for me to conclude that force-inlining should happen.

2022-03-04 15:23 UTC, philipturner commented
Please disregard my prior comments.

Do we still need `// FIXME(sil-serialize-all)` placed in several positions in the file? What needs to change in order to remove these notes? 

It seems that we should use `@usableFromInline` by default for new derivatives. Is this correct?

2022-03-21 19:55 UTC, closed without merging