[Demangling] Fix duplicate _gCRAnnotations symbol problems.
swiftlang/swift pull request #42109
Opened 2022-03-31 12:12 UTC by al45tair

Moved the `_gCRAnnotations` declarations to their own object module, which will help to avoid duplicate symbol problems (at least with `.a` files).

Also tweaked things to make it so that the demangler and runtime versions of the message setting code will interoperate (and so that they'll interoperate better with other implementations that might creep in from somewhere, like the one in LLVMSupport).

rdar://91095592

2022-03-31 12:13 UTC, al45tair commented
@swift-ci Please smoke test

2022-03-31 13:50 UTC, mikeash requested changes

2022-03-31 13:50 UTC, mikeash commented on stdlib/public/runtime/Errors.cpp
> +    std::memory_order_relaxed);
Not that it's going to matter much in practice, but this should be `SWIFT_MEMORY_ORDER_CONSUME`.

2022-03-31 15:43 UTC, al45tair commented
@swift-ci Please smoke test

2022-03-31 16:13 UTC, mikeash approved these changes

2022-03-31 21:52 UTC, al45tair commented
@swift-ci Please smoke test

2022-04-01 06:08 UTC, al45tair commented
@swift-ci Please smoke test

2022-04-01 11:11 UTC, al45tair commented
@swift-ci Please smoke test platform linux

2022-04-01 11:13 UTC, al45tair commented
@swift-ci Please smoke test Linux platform

2022-04-01 15:37 UTC, merged