[stdlib] Add Unicode script data to scalar properties
swiftlang/swift pull request #42227
Opened 2022-04-06 21:35 UTC by Azoy

I made the `script` and `scriptExtensions` return `UInt8` because the `Unicode.Script` enum defined in the regex parser cannot be made SPI in the stdlib due to the fact that we bootstrap the regex parser using the system's SDK (which won't have this SPI symbol). We can teach the parser to store strings instead and define the enum here as SPI for the string processing module to turn it into the enum.

2022-04-06 22:24 UTC, lorentey requested changes
We must follow the [Leading Underscore Rule](https://github.com/apple/swift/blob/main/docs/StandardLibraryProgrammersManual.md#the-leading-underscore-rule) when naming non-public interfaces, in every stdlib module.

2022-04-06 22:24 UTC, lorentey commented on stdlib/public/core/UnicodeSPI.swift
> +  public var script: UInt8 {
```suggestion
  public var _script: UInt8 {
```

2022-04-06 22:24 UTC, lorentey commented on stdlib/public/core/UnicodeSPI.swift
> +  public var scriptExtensions: [UInt8] {
```suggestion
  public var _scriptExtensions: [UInt8] {
```

2022-04-06 22:26 UTC, Azoy commented
> We must follow the [Leading Underscore Rule](https://github.com/apple/swift/blob/main/docs/StandardLibraryProgrammersManual.md#the-leading-underscore-rule) when naming non-public interfaces, in every stdlib module.

oops forgot, thanks!

2022-04-07 19:26 UTC, Azoy commented
@swift-ci please smoke test

2022-04-07 22:21 UTC, Azoy commented
@swift-ci please smoke test

2022-04-07 22:29 UTC, rxwei approved these changes

2022-04-07 22:29 UTC, rxwei commented on stdlib/public/stubs/Unicode/UnicodeScalarProps.cpp
> +                                                      __swift_uint8_t *count) {
Seems misindented

2022-04-07 23:20 UTC, Azoy commented
@swift-ci please smoke test

2022-04-08 03:53 UTC, lorentey approved these changes

2022-04-08 04:04 UTC, merged