[QoI] diagnose operator fixity attrs together; improve messages
swiftlang/swift pull request #4661
Opened 2016-09-07 06:55 UTC by jtbandes

Addresses an issue raised by @rintaro in #4628.

Previously, `infix` was not recognized as conflicting with `prefix` and `postfix`. We now offer to remove all but the first fixity attribute.

### RFC:

I'm not sure `ParseDecl.cpp` is really the right place to check these attrs. I like the idea of having `TypeCheckAttr.cpp` contain most of the attribute-verifying logic, but it's structured as a simple visitor which doesn't have the power to handle a few related attributes at the same time (without architectural changes). Maybe I'm missing something, but to me the current distinction between things in `DiagnosticsSema.def` and things in `DiagnosticsParse.def` seems somewhat arbitrary.

Perhaps @DougGregor or someone else can provide a better alternative.

### Before:

<pre><b>no error 😱</b>
infix prefix operator ++

<b>attribute 'postfix' cannot be combined with this attribute</b>
postfix prefix operator --
        ^
</pre>

### After:

<pre><b>error: 'prefix' contradicts previous modifier 'infix'</b>
infix prefix operator ++
      ^~~~~~~

<b>error: 'prefix' contradicts previous modifier 'postfix'</b>
postfix prefix operator --
        ^~~~~~~</pre>

2016-09-07 06:56 UTC, jtbandes commented
@swift-ci please smoke test

2016-09-07 07:12 UTC, jtbandes commented
@swift-ci please smoke test

2016-09-07 07:43 UTC, jtbandes commented
@swift-ci smoke test linux

2016-09-20 03:37 UTC, DougGregor commented on lib/Parse/ParseDecl.cpp
> +      FD->setInvalid();
It doesn't seem necessary to mark the whole declaration invalid, does it?

2016-09-20 03:37 UTC, DougGregor commented on lib/Parse/ParseDecl.cpp
> +    res->setInvalid();
Same here: I don't think the whole operator declaration needs to be invalid.

2016-09-20 03:37 UTC, DougGregor requested changes

2016-09-21 03:54 UTC, jtbandes commented on lib/Parse/ParseDecl.cpp
> +    res->setInvalid();
Fair enough — removed.

2016-09-21 03:55 UTC, jtbandes commented
@swift-ci please smoke test

2016-09-22 06:23 UTC, DougGregor commented
LGTM now, thanks!

2016-09-22 06:23 UTC, merged