[sil-escape-analysis] Various improvements
swiftlang/swift pull request #4818
Opened 2016-09-15 23:20 UTC by swiftix

Tech escape analysis a few new tricks:
- It is now able to look through basic block arguments
- It is able to analyze destructors of local objects

For more detailed description see the specific commits.

2016-09-15 23:21 UTC, swiftix commented
@swift-ci Please smoke test

2016-09-15 23:22 UTC, swiftix commented
@eeckstein Erik, do you mind reviewing this PR? I suggest looking at separate commits, because it is easier to understand what is going on then.

2016-09-18 16:03 UTC, swiftix commented
@swift-ci Please smoke test Linux

2016-09-19 16:05 UTC, eeckstein requested changes
LTGM!
But please add more test(s) to check the destructor analysis.

Thanks for doing this work!

2016-09-19 20:44 UTC, swiftix commented on test/SILOptimizer/escape_analysis.sil
> +}
@eeckstein I added a couple of tests to demonstrate that destructors which allow objects to escape are handled properly.

2016-09-19 21:13 UTC, eeckstein approved these changes

2016-09-19 21:15 UTC, swiftix commented
@swift-ci Please smoke test and merge

2016-09-19 21:15 UTC, swiftix commented
@swift-ci Please smoke test and merge

2016-09-19 22:12 UTC, merged