[utils][SR-2695] Tag checkout support for all repositories.
swiftlang/swift pull request #4892
Opened 2016-09-20 22:15 UTC by aleksgapp

Add support for a specific tag checkout for all repositories.

Resolves [SR-2695](https://bugs.swift.org/browse/SR-2695).

2016-09-20 22:36 UTC, modocache commented on utils/update-checkout
> +        dest='tag')
nit-pick: This `dest` parameter is unnecessary; since the argument name is `--tag` the destination will automagically be named `tag`.

2016-09-20 22:39 UTC, modocache commented on utils/update-checkout
> +                    continue
Nice touch!! I love it.

2016-09-20 22:40 UTC, modocache approved these changes
This looks great! Thanks a lot for doing this.

I haven't heard from any other Swift committers since creating the starter task. I wonder if they have any thoughts on adding this flag? /cc @gottesmm

2016-09-21 05:49 UTC, gottesmm commented
@erg What do you think of this?

2016-09-21 10:00 UTC, aleksgapp commented on utils/update-checkout
> +        dest='tag')
Oh, right, it's removed now.

2016-09-24 00:53 UTC, gottesmm commented
Since @erg didn't respond, I'll review this real quick. This function is getting quite big. Can you split it into two functions? One for the tag and for the non-tag case?

2016-09-25 19:05 UTC, aleksgapp commented
Done!

2016-09-25 19:52 UTC, modocache commented
@swift-ci Please Python lint

2016-09-25 19:52 UTC, modocache commented
@swift-ci please smoke test

2016-09-25 22:24 UTC, gottesmm requested changes
This is not what I was suggesting. I was suggesting that you keep 1 function but if you had the tag or scheme you delegated to different functions. It is just the middle section that should be refactored. Everything else is the same.

2016-09-26 14:39 UTC, aleksgapp commented
Oops, should be as you've suggested now.

2016-09-26 18:38 UTC, gottesmm commented
@aleksgapp No worries. Thanks for fixing this.

@aleksgapp, @modocache. An additional question: I have not thought about this (and I am fine doing this in a follow on commit), but given that tag/scheme are exclusive options I wonder if there is a way to express them on the command line in an exclusive manner. Just doing something like --type=scheme --type=tag won't work since they require options. Maybe the thing to do is just make sure that only one is set and error otherwise? [Trying to steal a minute of your brain power = )]

2016-09-26 18:38 UTC, gottesmm approved these changes

2016-09-26 18:40 UTC, gottesmm commented
I guess we could use subparsers? Maybe have something like:

./update-checkout scheme <name>
./update-checkout tag <name>
./update-checkout <[need a name for when we just update what is locally there]>

Not sure.

2016-09-27 11:14 UTC, aleksgapp commented
@gottesmm I had a quick look at this direction, but didn't include this to my initial implementation.

There is an `parser.add_mutually_exclusive_group()` option that makes this possible:
```
update-checkout: error: argument --scheme/--branch: not allowed with argument --tag
```

One more thing that isn't fitting well here is optional arguments, e.g, `--github-comment` relates only to `scheme/branch` argument and would be just skipped if given with `tag` argument, `--skip-history` is taken in account only if `clone/clone-with-ssh` is given. 

I'm not sure if we need take care of those here? May be just adding an exclusiveness for `tag/scheme` options would be enough in scope of this pull request?

2016-09-28 22:43 UTC, gottesmm commented
@aleksgapp Yes, any such changes are 100% out of scope for this PR. Lets get this in.

2016-09-28 22:44 UTC, gottesmm commented
@swift-ci Please smoke test and merge

2016-09-29 09:31 UTC, aleksgapp commented on utils/update-checkout
> -        dest='github_comment'),
@gottesmm Resolved small conflict, I believe this comma was a typo, right?

2016-10-03 21:40 UTC, shahmishal commented
@swift-ci Please smoke test and merge

2016-10-11 23:03 UTC, shahmishal commented
@swift-ci Please smoke test and merge

2016-10-12 00:02 UTC, merged