[Diagnostics] Fix bad diagnostic for failed assignment from Any to a more specific type
swiftlang/swift pull request #5105
Opened 2016-10-03 20:35 UTC by xedin

When generating constraints for subscript convert InOutType into LValueType,
because base of the subscript should never be marked as inout, but rather as
@lvalue to denote mutability.

Resolves <rdar://problem/25601651>.

2016-10-03 20:35 UTC, xedin commented
/cc @rudkx

2016-10-04 00:35 UTC, rudkx commented
@swift-ci Please smoke test.

I'll take a closer look at this change this evening.

2016-10-04 15:58 UTC, rudkx commented
@swift-ci Please smoke test

2016-10-04 18:11 UTC, rudkx commented
@xedin FYI the bug number in the commit message still has two digits swapped.

So I'm torn on this one. This really isn't fixing the core issue here, but is papering over it.

The core issue is that during diagnostics we apply a solution that adds an InOutExpr, and that particular pass of typeCheckChildIndependently() doesn't turn up anything, so we continue on and build a new constraint system with this mutated AST.

We could take your patch, amended with a comment explaining that it is a pragmatic hack for the time being, or could defer this until we have time to rework (what I expect to be a lot of stuff) to design things like this out of the system.

@DougGregor What do you think?

If we do take the patch I think the more principled thing to do is check to see if the InOutExpr's subexpr is an LValue and only make the result an LValue if it is.

2016-10-04 18:12 UTC, rudkx commented
FWIW, I believe I've seen other bugs that are probably hitting the exact same issue so we might be able to kill off more than one bug with this change.

2016-10-04 19:19 UTC, xedin commented
@rudkx Pushed a fix for a commit message (sorry about that, apparently i can't even copy-paste correctly...)!

Let me elaborate a bit more about why I did what I did here: When you look at the example in the test - here was the initial state with force_value_expr at the top:

```
(force_value_expr type='$T8' location=<REPL Input>:4:36 range=[<REPL Input>:4:23 - line:4:36]
  (call_expr type='$T7' location=<REPL Input>:4:29 range=[<REPL Input>:4:23 - line:4:35]  arg_labels=
    (unresolved_dot_expr type='$T6' location=<REPL Input>:4:29 range=[<REPL Input>:4:23 - line:4:29] field 'value' function_ref=single
      (force_value_expr type='$T5' location=<REPL Input>:4:27 range=[<REPL Input>:4:23 - line:4:27]
        (subscript_expr type='$T4' location=<REPL Input>:4:24 range=[<REPL Input>:4:23 - line:4:26]  arg_labels=_:
          (unresolved_dot_expr type='@lvalue [S_r25601561?]' location=<REPL Input>:4:23 range=[<REPL Input>:4:23 - line:4:23] field 'a' function_ref=unapplied
            (declref_expr implicit type='C_r25601561' location=<REPL Input>:4:23 range=[<REPL Input>:4:23 - line:4:23] decl=REPL.(file).C_r25601561.func decl.self@<REPL Input>:3:10 function_ref=unapplied specialized=no))
          (paren_expr type='(Int)' location=<REPL Input>:4:25 range=[<REPL Input>:4:24 - line:4:26]
            (declref_expr type='Int' location=<REPL Input>:4:25 range=[<REPL Input>:4:25 - line:4:25] decl=REPL.(file).C_r25601561.func decl.i@<REPL Input>:3:15 function_ref=unapplied specialized=yes)))))
    (tuple_expr type='()' location=<REPL Input>:4:34 range=[<REPL Input>:4:34 - line:4:35])))
```

When solving that the only constraint which is going to fail is contextual type conversion - `$T8 conv String`, which forces diagnostics as follows - first it goes into `diagnoseExprFailure` and tries to diagnose ForceValueExpr via `FailureDiagnosis::visitForceValueExpr`, what that actually does is extracts a sub-expression which is CallExpr and tries to solve it instead to check if there are any structural errors - none in that case. 

```
(call_expr type='Any?' location=<REPL Input>:4:29 range=[<REPL Input>:4:23 - line:4:35]  arg_labels=
  (dot_syntax_call_expr type='() -> Any?' location=<REPL Input>:4:29 range=[<REPL Input>:4:23 - line:4:29]
    (declref_expr type='(S_r25601561) -> () -> Any?' location=<REPL Input>:4:29 range=[<REPL Input>:4:29 - line:4:29] decl=REPL.(file).S_r25601561.value()@<REPL Input>:2:10 function_ref=double specialized=no)
    (load_expr implicit type='S_r25601561' location=<REPL Input>:4:27 range=[<REPL Input>:4:23 - line:4:27]
      (force_value_expr type='@lvalue S_r25601561' accessKind=read location=<REPL Input>:4:27 range=[<REPL Input>:4:23 - line:4:27]
        (subscript_expr type='@lvalue S_r25601561?' accessKind=read location=<REPL Input>:4:24 range=[<REPL Input>:4:23 - line:4:26]  decl=Swift.(file).Array.subscript [with S_r25601561?]  arg_labels=_:
          (inout_expr implicit type='inout Array<S_r25601561?>' location=<REPL Input>:4:23 range=[<REPL Input>:4:23 - line:4:23]
            (member_ref_expr type='@lvalue [S_r25601561?]' accessKind=readwrite location=<REPL Input>:4:23 range=[<REPL Input>:4:23 - line:4:23] decl=REPL.(file).C_r25601561.a@<REPL Input>:2:9
              (declref_expr implicit type='C_r25601561' location=<REPL Input>:4:23 range=[<REPL Input>:4:23 - line:4:23] decl=REPL.(file).C_r25601561.func decl.self@<REPL Input>:3:10 function_ref=unapplied specialized=no)))
          (paren_expr type='(Int)' location=<REPL Input>:4:25 range=[<REPL Input>:4:24 - line:4:26]
            (declref_expr type='Int' location=<REPL Input>:4:25 range=[<REPL Input>:4:25 - line:4:25] decl=REPL.(file).C_r25601561.func decl.i@<REPL Input>:3:15 function_ref=unapplied specialized=no))))))
  (tuple_expr type='()' location=<REPL Input>:4:34 range=[<REPL Input>:4:34 - line:4:35]))
```

So following that `diagnoseExprFailure` happy returns with correctly type checked sub-expression attached to the ForceValueExpr and now it's time to do `diagnoseContextualConversionError` (which is correct), what that does is - it strips away all of the already assigned types from the expressions but not their newly found declarations, which results into the problem at hand. So since subscript in the normal case doesn't deal with re-written AST which contains InOutExpr, and I think it's valid to have InOutExpr there since that particular subscript is mutable and CallExpr had successfully type-checked, I decided to simply fix subscript generation to handle inout'ness.

2016-10-04 21:38 UTC, rudkx commented
@xedin Yes, that's what I saw under the debugger and it's good to detail exactly what's going on.

My concern with this particular fix is it doesn't look like under normal circumstances we would ever have an InOutExpr as a child of a SubscriptExpr on entry to the type checker. We only get these as a result of a successful type check, and you wouldn't normally expect to feed a successfully type checked expression back into the type checker.

The current mechanism used in the diagnostics (of type checking pieces and mutating the AST) isn't ideal. I believe we see a significant number of crashers directly as a result of this kind of mutation happening, for reasons similar to this one. I think the right long term design would be to either not mutate the AST during diagnostics emission, or to roll back those changes before attempting to build a new constraint system. It's not clear to me how large a change that would end up being.

My specific concern about taking changes like these is that it's easy for other people who are coming up-to-speed on our code to see something like this and assume that we should expect InOutExprs in subscripts, and that the right way to deal with them is to force them to LValues.

Being pragmatic, though, it's a fine fix to avoid this particular issue - I think we just need ample warning to go with the code explaining why it's there (e.g., "// FIXME: We don't normally expect InOutExpr subexpressions of subscripts on entry to constraint generation but can get them as a result of diagnostics passes mutating the AST. We should ideally fix diagnostics to not do that.").

One other suggestion on your particular change which I think would make it a bit cleaner is to explicitly check for InOutExpr and walk through it rather than looking at and modifying the types. That should work, and with a comment explaining why we're doing this I think we could probably take the change with the hope that one day we can fix the diagnostics passes.

Thanks for working on this - as I mentioned I think this probably fixes more than one reported issue.

2016-10-04 21:47 UTC, xedin commented
@rudkx We are totally on the same page, I just wanted to write it down so we have it in logged. 

What you are describing is exactly what I tried to do, but I couldn't find a way to get that original sub-expression back after type checking of the ForceValueExpr rewrote whole AST :( I think that would require bigger change to fix properly, I'll make a change for checking for InOutExpr explicitly and put FIXME for that, and you are right, that would make things for clean for new people (like myself).

I can also attempt to properly solve this situation as a separate issue, WDYT?

2016-10-04 21:50 UTC, rudkx commented
@xedin I think the proper solution is probably best to defer for the moment. At some point it's definitely something worth tackling, though!

2016-10-04 21:54 UTC, xedin commented
Got it!

2016-10-04 22:43 UTC, xedin commented
@rudkx ^ All done, please let me know what you think about FIXME message.

2016-10-04 22:54 UTC, rudkx requested changes
One more suggestion and then I think we're set.

2016-10-04 22:54 UTC, rudkx commented on lib/Sema/CSGen.cpp
> +
It's simpler to just say:
```
if (auto inoutExpr = dyn_cast<InOutExpr>(base))
  base = inoutExpr->getSubExpr();
```
The subexpr type should be an LValueType when it needs to be, or else something else has gone wrong.

2016-10-04 22:54 UTC, rudkx commented on lib/Sema/CSGen.cpp
> +      // circumstances subscript should never have InOutExpr as a direct child.
Slight correction: It's not that subscript shouldn't have InOutExpr as a child, it's that it shouldn't happen in un-typechecked ASTs.

2016-10-04 23:09 UTC, xedin commented on lib/Sema/CSGen.cpp
> +      // circumstances subscript should never have InOutExpr as a direct child.
Thanks, I've added clarification to the comment.

2016-10-04 23:23 UTC, xedin commented
@rudkx ^ all requested changes are addressed.

2016-10-04 23:25 UTC, rudkx approved these changes

2016-10-04 23:26 UTC, rudkx commented
@swift-ci Please smoke test and merge

2016-10-05 01:52 UTC, xedin commented
Looks like swift-ci doesn't want to merge automatically for some reason...

2016-10-05 02:51 UTC, merged