Replace take-initialization copy_addr instructions with moves in arc-inert blocks
swiftlang/swift pull request #5138
Opened 2016-10-05 22:56 UTC by shajrawi

radar rdar://problem/24011383

This concludes this radar by turning copy_addr instructions into moves in simplifyProgramTerminationBlock()

2016-10-05 22:56 UTC, shajrawi commented
@gottesmm Can you please review?

2016-10-05 22:57 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-05 23:22 UTC, jckarter commented
Why does it have to be ARC-inert? It should always be possible to break a `copy_addr [init] [take]` into a load and store.

2016-10-05 23:29 UTC, gottesmm commented
@jckarter That is not what is happening here. What is happening here is that we are changing copy_addr in blocks that we know are leaking to just be moves.

2016-10-06 16:01 UTC, jckarter commented
The transformation here is always valid; `copy_addr [init] [take]` should always be equivalent to `load; store` for a loadable type. I was wondering why we were constraining the transformation only to 'ARC-inert' blocks; AFAICS this transformation should always be OK.

2016-10-09 01:00 UTC, gottesmm commented
@shajrawi Sorry for the delay. I am reviewing this now.

2016-10-09 01:05 UTC, gottesmm requested changes
I think we can make this even more aggressive. Given that we are always going to leak in these blocks, we can also ignore:

copy_addr [take] %0 to %1

2016-10-09 01:05 UTC, gottesmm commented on lib/SILOptimizer/Transforms/SimplifyCFG.cpp
> +        !isa<CopyAddrInst>(I))
Maybe refactor this query into a helper function?

2016-10-09 01:05 UTC, gottesmm commented on lib/SILOptimizer/Transforms/SimplifyCFG.cpp
> +  for (auto I : InstsToReplace) {
May be good to make it clear that this is a pointer by making it an auto *

2016-10-09 01:05 UTC, gottesmm commented on lib/SILOptimizer/Transforms/SimplifyCFG.cpp
> +    auto CAI = cast<CopyAddrInst>(I);
Can you also make this an auto *.

2016-10-09 01:05 UTC, gottesmm commented on lib/SILOptimizer/Transforms/SimplifyCFG.cpp
> +    auto LI = Builder.createLoad(Loc, CAI->getSrc());
Also this please make an auto * ; ).

2016-10-09 01:07 UTC, gottesmm commented
The reason why we do not want to eliminate retains is we want to make sure that we fail at the actual program termination point, not before.

There is a possibility where we could by removing the retain change a balanced retain count to be unbalanced resulting in us touching a deallocated object.

In contrast, removing a release just makes us leak even more, which we are fine with.

2016-10-10 16:42 UTC, jckarter commented
Changing `copy_addr [take] %0 to %1` into a take-initialization is not safe in all cases. If the type being operated on contains weak references or other side references, it will corrupt the weak reference table if you fail to deregister the value currently at `%1`. Maybe it's safe for all currently loadable types, but if we move in the direction of semantic ARC and start representing all types as SSA values, would this be a liability?

Again, `copy_addr [take] [init]` are `load; store` are *always* equivalent, so I don't understand why we're limiting this transformation to unreachable blocks.

2016-10-10 19:55 UTC, shajrawi commented
@gottesmm can you please answer @jckarter 's input, I feel you are more qualified to answer his concerns.
I also updated the PR with all the changes you requested.

2016-10-10 19:55 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-10 19:56 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-10 21:47 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-10 23:56 UTC, gottesmm commented
Joe, can we talk about this tomorrow in person?

2016-10-10 23:56 UTC, gottesmm commented
@jckarter I mean ; )

2016-10-11 22:56 UTC, shajrawi commented
Updated the PR: removed code modifications and replaced it with a comment that sums-up the offline discussion with @jckarter and @gottesmm

2016-10-11 22:57 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 22:57 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 22:57 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 23:12 UTC, gottesmm approved these changes

2016-10-11 23:50 UTC, merged