[Parse] Several improvement for attribute parsing.
swiftlang/swift pull request #5173
Opened 2016-10-07 04:51 UTC by rintaro

### [Parse] Eliminate Parser::canParseAttributes()

`@foo=bar` style attributes are no longer supported anyway.
So as `,` separated attribute list.

In `canParseTypeTupleBody()`, `canParseType()` can more accurately consume
type attributes.

In `isStartOfGetSetAccessor()`, we can trivially inline the functionality.

### [QoI][Parse] Improve recovering from unknown attribute

By consuming parens.
As for type attributes, handle `@unknownAttribute(Arg) -> Ret` case.

Improves diagnostic QoI. For example, on:
`func foo(x: @unknown(x) Int) {}`

Before:
```
test.swift:1:14: error: unknown attribute 'unknown'
test.swift:1:25: error: expected ',' separator
test.swift:1:25: error: unnamed parameters must be written with the empty name '_'
test.swift:1:22: error: use of undeclared type 'x'
```

Now, we just emit the first one:
```
test.swift:1:14: error: unknown attribute 'unknown'
func foo(x: @unknown(x) Int) {}
             ^
```

### [Parse] Remove unnecessary parameters from `parseDeclAttributeList` function.

`InParam` was not used at all.

`StopAtTypeAttributes`
As far as I understand, this option *was* merely for improving diagnostic QoI
for declarations like:
  `func foo(@typeattr Arg) {}`
to fix-it to:
  `func foo(_: @typeattr Arg) {}`

But, this causes the very loudly diagnostics for misplaced type attributes.
For example, on:
`func foo(@convention(block) x: () -> CInt) {}`

```
test.swift:1:10: error: expected parameter name followed by ':'
test.swift:1:10: error: expected ',' separator
test.swift:1:10: error: expected ')' in parameter
test.swift:1:9: note: to match this opening '('
test.swift:1:10: error: consecutive statements on a line must be separated by ';'
test.swift:1:11: error: attribute can only be applied to types, not declarations
test.swift:1:21: error: expected declaration
test.swift:1:44: error: statement cannot begin with a closure expression
test.swift:1:44: note: explicitly discard the result of the closure by assigning to '_'
test.swift:1:44: error: braced block of statements is an unused closure
test.swift:1:6: error: expected '{' in body of function declaration
test.swift:1:44: error: expression resolves to an unused function
```

Now, we emit more accurate diagnostic:
```
test.swift:1:11: error: attribute can only be applied to types, not declarations
func foo(@convention(block) x: () -> CInt) {}
          ^
```
Note that This causes small regression in diagnostics for bare type parameter
like `func foo(@convention(c) () -> CInt) {}`:

Before:
```
test.swift:1:10: error: unnamed parameters must be written with the empty name '_'
func foo(@convention(block) () -> CInt) {}
         ^
         _:
```
Now:
```
test.swift:1:11: error: attribute can only be applied to types, not declarations
func foo(@convention(block) () -> CInt) {}
          ^
test.swift:1:29: error: unnamed parameters must be written with the empty name '_'
func foo(@convention(block) () -> CInt) {}
                            ^
                            _:
```

### [AST] Remove @escaping from decl attributes.

`@escaping` is not really a decl attribute, ever since it was introduced.

2016-10-07 23:00 UTC, jrose-apple requested changes

2016-10-08 00:29 UTC, rintaro commented on lib/Parse/ParseDecl.cpp
> +      if (Tok.is(tok::arrow))
Thanks! Added `getEndOfPreviousLoc() == Tok.getLoc()` condition, and `throws` after paren check.
How do you think now?

2016-10-10 10:10 UTC, rintaro commented
@swift-ci Please smoke test

2016-10-10 12:03 UTC, rintaro commented
@swift-ci Please smoke test Linux

2016-10-10 16:29 UTC, jrose-apple approved these changes
Looks great. Nice cleanup, thanks Rintaro!

2016-10-10 17:26 UTC, merged

2016-10-10 17:26 UTC, rintaro commented
Thank you for reviewing!