Log debug elapsed time using 3 decimal places
swiftlang/swift pull request #5200
Opened 2016-10-09 18:35 UTC by benasher44

`-debug-time-function-bodies` is a useful flag for determining compile-time slowness, but it only logs elapsed parse times to 1/10th of a millisecond. While this is useful if a function takes a long time to parse, it doesn't help determine time lost to parsing function bodies that take a short time to parse (less than 0.1ms) but are parsed multiple times over the course of a build and therefore add up to occupying a significant portion of the build time.

Changing this helped me determine the impact of [SR-2901](https://bugs.swift.org/browse/SR-2901).

2016-10-09 19:46 UTC, mxswd commented
This also fixes SR-16

2016-10-10 03:09 UTC, CodaFi commented
Just to get this rolling

@swift-ci please smoke test.

2016-10-10 15:45 UTC, jrose-apple commented
I deliberately picked short precision because this was really only for tracking long times, but the other reason to keep it short is to not imply precision that isn't there. On a regularly loaded system, times can vary quite a bit. How about two decimal places, or even just keeping one, but rounding up first?

2016-10-10 15:52 UTC, benasher44 commented
I see. That makes sense. I'm only interested in ensuring that 0.0ms isn't logged, since it isn't that useful. Even though the precision might be there, the situation in which this data is useful is when you have lots of samples because of the nature of the bug. How about 2 decimal places + rounding? This'll give a bit more precision than

2016-10-10 15:58 UTC, jrose-apple commented
Sounds good to me. Thanks, Ben!

2016-10-10 22:41 UTC, jrose-apple requested changes

2016-10-10 22:41 UTC, jrose-apple commented on lib/Sema/TypeCheckStmt.cpp
> +        // Round to the nearest 100th of a millisecond
Nitpick: comments should end with periods.

2016-10-10 22:41 UTC, jrose-apple commented on lib/Sema/TypeCheckStmt.cpp
> +        llvm::errs() << llvm::format("%0.2f", round(elapsed * 100000) / 100) << "ms\t";
I thought we settled on `ceil`?

2016-10-10 22:43 UTC, benasher44 commented on lib/Sema/TypeCheckStmt.cpp
> +        llvm::errs() << llvm::format("%0.2f", round(elapsed * 100000) / 100) << "ms\t";
Oh I think I read over the "up" part in "rounding up." Will fix!

2016-10-10 23:29 UTC, jrose-apple commented
@swift-ci Please smoke test

2016-10-10 23:29 UTC, jrose-apple approved these changes

2016-10-11 16:14 UTC, CodaFi commented
@swift-ci please smoke test.

2016-10-11 17:31 UTC, merged