Do not emit shadow copied for inout parameters
swiftlang/swift pull request #5218
Opened 2016-10-11 00:25 UTC by shajrawi

radar rdar://problem/28434323

SILGen has no reason to insert shadow copies for inout parameters any more. They cannot be captured. We still emit these copies. Sometimes deshadowing removes them, but sometimes it does not.

In this PR we just avoid emitting the copies and remove the deshadowing pass.

This PR chery-picked some of @dduan work and built-up on to of it.

2016-10-11 00:26 UTC, shajrawi commented
@atrick Can you please review?

2016-10-11 00:26 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 01:22 UTC, atrick requested changes
Can you identify some unit tests that handle captured inout, and are you convinced they do the right thing? Can you add a test from the bug report to verify that local functions capturing inout are now handled the same as anonymous closures?

Otherwise this looks fine to me.

2016-10-11 01:22 UTC, atrick commented on lib/SILGen/SILGenProlog.cpp
> +      gen.B.createDebugValueAddr(loc, argrv.getValue(), {vd->isLet(), ArgNo});
The BuiltinUnsafeValueBufferType case above passes the unmanaged address to DebugValueAddr. This new default case passes a the argv value directly to DebugValueAddr. Why is there any difference?

2016-10-11 04:04 UTC, lattner commented
Awesome, thank you for working on this Joe, I look forward to this all getting cleaner and simpler.

2016-10-11 18:30 UTC, shajrawi commented on lib/SILGen/SILGenProlog.cpp
> +      gen.B.createDebugValueAddr(loc, argrv.getValue(), {vd->isLet(), ArgNo});
Combined debug value creation + added unit tests as requested.

2016-10-11 18:30 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 18:30 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 19:42 UTC, shajrawi commented
Linux smoke test failing with the usual non-PR related error - rerunning:
/home/buildnode/disk2/workspace/swift-PR-Linux-smoke-test/branch-master/swiftpm/Tests/XcodeprojTests/XcodeProjectModelTests.swift:12:8: error: module file was created by an older version of the compiler; rebuild 'TestSupport' and try again: /home/buildnode/disk2/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swiftpm-linux-x86_64/debug/TestSupport.swiftmodule

2016-10-11 19:42 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 19:42 UTC, shajrawi commented
@swift-ci Please smoke test

2016-10-11 19:49 UTC, CodaFi commented
Before this is merged, could you please squash @dduan's commits?

2016-10-11 19:53 UTC, dduan commented
Yes please squash...these were never meant to be public :)

2016-10-11 19:56 UTC, shajrawi commented
I intended to auto-squash everything into one commit on merge - all commits are about the same thing :)

2016-10-13 17:08 UTC, atrick approved these changes

2016-10-13 17:11 UTC, merged

2016-10-13 17:21 UTC, swiftix commented
@shajrawi Have you forgotten to squash the commits?

2016-10-13 17:24 UTC, shajrawi commented
@swiftix I squashed it - it is a single commit on mainline, no? (I clicked squash and merge In the PR)

2016-10-13 17:30 UTC, swiftix commented
@shajrawi Ah, OK. I assumed you you'd squash and push --force on the PR first and then merge. This is the usual way to it, because then the PR looks the same as the final merged set of commits.