[stdlib] Improved documentation for popLast() in BidirectionalCollection
swiftlang/swift pull request #5333
Opened 2016-10-17 21:57 UTC by LouisDhauwe

Added detailed documentation to `popLast()` regarding its safety compared to `removeLast()`,
as well as noting the performance cost `popLast()` has.

2016-10-17 21:59 UTC, moiseev commented
/cc @dabrahams and @natecook1000

2016-10-17 22:07 UTC, hooman commented
I think a similar note is needed for `removeLast()` as well.

2016-10-17 22:22 UTC, LouisDhauwe commented
@hooman Good point, documentation has now been updated for both `popLast()` and `removeLast()`.

2016-10-18 01:31 UTC, dabrahams reviewed
These changes are good, but we shouldn't be claiming popLast is safer. It's only preferable because it's guaranteed to be O(1) if it's available.

2016-10-18 14:01 UTC, LouisDhauwe commented
@dabrahams Ok, I removed the safety claim.

2016-10-18 15:55 UTC, dabrahams commented
I'm sorry, but I'm not comfortable with the recommendation either.  It seems to me that either `removeLast` should be considered no less preferable than `removeRange`, or if we really believe its usefulness is so marginal as to be a corner case, we should just tell users to `remove(at: index(before: endIndex))`.

2016-10-18 17:16 UTC, moiseev commented
@dabrahams Safety claim is perhaps my incorrect wording. It is safer in a sense that the type gives you all the info about the behavior of the function, whereas with `removeLast` it will trap in runtime. It is not about memory safety, it's about convenience and predictable behavior.

2016-10-18 19:15 UTC, natecook1000 requested changes

2016-10-18 19:15 UTC, natecook1000 commented on stdlib/public/core/BidirectionalCollection.swift
> +  /// is not empty and performance is an issue.
Could we rewrite this as:

> Use `popLast()` to remove the last element of a collection that might be empty. The `removeLast()` method must be used only on a nonempty collection.

2016-10-18 19:37 UTC, LouisDhauwe commented
@natecook1000 Ok, I've updated according to your requested changes.

2016-10-18 19:45 UTC, moiseev commented
Sorry for the back and forth on this, the problem turned out to be deeper than it originally looked =)

The problem with the comment I originally suggested is: both these methods are not necessarily available in all contexts. You can see that `removeLast` is defined for bidirectional collections and range-replaceable collections, but `popLast` is only available in bidirectional.

Interestingly, `removeLast` uses a hook in the protocol (see `_customRemoveLast`) that returns the last element if it existed, but it also requires the collection to be non-empty.

TL;DR: I think the right thing to do *now* is simply cross-reference the two methods in the documentation. Pretty much the way you've done it at the time of this writing.

This case clearly identifies the flaw in the design of these methods, solving which might become a part of a follow-up to [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0132-sequence-end-ops.md) one day.

Thanks for working on this, @LouisDhauwe!

2016-10-18 19:47 UTC, moiseev commented
This is sort of weird for a comment only change, but needs to be done.
@swift-ci Please smoke test

2016-10-18 19:51 UTC, natecook1000 approved these changes

2016-10-18 22:15 UTC, moiseev commented
@swift-ci Please smoke test and merge

2016-10-18 22:22 UTC, moiseev commented
@swift-ci Please smoke test and merge

2016-10-18 23:18 UTC, merged