[SR-2855] Show inputs mismatch in -driver-show-incremental
swiftlang/swift pull request #5340
Opened 2016-10-18 04:03 UTC by modocache

SR-2855 suggests `-driver-show-incremental` not only print information about why certain files are included in incremental compilation, but also print out why incremental compilation may be disabled altogether.

Add a message for one such reason: when the inputs passed to the Swift compiler don't match the ones used previously.

This addresses one part of [SR-2855](https://bugs.swift.org/browse/SR-2855).

2016-10-18 16:53 UTC, jrose-apple requested changes

2016-10-18 16:53 UTC, jrose-apple commented on lib/Driver/Driver.cpp
> +      llvm::StringSet<> missingInputs;
Please use a SmallVector for this, so that the results come out deterministically!

2016-10-18 16:53 UTC, jrose-apple commented on lib/Driver/Driver.cpp
> +        if(inputArgs.find(previousInputArg) == inputArgs.end()) {
Nitpick: missing space after 'if'.

2016-10-18 16:53 UTC, jrose-apple commented on lib/Driver/Driver.cpp
> +        llvm::outs() << " " << missing.getKey();
Most of the time these are going to be absolute paths, so I suggest putting them on their own lines.

2016-10-18 21:00 UTC, modocache commented
@swift-ci please test

2016-10-18 21:20 UTC, jrose-apple commented on test/Driver/Dependencies/driver-show-incremental-inputs.swift
> +// CHECK-INPUTS-MISMATCH: Incremental compilation has been disabled
To be clear, I'm worried about the test matching a case where it's disabled for some other reason.

2016-10-19 19:14 UTC, modocache commented
@swift-ci please smoke test

2016-10-19 21:45 UTC, jrose-apple approved these changes

2016-10-20 00:57 UTC, modocache commented
@swift-ci please smoke test os x platform

2016-10-20 01:36 UTC, merged