[Diagnostics] Improve diagnostics of overloaded mutating methods
swiftlang/swift pull request #5808
Opened 2016-11-15 23:37 UTC by xedin

Add special logic to FailureDiagnosis::visitApplyExpr to
handle situation like following:

struct S {
  mutating func f(_ i: Int) {}
  func f(_ f: Float) {}
}

Given struct has an overloaded method "f" with a single argument of
multiple different types, one of the overloads is marked as
"mutating", which means it can only be applied on LValue base type.
So when struct is used like this:

let answer: Int = 42
S().f(answer)

Constraint system generator is going to peek `f(_ f: Float)` as
only possible overload candidate because "base" of the call is immutable
and contextual information about argument type is not available yet.
Such leads to incorrect contextual conversion failure diagnostic because
type of the argument is going to resolved as (Int) no matter what.
To workaround that fact and improve diagnostic of such cases we are going
to try and collect all unviable canddidates for a given call and check if
at least one of them matches established argument type before even trying
to re-check argument expression.

Resolves: <rdar://problem/28051973>.

2016-11-15 23:38 UTC, xedin commented
/cc @rudkx

2016-11-28 20:56 UTC, rudkx commented
@swift-ci Please smoke test

2016-11-28 22:10 UTC, rudkx requested changes
A few typos that would be great to fix before merging, but otherwise LGTM.

2016-11-28 22:10 UTC, rudkx commented on lib/Sema/CSDiag.cpp
> +  // Constraint system generator is going to peek `f(_ f: Float)` as
typo: peek instead of pick

2016-11-28 22:10 UTC, rudkx commented on lib/Sema/CSDiag.cpp
> +  // to try and collect all unviable canddidates for a given call and check if
typo: canddidates

2016-11-28 22:10 UTC, rudkx commented on lib/Sema/CSDiag.cpp
> +  // If one of the inviable candidates matches arguments exactly,
typo: inviable

2016-11-28 22:24 UTC, xedin commented
@rudkx Fixed all of the typos (in commit message as well), sorry that this keeps happening...

2016-11-28 22:27 UTC, rudkx commented
@swift-ci Please smoke test and merge.

2016-11-28 23:27 UTC, xedin commented
@rudkx looks like CI which was building macOS crashed :(

2016-11-28 23:29 UTC, rudkx commented
@xedin I'll try kicking it off again in a little while.

2016-11-28 23:29 UTC, rudkx approved these changes

2016-11-29 00:22 UTC, rudkx commented
@swift-ci Please smoke test and merge

2016-11-29 01:01 UTC, merged