[Codable][Sema] Change local bindings to match auto-generated coding keys
swiftlang/swift pull request #58454
Opened 2022-04-27 13:31 UTC by philipturner

When an enum conforms to `Codable` and a case has associated values with specific labels, they can conflict with auto-generated coding keys. The cases of `_0, _1, _2...` are already accounted for by the compiler. Names such as `a0, a1, a2...` are not, resulting in a corrupted compiler state that can crash in either Sema or SILGen. When conflicting keys match values with the same Swift type, the crash happens later on because it slips past an assertion. At SILGen, it results in duplicated debug variables.

```swift
enum Foo: Codable {
  case foo(Int, a0: String)
}
```

The compiler is bound to stop compiling in the cases of `a0, a1, a2...`. This PR makes the compiler emit a correct warning before stopping, by checking for `a0` at the same time as it checks for `_0`. In addition, it adds a validation test that covers all possible permutations of associated values like `_0` or `a0`. Many do not conflict with auto-generated names, and are allowed to compile.

Resolves a crash found in https://github.com/apple/swift/pull/39825#issuecomment-950506828, which was related to a solution for SR-15271.

2022-04-30 20:51 UTC, philipturner commented
CC: @jirid

2022-05-04 03:42 UTC, jirid commented
While this is an improvement over the status quo, I believe we can do even better.

The underscored names are used for the synthesized `CodingKeys`, therefore they appear in serialized data, therefore changing them would break backwards compatibility, and therefore in this case we need to inform the user that they should not be using such names (that's the current behavior).

The `a` prefixed names are on the other hand only used as names for local bindings in pattern matching, therefore we can use different names whenever needed.

I was talking to @CodaFi about this and he suggested prefixing the variable names with a `$` because users cannot use such an identifier but we can internally in the compiler. I believe we should adopt this approach (look for `DerivedConformance::indexedVarDecl`).

2022-05-04 03:42 UTC, jirid commented
While this is an improvement over the status quo, I believe we can do even better.

The underscored names are used for the synthesized `CodingKeys`, therefore they appear in serialized data, therefore changing them would break backwards compatibility, and therefore in this case we need to inform the user that they should not be using such names (that's the current behavior).

The `a` prefixed names are on the other hand only used as names for local bindings in pattern matching, therefore we can use different names whenever needed.

I was talking to @CodaFi about this and he suggested prefixing the variable names with a `$` because users cannot use such an identifier but we can internally in the compiler. I believe we should adopt this approach (look for `DerivedConformance::indexedVarDecl`).

2022-05-04 03:46 UTC, CodaFi requested changes
This approach is not correct because these identifiers are still user accessible and conflicts with generated code often crash later or lead to bizarre hard-to-diagnose runtime issues. We should fix the name generator and accept the behavior break it implies.

2022-08-16 00:16 UTC, closed without merging