[stdlib] Test setting NFC bit for string
swiftlang/swift pull request #58605
Opened 2022-05-01 19:34 UTC by Azoy

2022-05-01 19:34 UTC, Azoy commented
@swift-ci please benchmark

2022-05-03 21:14 UTC, lorentey requested changes
If the new initializers aren't back deployable, but we switch over to using them unconditionally, how will we be able to continue to build code that needs to run on earlier versions of the stdlib?

(Other nitpicks noted below)

2022-05-03 21:14 UTC, lorentey commented on stdlib/public/core/StringObject.swift
> +      isNFC: flags & (0x1 << 1) != 0,
Let's define some names for these bits, instead of using numerical values here.

2022-05-03 21:14 UTC, lorentey commented on lib/SILOptimizer/SILCombiner/SILCombinerApplyVisitors.cpp
>      auto isAscii = Builder.createIntegerLiteral(AI->getLoc(),
This variable probably ought to be renamed to `flags`

2022-05-03 21:14 UTC, lorentey commented on lib/SILOptimizer/Transforms/StringOptimization.cpp
>    auto *isAscii = builder.createIntegerLiteral(loc,
Ditto

2022-05-03 21:14 UTC, lorentey commented on stdlib/public/core/CompilerProtocols.swift
> +    length: Builtin.Word,
`utf8CodeUnitCount` was a mouthful, but it did clarify the expected encoding of the data -- perhaps it'd be worth adding UTF-8 back in this name somewhere.

2022-05-03 21:14 UTC, lorentey commented on stdlib/public/core/CompilerProtocols.swift
> +    length: Builtin.Word,
This could also use a mention of the expected encoding.

2023-08-03 22:48 UTC, closed without merging