Only copy bootstrap legacy layout files when bootstrapping
swiftlang/swift pull request #59010
Opened 2022-05-21 20:50 UTC by etcwilde

We only need to copy the legacy layout file for bootstrapping if we're bootstrapping.

2022-05-21 20:50 UTC, etcwilde commented
@swift-ci please test

2022-05-23 07:26 UTC, eeckstein requested changes

2022-05-23 07:26 UTC, eeckstein commented on stdlib/toolchain/legacy_layouts/CMakeLists.txt
> +if(${BOOTSTRAPPING_MODE} STREQUAL "BOOTSTRAPPING.*")
I believe `STREQUAL` will not work here. It needs to be `MATCHES`.
Did you test this change?

2022-05-23 16:19 UTC, etcwilde commented
Admittedly, not locally. Wrote the patch on a phone.
Yes, it should be `MATCHES`.

2022-05-23 16:19 UTC, etcwilde commented
@swift-ci please test

2022-05-23 18:00 UTC, eeckstein approved these changes
lgtm.
And yes, please test the change locally.

2022-05-23 20:45 UTC, merged