[cxx-interop] Add support for reference counting operations on foreign reference types.
swiftlang/swift pull request #59509
Opened 2022-06-16 21:31 UTC by zoecarver

Based on #59439

2022-06-16 21:38 UTC, zoecarver commented
This is still a bit of a wip: I need to change a lot of these asserts into diagnostics.

2022-06-16 22:56 UTC, hyp commented
Could you also add an execution test that covers the use of the refcounted FRT in a generic context?

Also, perhaps a struct that has stored refcounted FRT in a generic context as well, that would be nice to validate.

2022-06-24 14:01 UTC, rjmccall requested changes

2022-06-30 20:59 UTC, zoecarver commented on lib/IRGen/GenMeta.cpp
> +    }
This PR was out of date. I fixed this in the previous PR that this one is based on. Once I rebase the changes will be reflected.

2022-06-30 21:01 UTC, zoecarver commented on lib/IRGen/GenHeap.cpp
> +    llvm_unreachable("Ref counting should be handled in TypeInfo.");
That's what I would have liked to do, but that would require trafficking an optional ClassDecl to this case. While not ideal, I think my current solution is the best option without doing a major refactor. If you'd prefer me to traffic an optional ClassDecl through, I'm happy to do that instead.

2022-06-30 21:04 UTC, zoecarver commented on stdlib/public/runtime/Casting.cpp
> +  // Foreign reference types don't suppport casting.
Good point. I updated this comment to be more correct and added some radar links.

2022-06-30 21:05 UTC, zoecarver commented on include/swift/AST/ReferenceCounting.h
> +  CxxCustom,
Good call. Done.

2022-06-30 21:07 UTC, zoecarver commented
> This is still a bit of a wip: I need to change a lot of these asserts into diagnostics.

I think it may be better to do this after the fact. Just so that we can break this PR up a bit and make it easier to review. Then we can have a PR to bike shed the diagnostics. WDYT?

2022-06-30 22:49 UTC, zoecarver commented
@swift-ci please smoke test

2022-07-05 23:09 UTC, zoecarver commented
@swift-ci please smoke test Linux

2022-07-21 16:35 UTC, zoecarver commented
@swift-ci please test.

2022-07-21 20:37 UTC, zoecarver commented
@swift-ci please smoke test.

2022-07-21 21:34 UTC, zoecarver commented
@swift-ci please smoke test.

2022-07-22 14:24 UTC, zoecarver commented
@swift-ci please smoke test.

2022-07-23 23:57 UTC, zoecarver commented
@swift-ci please test.

2022-07-24 03:51 UTC, merged