Port swift/Immediate to Windows
swiftlang/swift pull request #5957
Opened 2016-11-28 18:02 UTC by hughbe

- Fix _MSC_VER condition to _WIN32
- Add WIN32_LEAN_AND_MEAN and NOMINMAX
- Fix LoadRuntimeLib to work when compiling with unicode
- Change use of dlsym that is not available on Windows

2016-11-29 04:39 UTC, compnerd requested changes

2016-11-29 04:39 UTC, compnerd commented on lib/Immediate/Immediate.cpp
> +  return (void*)x;
Please use a C++ style cast.

2016-11-29 04:39 UTC, compnerd commented on lib/Immediate/Immediate.cpp
> +          = (ArgOverride)GetProcAddress(static_cast<HMODULE>(stdlib), "_swift_stdlib_overrideUnsafeArgvArgc");
Please use a C++ style cast.  clang-format the line.  It looks pretty long.

2016-11-29 05:27 UTC, CodaFi commented on lib/Immediate/Immediate.cpp
> +static void* loadRuntimeLib(StringRef runtimeLibPathWithName) {
Nit: Why did the pointer star move?

2016-11-29 11:29 UTC, hughbe commented on lib/Immediate/Immediate.cpp
> +          = (ArgOverride)GetProcAddress(static_cast<HMODULE>(stdlib), "_swift_stdlib_overrideUnsafeArgvArgc");
done and formatted

2016-11-29 11:29 UTC, hughbe commented on lib/Immediate/Immediate.cpp
> +  return (void*)x;
done, thanks

2016-11-29 11:29 UTC, hughbe commented on lib/Immediate/Immediate.cpp
> +static void* loadRuntimeLib(StringRef runtimeLibPathWithName) {
accidental, fixed

2016-11-29 17:43 UTC, jrose-apple commented on lib/Immediate/Immediate.cpp
> +  #if defined(_WIN32)
Nitpick: Please leave all preprocessor directives unindented.

2016-11-30 16:31 UTC, hughbe commented on lib/Immediate/Immediate.cpp
> +  #if defined(_WIN32)
fixed, my bad

2016-12-02 10:03 UTC, hughbe commented
@jrose-apple could you trigger testing for this. I assume I should also apply for testing privileges right?

2016-12-02 13:53 UTC, CodaFi commented
@hughbe I got you.

@swift-ci please smoke test.

2016-12-02 16:32 UTC, jrose-apple commented
LGTM when @compnerd's happy with it.

2016-12-07 22:19 UTC, hughbe commented
@compnerd PTAL a when you have time, thanks

2016-12-08 03:00 UTC, compnerd approved these changes

2016-12-08 03:00 UTC, compnerd commented
LGTM

2016-12-08 03:08 UTC, merged