[5.7] Remove the need for `convenience` keyword for delegating actor initializers
swiftlang/swift pull request #59741
Opened 2022-06-28 02:36 UTC by kavon

Cherry-pick of https://github.com/apple/swift/pull/41083

This is part of SE-327 and includes new warnings for the `convenience` keyword appearing and has a fix-it to delete it. Those warnings turn into an error in Swift 6.

2022-06-28 02:37 UTC, kavon commented
@swift-ci please test

2022-06-30 05:44 UTC, kavon commented
@swift-ci please test

2022-06-30 17:36 UTC, kavon commented
@swift-ci please test

2022-06-30 18:11 UTC, DougGregor approved these changes

2022-06-30 18:18 UTC, DougGregor requested changes
I want us to explore the ABI issue in more detail before we commit to this.

2022-06-30 19:50 UTC, DougGregor approved these changes

2022-06-30 23:05 UTC, kavon commented
@swift-ci please test and merge

2022-07-01 01:10 UTC, kavon commented
@swift-ci please test and merge

forgot to add a `REQUIRES: objc_interop`

2022-07-01 02:43 UTC, kavon commented
@swift-ci please test

2022-07-01 16:32 UTC, merged