[stdlib] Properly identify assert.h.
swiftlang/swift pull request #59987
Opened 2022-07-09 20:20 UTC by 3405691582

This should be qualified with GLIBC_INCLUDE_PATH, otherwise it will look
for assert.h relative to the modulemap file, which is likely not what was
intended.

Partially buildfixes OpenBSD and FreeBSD.

2022-07-09 20:21 UTC, 3405691582 commented
cc @egorzhdan

2022-07-10 05:25 UTC, buttaface approved these changes
I don't know enough C modules to know why we're putting this here and not in `SwiftGlibc.h`, but this include path is definitely needed on Android too.

2022-07-11 09:40 UTC, egorzhdan requested changes
> it will look for assert.h relative to the modulemap file, which is likely not what was
intended.

This was intended: the modulemap file is now injected into the Glibc include path (see `getClangInvocationFileMapping`), so the headers can be referenced directly from the modulemap.

This works by calling into Clang driver to extract include paths (`clangToolchain.AddClangSystemIncludeArgs`) and find the include path with Glibc. Perhaps Clang returns incorrect include paths on Android/OpenBSD?

I was actually going to remove `GLIBC_INCLUDE_PATH` from the build entirely to improve portability of the toolchains, I won't do that now to avoid breaking more of Android/OpenBSD, but I don't think we should accumulate more usages of it.

2022-07-11 10:12 UTC, buttaface commented
> Perhaps Clang returns incorrect include paths on Android/OpenBSD?

Yes, that change probably doesn't work when cross-compiling with the Android NDK- looking into it today- though it _does_ work when building natively on Android itself.

> I was actually going to remove GLIBC_INCLUDE_PATH from the build entirely to improve portability of the toolchains, I won't do that now to avoid breaking more of Android/OpenBSD, but I don't think we should accumulate more usages of it.

I agree with removing that path, once we figure this last issue out, and [Android had already disabled the last use of it](https://github.com/apple/swift/blob/main/stdlib/public/Platform/glibc.modulemap.gyb#L52).

2022-07-11 18:59 UTC, buttaface commented
It appears I was wrong to say this is needed on Android, as this line depends on #59846 working, and I had reverted that pull when natively building on Android earlier. After applying that pull again and testing locally, it turns out this pull is not needed on Android, and as you both discussed elsewhere, probably won't be needed on OpenBSD either once [this mistake is corrected](https://github.com/apple/swift/blob/59cc7c49e3e3478a5f5d395b790ea716526d994b/lib/ClangImporter/ClangIncludePaths.cpp#L178).

2022-07-11 19:01 UTC, egorzhdan commented
Awesome, thanks @buttaface for checking that!

2022-07-13 15:07 UTC, closed without merging

2022-07-13 15:24 UTC, buttaface commented
> OpenBSD still needs the underlying VFS changes to make this work

Does #59846 not work for you? It works for me when natively compiling on Android but not when cross-compiling with the NDK, going to look into why.

2022-07-14 14:59 UTC, 3405691582 commented
No -- this requires https://reviews.llvm.org/D129654 plus the `isOSLinux()` change.