[SILOpt] Handle reborrows of owned phis in CanonicalizeOSSALifetime.
swiftlang/swift pull request #60121
Opened 2022-07-19 00:19 UTC by nate-chandler

When canonicalizing lifetime of an owned phi, update liveness for all reborrows any of whose underlying values are transitively borrows of any of the owned phi's underlying values.

rdar://94346482

2022-07-19 00:20 UTC, nate-chandler commented
@swift-ci please test

2022-07-19 06:11 UTC, atrick requested changes
Fantastic code and comments.

My concerns so far (I haven't had time to think of alternatives):

We're repeatedly recomputing phi webs and rediscovering the mapping between all the enclosing scope phis and inner scope phis

The PrunedLiveness abstraction is broken if we allow reborrows. We're either computing SSA liveness or phi-web liveness and that needs to be clear when we handle reborrows. For phi webs, we need to explicitly initialize liveness for all the roots of the phi-web as defs. If we're doing liveness for phi-webs, then we need to make it clear how to use the API correctly.

Along the same lines, we might be visiting uses that aren't dominated by the original def for which we initialized liveness.

We might want a general enclosingScope analysis that maps inner phis to their enclosing scope phis, but I'm not sure we need it yet.

2022-07-20 21:40 UTC, nate-chandler commented on lib/SIL/Utils/OwnershipUtils.cpp
> +/// reborrows of some underlying def if the incoming owned value is itself a
Reworded in terms of {reaching values of, values reaching} the phi of interest.

2022-07-20 21:41 UTC, nate-chandler commented on lib/SIL/Utils/OwnershipUtils.cpp
> +  SmallVector<SILPhiArgument *, 4> ownedArguments;
Renamed this and other variables, hopefully to be clearer.

2022-07-20 21:42 UTC, nate-chandler commented on include/swift/SIL/OwnershipUtils.h
> +bool visitReborrowsOfOwnedPhiArgument(SILPhiArgument *arg,
Great point!  Renamed and dropped the assertion.

2022-07-20 21:42 UTC, nate-chandler commented on lib/SIL/Utils/PrunedLiveness.cpp
> +         op->getOperandOwnership() == OperandOwnership::Reborrow);
Removed this bit, now that we're adding the adjacent reborrow phis to the def use worklist.

2022-07-20 21:42 UTC, nate-chandler commented
@swift-ci please test

2022-07-21 00:14 UTC, nate-chandler commented
@swift-ci please test

2022-07-21 16:30 UTC, atrick approved these changes
Awesome!

2022-07-21 16:35 UTC, nate-chandler commented
@swift-ci please test macOS platform

2022-07-21 22:04 UTC, nate-chandler commented
@swift-ci please test

2022-07-21 22:37 UTC, nate-chandler commented
@swift-ci please test

2022-07-22 14:37 UTC, nate-chandler commented
@swift-ci please test macOS platform

2022-07-22 14:38 UTC, nate-chandler commented
@swift-ci please test linux platform

2022-07-22 18:08 UTC, merged