[CodeComplete] Fix mangling of protocols with primary associated types for cached type relations
swiftlang/swift pull request #60765
Opened 2022-08-25 11:10 UTC by ahoppen

apple/swift#59763 changed `appendType` to no longer be able to mangle `ParameterizedProtocolType`. Instead, we need to call into `appendConstrainedExistential` directly.

This manifested as a SourceKit crash every time you invoke code completion when you import a module that exports a type alias that resolves to a protocol with a primary associated type.

rdar://98623438

2022-08-25 11:10 UTC, ahoppen commented
@swift-ci Please smoke test

2022-08-25 22:25 UTC, rintaro approved these changes
Looks reasonable, but I think @CodaFi should verify this

2022-08-26 00:09 UTC, CodaFi requested changes
This isn't quite correct. The reason this isn't handled by appendType is because you should never see a ParameterizedProtocolType that isn't wrapped in an ExistentialType or in an existential metatype type AST.

2022-08-26 08:11 UTC, ahoppen commented
OK, I’ve decided to use this PR to implement a minimal workaround to avoid the crash on the SourceKit side so the underlying issue can be fixed independently.

2022-08-26 09:22 UTC, ahoppen commented
@swift-ci Please smoke test

2022-08-26 17:02 UTC, CodaFi commented on tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
> +    if (auto MetaTy = Ty->getAs<MetatypeType>()) {
You'll want to look through all layers of metatype you can get.

2022-08-26 17:08 UTC, CodaFi approved these changes

2022-08-26 17:09 UTC, ahoppen commented
@swift-ci Please smoke test

2022-08-26 17:36 UTC, rintaro approved these changes

2022-08-26 22:36 UTC, merged