Move `SWIFT_RETURNS_NONNULL` and `SWIFT_NODISCARD` attributes after the function name for exported functions.
swiftlang/swift pull request #61473
Opened 2022-10-06 18:11 UTC by allevato

More recent versions of Clang (~July 2022) have stricter enforcement of the positioning of attributes; for example, the `nonnull` and `nodiscard` attributes can no longer precede the `extern "C"` specifier and must follow the name of the function (and not the signature of the function) to which they apply.

This appears to just affect functions exported with `extern "C"`; other functions using these attributes can still have these attributes first without issue. 🤷🏻‍♂️ 

I have mixed feelings about the formatting here, but it's what `clang-format` did.

2022-10-06 18:11 UTC, allevato commented
@swift-ci please test

2022-10-06 18:15 UTC, compnerd reviewed
I really am tempted to say that we should ignore clang-format here.  The interleaving already makes the functions more difficult to locate, but the formatting with `^SWIFT_NODISCARD(` just is a whole different level of terrible.

I am also wondering if it makes sense to have a `SWIFT_NONNULL_NODISCARD` to help the flow of the text.

2022-10-06 18:15 UTC, compnerd commented on include/swift/Runtime/HeapObject.h
> +SWIFT_NODISCARD(HeapMetadata const *metadata, size_t requiredSize,
Are you okay clang-format?

2022-10-06 18:22 UTC, allevato commented
> I really am tempted to say that we should ignore clang-format here. The interleaving already makes the functions more difficult to locate, but the formatting with `^SWIFT_NODISCARD(` just is a whole different level of terrible.
> 
> I am also wondering if it makes sense to have a `SWIFT_NONNULL_NODISCARD` to help the flow of the text.

It probably doesn't help that they're wrapped in macros so clang-format doesn't see them as attributes but as... something else.

I don't know how I feel about adding Yet Another Macro™ to this just to make the formatting slightly improved, since if someone needs to add more attributes to a particular function, we're just back to the same situation again.



> This implies that this is occurring only in the C++ code path. Perhaps another, more invasive option, is to introduce an `extern "C"` scope for the functions to avoid interleaving the attributes.
> 
> CC: @etcwilde @bnbarham - they may have valuable insight/opinions given the previous experience with rebranching

I'd be quite happy to do something like that if it ends up cleaner!

2022-10-06 18:45 UTC, compnerd commented
I find it a bit more palatable, but that is just my opinion.  https://github.com/apple/swift/pull/61476

Let us see what the others think.

2022-10-06 21:09 UTC, bnbarham commented
> I find it a bit more palatable, but that is just my opinion. #61476
> 
> Let us see what the others think.

That's a +1 from me. It's ... unfortunate. But the interleaving is quite awful 😅. My main question here is whether or not it's intentional that there's a behavior difference between `extern "C" { ... }` and `extern "C"` on the decl. Ie. it's odd that
> must follow the name of the function (and not the signature of the function) to which they apply
changes in these cases.

If it is intentional then I would prefer @compnerd's PR. Otherwise this seems like the only option, though it would be nice to ignore clang-format here (or have clang-format treat those macros as attributes somehow).

2022-10-06 21:12 UTC, allevato commented
If there aren't any other odd effects from @compnerd's PR, I definitely agree it's the better/cleaner option here.

2022-10-06 21:13 UTC, compnerd commented
I'll try to find out about the behavioural differences and if this is truly intentional.  Once we have that we can decide how to proceed :)

2022-10-07 14:31 UTC, compnerd requested changes
I think that this change is not the right approach.  The problem stems from the fact that the linkage is being intertwined with the attributes due to the macros being mis-ordered.  Please see #61489

2022-10-12 12:01 UTC, TiaMonique approved these changes

2022-10-12 12:01 UTC, TiaMonique commented on include/swift/Runtime/Heap.h
> -SWIFT_RETURNS_NONNULL SWIFT_NODISCARD SWIFT_RUNTIME_EXPORT
include/swift/Runtime/Heap.h

2022-10-12 12:04 UTC, TiaMonique reviewed
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/Heap.h
> -SWIFT_RETURNS_NONNULL SWIFT_NODISCARD SWIFT_RUNTIME_EXPORT
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/HeapObject.h
> -                              size_t requiredSize,
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/HeapObject.h
> -SWIFT_RETURNS_NONNULL SWIFT_NODISCARD SWIFT_RUNTIME_EXPORT
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/HeapObject.h
> -HeapObject* swift_allocEmptyBox();
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/HeapObject.h
> -HeapObject* swift_allocEmptyBox();
allevato:shuffle-clang-attributes

2022-10-12 12:04 UTC, TiaMonique commented on include/swift/Runtime/HeapObject.h
> -HeapObject* swift_allocEmptyBox();
allevato:shuffle-clang-attributes

2022-10-12 12:11 UTC, TiaMonique commented
allevato:shuffle-clang-attributes

2022-11-16 19:05 UTC, compnerd commented
There is a fix up for https://github.com/llvm/llvm-project/issues/58229 (https://reviews.llvm.org/D137979)

2022-11-16 21:29 UTC, allevato commented
Closing this in favor of the Clang fix.

2022-11-16 21:29 UTC, closed without merging