[Demangler] Remove and replace DEMANGLER_ALWAYS_ASSERT
swiftlang/swift pull request #61780
Opened 2022-10-27 23:19 UTC by kastiglione

2022-10-27 23:23 UTC, kastiglione commented
@swift-ci smoke test

2022-10-28 07:41 UTC, al45tair requested changes
I don't think this is the right thing to do. The reason I added the always-assert in the first place is that we were seeing occasional instances of this in the runtime, and we actively _want_ that to crash because it's a bug and we need to track it down.

If it's causing problems for LLDB, where I think I'd agree that we don't want to crash, maybe it should be `ALWAYS_ASSERT_BUT_NOT_IN_LLDB_SOMEHOW`.

2022-10-28 07:42 UTC, al45tair commented
To be clear, we _want_ this to crash in the runtime, and we _want_ it to crash in the compiler. I agree that crashing in LLDB is not desirable.

2022-10-28 15:53 UTC, kastiglione commented
From https://github.com/apple/swift/pull/41452:
> We need this in order to gather relevant information when this situation arises;

Is the information gathering still active? This presentation made me think this assert was temporary and could maybe removed.

> If it's causing problems for LLDB, where I think I'd agree that we don't want to crash, maybe it should be `ALWAYS_ASSERT_BUT_NOT_IN_LLDB_SOMEHOW`.

I'll look into this.

2022-10-28 17:35 UTC, al45tair commented
Fundamentally, if we're hitting this assertion, it means there's a bug, so if you're still seeing it occasionally then we haven't found all of the causes of it yet. It _shouldn't_ be happening.

2022-11-30 20:46 UTC, closed without merging