Remove is_unique invariant we don't guarantee
swiftlang/swift pull request #61791
Opened 2022-10-28 17:03 UTC by meg-gupta

The invariant is checking if the "cached" `isUniquelyReferenced` result is still valid. The compiler can insert copies for lifetime adjustment during optimizations between the time `isUniquelyReferenced` is first "cached" to the invariant, such copies don't escape and don't really matter for COW. In such cases, this invariant will fire.

This PR turns off this invariant.

rdar://100530373

2022-10-28 17:04 UTC, meg-gupta commented
I don't have a unit test for this. This was firing in a few sodlib tests in our repository on certain Linux configurations.

2022-10-28 17:04 UTC, meg-gupta commented
@swift-ci smoke test

2022-10-31 06:46 UTC, eeckstein requested changes
Basically LGTM.
But this should also be removed in `ContiguousArray` and in `Array/ContiguousArray::_reserveCapacityImpl`

2022-11-02 03:15 UTC, meg-gupta commented
I am going to close this PR and address the underlying reason here - https://github.com/apple/swift/pull/61826

2022-11-02 03:15 UTC, closed without merging