[stdlib] Add RISCV64 support
swiftlang/swift pull request #61815
Opened 2022-10-31 03:56 UTC by colemancda

Added support to cross-compile the StdLib for RISCV64.

Resolves [SR-16005](https://bugs.swift.org/browse/SR-16005).

2022-10-31 03:57 UTC, colemancda commented
Rework of #42055 for latest trunk and removes the build preset.

2022-11-01 15:01 UTC, buttaface commented
@compnerd, would you review?

2022-11-01 16:33 UTC, compnerd requested changes

2022-11-01 16:33 UTC, compnerd commented on stdlib/public/runtime/HeapObject.cpp
> +#elif defined(__x86_64__) || defined(__arm64__) || defined(__aarch64__) || defined(_M_ARM64) || defined(__s390x__) || defined(__riscv) || (defined(__powerpc64__) && defined(__LITTLE_ENDIAN__))
Since the arch support is explicitly for `riscv64` rather than using `arch(riscv)`, please ensure that `__xlen` is `64`.

2022-11-01 16:33 UTC, compnerd commented on stdlib/public/stubs/MathStubs.cpp
> +    (defined(__linux__) && defined(__riscv)) || \
Similar

2022-11-02 07:02 UTC, colemancda commented
@compnerd Added requested changes

2022-11-02 14:09 UTC, compnerd approved these changes
Thanks!

2022-11-02 14:09 UTC, compnerd commented
@swift-ci please smoke test

2022-11-02 16:53 UTC, merged

2022-11-02 23:00 UTC, colemancda commented
Added more changes needed for RISCV in https://github.com/apple/swift/pull/61891