[IRGen] Re-introduce TypeLayout strings
swiftlang/swift pull request #62059
Opened 2022-11-11 16:49 UTC by drexin

Layout strings encode the structure of a type into a byte string that can be
interpreted by a runtime function to achieve a destroy or copy. Rather than
generating ir for a destroy/assignWithCopy/etc, we instead generate a layout
string which encodes enough information for a called runtime function to
perform the operation for us. Value witness functions tend to be quite large,
so this allows us to replace them with a single call instead. This gives us the
option of making a codesize/runtime cost trade off.

2022-11-11 16:52 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-11 18:00 UTC, drexin commented
@swift-ci smoke test

2022-11-11 21:45 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-14 22:54 UTC, drexin commented
@swift-ci smoke test

2022-11-15 00:12 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-15 17:10 UTC, drexin commented
@swift-ci smoke test

2022-11-15 19:14 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-15 21:34 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-15 22:45 UTC, drexin commented
@swift-ci smoke test macos

2022-11-15 23:07 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test macos

2022-11-16 17:45 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test macos

2022-11-16 18:02 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test macos

2022-11-16 19:02 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test macos

2022-11-16 19:44 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test macos

2022-11-17 17:49 UTC, aschwaighofer requested changes
LGTM (mostly, besides on MUSTFIX comment)

2022-11-17 17:49 UTC, aschwaighofer commented on lib/IRGen/ScalarTypeInfo.h
> +    return IGM.typeLayoutCache.getOrCreateScalarEntry(asDerived(), T,
[MUST FIX] Missing check.

2022-11-17 17:49 UTC, aschwaighofer commented on lib/IRGen/TypeLayout.cpp
> +    switch (size.getValueInBits()) {
This does not handle i1 (bool).

2022-11-17 17:49 UTC, aschwaighofer commented on stdlib/toolchain/CompatibilityBytecodeLayouts/BytecodeLayouts.h
> +//   I8 = 'c',
Missing (at least) i1.

2022-11-17 17:49 UTC, aschwaighofer commented on stdlib/toolchain/CompatibilityBytecodeLayouts/BytecodeLayouts.h
> +//   I8 = 'c',
I don't think the scalar encoding as is is sufficient. LLVM builtin types are available -- eventually, we need to be able to match/encode the results of `getSpareBitsForType`.

2022-11-28 17:36 UTC, drexin commented on lib/IRGen/ScalarTypeInfo.h
> +    return IGM.typeLayoutCache.getOrCreateScalarEntry(asDerived(), T,
Fixed

2022-11-28 17:37 UTC, drexin commented
@swift-ci smoke test

2022-11-28 18:42 UTC, drexin commented
https://github.com/apple/swift-syntax/pull/1073

@swift-ci smoke test

2022-11-29 19:26 UTC, drexin commented
@swift-ci smoke test

2022-11-29 21:18 UTC, drexin commented
@swift-ci smoke test

2022-11-30 05:05 UTC, merged