[SR-15231] #sourceLocation doesn't recognize CRLF line endings #57553
swiftlang/swift pull request #63071
Opened 2023-01-17 20:48 UTC by grynspan

This fix allows for the presence of a single `\r` character before `\n` in a line containing a `#sourceLocation` directive.

Resolves #57553.

2023-01-17 20:49 UTC, grynspan commented
@swift-ci please test

2023-01-17 21:12 UTC, compnerd approved these changes
Thanks for fixing this!

2023-01-17 22:03 UTC, rintaro approved these changes

2023-01-17 22:47 UTC, grynspan commented
@swift-ci please test macOS

2023-01-17 22:59 UTC, grynspan commented
@swift-ci please test

2023-01-18 09:37 UTC, al45tair requested changes

2023-01-18 09:37 UTC, al45tair commented on lib/Parse/ParseDecl.cpp
> +  if (*LastTokTextEnd == '\r') {
IMO this code should read
```
  while (*LastTokTextEnd == ' ' || *LastTokTextEnd == '\t')
    ++LastTokTextEnd;

  SourceLoc nextLineStartLoc;
  switch (*LastTokTextEnd++) {
  case '\r':
    if (*LastTokTextEnd == '\n')
      ++LastTokTextEnd;
    LLVM_FALLTHROUGH;
  case '\n':
    nextLineStartLoc = Lexer::getSourceLoc(LastTokTextEnd);
    break;
  default:
    diagnose(Tok.getLoc(), diag::extra_tokens_line_directive);
    return makeParserError();
  }
```

That better matches what we do in the lexer (namely, we generally regard `\r`, `\r\n` and `\n` as line endings; there are probably some omissions, but those are bugs IMO).

2023-01-18 09:37 UTC, al45tair commented on test/Parse/line-directive-crlf.swift.gyb.swift
> +}
Rather than just testing `\r\n`, could we please test `\r`, `\r\n` and `\n` here? All of them should work, IMO.

2023-01-18 16:06 UTC, grynspan commented
@swift-ci please test

2023-01-18 18:51 UTC, grynspan commented
@swift-ci please test

2023-01-18 19:02 UTC, al45tair approved these changes

2023-01-18 22:46 UTC, grynspan commented
@swift-ci please test macOS

2023-01-19 15:22 UTC, merged