[5.8][Concurrency] Add include of unistd.h to TaskGroup.cpp
swiftlang/swift pull request #63344
Opened 2023-02-01 08:17 UTC by ktoso

**Description:** This fixes compilation in the SWIFT_CONCURRENCY_TASK_TO_THREAD_MODEL, which was not caught in CI because CI does not verify this configuration. We fixed this on main here: https://github.com/apple/swift/pull/63265/ and should have the same fix on 5.8 to avoid a surprise in case we'd want to use this mode in 5.8.
**Risk:** Low
**Review by:** @DougGregor @drexin 
**Testing:** CI testing
**Original PR:**  https://github.com/apple/swift/pull/63265
**Radar:** rdar://104758975

2023-02-01 14:38 UTC, DougGregor approved these changes

2023-02-01 15:40 UTC, drexin approved these changes

2023-02-01 22:23 UTC, ktoso commented
@swift-ci please test

2023-02-02 18:42 UTC, drexin commented
Hold off on merging this. This is causing some other issues and I am working on a fix.

2023-02-02 18:42 UTC, drexin requested changes
Hold off on merging this. This is causing some other issues and I am working on a fix.

2023-02-06 13:54 UTC, ktoso commented
@swift-ci please test

2023-02-06 13:55 UTC, ktoso commented
This branch now includes @drexin's complete fix for this, so it can be merged.
 
Thank you @drexin for the help here!

2023-02-06 13:56 UTC, ktoso commented
Resolves rdar://104198044

2023-02-06 22:02 UTC, drexin approved these changes

2023-02-06 22:51 UTC, merged