[Sema] Mark VarDecl in capture lists
swiftlang/swift pull request #6490
Opened 2016-12-25 21:44 UTC by modocache

Fixes [SR-2757](https://bugs.swift.org/browse/SR-2757).

Variables in capture lists are treated as 'let' constants, which can result in misleading, incorrect diagnostics. Mark them as such in order to produce better diagnostics.

Alternatively, these variables could be marked as implicit, but that results in other diagnostic problems: capture list variables that are never used produce warnings, but these warnings aren't normally emitted for implicit variables. Other assertions in the compiler also misfire when these variables are treated as implicit.

Another alternative would be to walk up the AST and determine whether the `VarDecl`, but there doesn't appear to be a way to do so.

2016-12-25 23:10 UTC, slavapestov reviewed
Looks good otherwise

2016-12-25 23:10 UTC, slavapestov commented on test/expr/closure/closures.swift
> +  capturedVariable += 1 // expected-error {{left side of mutating operator isn't mutable: 'capturedVariable' is an immutable capture list variable}}
How about just "is an immutable capture"?

2016-12-25 23:27 UTC, modocache commented
Done! Thanks, @slavapestov!! Can't wait for CI to reopen, and for my first commit to Sema :)

2016-12-26 02:09 UTC, rintaro commented on lib/AST/Decl.cpp
> +    if (PBD->getLoc().isInvalid() || PBD->isImplicit() || isCaptureList())
You don't need `PBD` here, you can hoist this out.
Maybe, right after [`if (!isLet()) return;` line](https://github.com/apple/swift/pull/6490/files#diff-18d4a886db0259206b4f3bd502d67c75R3726):
```cpp
// Don't touch capture list
if (isCaptureList()) return;
```

2016-12-26 23:53 UTC, modocache commented
@swift-ci Please smoke test

2016-12-26 23:53 UTC, modocache commented
@swift-ci please smoke test

2016-12-27 07:08 UTC, kostiakoval commented on lib/AST/Decl.cpp
> +  // Don't suggest any fixes for caoture list elements.
:) Spelling. caoture -> capture

2016-12-30 06:10 UTC, CodaFi requested changes

2016-12-30 06:10 UTC, CodaFi commented on include/swift/AST/Decl.h
> +  void setCaptureList(bool captureList = true) {
Since this only seems to be effectively read only, can this setter be removed and the bit set in the constructor?

2016-12-30 19:23 UTC, modocache commented on include/swift/AST/Decl.h
> +  void setCaptureList(bool captureList = true) {
That's a good idea, thanks for the suggestion. Will do!

2017-01-01 17:46 UTC, modocache commented
Thanks for the suggestion to move the `IsCaptureList` parameter to the initializer, @CodaFi! I had to change a lot of initializer callsites, I hope that's OK. I thought about making `IsCaptureList = false` by default, but it doesn't seem like any other Decl classes use default initializer parameters, so I held off.

2017-01-01 21:06 UTC, CodaFi approved these changes

2017-01-04 03:40 UTC, CodaFi commented
@swift-ci please smoke test and merge.

2017-01-04 06:17 UTC, CodaFi commented
Looks like LLDB is calling this constructor and will require an update.  If you want to revert the change I requested to get this merged sooner, I think that would be fine.  Otherwise, see the Linux test logs for the constructor that needs to be updated.

2017-01-04 06:23 UTC, modocache commented
No rush, I'd be happy to update the LLDB callsite as well. Expect an update before Monday.

2017-01-06 02:21 UTC, modocache commented
@swift-ci please smoke test Linux platform

2017-01-06 03:39 UTC, modocache commented
@swift-ci Please test
Please test with following PR: https://github.com/apple/swift-lldb/pull/115

2017-01-06 03:40 UTC, modocache commented
@swift-ci Please test with following PR: https://github.com/apple/swift-lldb/pull/115

2017-01-06 03:40 UTC, modocache commented
@swift-ci please test with following PR: https://github.com/apple/swift-lldb/pull/115

2017-01-06 03:41 UTC, modocache commented
@swift-ci please test with following pull request: https://github.com/apple/swift-lldb/pull/115

2017-01-06 03:42 UTC, modocache commented
Please test with following pull request:
https://github.com/apple/swift-lldb/pull/115

@swift-ci Please test

2017-01-06 04:36 UTC, CodaFi commented
Wonderful ✨ .  Thanks for the secondary patch.

⛵️

2017-01-06 04:36 UTC, merged

2017-01-06 04:37 UTC, modocache commented
Thank you for the reviews and the suggestion to modify the initializer!