[gardening] replace unused closure parameters with '_' in stdlib source
swiftlang/swift pull request #6522
Opened 2017-01-01 02:03 UTC by jpsim

Replacing unused parameters with `_` clearly communicates the intent that this parameter was unused on purpose and helps avoid bugs.

2017-01-02 06:06 UTC, karwa commented on stdlib/public/SDK/Foundation/NSDictionary.swift
> +       _) in
can you remove the newline since the signature is now shorter?

2017-01-02 06:07 UTC, karwa commented on stdlib/public/SDK/Foundation/NSDictionary.swift
> +       _) in
and here

2017-01-03 21:53 UTC, CodaFi requested changes

2017-01-03 21:53 UTC, CodaFi commented on stdlib/public/SDK/Foundation/NSDictionary.swift
>        builder.add(
This should let you move these parameter lists inline with the open brace.

2017-01-03 21:53 UTC, CodaFi commented on stdlib/public/SDK/Foundation/NSSet.swift
> +      (anyMember: Any, _) in
Ditto

2017-01-04 00:30 UTC, CodaFi approved these changes

2017-01-04 00:30 UTC, CodaFi commented
@swift-ci please smoke test.

2017-01-04 03:10 UTC, CodaFi commented
⛵️

2017-01-04 03:10 UTC, merged