[SymbolGraphGen] skip class types when handling protocol expansions
swiftlang/swift pull request #66012
Opened 2023-05-19 00:13 UTC by QuietMisdreavus

Resolves rdar://109418762

When a protocol has a class inheritance requirement, and a conformance to that protocol is added via an extension, the code that checks for additional protocols currently crashes due to assuming it will only need to handle protocols and protocol compositions. This PR updates that code to gracefully handle class inheritance requirements by simply skipping them - that information is already handled elsewhere.

2023-05-19 00:13 UTC, QuietMisdreavus commented
@swift-ci Please smoke test

2023-05-19 03:35 UTC, theMomax approved these changes
Looks good, thanks for fixing this!

It would be great if you could add a check in the test that connects the name of the symbols with their mangled name or at least annotate source and target with the readable names. Otherwise I can only guess what the target/source is.

2023-05-19 13:00 UTC, slavapestov requested changes
You can also have a BoundGenericClassType or ParameterizedProtocolType:

```
protocol P: C<Int> {}
protocol Q: Iterator<Int> {}
```

But if you want a flat list of inherited protocols without the superclass or any sugar, call ProtocolDecl::getInheritedProtocols() instead of getInherited().

Similarly to get the “semantic” protocols for an ExtensionDecl, call getLocalConformances() and then getProtocol() on each element.

2023-05-19 16:54 UTC, QuietMisdreavus commented
It looks like ParameterizedProtocolTypes still resolve down to ProtocolDecls via the `getAnyNominal` that's called right before the code i added. However, that's a good catch on BoundGenericClassType. I'll take a look at the functions you mentioned. Thanks!

2023-05-19 22:57 UTC, QuietMisdreavus commented
@swift-ci Please smoke test

2023-05-20 01:35 UTC, slavapestov approved these changes

2023-05-22 15:27 UTC, merged