[cherry-pick][release/5.9] [Build] Build libcxx on lldb ASAN/UBSAN bots
swiftlang/swift pull request #66079
Opened 2023-05-23 16:30 UTC by Michael137

The preset for ubsan/asan buildbots include the
`buildbot_incremental_base` preset, which builds/runs tests. But the tests now require libcxx to be built since https://github.com/apple/swift/pull/66018

(cherry picked from commit 7893c8e69b25bab559f7942ae82387b47c4e1928)

2023-05-23 16:31 UTC, Michael137 commented
@swift-ci test

2023-05-26 15:46 UTC, adrian-prantl approved these changes

2023-05-26 15:48 UTC, adrian-prantl commented on utils/build-presets.ini
> +libcxx
Should this be more targeted at LLDB presets?

2023-05-26 15:49 UTC, adrian-prantl commented on utils/build-presets.ini
> +libcxx
,lldb_asan_ubsan

2023-05-26 15:49 UTC, adrian-prantl requested changes
lldb_asan_ubsan

2023-05-27 12:55 UTC, Michael137 commented
preset=buildbot_incremental,lldb_asan_ubsan
@swift-ci Please test with preset macOS platform

2023-05-27 12:56 UTC, Michael137 commented
preset=buildbot_incremental,lldb_asan_ubsan
@swift-ci Please test with preset macOS

2023-05-28 14:57 UTC, Michael137 commented
@swift-ci test

2023-05-30 13:32 UTC, Michael137 commented
preset=buildbot_incremental,lldb_asan_ubsan
@swift-ci Test macOS Platform with preset

2023-05-30 16:12 UTC, adrian-prantl approved these changes

2023-05-30 16:12 UTC, merged