Corrects wrong insertion point for 'await' at uncovered 'async' site.
swiftlang/swift pull request #66732
Opened 2023-06-17 07:33 UTC by Rajveer100

Fixes Issue #65913

2023-06-17 07:35 UTC, Rajveer100 commented
@YOCKOW @AnthonyLatsis

2023-06-17 11:12 UTC, AnthonyLatsis requested changes
Please add a test. As is, this change will most likely break some tests, so I'm going to trigger CI for you to inspect the failures.

2023-06-17 11:12 UTC, AnthonyLatsis commented
@swift-ci please smoke test macOS

2023-06-17 11:22 UTC, Rajveer100 commented
> Please add a test. As is, this change will most likely break some tests, so I’m going to trigger CI for you to inspect the failures.

Well, I do suspect that too as we must probably handle the cases separately for each type of expression in an async await call expression (ex. `tryExpr`, `closure`, `_`, etc), let's see!

Regarding tests, I presume there would be cases as mentioned above, let me know if I missed out any!

2023-06-17 11:34 UTC, Rajveer100 commented on lib/Sema/TypeCheckEffects.cpp
> +      .fixItInsert(awaitInsertLoc, StringRef(awaitInsertString))
If you meant a normal variable declaration (i.e. `var _ = asyncFunc()`, we would get the following error:

```
error: 'async' call in a function that does not support concurrency
```

It actually doesn't provide a fixit to add the `await` keyword.

2023-06-19 10:35 UTC, Rajveer100 commented
After some debugging I found that only these two lines by themselves are causing an issue:

`auto anchorVar = dyn_cast<VarDecl>(anchorDecl->getDecl());`

Regarding the tests itself, before they are even checked, there seems to be internal error (probably memory error/bad access/similar), hence shows 'Please submit a bug report' as `stderr`.

2024-02-20 18:18 UTC, closed without merging

2024-02-20 18:27 UTC, AnthonyLatsis commented
For the future, don’t be shy to ping  someone once every 2 weeks or so in PRs if you want a review. We sometimes *do* forget to get back to stuff.

2024-02-20 18:32 UTC, Rajveer100 commented
> For the future: Don’t be shy to ping someone once every 2 weeks or so in PRs if you want a review. We sometimes _do_ forget to get back to stuff.

Indeed! 

PS: By the way I am excited for GSoC 2024, hoping to get land proposals just like last year and getting accepted this time!