[QoI] Add diagnostic for unused literal values
swiftlang/swift pull request #6703
Opened 2017-01-10 07:37 UTC by jtbandes

Resolves [SR-3522](https://bugs.swift.org/browse/SR-3522).

Best demonstrated with test cases:

```swift
func testUnusedLiterals_SR3522() {
  42 // expected-warning {{integer literal is unused}}
  2.71828 // expected-warning {{floating-point literal is unused}}
  true // expected-warning {{boolean literal is unused}}
  false // expected-warning {{boolean literal is unused}}
  "Hello" // expected-warning {{string literal is unused}}
  "Hello \(42)" // expected-warning {{string literal is unused}}
  #file // expected-warning {{#file literal is unused}}
  (#line) // expected-warning {{#line literal is unused}}
  #column // expected-warning {{#column literal is unused}}
  #dsohandle // expected-warning {{#dsohandle literal is unused}}
  __FILE__ // expected-error {{__FILE__ has been replaced with #file in Swift 3}} expected-warning {{#file literal is unused}}
  __LINE__ // expected-error {{__LINE__ has been replaced with #line in Swift 3}} expected-warning {{#line literal is unused}}
  __COLUMN__ // expected-error {{__COLUMN__ has been replaced with #column in Swift 3}} expected-warning {{#column literal is unused}}
  __DSO_HANDLE__ // expected-error {{__DSO_HANDLE__ has been replaced with #dsohandle in Swift 3}} expected-warning {{#dsohandle literal is unused}}

  nil // expected-error {{'nil' requires a contextual type}}
  #fileLiteral(resourceName: "what.txt") // expected-error {{could not infer type of file reference literal}} expected-note {{}}
  #imageLiteral(resourceName: "hello.png") // expected-error {{could not infer type of image literal}} expected-note {{}}
  #colorLiteral(red: 1, green: 0, blue: 0, alpha: 1) // expected-error {{could not infer type of color literal}} expected-note {{}}
}
```

### Implementation note

Since some literals are translated to constructor calls during CSApply, before `checkIgnoredExpr`, I just dug into the implicit call to get the LiteralExpr out. 🤢 This is kind of gross, and someone should let me know if they can come up with a better way of doing it...

2017-01-10 07:37 UTC, jtbandes commented
@swift-ci please smoke test

2017-01-10 07:51 UTC, jtbandes commented
@swift-ci please smoke test

2017-01-10 17:33 UTC, practicalswift commented
Great!

2017-01-10 17:41 UTC, DougGregor requested changes
Thanks for working on this! I suggest use of `ExprNodes.def` to future-proof this code, lest we make more easy targets for @practicalswift in the future.

2017-01-10 17:41 UTC, DougGregor commented on include/swift/AST/DiagnosticsSema.def
> +        "%0 literal is unused", (StringRef))
We often use `%select{}` for this, so all of the text of the warning is visible in the .def file, but it's not critical.

2017-01-10 17:41 UTC, DougGregor commented on lib/Sema/TypeCheckStmt.cpp
> +    default:
If ever we add a new literal kind, we're going to forget to update this code and crash here. Idea: add a `LITERAL_EXPR` X-macro to `ExprNodes.def` and use it to mark the (non-abstract) literal expressions. Then you can

  #define LITERAL_EXPR(Id, Parent)
  #define ABSTRACT_EXPR(Id, Parent)
  #define EXPR(Id, Parent) case ExprKind::Id:
  #include "swift/AST/ExprNodes.def"
    llvm_unreachable("Not a literal expression");

in your switch statement to get all of the non-literal expression kinds listed, and drop the `default` clause. When someone adds a new literal kind, they'll get a warning on this incomplete switch.

2017-01-10 17:47 UTC, jtbandes commented on include/swift/AST/DiagnosticsSema.def
> +        "%0 literal is unused", (StringRef))
Yeah, I didn't see a great value that I could pass in for the select. But maybe I can out the literal descriptions in ExprNodes.def too.

How will folks remember to add their hypothetical new LITERAL_EXPR in ExprNodes?

2017-01-10 18:14 UTC, jrose-apple commented
My contribution is that we should have some kind of RewrittenExpr some day that has both the syntactic and semantic form of an expression that gets significantly rewritten during type-checking. Or perhaps the right answer is mappings between the pre-type-checked AST and the post-type-checked AST. Either way, digging out a LiteralExpr is fine for now; we do it elsewhere as well.

2017-01-11 00:30 UTC, slavapestov commented
@jrose-apple Even better would be for the output of the type checker to be a set of lookup tables that store resolved overloads, required type conversions and the types themselves of the AST nodes. Rewriting the AST or making new AST nodes during type checking shouldn't be a thing at all. :-)

2017-01-11 01:10 UTC, jtbandes commented
@slavapestov Well, the literal will still need to be converted to a constructor call at some point, right? I guess it could happen after type checking though.

2017-01-11 04:44 UTC, jtbandes commented
@DougGregor Thanks for the feedback. I've updated the PR to include a LITERAL_EXPR macro used in ExprNodes.def. As mentioned above I didn't have a great way of using %select short of defining a new enum to be used for this purpose only, so I left it as a StringRef for now.

@swift-ci please smoke test

2017-01-11 06:43 UTC, slavapestov commented
The change LGTM. Doug still needs to take a look; he can merge it if it looks ok.

2017-01-12 00:36 UTC, DougGregor approved these changes

2017-01-12 00:36 UTC, DougGregor commented on include/swift/AST/DiagnosticsSema.def
> +        "%0 literal is unused", (StringRef))
I agree that `%select{}` wouldn't add anything here.

2017-01-12 00:36 UTC, DougGregor commented on lib/Sema/TypeCheckStmt.cpp
> +      llvm_unreachable("Not a literal expression");
Much better, thank you! Now the warning will help us avoid a screw-up if we go add a new literal kind.

2017-01-12 00:37 UTC, merged