[Diagnostics] Display correct debug note for compound references typo suggestions
swiftlang/swift pull request #6715
Opened 2017-01-10 23:15 UTC by OscarSwanros

This PR tries to address the issue where functions with multiple arguments would just be diagnosed incorrectly ignoring their attributes.

Resolves [SR-3254](https://bugs.swift.org/browse/SR-3254).

2017-01-10 23:16 UTC, OscarSwanros commented
@swift-ci Please smoke test

2017-01-10 23:58 UTC, modocache reviewed
This looks pretty good to me! Just needs a few code style changes. Assuming the tests pass, I think this could be merged -- but I'll leave it to someone more familiar with this part of the codebase to approve the pull request.

2017-01-10 23:58 UTC, modocache commented on lib/Sema/TypeCheckNameLookup.cpp
> +diagnoseTypoCorrection(TypeChecker &tc, DeclNameLoc loc, ValueDecl *decl, FunctionRefKind refKind) {
nit-pick: The style guide for C++ in Swift projects is a 80 character column width. You should format this like so:

```cxx
diagnoseTypoCorrection(TypeChecker &tc,
                       DeclNameLoc loc,
                       ValueDecl *decl,
                       FunctionRefKind refKind) {
```

Same goes for the line of code below this one: you'll need to split it across two lines for it to fit within 80 characters.

2017-01-10 23:58 UTC, modocache commented
@swift-ci please smoke test

2017-01-11 00:01 UTC, OscarSwanros commented on lib/Sema/TypeCheckNameLookup.cpp
> +diagnoseTypoCorrection(TypeChecker &tc, DeclNameLoc loc, ValueDecl *decl, FunctionRefKind refKind) {
Oh, thanks! Will update accordingly.

2017-01-11 00:06 UTC, OscarSwanros commented
@modocache updated with code-style comments. Thanks for the eyes on this!

2017-01-11 04:54 UTC, CodaFi requested changes

2017-01-11 04:54 UTC, CodaFi commented on lib/Sema/TypeCheckNameLookup.cpp
> +  auto name = refKind == FunctionRefKind::Compound ? decl->getFullName() :
LLVM style moves the colon to a new line in-line with the else condition and aligns it with the question mark.

2017-01-11 04:54 UTC, CodaFi commented on test/Sema/compound_references.swift
> +let f = foo(_:) // expected-error {{use of unresolved identifier 'foo'}}
Please remove this file and add these tests to `Sema/typo_correction.swift` (sans * on the `expected-note`).

2017-01-11 04:57 UTC, CodaFi commented on lib/Sema/TypeCheckNameLookup.cpp
> +                       DeclNameLoc loc,
You don't necessarily have to fold the entire signature over, just those that go over the line-limit.  If it makes it easier, you can run `clang-format` with the default LLVM style to have it wrap these for you.

2017-01-11 16:40 UTC, OscarSwanros commented
@CodaFi Fixed your comments. Thanks!

2017-01-14 18:32 UTC, CodaFi requested changes

2017-01-14 18:32 UTC, CodaFi commented on test/Sema/typo_correction.swift
> +foo(x: Int) {} // expected-note {{did you mean 'foo(x:)'?}}
This doesn't test the part of the diagnostic you're interested in.

2017-01-14 18:32 UTC, CodaFi commented on lib/Sema/TypeCheckNameLookup.cpp
> +                                                   : decl->getName();
Here you must add the quotes back or it'll fall any existing typo correction tests that rely on it.

2017-01-14 18:32 UTC, CodaFi commented on lib/Sema/TypeChecker.h
> +                          FunctionRefKind refKind = FunctionRefKind::Unapplied);
I'm still not 100% sure this is the right type for this.  For names that aren't function references that go through typo correction this is kind of nonsensical.

2017-01-19 00:14 UTC, OscarSwanros commented on lib/Sema/TypeChecker.h
> +                          FunctionRefKind refKind = FunctionRefKind::Unapplied);
Is there any other type that would work in this case?

2017-06-01 17:16 UTC, CodaFi commented
@OscarSwanros What's the status of this pull request?  If you're still interested in this bug fix, could you rebase this pull request and give me a ping?

2017-07-12 17:52 UTC, CodaFi commented
This patch has fallen behind after a month.  @OscarSwanros feel free to reopen this when you find the time.

2017-07-12 17:52 UTC, closed without merging

2017-07-12 17:58 UTC, OscarSwanros commented
Oh, sorry @CodaFi — have been swamped and missed your notification. Will try to find the time soon.