[5.9][build] Make sure SPM is built with the forked clang, not the host clang
swiftlang/swift pull request #67249
Opened 2023-07-12 12:40 UTC by finagolfin

Cherrypick of #64629

__Explanation:__ SPM was built with the freshly-built Swift toolchain, including the Swift-forked clang, for years, but a change in apple/swift-package-manager#5894 late last year inadvertently switched it to be built with the system clang used to natively build the Swift compiler, ie `self.toolchain.cc` in `build-script`. That passed the CI but caused problems when cross-compiling SPM on my daily Android CI, as the system clang is only meant for native compilation- for example, [we use the freshly-built Swift-forked clang for the native host by default when cross-compiling the Swift compiler itself](https://github.com/apple/swift/blob/80e4e0465c76749dfc4ec45405ce1588d739ec76/utils/build-script-impl#L1773)- so I've been using [this patch for the last seven months on my Android CI](https://github.com/finagolfin/swift-android-sdk/commit/8bb330b216c8af01e046bab35eb7f492d0842f98#diff-1d2c5fe1e8bb2625975dc65af9af541252788b229ecadc07ee12905499fcbc51R24).

__Scope:__ Only affects the C/C++/asm files built as part of SwiftPM, particularly when cross-compiled

__Issue:__ None

__Risk:__ low, as this only affects compilation of non-Swift portions of SPM itself

__Testing:__ Passed all CI on trunk and I've been using this on my Android CI since last year

__Reviewer:__ @etcwilde

2023-07-12 12:46 UTC, finagolfin commented
@kateinoigakukun, would you run the CI on this?

2023-07-17 19:04 UTC, al45tair requested changes
We’re going to revert the original as it’s broken the SwiftPM option on build-script.

2023-07-25 23:44 UTC, finagolfin commented
This has been reapplied to trunk.

@bnbarham, please run the CI on this again.

2023-07-25 23:49 UTC, bnbarham commented
It's already passed, but I can run again since https://github.com/apple/swift-package-manager/pull/6729 may have caused changes.

2023-07-25 23:49 UTC, bnbarham commented
@swift-ci please test

2023-07-26 07:47 UTC, finagolfin commented
@al45tair, please remove the request whenever you think this is safe to go in.

If there are no further problems on trunk, do you think we can get this into 5.8 also? We'd probably need to get your SPM change in there too.

2023-07-26 11:08 UTC, al45tair commented
5.9 should be good to go in now.

2023-07-26 11:08 UTC, al45tair approved these changes

2023-07-26 11:39 UTC, finagolfin commented
@etcwilde, ready for merge.

2023-07-28 14:05 UTC, finagolfin commented
@tomerd, ready to go.

2023-07-28 16:22 UTC, tomerd approved these changes

2023-07-28 16:24 UTC, merged