[5.8][build] Make sure SPM is built with the forked clang, not the host clang
swiftlang/swift pull request #67328
Opened 2023-07-17 09:23 UTC by finagolfin

Cherrypick of #64629

__Explanation:__ SPM was built with the freshly-built Swift toolchain, including the Swift-forked clang, for years, but a change in apple/swift-package-manager#5894 late last year inadvertently switched it to be built with the system clang used to natively build the Swift compiler, ie `self.toolchain.cc` in `build-script`. That passed the CI but caused problems when cross-compiling SPM on my daily Android CI, as the system clang is only meant for native compilation- for example, [we use the freshly-built Swift-forked clang for the native host by default when cross-compiling the Swift compiler itself](https://github.com/apple/swift/blob/80e4e0465c76749dfc4ec45405ce1588d739ec76/utils/build-script-impl#L1773)- so I've been using [this patch for the last seven months on my Android CI](https://github.com/finagolfin/swift-android-sdk/commit/8bb330b216c8af01e046bab35eb7f492d0842f98#diff-1d2c5fe1e8bb2625975dc65af9af541252788b229ecadc07ee12905499fcbc51R24).

__Scope:__ Only affects the C/C++/asm files built as part of SwiftPM, particularly when cross-compiled

__Issue:__ None

__Risk:__ low, as this only affects compilation of non-Swift portions of SPM itself

__Testing:__ Passed all CI on trunk and I've been using this on my Android CI since last year

__Reviewer:__ @etcwilde

2023-07-17 09:25 UTC, finagolfin commented
@kateinoigakukun, would you run the CI on this?

2023-07-17 19:03 UTC, al45tair requested changes
We’re going to revert the original as it’s broken the SwiftPM option on build-script.

2023-07-24 17:55 UTC, etcwilde commented
@swift-ci please test macOS

2023-07-26 11:38 UTC, finagolfin commented
@al45tair, what about this one? I can submit your SPM change for 5.8 too, then this should be fine.

2023-07-26 12:33 UTC, al45tair commented
Yeah, the SwiftPM change needs cherry picking first. I was going to do that later on today (I'm build wrangler at the moment so I'm busy doing that right now).

2023-07-28 11:18 UTC, finagolfin commented
@al45tair, I can submit that 5.8 SPM pull with your commit for you if you're busy, just let me know.

2023-07-28 12:29 UTC, al45tair commented
The cherry pick of that change is here: https://github.com/apple/swift-package-manager/pull/6754

2023-07-31 17:08 UTC, finagolfin commented
@egorzhdan, one last CI run and we can get this in.

2023-07-31 17:50 UTC, al45tair approved these changes

2023-07-31 17:51 UTC, al45tair commented
I don't think we need a CI run so much as a branch manager to approve it. @tomerd you can do that I believe.

2023-07-31 18:45 UTC, finagolfin commented
@al45tair, this pull has not been run through the CI since your SPM pull was merged into 5.8 before the weekend, which is why I suggested it.

2023-08-01 16:52 UTC, al45tair commented
@swift-ci Please test

2023-08-01 17:24 UTC, finagolfin commented
Linux CI failed when checking out the source, it seems super flaky this week.

2023-08-01 18:07 UTC, al45tair commented
@swift-ci Please test Linux platform

2023-08-01 22:36 UTC, finagolfin commented
@bnbarham, one last linux CI run?

2023-08-02 00:18 UTC, bnbarham commented
@swift-ci Please test Linux platform

2023-08-02 12:13 UTC, finagolfin commented
@egorzhdan, one more linux CI run, please.

2023-08-02 12:45 UTC, finagolfin commented
Whoo, it didn't crash at source checkout this time. 😄

2023-08-04 10:29 UTC, tomerd approved these changes

2023-08-04 10:40 UTC, merged