[Driver] SR-3175: Include the terminating signal number in the message of -parseable-output
swiftlang/swift pull request #6748
Opened 2017-01-12 02:39 UTC by matthewcarroll

Add the signal number of the terminated task to the output of -parseable-output. The new key is "signal".
https://bugs.swift.org/browse/SR-3175

In this commit, example output of `swiftc -Xfrontend -debug-crash-immediately` is:

{
  "kind": "signalled",
  "name": "compile",
  "pid": 32822,
  "output": "0  swift ...

  "error-message": "Illegal instruction: 4",
  "signal": 4
`<unknown>:0: error: unable to execute command: Illegal instruction: 4`
`<unknown>:0: error: compile command failed due to signal 4 (use -v to see invocation)`
}

2017-01-12 02:58 UTC, CodaFi requested changes

2017-01-12 02:58 UTC, CodaFi commented on include/swift/Basic/TaskQueue.h
> +  /// \param Signal the terminating signal number
As @jrose-apple pointed out in the linked SR, this should mention that it is not available on all platforms (or that is is specifically available on Unix-likes that use that particular implementation)

2017-01-12 02:58 UTC, CodaFi commented on include/swift/Basic/TaskQueue.h
> +                                             StringRef Output, StringRef Errors, void *Context, int Signal)>
This should probably be `Optional<int>`, as the [callsite in the generic queue](https://github.com/apple/swift/blob/master/lib/Basic/Default/TaskQueue.inc#L116) needs updating.

2017-01-12 17:16 UTC, jrose-apple commented
To add to @CodaFi's review, this does need a test. I suggest changing test/Driver/crash.swift to check for *some* signal—not a particular one, which may differ between platforms—using a [FileCheck regex](http://www.llvm.org/docs/CommandGuide/FileCheck.html#filecheck-expressions) like `{{-[0-9]+}}`.

2017-01-12 23:05 UTC, matthewcarroll commented
Jordan and Robert,

I made the Signal parameter Optional in `TaskSignalledCallback`, updated the header doc to say that the signal may not be available on all platforms, added a test to verify that the signal number is emitted, and added documentation for the new "signal" key emmited in the message of the driver output.

2017-01-13 18:52 UTC, matthewcarroll commented
see #6787

2017-01-13 18:52 UTC, closed without merging