Mark several C macros imported from <float.h> as deprecated.
swiftlang/swift pull request #6796
Opened 2017-01-13 22:35 UTC by stephentyrone

These macros all have straightforward replacements in terms of static properties on FloatingPoint or BinaryFloatingPoint. It is necessary to add 1 in a few places because of differences between how C and Swift count significand bits and normalize the significand, but this is expected to have minimal impact on code in practice (and when it does have impact, using the Swift definition is generally simpler).

2017-01-13 23:08 UTC, stephentyrone commented
@swift-ci Please test

2017-01-13 23:28 UTC, moiseev requested changes
A few nitpicks. Overall a :shipit:.

2017-01-13 23:28 UTC, moiseev commented on stdlib/public/Platform/Darwin.swift.gyb
> +%for type in ["Float","Double","Float80"]:
May I suggest:

```python
for type, prefix in [('Float', 'FLT'), ('Double', 'DBL'), ('Float80', 'LDBL')]:
```

2017-01-13 23:28 UTC, moiseev commented on stdlib/public/Platform/Darwin.swift.gyb
> +//  significand in [0.5, 1), but Swift (follwing IEEE 754) considers the
`s/follwing/following`

2017-01-13 23:28 UTC, moiseev commented on stdlib/public/Platform/Darwin.swift.gyb
> +% implicit = "implicit "
I don't see `${implicit}` being used anywhere. Does it belong in the comment?

2017-01-13 23:28 UTC, moiseev commented on test/stdlib/FloatConstants.swift
> +_ = LDBL_MANT_DIG // expected-warning {{is deprecated}}
Shouldn't it be surrounded by `#if arch(i386) || arch(x86_64) ... #endif`?

2017-01-13 23:29 UTC, moiseev commented
Also, could you please mention the radar (<rdar://problem/27871465>) in the commit message?

2017-01-14 01:32 UTC, stephentyrone commented
@swift-ci please test

2017-01-14 01:57 UTC, moiseev approved these changes

2017-01-14 02:33 UTC, merged

2017-01-14 19:27 UTC, gparker42 commented
Reverting in #6817. The FloatConstants test is failing on iOS. 

The test is incorrectly written for architectures that aren't i386 or x86_64; the verifier still expects the long double warnings and (correctly) doesn't get them.