[CMake] Use add_custom_command_target for copying std.apinotes
swiftlang/swift pull request #68499
Opened 2023-09-13 21:43 UTC by rintaro

`COMMAND` for `add_custom_target` are ["always considered out of date"](https://cmake.org/cmake/help/latest/command/add_custom_target.html) and executed every time. Because of that, targets depends on that were always marked "dirty". Use `add_custom_command_target` instead.

2023-09-13 21:43 UTC, rintaro commented
@swift-ci Please smoke test

2023-09-13 21:49 UTC, bnbarham approved these changes

2023-09-14 12:14 UTC, egorzhdan approved these changes
Thank you!

2023-09-14 23:50 UTC, rintaro commented on stdlib/public/Cxx/std/CMakeLists.txt
> +    OUTPUT "${output_dir}/std.apinotes"
This should be after `COMMAND` lines

2023-09-15 17:13 UTC, rintaro commented
@swift-ci Please smoke test

2023-09-15 17:24 UTC, bnbarham commented on stdlib/cmake/modules/SwiftSource.cmake
> +    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${file_path}.tmp" "${file_path}")
Could we just use `GENERATE` here?
```
file(GENERATE OUTPUT "${file_path}"
     CONTENT "'${source_files_quoted}'")
```

2023-09-15 17:39 UTC, rintaro commented on stdlib/cmake/modules/SwiftSource.cmake
> +    COMMAND ${CMAKE_COMMAND} -E copy_if_different "${file_path}.tmp" "${file_path}")
Nice! I didn't know `file(GENERATE`.

2023-09-15 17:39 UTC, rintaro commented
@swift-ci Please smoke test

2023-09-15 17:51 UTC, etcwilde approved these changes

2023-09-15 17:52 UTC, bnbarham approved these changes
Nice!

2023-09-15 17:52 UTC, compnerd commented on stdlib/cmake/modules/SwiftSource.cmake
> +        set(command_copy_interface_file
@DougGregor and I spoke about this - we need to build things in two forms, not just copy the swift interfaces.

2023-09-15 17:54 UTC, compnerd requested changes
Please drop the static swift interfaces or build the libraries appropriately.

2023-09-15 18:01 UTC, bnbarham commented
> Please drop the static swift interfaces or build the libraries appropriately.

Does that really need to be fixed in this PR? This is just fixing up rebuilds.

2023-09-15 20:48 UTC, rintaro commented
@swift-ci Please smoke test

2023-09-15 21:11 UTC, rintaro commented
```
CMake Error: Files to be generated by multiple different commands: "/Users/ec2-user/jenkins/workspace/swift-PR-macos-smoke-test/branch-main/build/buildbot_incremental/swift-macosx-x86_64/stdlib/public/Cxx/fba1e895a41a8251cfd70af7b678bc1b1e2ae381.txt"
```
This was because the function is called for each stdlib platform/arch , but the file name doesn't take those into account. So use `copy_if_different` instead.

2023-09-15 23:52 UTC, rintaro commented
> Please drop the static swift interfaces or build the libraries appropriately.

This is really not in the scope of this PR. This PR is only fixing the build issue. If the copying `.swiftinterface` is a problem, that should be fixed separately.

2023-09-15 23:52 UTC, merged