[swift-inspect]  Add an option to print mangled names while dumping generic metadata.
swiftlang/swift pull request #69488
Opened 2023-10-29 01:41 UTC by w6sec

This adds `--mangled` option to print mangled names while dumping generic metadata. We also cross-check to make sure pre-specialized generic metadata strictly exists in the `DATA`, `AUTH`, or `TEXT` segments of the images, and report on errors.

2023-10-29 14:03 UTC, w6sec commented
@swift-ci please test

2023-10-30 13:27 UTC, mikeash requested changes

2023-10-30 13:27 UTC, mikeash commented on tools/swift-inspect/Sources/swift-inspect/RemoteMirror+Extensions.swift
> +                           else { swift_reflection_copyDemangledNameForTypeRef(self, typeref) }
This is a bit awkward. What do you think about having a single `swift_reflection_copyNameForTypeRef` with a `mangled` parameter instead? We need to keep the old entrypoint around for other clients, but the new one could handle both cases.

2023-10-30 13:27 UTC, mikeash commented on tools/swift-inspect/Sources/swift-inspect/Operations/DumpGenericMetadata.swift
> +        print("Error: Following prespecialized metadata is not found in any DATA or AUTH segments")
```suggestion
        print("Error: the following metadata was not found in any DATA or AUTH segments, may be garbage")
```

2023-10-31 06:40 UTC, w6sec commented
@swift-ci please test

2023-10-31 15:27 UTC, w6sec commented
@swift-ci please test macOS platform

2023-10-31 18:29 UTC, mikeash approved these changes

2023-10-31 21:15 UTC, w6sec commented
@swift-ci please test macOS platform

2023-11-01 01:39 UTC, merged