[5.10][Concurrency] Isolated `static let`s are not safe to access across actors.
swiftlang/swift pull request #69607
Opened 2023-11-02 14:38 UTC by hborla

* **Explanation**: The rule to allow accessing isolated `let`s synchronously across actors was being applied to `static` variables. However, `static let` variables are initialized upon first access, so synchronously accessing them across actors can lead to data races.
* **Scope**: Only impacts global actor isolated `static let` variables (because `static` variables cannot be actor instance isolated).
* **Risk**: Low; the code change is trivial and it fixes a source of data races. However, some existing code may now fail to compile with `expression is 'async' but is not marked with 'await'` if it accesses an isolated `static let` from across isolation boundaries without `await`.
* **Testing**: Added a new test case.
* **Issue**: rdar://90436577, https://github.com/apple/swift/issues/58270
* **Reviewer**: @ktoso
* **Main branch PR**: https://github.com/apple/swift/pull/69598

2023-11-02 14:38 UTC, hborla commented
@swift-ci please test

2023-11-02 21:53 UTC, hborla commented
@swift-ci please test

2023-11-06 16:55 UTC, hborla commented
@swift-ci please test

2023-11-06 17:08 UTC, tbkka approved these changes

2023-11-06 17:23 UTC, nkcsgexi approved these changes

2023-11-06 17:37 UTC, DougGregor requested changes

2023-11-06 17:37 UTC, DougGregor commented on lib/Sema/TypeCheckConcurrency.cpp
> +    if (var->isGlobalStorage() && var->isLazilyInitializedGlobal())
I think this rule prohibits reasonable code from working and would like to discuss it further before merging.

2023-11-06 17:49 UTC, DougGregor approved these changes

2023-11-06 17:49 UTC, DougGregor commented on lib/Sema/TypeCheckConcurrency.cpp
> +    if (var->isGlobalStorage() && var->isLazilyInitializedGlobal())
@hborla has clarified that I misread the code, and this is already appropriate narrow in applicability.

2023-11-06 19:38 UTC, hborla commented
@swift-ci please test Linux

2023-11-06 21:58 UTC, merged