[ClangImporter] Use SwiftImportAsNonGeneric.
swiftlang/swift pull request #6962
Opened 2017-01-21 02:29 UTC by jrose-apple

Add support for the new 'SwiftImportAsNonGeneric' API note (apple/swift-clang#70 in upstream-with-swift), then replace a hardcoded set of class *hierarchies* to import as non-generic with explicit annotations in Foundation's API notes...and the one subclass of any of these types outside Foundation, ScriptingBridge's SBElementArray.

Swift side of rdar://problem/28455962.

2017-01-21 02:31 UTC, jrose-apple commented
This is technically a breaking change for any third-party subclasses of the classes listed here; do you think we need to hide it behind an `isSwiftVersion3`?.

Additionally, allowing someone to use this in the "SwiftVersions" section is probably going to be a problem trying to interoperate across Swift 3 and Swift 4...

2017-01-23 18:52 UTC, DougGregor requested changes
I'd like us to be clear about whether we have a source-compatibility issue here.

2017-01-23 18:52 UTC, DougGregor commented on lib/ClangImporter/ImportDecl.cpp
> +  return decl->hasAttr<clang::SwiftImportAsNonGenericAttr>();
The existing code explicitly looked up the superclass chain. Does `clang:: SwiftImportAsNonGenericAttr` actually get inherited by subclasses or are we changing behavior here? I suspect it's the latter (which the `SBElementArray` addition implies), but that makes this a source-compatibility break for Objective-C APIs that subclass `NSMutable<something>`.

In Swift 3 compatibility mode, should we follow the superclass chain here?

2017-01-23 18:54 UTC, jrose-apple commented on lib/ClangImporter/ImportDecl.cpp
> +  return decl->hasAttr<clang::SwiftImportAsNonGenericAttr>();
It does not get inherited, which I think is the desired behavior going forward, but yeah, maybe it's a good idea for Swift 3 compatibility mode to walk the superclass chain.

2017-03-23 20:48 UTC, jrose-apple commented
Revised to preserve the entire-hierarchy behavior in Swift 3 mode, and noted in the commit message that there's also a big problem with mix-and-match code that I'll need to deal with down the line. What do you think now, Doug?

@swift-ci Please test

2017-04-03 22:33 UTC, DougGregor approved these changes

2017-04-03 22:33 UTC, DougGregor commented
Yeah, I think this is the right approach so we don't break Swift 3 code yet can do something more intentional for Swift 4.

2017-04-03 22:39 UTC, merged