Lexer: Don't split an operator '.<' from '.<#placeholder#>'
swiftlang/swift pull request #7041
Opened 2017-01-26 01:21 UTC by bitjammer

'.<#placeholder#>' is actually an unresolved reference where the name is
an editor placeholder, not the operator '.<' followed by #placeholder#>.

rdar://problem/28457876

2017-01-26 01:22 UTC, bitjammer commented
Ben, would you mind reviewing for 3.1 when you get a chance?

2017-01-26 01:22 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 01:24 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 01:27 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 01:31 UTC, benlangmuir requested changes

2017-01-26 01:31 UTC, benlangmuir commented on lib/Parse/Lexer.cpp
> +    if (CurPtr[0] == '/' && (CurPtr[1] == '/' || CurPtr[1] == '*')) {
You can put comment syntax inside a placeholder, so this `if` should go away.

2017-01-26 01:31 UTC, benlangmuir commented on test/IDE/structure_object_literals.swift
> +_ = .<#placeholder#>
We should test some more cases, e.g.
```
_ = .<#line
_ = 1<#line
_ = 1<#line#>
```

2017-01-26 01:37 UTC, bitjammer commented on test/IDE/structure_object_literals.swift
> +_ = .<#placeholder#>
These shouldn't appear in the document structure, correct? We'd just be testing whether it affects the literal's appearance?

2017-01-26 01:37 UTC, bitjammer commented on lib/Parse/Lexer.cpp
> +    if (CurPtr[0] == '/' && (CurPtr[1] == '/' || CurPtr[1] == '*')) {
Sure thing.

2017-01-26 01:45 UTC, benlangmuir commented on test/IDE/structure_object_literals.swift
> +_ = .<#placeholder#>
Right

2017-01-26 02:38 UTC, bitjammer commented
How about it, @benlangmuir?

2017-01-26 02:39 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 02:58 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 15:38 UTC, benlangmuir commented on test/IDE/structure_object_literals.swift
> +_ = <object-literal-expression>#<name>colorLiteral</name>(<arg><name>red</name>: 0.0</arg>, <arg><name>green</name>: 0.0</arg>, <arg><name>blue</name>: 0.0</arg>, <arg><name>alpha</name>: 1.0</arg>)<
Missing `// CHECK-AFTER:`

2017-01-26 15:39 UTC, benlangmuir approved these changes

2017-01-26 15:39 UTC, benlangmuir commented
Please fix the missing FileCheck line, but otherwise LGTM!

2017-01-26 17:57 UTC, bitjammer commented
@swift-ci Please smoke test and merge

2017-01-26 17:57 UTC, bitjammer commented
@swift-ci Please smoke test and merge

2017-01-26 18:47 UTC, bitjammer commented
Looks like a spurious Linux failure. Trying again.

2017-01-26 18:47 UTC, bitjammer commented
@swift-ci Please smoke test

2017-01-26 20:50 UTC, merged

2017-01-27 12:03 UTC, gparker42 commented
Reverting. This is causing ASAN failures.

My reading is that `rangeContainsPlaceholderEnd()` increments `CurPtr` too early, so 
* the range check doesn't work, and
* the first character of the range is ignored, so text like `.<\n // #>` is handled incorrectly.

2017-01-27 12:47 UTC, bitjammer commented
Ah crap, you are totally right on the early increment. Thanks Greg, I'll fix it up in a little bit.