Simplifying implementation of `ExpressibleByStringLiteral`
swiftlang/swift pull request #7125
Opened 2017-01-28 06:52 UTC by therealbnut

**Added default implementations for `ExpressibleByUnicodeScalarLiteral` and `ExpressibleByExtendedGraphemeClusterLiteral`**
```swift
init(unicodeScalarLiteral value: UnicodeScalar)
init(extendedGraphemeClusterLiteral value: Character)
```

Now implementing `ExpressibleByStringLiteral` is as simple as:
```swift
extension Example: ExpressibleByStringLiteral {
    init(stringLiteral value: String) {
        self.string = value
    }
}
```

Previously you would have to implement something like this:
```swift
extension Example: ExpressibleByStringLiteral {
    init(stringLiteral value: String) {
        self.string = value
    }
    init(extendedGraphemeClusterLiteral value: Character) {
        self.string = String(describing: value)
    }
    init(unicodeScalarLiteral value: UnicodeScalar) {
        self.string = String(Character(value))
    }
}
```
As well as understand what each of these meant, and which types are valid.

**Changed `Character`'s implementation of `ExpressibleByUnicodeScalarLiteral`**
```diff
-  public init(unicodeScalarLiteral value: Character) {
+  public init(unicodeScalarLiteral value: UnicodeScalar) {
```
The documentation states:
```swift
/// Valid types for `UnicodeScalarLiteralType` are `UnicodeScalar`,
/// `String`, and `StaticString`.
```

2017-01-28 06:57 UTC, therealbnut commented
@swift-ci Please smoke test

2017-01-29 02:02 UTC, slavapestov commented
@swift-ci Please smoke test

2017-01-29 02:03 UTC, therealbnut commented
thanks :)

2017-01-29 02:30 UTC, therealbnut commented
This fails on source stability, this was expected, I've pushed a commit to remove the specific issue from the PR, although perhaps the documentation/test should be updated instead (See PR description).

```
swift/test/api-digester/tmp/source-stability.swift.expected
+Constructor Character.init(unicodeScalarLiteral:) has 1st parameter type change from Character to UnicodeScalar
```

2017-01-29 02:52 UTC, xwu commented on stdlib/public/core/CompilerProtocols.swift
> +    where Self.ExtendedGraphemeClusterLiteralType == Character
Drive-by nit: indents are two spaces in this file; otherwise a delightful addition!

2017-01-29 02:56 UTC, therealbnut commented
Fixed by e8e5240 thanks @xwu

2017-01-29 03:04 UTC, therealbnut commented
Also fixed indentation and **`where`** with d187c34, I left it indented after a search in stdlib for `^\s*where`.

2017-01-29 03:10 UTC, CodaFi commented
Is there documentation mentioning implementation requirements that requires updating here?

2017-01-29 03:27 UTC, therealbnut commented
@CodaFi not that I can find, the documentation states:

> To add `ExpressibleByStringLiteral` conformance to your custom type, implement **the** required initializer.

It already implies you only need to implement `init(stringLiteral:)`.

There is a comment that could possibly be removed.
```swift
  // FIXME: when we have default function implementations in protocols, provide
  // an implementation of init(extendedGraphemeClusterLiteral:).
```

2017-02-13 11:38 UTC, therealbnut commented
ping @dabrahams (as suggested by moiseev)

2017-02-25 02:12 UTC, therealbnut commented
ping @dabrahams (`"If it is not urgent, the common courtesy ping rate is one week."` let me know if I'm pestering you, or I should be pestering someone else)

2017-02-27 17:00 UTC, dabrahams commented
@airspeedswift let's discuss this.  It's clearly an improvement, barely squeaks by on not needing evolution review IMO, but we are planning to redesign everything in this space.  I guess I vote for merging if it passes tests.

2017-02-27 17:01 UTC, dabrahams commented
@swift-ci Please smoke test

2017-02-27 17:04 UTC, dabrahams requested changes
Please add tests that verify your default implementations work.  Also please eliminate any concrete implementations that are redundant with these defaults, except where it hurts performance.

Thanks!

2017-02-27 17:04 UTC, dabrahams commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
Please add a test that verifies the correctness of this edit.

2017-02-27 17:56 UTC, airspeedswift commented
@dabrahams I agree, can go ahead w/o evolution, and may as well merge even if we end up redesigning just in case that misses 4.0 due to other higher-priority stuff

2017-03-05 11:00 UTC, therealbnut commented
**note: I haven't had a chance to run the tests locally yet**

I believe I've addressed all the comments. I'm not 100% sure if the tests are in the right place though.

I had to make the protocol defaults slightly more generalised to remove redundant concrete implementations, the existing concrete implementations often used the same type for each protocol. I believe the generalisation improved the code overall though.

Implementing a valid `associatedtype` on one of these protocols will always produce a valid `associatedtype` in the default implementations. This is because the allowed types on each protocol is a subset of the types in its parent protocol. 

| protocol `associatedtype` | one of |
| --- | --- |
| `UnicodeScalarLiteralType` | `String`, `StaticString`, `Character`, `UnicodeScalar` |
| `ExtendedGraphemeClusterLiteralType` | `String`, `StaticString`, `Character` |
| `StringLiteralType` | `String`, `StaticString` |

2017-03-05 11:02 UTC, therealbnut commented
I'm getting an error trying to build master, I'll run tests locally once I've worked out what's going on there.
```bash
swift/include/swift/AST/TypeAlignments.h:104:21: error: no template named 'AlignOf' in namespace 'llvm'; did you mean 'AlignTo'?
static_assert(llvm::AlignOf<void*>::Alignment >= 2,
              ~~~~~~^~~~~~~
                    AlignTo
```

2017-03-06 18:45 UTC, jrose-apple submitted a review, later dismissed

2017-03-06 18:45 UTC, jrose-apple commented on stdlib/public/core/CompilerProtocols.swift
> +  @effects(readonly)
Please don't specify this. You can't guarantee the initializer you chain to follows it.

2017-03-11 06:23 UTC, therealbnut commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
Should be addressed by https://github.com/apple/swift/pull/7125/files#diff-4d7f8659b54e15ede9391722ae11cb74R24

Was this what you had in mind?

I‘m just verifying the tests locally, then I'll ping you so we can run them with CI and finalise the PR.

2017-03-11 06:24 UTC, therealbnut commented on stdlib/public/core/CompilerProtocols.swift
> +  @effects(readonly)
good point, thank you

2017-03-19 05:12 UTC, dabrahams commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
It's a start, but it doesn't check semantics.  Please write a test using StdlibUnittest that checks the results at runtime, thanks!

2017-03-25 05:43 UTC, therealbnut commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
I believe this is now covered by https://github.com/apple/swift/pull/7125/files/2201e882fa4715afb2b941bc86ed3ef991cc5eae..e67a2b3439b27d2d31d4b6a9745cbf1664002ed0 thanks for the feedback :)

2017-04-01 10:11 UTC, therealbnut commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
@dabrahams hi, just pinging you to hopefully finalise this review :)

2017-04-21 01:37 UTC, therealbnut commented on stdlib/public/core/CompilerProtocols.swift
> +  /// `Character`, `String`, and `StaticString`.
@dabrahams hey, pinging again to try and get this merged :)

2017-04-21 12:58 UTC, airspeedswift commented
@swift-ci Please test

2017-04-21 16:02 UTC, therealbnut commented
@airspeedswift Thanks for running CI.

The **failing test** seems to be in [swift-package-manager](https://github.com/apple/swift-package-manager/blob/master/Tests/BasicTests/ProcessSetTests.swift), I don't see how this could be affected by this branch.

I've merged latest master into this branch (it was 20 days behind with no conflicts), it would be awesome if you could run CI again, unless you think it may be this branch at fault.

2017-04-21 16:37 UTC, airspeedswift commented
@swift-ci Please test

2017-04-21 17:07 UTC, therealbnut commented
@airspeedswift sorry to pester you again, CI failed again, it claims "wrong sha", I suspect it's because it ran on 4d3ca09 and not 78c5df1...

I rebased on master, perhaps that will fix it...

2017-04-21 17:15 UTC, airspeedswift commented
@swift-ci Please test

2017-04-21 17:15 UTC, airspeedswift commented
c'mon @swift-ci you can do it...

2017-04-22 00:00 UTC, therealbnut commented
@airspeedswift I'm not sure if that actually triggered a build, the currently running build was triggered half an hour ago, and this one was 7 hours ago...

2017-04-22 00:47 UTC, airspeedswift commented
@swift-ci Please test

2017-04-22 00:51 UTC, therealbnut commented
Hmm, it seems to have used the wrong commit again

2017-04-22 02:10 UTC, airspeedswift commented
Ok it's down to an unrelated failure on the full macOS test suite that I think is also failing in master. We can smoke test then merge probably.

2017-04-22 02:10 UTC, airspeedswift commented
@swift-ci Please smoke test macOS platform

2017-04-22 02:26 UTC, therealbnut commented
Thank @airpseedswift :)

2017-04-22 02:28 UTC, therealbnut commented
Thanks @airspeedswift 🙂

2017-04-22 03:45 UTC, merged

2017-04-22 03:48 UTC, therealbnut commented
Thank you everyone that helped review :)

2017-04-22 03:49 UTC, therealbnut commented
Thank you @airspeedswift for your persistence with CI :)