[ClangImporter] Import NSNotificationName constants as `nonisolated`
swiftlang/swift pull request #71419
Opened 2024-02-06 21:29 UTC by xedin

These constants could be used with observer APIs from a different isolation
context, so it's more convenient to import them as `nonisolated` unless
they are explicitly isolated to a MainActor.

Resolves: rdar://114052705

2024-02-06 21:29 UTC, xedin commented
@swift-ci please test

2024-02-07 00:16 UTC, xedin commented
@swift-ci please test

2024-02-07 18:29 UTC, beccadax requested changes

2024-02-07 18:29 UTC, beccadax commented on lib/ClangImporter/ImportDecl.cpp
> +          isNSNotificationName(cast<clang::ValueDecl>(ClangDecl)->getType())) {
This logic should probably be driven off `importer::isNSNotificationGlobal()` or some version of that. There are *many* constants in the SDK that are declared as type `NSString *`, but are imported as `NSNotification.Name` based on their names having a `Notification` suffix—this logic ought to apply to them, too.

2024-02-07 19:01 UTC, beccadax commented on lib/ClangImporter/ImportDecl.cpp
> +          isNSNotificationName(cast<clang::ValueDecl>(ClangDecl)->getType())) {
Sorry, misunderstood the requirements here. We're trying to fix something that only affects notification names that have been `NS_SWIFT_NAME()`d into an actor-isolated type, and `isNSNotificationGlobal()` rejects anything with an `NS_SWIFT_NAME()`.

2024-02-07 19:12 UTC, beccadax approved these changes
After rethinking what this PR is actually trying to accomplish, I think this is *probably* okay.

2024-02-07 19:13 UTC, xedin commented
@swift-ci please test

2024-02-08 17:30 UTC, merged