add a no-parameter initializer to pthread_t on Darwin
swiftlang/swift pull request #7200
Opened 2017-02-02 03:30 UTC by glessard

This adds a no-parameter initializer to `pthread_t`, aka `UnsafeMutablePointer<_opaque_pthread_t>`. With this addition, `pthread_t` can once again be initialized the same way on both Linux and Darwin.
`var thread = pthread_t()`

Resolves [SR-775](https://bugs.swift.org/browse/SR-775).

2017-02-02 05:29 UTC, gparker42 commented
This seems like a strange outcome. Do we have any other types where `T()` is nil-like?

I assume that nobody ever wants to perform integer-like operations on a Linux `pthread_t`. Perhaps Linux should also import `pthread_t` as a pointer-like type.

2017-02-02 06:00 UTC, glessard commented
On Linux, pthread_t maps to a long int; who knows how it's used.
From /usr/include/x86_64-linux-gnu/bit/pthreadtypes.h:
`typedef unsigned long int pthread_t;`

On macOS, from /usr/include/sys/_pthread/_pthread_t.h:
`typedef __darwin_pthread_t pthread_t;` // this is the only definition in that header
and from /usr/include/sys/_pthread/_pthread_types.h:
`typedef struct _opaque_pthread_t *__darwin_pthread_t;`

Given that pthread_t is supposed to be opaque, having it be mapped as a pointer is not particularly useful. With the never-nil pointers, it's also confusing.

2017-02-02 06:18 UTC, slavapestov commented
I don't understand this well enough to offer any feedback, but I'm just curious -- when do you need to create 'uninitialized' pthread_t values?

2017-02-02 07:26 UTC, glessard commented
You don't, really. `pthread_t` is actually initialized by calling `pthread_create()`; it doesn't care what was previously in the variable, it allocates its opaque data structure and just fills in the pthread_t with the "thread id" (which everyone knows is a pointer to opaque data).

Swift demands initialization of variable, though, so we need something.

The two following programs do the same silly thing:
```
import Darwin

func start(_ ump: UnsafeMutableRawPointer) -> UnsafeMutableRawPointer?
{
  print(ump)
  return nil
}

var p: pthread_t? = nil
pthread_create(&p, nil, start, &p)
pthread_join(p!, nil)
```

```
import Glibc

func start(_ ump: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer?
{
  print(ump!)
  return nil
}

var p = pthread_t()                // var p: pthread_t = 0 also works
pthread_create(&p, nil, start, &p)
pthread_join(p, nil)
```

As you can see from the various differences, the pthreads interface gets imported differently on both platforms, despite having pretty much the same headers. This contribution is a very limited reduction to the overall pain.

2017-02-02 16:35 UTC, jrose-apple commented
I don't know if pthread_t is special here. There are plenty of other types that are integers or structs on one platform and pointers on another. Maybe we should just bring back the no-argument initializer for Optionals.

(cc @airspeedswift)

2017-09-14 16:57 UTC, CodaFi commented
@glessard If it still makes sense to take this, could you rebase this patch?

2017-09-14 17:19 UTC, jrose-apple requested changes
I'd like ruling on swift-evolution over whether these kinds of changes are okay. This is certainly convenient, but it's also not how any other pointer type works today.

2017-09-14 20:32 UTC, jrose-apple commented
I understand that's [how pthread_t is intended to work](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html). The point that needs discussion is whether the Swift platform overlay should include per-type concessions to things like this.

2017-09-14 22:10 UTC, glessard commented
Would there be a way to override the importer and define `pthread_t` as a typealias for `Int`? In C it doesn't matter in use whether it's a pointer or a `long int`. In Swift the knock-on effects are numerous, and it transforms pthreads into a non-portable api.

2017-09-15 00:03 UTC, jrose-apple commented
Anything we do, clever or non-clever, has to go through swift-evolution.

2017-09-15 00:11 UTC, glessard commented
Understood, but is it even possible? Making `pthread_t` not-a-pointer would be the better solution, if only it were possible.

2017-09-15 00:20 UTC, jrose-apple commented
I think it's possible, but I'd be concerned about platforms that may have implemented it as non-word-sized. Then we're just back to a different incompatibility.

2017-09-15 01:18 UTC, glessard commented
This is only about the way the type is imported on Darwin… does it necessarily affect other platforms? (I haven't tried it again, but before I submitted this PR it didn't affect the Linux build). In any event, conditional compilation is certainly an option.

2017-09-15 01:29 UTC, jrose-apple commented
Ah, changes in import would be special-cased in the compiler, so it'd be clunkier to make it platform-specific.

2017-09-15 01:30 UTC, jrose-apple commented
But what's the point of doing it for Darwin if it's not going to be consistent across other OSs?

2017-09-15 01:48 UTC, glessard commented
`pthread_t` should be opaque and behave as such. On Darwin, the Swift importer is _violating_ that by interpreting it as a pointer -- which is not quite opaque and triggers a large amount of compiler magic. That makes the type impossible to use as intended. If any other platform imports it as a pointer, it would have to be fixed there too. The strategy that happens to work (this is all clearly accidental) is declaring the type as an int.

If you look at the examples I put above, the Glibc/Linux version looks like pthread code. The Darwin version does not, because it is encumbered with Optionals that don't make sense in that context. The rational options are to fix it or to nix the pthreads import. Either works.

2019-11-14 21:49 UTC, CodaFi commented
@glessard A change like this to the standard library now requires evolution discussion.  I apologize that we were not able to resolve this at the time.  If you wish to pursue this change, please open a pull request to the swift evolution repository and a pitch thread on the forums.

2019-11-14 21:49 UTC, closed without merging