[cxx-interop] Fix wrong field offsets with value types using inheritance
swiftlang/swift pull request #74570
Opened 2024-06-20 12:39 UTC by Xazax-hun

The code path responsible for calculating field offsets creates opaque fields for all the base classes. This code path simply summed up the sizes of the base classes to get the offset. Unfortunately, this does not work for base classes with vptrs. C++ does not embedd the vptrs from the base classes into the derived class. The derived class has a single vptr. This PR removes this assumption that we can just add the base class sizes up and relies purely on base and field offsets to calculate the sizes for the opaque fields representing the base classes.

rdar://126754931

2024-06-21 17:40 UTC, Xazax-hun commented
@swift-ci please smoke test

2024-06-24 14:28 UTC, Xazax-hun commented
@swift-ci please smoke test

2024-06-24 18:34 UTC, Xazax-hun commented
A high-level comment. I could have tried to correctly calculate the ABI by introducing adjustments, like subtracting the size of the vptr from the base's size. But there are complex ABI rules in some cases where fields can be packed into the base's trailing padding. I decided that only relying on the offsets is more reliable and less likely to break when something changes in Clang.

2024-06-26 16:07 UTC, rjmccall requested changes
I think the basic approach here is just wrong.  If we want to add opaque storage for a (non-empty) base, we should add storage covering its nv-size rather than trying to compute it by the range to the next base in the layout.  But really, I think we should be recursing into the base rather than treating it as totally opaque.

2024-06-26 16:07 UTC, rjmccall commented on lib/IRGen/GenStruct.cpp
> +      // reliably calculate base subobject sizes using the next base's offset.
It is not generally true that empty bases are all at offset zero.

2024-06-26 17:12 UTC, Xazax-hun commented
> I think the basic approach here is just wrong. If we want to add opaque storage for a (non-empty) base, we should add storage covering its nv-size rather than trying to compute it by the range to the next base in the layout. But really, I think we should be recursing into the base rather than treating it as totally opaque.

I will give the non-virtual size a try and see if this works out. By recursing into the base you mean collecting all the fields from the base classes as well, right?

2024-06-26 17:46 UTC, rjmccall commented
> > I think the basic approach here is just wrong. If we want to add opaque storage for a (non-empty) base, we should add storage covering its nv-size rather than trying to compute it by the range to the next base in the layout. But really, I think we should be recursing into the base rather than treating it as totally opaque.
> 
> I will give the non-virtual size a try and see if this works out. By recursing into the base you mean collecting all the fields from the base classes as well, right?

Yes, I mean collecting fields from base classes (offset as necessary) as an alternative to just adding the entire base subobject as opaque storage.

While you're at it, please fix this to not just ignore virtual bases.  Maybe we don't import these types yet, but (1) there's no reason for this code to handle them incorrectly and (2) I suspect we can visit them indirectly, e.g. if you have a class with a field that has a virtual base.  The correct way to handle virtual bases is to handle them exactly like normal bases, but only when you're visiting the object as a complete object type (i.e. *not* when you're recursively visiting base subobjects in the walk I'm asking you to add).

2024-07-11 16:23 UTC, Xazax-hun commented
Thanks! It took some time to get back to this, but I opened a new PR that does the recursive walk: https://github.com/swiftlang/swift/pull/75176

This one does not deal with virtual inheritance yet, because that is not required to fix the crash and we have some higher priority items to address first (and the patch is already getting larger enough, so splitting up might also make reviewing easier).

2024-07-11 16:23 UTC, closed without merging