[IRGen] Upstream pointer auth for value witness tables
swiftlang/swift pull request #74625
Opened 2024-06-21 17:57 UTC by egorzhdan

2024-06-21 17:57 UTC, egorzhdan commented
@swift-ci please test

2024-06-27 15:29 UTC, egorzhdan commented
@swift-ci please test

2024-06-27 18:25 UTC, egorzhdan commented
@swift-ci please test Windows

2024-06-27 21:10 UTC, rjmccall requested changes
Mostly LGTM, but some small requests.

2024-06-28 13:00 UTC, egorzhdan commented on lib/IRGen/GenMeta.cpp
> +  auto intSize = Size::forBits(targetInfo.getIntWidth());
Sounds good, I removed this change from the patch.

2024-07-01 14:13 UTC, rjmccall reviewed
One last tweak, but otherwise LGTM

2024-07-01 14:13 UTC, rjmccall commented on lib/IRGen/GenMeta.cpp
> +      if (wtable != llvm::ConstantPointerNull::get(IGM.WitnessTablePtrTy)) {
```suggestion
      if (!isa<llvm::ConstantPointerNull>(wtable)) {
```

2024-07-01 15:38 UTC, egorzhdan commented on lib/IRGen/GenMeta.cpp
> +      if (wtable != llvm::ConstantPointerNull::get(IGM.WitnessTablePtrTy)) {
Applied this, thanks!

2024-07-01 16:01 UTC, rjmccall approved these changes

2024-07-01 21:17 UTC, merged