Typos: `test/SILOptimizer`
swiftlang/swift pull request #75028
Opened 2024-07-07 13:20 UTC by Sajjon

Fix typos in `test/SILOptimizer`

2024-07-08 14:05 UTC, eeckstein requested changes

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/access_enforcement_selection.sil
> +// partial_applies.
-> `partial_apply` instructions

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/access_enforcement_selection.sil
> +sil [dynamically_replaceable] [ossa] @closureCapturingByStorageAddress2 : $@convention(thin) (@inout_aliasable Builtin.Int64) -> ()
That needs to be fixed in SILPrinter + SILParser first

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/dictionary_lookup_with_default.swift
> +// Check that all partial_applies can be optimized away so that no closure context needs to be allocated.
-> `partial_apply` instructions

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/exclusivity_static_diagnostics.sil
> +sil private [dynamically_replaceable] [ossa] @testDynamicLocal : $@convention(thin) (@inout Builtin.Int64, @inout_aliasable TestDynamic) -> () {
same here

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/function_uses.sil
> +sil hidden [dynamically_replaceable] @internal_func : $@convention(thin) () -> () {
same here

2024-07-08 14:05 UTC, eeckstein commented on test/SILOptimizer/simplify_cfg_ossa_jump_threading.sil
> +// lowering certain [on_stack] partial_applies in certain
-> `partial_apply` instructions

2024-07-08 14:08 UTC, eeckstein commented on test/SILOptimizer/access_enforcement_selection.sil
> +sil [dynamically_replaceable] [ossa] @closureCapturingByStorageAddress2 : $@convention(thin) (@inout_aliasable Builtin.Int64) -> ()
I think the best is if you create a separate PR just fixing dynamically_replacable.

2024-07-08 18:48 UTC, Sajjon commented
@eeckstein Thank you for review! I've reverted according to your suggestions.

2024-07-08 19:17 UTC, eeckstein approved these changes

2024-07-09 06:05 UTC, eeckstein commented
@swift-ci smoke test

2024-07-09 10:01 UTC, merged