[macCatalyst] Support generating macCatalyst object files
swiftlang/swift pull request #75261
Opened 2024-07-16 01:50 UTC by drodriguez

This implements the missing support for macCatalyst in the open source version of Swift. It seems that years ago, the minimal support for macCatalyst was included in #29017, but except some fixes over the years, the work seemed to be blocked there, waiting for LLVM/Clang support that had not landed by the time and the open source toolchain cannot target macCatalyst.

- Implement code to access to `_stdlib_isOSVersionAtLeastOrVariantVersionAtLeast` from the stdlib.
- Implement code to choose `isOSVersionAtLeast` or `isOSVersionAtLeastOrVariantVersionAtLeast` depending on the command line being provided a target variant.
- When an availability statement need to be emitted, pass the target variant version range in order to generate the right stdlib call.
- Implement `isOSVersionAtLeastOrVariantVersionAtLeast` using the variant version information and forwarding both checks to `isOSVersionAtLeast`.
- Set the LLVM Module with the target variant information, so the code is generated correctly.
- Similar code for when the Clang importer is used.
- Modify a test that, when used precompiled modules from Xcode, uses code compiled for macCatalyst and uses the `isOSVersionAtLeastOrVariantVersionAtLeast` instead of the previously expected `isOSVersionAtLeast`. Another option is using `prefer-parseable`, which uses the "expected" stdlib function.
- Modify a test that was checking for availability in a fixed order even when the parameters in the command line were flipped. This test was probably never run in open source CI because it requires `maccatalyst_support`, which was not possible without these changes.

2024-07-16 01:50 UTC, drodriguez commented
@swift-ci please test

2024-07-16 01:54 UTC, drodriguez commented
For the people at Apple: I am pretty sure this code exists internally because Xcode is quite capable to compile Swift macCatalyst. I will be happy to abandon this PR if the internal code is contributed to the open source implementation, since it will avoid internal classes if this code ever lands in the repository. These are the changes I needed to get things working as I think they should work when using `--maccatalyst` in the `build-script`, but there's probably some code internally that I am missing, or the implementation could be better. Happy to help to open source those bits in whatever I can.

2024-07-16 15:56 UTC, tshortli requested changes
Hey @drodriguez, thanks for reminding us about this missing support. Let me investigate upstreaming the missing bits so that we can minimize divergence. I will update you here when I have more information.

2024-07-18 01:39 UTC, tshortli commented
> This implements the missing support for macCatalyst in the open source version of Swift. It seems that years ago, the minimal support for macCatalyst was included in #29017, but except some fixes over the years, the work seemed to be blocked there, waiting for LLVM/Clang support that had not landed by the time and the open source toolchain cannot target macCatalyst.

I dug into this a bit and found that this is still blocked in general on several missing pieces in llvm/clang.

> * Implement `isOSVersionAtLeastOrVariantVersionAtLeast` using the variant version information and forwarding both checks to `isOSVersionAtLeast`.

In particular, this part of the PR doesn't produce correct behavior. `isOSVersionAtLeastOrVariantVersionAtLeast` needs to call a (currently unavailable) runtime function provided by `compiler-rt` that takes all 6 version arguments instead.

Finding a resolution to this will remain on my todo list but unfortunately it's going to nontrivial effort to get it to parity and I may need help on the clang side. @drodriguez which pieces of missing macCatalyst support are blocking you the most? Maybe we can fill in some of the simpler pieces to get you unblocked sooner, while not immediately supporting runtime availability checks correctly.

2024-07-18 16:19 UTC, drodriguez commented
> In particular, this part of the PR doesn't produce correct behavior. isOSVersionAtLeastOrVariantVersionAtLeast needs to call a (currently unavailable) runtime function provided by compiler-rt that takes all 6 version arguments instead.

I was quite sure that the implementation couldn't be that simple. I was just trying to reconstruct the function from the pieces that were already there. It is not the highest priority to have it in a working state, but obviously it would be great to have the actual implementation available.

>  @drodriguez which pieces of missing macCatalyst support are blocking you the most? Maybe we can fill in some of the simpler pieces to get you unblocked sooner, while not immediately supporting runtime availability checks correctly.

That would be great. I think the pieces in IRGen are the biggest missing pieces. Those are the ones I started with, but that led to a test breakage around `isOSVersionAtLeastOrVariantVersionAtLeast`, which I tried to fix, which led to the rest of the changes. If you can upstream those pieces in IRGen and maybe XFAIL the tests that relate to to the missing availability support, I think that would cover a lot.

I was looking at trying to implement what Egor ended up doing independently in #74994, and found out that the open source toolchain did not seem to support macCatalyst, so I was trying to fill the gaps. We have some interest in trying somethings out in macCatalyst, but without a working compiler we can target at macCatalyst it was not possible.

2024-07-24 00:09 UTC, tshortli commented
Here's a PR adding the majority of the missing support: https://github.com/swiftlang/swift/pull/75432

2024-07-24 01:57 UTC, drodriguez commented
Thanks so much for all that work. I hope it at least reduces a little the internal patchset over at Apple.

Glad I was close in some cases and glad to see the actual code, because in many cases I would have break things so badly (funny that there actually was a `_stdlib_isVariantOSVersionAtLeast` and my laziness ended up using `IsVariantOSVersionAtLeastDecl` instead of the longer `IsOSVersionAtLeastOrVariantVersionAtLeast`).

Closing this one.

2024-07-24 01:57 UTC, closed without merging