Update the link from https://github.com/apple/ to https://github.com/swiftlang/
swiftlang/swift pull request #75388
Opened 2024-07-21 08:54 UTC by lamtrinhdev

### PR Summary:
PR simply fixes the link from:

+ "https://github.com/apple/swift/tree/main/docs/HowToGuides/FAQ.md" => "https://github.com/swiftlang/swift/tree/main/docs/HowToGuides/FAQ.md

2024-07-21 08:55 UTC, lamtrinhdev commented
@swift-ci please smoke test

2024-07-21 09:31 UTC, AnthonyLatsis commented
@lamtrinhdev Could you compose all of your updates to links in the `docs` directory in a single PR instead of creating separate PRs per file? Merging this as a single commit is a lot cleaner.

2024-07-21 09:45 UTC, lamtrinhdev commented
Dear @AnthonyLatsis , 

Sure. Let me update all of them in the docs folder.

Thanks,
Lam

2024-07-21 10:11 UTC, lamtrinhdev commented
Dear @AnthonyLatsis ,

Thank you for the suggestion. I just updated all the links from https://github.com/apple/swift to https://github.com/swiftlang/swift Please help me to review it.

Thanks,
Lam

2024-07-22 07:54 UTC, ktoso commented
AFAICS LGTM, but we need to squash when merging this, or you should squash yourself.

2024-07-22 07:54 UTC, ktoso commented
@swift-ci please smoke test

2024-07-22 08:16 UTC, lamtrinhdev commented
Thank you for your feedback @ktoso .

2024-07-22 08:16 UTC, lamtrinhdev commented
Dear @AnthonyLatsis ,

I just completed all my update. If you have time. Please support me to review the PR.

Thanks,
Lam

2024-07-22 09:51 UTC, ktoso commented
@swift-ci please smoke test

2024-07-22 15:30 UTC, AnthonyLatsis requested changes

2024-07-22 15:55 UTC, lamtrinhdev commented on docs/AndroidBuild.md
> +1. Clone `swiftlang/swift-llvm` into a directory named `llvm`
Thank you for your support @AnthonyLatsis . I updated it.

2024-07-22 15:56 UTC, lamtrinhdev commented on docs/AndroidBuild.md
> +git clone https://github.com/swiftlang/swift-llvm llvm
Thank you for your support @AnthonyLatsis . I updated it.

2024-07-22 15:57 UTC, lamtrinhdev commented
@swift-ci please smoke test

2024-07-22 16:22 UTC, AnthonyLatsis commented
> @swift-ci please smoke test

FWIW, this will not work. You need permissions.

2024-07-22 16:22 UTC, AnthonyLatsis approved these changes

2024-07-22 16:23 UTC, AnthonyLatsis commented
@swift-ci please smoke test

2024-07-22 19:22 UTC, merged

2024-07-22 19:58 UTC, AnthonyLatsis commented
Thank you for helping with the migration, Lam.