Port swiftSyntax to Windows
swiftlang/swift pull request #7588
Opened 2017-02-18 06:32 UTC by hughbe

`strndup` is not available on Windows. Windows does provide `strdup` but that isn't the behaviour we want unfortunately.

So roll out our own solution

@bitjammer

2017-02-18 06:43 UTC, bitjammer requested changes
To add a test:
- Add an OwnedString.cpp to ./unittests
  - Don't forget the license header; see other files in the directory.
- Include OwnedString.cpp in ./unittests/CMakeLists.txt

2017-02-18 06:43 UTC, bitjammer commented on include/swift/Basic/OwnedString.h
> +
Let's do the following, please.
- Change  `OwnedString(const char *Data, size_t Length, StringOwnership Ownership)` to:
  `OwnedString(const char *Data, size_t Length)`
  - assume `StringOwnership::Unowned`
- Move `copyString(const char *s, size_t length)` to `OwnedString OwnedString::copy()`
- Add *rigorous* testing for copying. This is an absolute must if we are going to be implementing the equivalent to `strndup`.

2017-02-18 07:08 UTC, gottesmm commented
@bitjammer It is also important that the test follows the naming convention. Specifically, it should be OwnedStringTest.cpp like all of the other tests in ./unittests.

2017-02-18 09:16 UTC, hughbe commented
@swift-ci please smoke test

2017-02-18 09:17 UTC, hughbe commented
@swift-ci please smoke test

2017-02-18 09:23 UTC, hughbe commented
..and fix a Clang compile error (odd that MSVC allows the name of a function definition to be qualified with the class name in a header)

2017-02-18 09:23 UTC, hughbe commented
@swift-ci please smoke test

2017-02-18 09:23 UTC, hughbe commented
@swift-ci please smoke test

2017-02-18 18:39 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 03:24 UTC, hughbe commented
Okay, so I'm getting these errors "pointer being freed was not allocated". Odd, considering the only time we are `StringOwnership::Copied` is when we call `OwnedString::copy`. This always causes an allocation

I'm not really sure where I'm going wrong - If you guys have any ideas, I'd appreciate this!

2017-02-20 09:16 UTC, bitjammer commented
You took the copy out of OwnedString(const OwnedString &Other), but you're still reusing the StringOwnership argument. You need to do a copy there in that constructor if the ownership is Copied, otherwise you'll free the same pointer twice.

2017-02-20 10:54 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 10:54 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 10:55 UTC, hughbe commented
Thanks David - you're right! I've updated the PR and added some unit tests that pass on Windows. I haven't got anything in `tests/*` working on Windows yet, so let's see!

2017-02-20 11:13 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 11:13 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 17:10 UTC, jrose-apple commented on include/swift/Basic/OwnedString.h
> +    if (Ownership == StringOwnership::Copied && Data) {
This shouldn't be necessary; `free` accepts a null pointer.

2017-02-21 01:48 UTC, hughbe commented
@swift-ci please smoke test

2017-02-21 01:48 UTC, hughbe commented
@swift-ci please smoke test

2017-02-21 03:01 UTC, bitjammer commented
@swift-ci Please asan test

2017-02-21 03:13 UTC, shahmishal commented
@swift-ci Please test ASAN

2017-02-21 03:14 UTC, bitjammer commented
It looks like this had been kicked off: https://ci.swift.org/view/All/job/swift-PR-osx-ASAN-test/47/

2017-02-21 03:14 UTC, bitjammer commented
(But no progress reported)

2017-02-21 03:16 UTC, shahmishal commented
its due to wrong sha 

Setting status of d0eed9e97782d1b30b6481341a92f4a1b045510a to PENDING with url https://ci.swift.org/job/swift-PR-osx-ASAN-test/47/ and message: 'Build started.'

2017-02-21 03:16 UTC, shahmishal commented
@swift-ci Please asan test

2017-02-21 03:17 UTC, shahmishal commented
Setting status of b564a917be72b0b4b731da70d5639a25fa99b80d to PENDING with url https://ci.swift.org/job/swift-PR-osx-ASAN-test/48/ and message: 'Build started.'

This worked now, sorry for the trouble.

2017-02-21 06:21 UTC, hughbe commented
```
FAIL: Swift(macosx-x86_64) :: Demangle/remangle.swift (8764 of 9405)
******************** TEST 'Swift(macosx-x86_64) :: Demangle/remangle.swift' FAILED ********************
Script:
--
sed -ne '/--->/s/ *--->.*$//p' < /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/swift/test/Demangle/Inputs/manglings.txt > /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/test-macosx-x86_64/Demangle/Output/remangle.swift.tmp.input
swift-demangle -test-remangle < /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/test-macosx-x86_64/Demangle/Output/remangle.swift.tmp.input > /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/test-macosx-x86_64/Demangle/Output/remangle.swift.tmp.output
diff /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/test-macosx-x86_64/Demangle/Output/remangle.swift.tmp.input /Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/test-macosx-x86_64/Demangle/Output/remangle.swift.tmp.output
--
Exit Code: 134

Command Output (stderr):
--
=================================================================
==42010==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000060892 at pc 0x00010390f689 bp 0x7fff5c3965b0 sp 0x7fff5c3965a8
READ of size 1 at 0x607000060892 thread T0
atos[42011]: [fatal] unable to ask for permission to examine process; run tool using sudo, or without redirecting stdin and stderr.
==42010==WARNING: Can't read from symbolizer at fd 5
atos[42012]: [fatal] unable to ask for permission to examine process; run tool using sudo, or without redirecting stdin and stderr.
==42010==WARNING: Can't read from symbolizer at fd 5
atos[42013]: [fatal] unable to ask for permission to examine process; run tool using sudo, or without redirecting stdin and stderr.
==42010==WARNING: Can't read from symbolizer at fd 5
atos[42014]: [fatal] unable to ask for permission to examine process; run tool using sudo, or without redirecting stdin and stderr.
==42010==WARNING: Can't read from symbolizer at fd 5
==42010==WARNING: Failed to use and restart external symbolizer!
    #0 0x10390f688 in (anonymous namespace)::Remangler::trySubstitution(swift::Demangle::Node*, (anonymous namespace)::SubstitutionEntry&, bool) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x1000a7688)
    #1 0x1039148fa in (anonymous namespace)::Remangler::mangleIdentifierImpl(swift::Demangle::Node*, bool) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x1000ac8fa)
    #2 0x1038feae5 in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100096ae5)
    #3 0x10390425d in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009c25d)
    #4 0x1038fd18d in swift::Demangle::mangleNode(std::__1::shared_ptr<swift::Demangle::Node> const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009518d)
    #5 0x10386ba13 in demangle(llvm::raw_ostream&, llvm::StringRef, swift::Demangle::Context&, swift::Demangle::DemangleOptions const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100003a13)
    #6 0x10386aa7b in main (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100002a7b)
    #7 0x7fffcd5b1254 in start (/usr/lib/system/libdyld.dylib:x86_64+0x5254)

0x607000060892 is located 18 bytes inside of 72-byte region [0x607000060880,0x6070000608c8)
freed by thread T0 here:
    #0 0x103c03cab in wrap__ZdlPv (/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x61cab)
    #1 0x7fffcc183dad in std::__1::__shared_weak_count::__release_shared() (/usr/lib/libc++.1.dylib:x86_64+0x3bdad)
    #2 0x1038feb00 in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100096b00)
    #3 0x10390425d in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009c25d)
    #4 0x1038fd18d in swift::Demangle::mangleNode(std::__1::shared_ptr<swift::Demangle::Node> const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009518d)
    #5 0x10386ba13 in demangle(llvm::raw_ostream&, llvm::StringRef, swift::Demangle::Context&, swift::Demangle::DemangleOptions const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100003a13)
    #6 0x10386aa7b in main (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100002a7b)
    #7 0x7fffcd5b1254 in start (/usr/lib/system/libdyld.dylib:x86_64+0x5254)

previously allocated by thread T0 here:
    #0 0x103c036ab in wrap__Znwm (/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x616ab)
    #1 0x1038fe99f in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009699f)
    #2 0x10390425d in (anonymous namespace)::Remangler::mangle(swift::Demangle::Node*) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009c25d)
    #3 0x1038fd18d in swift::Demangle::mangleNode(std::__1::shared_ptr<swift::Demangle::Node> const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x10009518d)
    #4 0x10386ba13 in demangle(llvm::raw_ostream&, llvm::StringRef, swift::Demangle::Context&, swift::Demangle::DemangleOptions const&) (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100003a13)
    #5 0x10386aa7b in main (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x100002a7b)
    #6 0x7fffcd5b1254 in start (/usr/lib/system/libdyld.dylib:x86_64+0x5254)

SUMMARY: AddressSanitizer: heap-use-after-free (/Users/buildnode/jenkins/workspace/swift-PR-osx-ASAN-test/buildbot_incremental_asan/swift-macosx-x86_64/bin/swift-demangle:x86_64+0x1000a7688) in (anonymous namespace)::Remangler::trySubstitution(swift::Demangle::Node*, (anonymous namespace)::SubstitutionEntry&, bool)
Shadow bytes around the buggy address:
  0x1c0e0000c0c0: 00 00 00 00 01 fa fa fa fa fa 00 00 00 00 00 00
  0x1c0e0000c0d0: 00 00 01 fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x1c0e0000c0e0: 00 00 fa fa fa fa 00 00 00 00 00 00 00 00 01 fa
  0x1c0e0000c0f0: fa fa fa fa 00 00 00 00 00 00 00 00 01 fa fa fa
  0x1c0e0000c100: fa fa 00 00 00 00 00 00 00 00 00 fa fa fa fa fa
=>0x1c0e0000c110: fd fd[fd]fd fd fd fd fd fd fa fa fa fa fa 00 00
  0x1c0e0000c120: 00 00 00 00 00 00 00 f [...]

2017-02-21 06:22 UTC, hughbe commented
Is the ASAN failure related?

2017-02-21 08:53 UTC, hughbe commented
https://github.com/apple/swift/pull/7664

2017-02-21 18:46 UTC, shahmishal commented
This should be fixed now.

@swift-ci Please asan test

2017-02-21 19:46 UTC, shahmishal commented
I will re-trigger this asan job right after I update the Xcode.

2017-02-21 21:00 UTC, shahmishal commented
@swift-ci Please asan test

2017-02-22 02:51 UTC, hughbe commented
Great! Thanks Mishal. Tests have passed, let me know if you have any more comments

2017-02-22 03:03 UTC, bitjammer approved these changes
Looks good - thanks so much for taking the time to do this right. I appreciate it.

2017-02-22 03:26 UTC, merged