Port SwiftLangSupport::resolvePathSymlinks to Windows
swiftlang/swift pull request #7611
Opened 2017-02-19 07:28 UTC by hughbe

@compnerd could you sign off on this change, it's less trivial than the others!

2017-02-19 07:39 UTC, hughbe commented
@swift-ci please smoke test

2017-02-19 19:42 UTC, compnerd requested changes

2017-02-19 19:42 UTC, compnerd commented on tools/SourceKit/lib/SwiftLang/SwiftLangSupport.cpp
> +      nullptr /*hTemplateFile*/);
We generally don't do naming on the parameters unless they are trailing booleans.

2017-02-19 19:42 UTC, compnerd commented on tools/SourceKit/lib/SwiftLang/SwiftLangSupport.cpp
> +  }
Unnecessary braces.

2017-02-19 19:42 UTC, compnerd commented on tools/SourceKit/lib/SwiftLang/SwiftLangSupport.cpp
> +  if (success) {
Why not use a ternary?

    return (success ? full_path : InputPath);

2017-02-19 19:42 UTC, compnerd commented on tools/SourceKit/lib/SwiftLang/SwiftLangSupport.cpp
> +      sizeof(full_path) /*cchFilePath*/, FILE_NAME_NORMALIZED /*dwFlags*/);
Drop the parameter names.

2017-02-20 03:03 UTC, hughbe commented
@swift-ci please smoke test and merge

2017-02-20 03:03 UTC, hughbe commented
@swift-ci please smoke test and merge

2017-02-20 03:03 UTC, hughbe commented
Cheers, I've addressed your comments

2017-02-20 03:04 UTC, hughbe commented
@swift-ci please smoke test

2017-02-20 04:37 UTC, merged