[stdlib] Rewrite some integer arithmetic and split a bounds check
swiftlang/swift pull request #76361
Opened 2024-09-10 00:15 UTC by Azoy

The integer arithmetic in `BinaryInteger.advanced(by:)` for signed integers whose `bitWidth` is less than `Int`'s would 1. convert `self` into `Int` 2. perform the addition to `n` 3. convert the result back into the `Self` type. This sequence of arithmetic was blocking some LLVM optimizations from occurring (in fact it made codegen significantly worse by trying to vectorize the loop in the test). It seems LLVM would much rather prefer the arithmetic to occur in the original type's width, so let's rewrite it to instead 1. convert `n` to `Self` (if this fails the addition would never have worked in the first place) and 2. perform the addition.

That rewrite resolves the poor codegen for all signed integers (at least those whose bit width is less than or equal to `Int`'s), but the unsigned integers were still generating really bad code. The `_failEarlyRangeCheck` in `Range.index(after:)` was blocking the other half of this optimization, specifically the check `i < upperBound`. We can rewrite this latter half of the bounds check to be `i != upperBound` because if we're not the endIndex then the advancement should always succeed because it's impossible for the upperBound to be greater than an integer max. Somehow this allows LLVM to do its thing and optimize the bounds checking entirely and unrolls the loop.

Workaround for: rdar://135519239

2024-09-10 00:15 UTC, Azoy commented
@swift-ci please test

2024-09-10 00:20 UTC, Catfish-Man commented on stdlib/public/core/Range.swift
> +    _precondition(i != upperBound)
Does this open up a safety hole for situations where arbitrary indices are easy to construct by hand (e.g. integers)?

2024-09-10 08:31 UTC, oscbyspro commented on stdlib/public/core/Integers.swift
> +        return self + Self(n)
```swift
Int8.min.advanced(by: 255 as Int) == Int8.max // ✅ works (old)
Int8.min.advanced(by: 255 as Int) == Int8.max // 💥 crash (new)
```

2024-09-10 10:36 UTC, oscbyspro commented
I know Swift has added protocol requirements retroactively before (SE-0425). So, if the `Int` conversion is problematic for performance reasons, perhaps Swift could add `successor()` and `predecessor()` requirements to `Strideable`. A stride-by-one method would not have to perform this kind of asymmetric integer-type gymnastics. Just a thought.

2024-09-10 13:27 UTC, stephentyrone commented on stdlib/public/core/Integers.swift
> +        return self + Self(n)
This isn't quite correct. Consider `self: Int8 = -1`, `n = 128`.

2024-09-10 13:34 UTC, stephentyrone commented on stdlib/public/core/Integers.swift
> +        return self + Self(n)
(Ah, @oscbyspro beat me to it. But yeah, this is incorrect.)

2024-09-10 13:35 UTC, stephentyrone requested changes
Needs to fix overflow handling in the signed path.

2024-09-10 13:38 UTC, stephentyrone commented
> I know Swift has added protocol requirements retroactively before ([SE-0425](https://swiftlang.github.io/swift-evolution/#?proposal=SE-0425)). So, if the `Int` conversion is problematic for performance reasons, perhaps Swift could add `successor()` and `predecessor()` requirements to `Strideable`. A stride-by-one method would not have to perform this kind of asymmetric integer-type gymnastics.

I'm not really convinced that mixed-type arithmetic is the ultimate cause of the hazard that Alex is trying to fix here. We can consider this option, but there are some large downsides to adding new protocol requirements in the standard library as well (both codesize due to new witnesses, but also complexity because we have to maintain parallel implementations of anything inlinable that wants to use the new requirements--for low-level arithmetic like this, that tends to end up being a lot of stuff).

2024-09-10 15:11 UTC, Azoy commented
Unfortunately even splatting out all of those implementations still results in really bad codegen. I think the best bet is to just file an LLVM bug and get it fixed there.

2024-09-10 16:26 UTC, stephentyrone commented
Something else is going on then, because the codegen for adding 1 is essentially optional when doing so.

2024-09-11 08:30 UTC, oscbyspro commented
You could, perhaps, try this to speed up the small, unsigned, integer case:

```swift
extension BinaryInteger {
  @inlinable
  @inline(__always)
  public func advanced(by n: Int) -> Self {
    if self.bitWidth < n.bitWidth {
      return Self(Int(truncatingIfNeeded: self) + n)
    } else if Self.isSigned {
      return self + Self(truncatingIfNeeded: n)
    } else if n < (0 as Int) {
      return self - Self(truncatingIfNeeded: UInt(bitPattern: 0 &- n))
    } else {
      return self + Self(truncatingIfNeeded: UInt(bitPattern: n))
    }
  }
}
```

The current code doesn't quite "splat" in the way @stephentyrone suggested.

2025-02-26 18:41 UTC, closed without merging