Sema: generalize `findSyntacticErrorForConsume`
swiftlang/swift pull request #76660
Opened 2024-09-23 21:29 UTC by kavon

Since this function is being called from the constraint solver now, we need to generalize the way it obtains the Type of an Expression, as the expression itself may not know its own type, only the solver does.

resolves rdar://134371893 / https://github.com/swiftlang/swift/issues/75999

2024-09-23 21:29 UTC, kavon commented
@swift-ci smoke test

2024-09-23 21:44 UTC, xedin requested changes

2024-09-24 20:50 UTC, kavon commented on lib/Sema/TypeCheckConstraints.cpp
> +bool swift::canAddExplicitConsume(constraints::ConstraintSystem &CS,
Gotcha. I'll change a few other spots that were using `ConstraintSystem::getType` when emitting this diagnostic.

2024-09-24 20:55 UTC, kavon commented
Linux failure seems unrelated.

2024-09-24 21:01 UTC, kavon commented
@swift-ci smoke test

2024-09-25 22:30 UTC, kavon commented
@swift-ci smoke test windows

2024-09-26 00:06 UTC, xedin approved these changes

2024-09-26 02:20 UTC, merged