[Diagnostics] Improve insertion location check when handling a missin…
swiftlang/swift pull request #77226
Opened 2024-10-25 17:17 UTC by JanBaig

When diagnosing a missing argument, cases without parentheses lack a clear insertion location. 
This change adds a concise, targeted check to return false early in these cases, making error handling more precise.

2024-10-28 16:50 UTC, xedin commented
@swift-ci please test Windows platform

2024-10-28 16:50 UTC, xedin commented
@swift-ci please test Linux platform

2024-10-29 21:03 UTC, xedin requested changes
I left a comment inline but we also need a test-case that we can use to make sure that fix-it works correctly for "no arguments" case.

2024-10-29 21:03 UTC, xedin commented on lib/Sema/CSDiagnostics.cpp
> +        return false;
I think this is too drastic. If there are no parens we can still produce a diagnostic and suggest a fix-it. The diagnostic can be attached to the end of the "fn" - `fnExpr->getEndLoc()` and suggest adding parens.

2024-10-31 01:57 UTC, JanBaig commented
@swift-ci please test

2024-10-31 18:50 UTC, xedin approved these changes

2024-10-31 21:32 UTC, xedin commented
@swift-ci please test

2024-11-01 16:09 UTC, xedin commented
@swift-ci please test Windows platform

2024-11-01 22:12 UTC, merged