Emit reabstraction thunks for implicit conversions between T.TangentType and Optional<T>.TangentType
swiftlang/swift pull request #78076
Opened 2024-12-10 00:47 UTC by asl

Fixes https://github.com/swiftlang/swift/issues/77924

2024-12-10 00:47 UTC, asl commented
@swift-ci Please test

2024-12-10 00:48 UTC, asl commented
Tagging @JaapWijnen

2024-12-10 00:51 UTC, asl commented
@swift-ci Please test

2024-12-10 17:57 UTC, slavapestov requested changes

2024-12-10 22:29 UTC, asl commented
@swift-ci please test

2024-12-10 22:29 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +  // - T.TangentVector to Optional<T>.TangentVector
Factored out into helpers

2024-12-20 18:36 UTC, asl commented
@slavapestov @hamishknight ping

2024-12-30 14:48 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +  auto wrappedVal = B.createStructExtract(loc, input, wrappedValueVar);
I think you'll want to use `emitRValueForStorageLoad` here instead, as that will handle address-only cases, e.g:

```swift
func foo<T>(_ fn: @escaping @differentiable(reverse) (T?) -> Double) {
  let _: @differentiable(reverse) (T) -> Double = fn
}
```

2024-12-30 14:48 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +  if (CanType optionalTy = outputSubstType.getNominalParent(); // `Optional<T>`
`getNominalParent` assumes that `outputSubstType` is a nominal type, we probably ought to check to make sure that's the case before accessing

2024-12-30 14:48 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +  }
I think this would also be worth factoring out, looks copied from `PullbackCloner::Implementation::visitEnumInst`

2025-01-10 01:20 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +  }
Yes, this is unfortunate implementation detail that is exposed. I decided to copy as I have not found good "common" place for both SILGen and differentiation transform. Will check what could be done here.

2025-01-10 01:22 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +#endif
Looks pretty niche and rarely used to get cached in `ASTContext`, no?

2025-01-14 17:05 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +#endif
Saves needing to do the lookup on each emission, and the ASTContext is where we store all the "known decls" the compiler is aware of, so IMO it would be nice for consistency. I don't feel too strongly about that though, the main thing is it really ought to be factored out

2025-01-14 17:07 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +#endif
Yes. Still, what will be good place for this? We need to share code between silgen and mandatory SIL optimizations.

2025-01-14 17:14 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +#endif
The ASTContext should be accessible to both :)

2025-01-14 17:15 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +#endif
Well, yes. Just wanted to be a bit more localized :)

2025-01-18 01:02 UTC, asl commented
@swift-ci please test

2025-01-18 01:05 UTC, asl commented
@hamishknight I believe I addressed all the comments. Also added test for address-only type conversion

2025-01-18 18:15 UTC, asl commented
@swift-ci please test

2025-01-18 18:15 UTC, asl commented
@swift-ci please test

2025-01-18 20:51 UTC, hamishknight approved these changes
Thanks! LGTM modulo a couple of nits, but nothing blocking

2025-01-18 20:51 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +      /*isImplicitUnwrap*/ true, getTypeLowering(wrappedType), ctxt);
This should be using `optionalOfWrappedTanType` I think, not that it currently matters since it's unused by `emitCheckedGetOptionalValueFrom`

```suggestion
      /*isImplicitUnwrap*/ true, getTypeLowering(optionalOfWrappedTanType), ctxt);
```

2025-01-18 20:51 UTC, hamishknight commented on lib/SILGen/SILGenPoly.cpp
> +                                               Type(), SGFContext());
I think this ought to be able to use the passed `SGFContext`

```suggestion
                                               Type(), ctxt);
```

2025-01-20 01:46 UTC, asl commented on lib/SILGen/SILGenPoly.cpp
> +      /*isImplicitUnwrap*/ true, getTypeLowering(wrappedType), ctxt);
Oh, right, nice catch!

2025-01-20 02:18 UTC, asl commented
@swift-ci please test

2025-01-21 19:34 UTC, asl commented
Let's check if CI is healthy on `main` again
@swift-ci please test

2025-01-21 20:53 UTC, asl commented
@swift-ci please test linux

2025-01-21 21:29 UTC, asl commented
@slavapestov Please let me know if you're having further comments here, or if this PR is good to go

2025-01-24 18:01 UTC, asl commented
@swift-ci please test

2025-01-31 06:03 UTC, asl commented
@swift-ci please test

2025-01-31 06:06 UTC, asl commented
@slavapestov will you please take a look when you will have a chance?

2025-02-05 18:17 UTC, slavapestov approved these changes
Sorry, I didn't get notifications about your pings for some reason.

2025-02-05 18:17 UTC, slavapestov commented on lib/AST/ASTContext.cpp
> +#ifdef NDEBUG
For future PRs: we're trying to get away from conditional asserts. Instead, use `ASSERT` and avoid `#ifdef NDEBUG`

2025-02-05 21:39 UTC, asl commented on lib/AST/ASTContext.cpp
> +#ifdef NDEBUG
Ah ok, wasn't aware of this, thanks!

2025-02-05 21:39 UTC, asl commented
@swift-ci please smoke check

2025-02-05 21:40 UTC, asl commented
@swift-ci please smoke test

2025-02-06 04:57 UTC, merged