Bump ninja to 1.12.1 to fix Python 3.13 build error
swiftlang/swift pull request #78240
Opened 2024-12-17 15:00 UTC by MaxDesiatov

New version of ninja includes https://github.com/ninja-build/ninja/issues/2471, which allows building Swift when Python 3.13 is installed

2024-12-17 15:01 UTC, MaxDesiatov commented
@swift-ci test

2024-12-17 15:01 UTC, MaxDesiatov commented
@swift-ci build toolchain

2024-12-17 15:59 UTC, compnerd approved these changes
@etcwilde do you remember if this was the version of ninja that occasionally had flakes?

2024-12-17 17:21 UTC, etcwilde requested changes

2024-12-17 17:21 UTC, etcwilde commented on utils/update_checkout/update-checkout-config.json
> +                "ninja": "v1.12.1",
There's a bug in 1.12+ that results in dependencies not always rebuilding correctly. I haven't been able to fully investigate, but we should not do this until we know what is happening and have a fix.

2025-01-04 22:19 UTC, bc-lee commented
I agree that we need to replace the existing `pipes.quote` in Ninja to address the incompatibilities with Python 3.13.  

If upgrading the Ninja version is not feasible at this time, perhaps the Swift community forking [https://github.com/ninja-build/ninja](https://github.com/ninja-build/ninja) and applying the necessary changes to the forked repository could be a viable solution. 
. Specifically, we could cherry-pick commit [9cf13cd1ecb7ae649394f4133d121a01e191560b](https://github.com/ninja-build/ninja/commit/9cf13cd1ecb7ae649394f4133d121a01e191560b) to resolve the issue. (For context, I authored that commit.)

2026-01-05 11:50 UTC, MaxDesiatov commented
Closing as we're already on ninja 1.13.1.

2026-01-05 11:50 UTC, closed without merging