Diagnose unavailability and deprecation only with a valid SourceRange
swiftlang/swift pull request #7919
Opened 2017-03-05 19:43 UTC by CodaFi

Typechecking walks a bit too far into external declarations to diagnose their unavailability when using the SDK.  This may be desirable in some circumstances, so for now I've only disabled the diagnostic when there is no applicable source range to diagnose at.

Resolves [SR-4162](https://bugs.swift.org/browse/SR-4162) and rdar://30480908

2017-03-05 19:43 UTC, CodaFi commented
@swift-ci please smoke test

2017-03-05 19:59 UTC, jtbandes commented
Do you know why `cacheParamsComputed`, `memoryless`, etc. were triggered in particular? Why are decls having their availability diagnosed when they were not referenced in the program?

2017-03-05 20:21 UTC, CodaFi commented
They are being referenced somewhere (we're building and diagnosing DeclRefExprs), but I can't know for sure where without digging into the Clang Importer.

2017-03-06 16:39 UTC, jrose-apple requested changes
The unavailability is #6990, but the deprecations are something else. I'd rather not just squelch the warning.

(Also, the test is way too hard-coded. I suspect none of those messages come up anyway because you're using the mock SDK, but even if you weren't it still wouldn't be something to check in because we have no control over those headers.)

2017-03-06 18:11 UTC, CodaFi commented
@jrose-apple You're right about the test.

The initializer for NSImageRep's internal flags structure is referencing deprecated field bits and the type checker is taking notice.  It seems appropriate to squash the error in that case - it's irrelevant and unfixable by the user, and AppKit most likely needs it for backwards compatibility.  Unless there's importer magic that can be applied here.

2017-03-06 18:38 UTC, CodaFi commented
Come to think of it, I could also extend the precondition that bails if we're already inside a deprecated declaration to check if we're in a private context too.

2017-03-17 23:40 UTC, jrose-apple commented
I definitely wouldn't want unavailability to slip through—that could lead to errors down the line. I don't really know what to do about the deprecations, but I guess it's better to silence them at this point if we don't have an alternative.

2017-04-25 04:49 UTC, slavapestov commented
What's the current status of this PR?

2017-04-25 13:27 UTC, CodaFi commented
It needs changes that I don't have time to focus on at the moment.  Closing for now.

2017-04-25 13:27 UTC, closed without merging

2017-10-08 05:49 UTC, hlovatt commented
I am getting the 'cache...' depreciated warnings on Version 9.1 beta (9B37), wasn't getting the warnings on 9.0.