[stdlib] [SR-4005] Allow heterogenous comparisons in elementsEqual
swiftlang/swift pull request #8045
Opened 2017-03-13 11:14 UTC by Cbieniak

When supplying a predicate to compare, type equivalence of the two sequences are not necessary

Resolves [SR-4005](https://bugs.swift.org/browse/SR-4005).

2017-03-13 11:16 UTC, Cbieniak commented
@swift-ci Please smoke test

2017-03-13 23:33 UTC, jrose-apple commented on stdlib/public/core/SequenceAlgorithms.swift.gyb
>      OtherSequence.${GElement} == ${GElement} {
@nkcsgexi It is concerning that the change in the generic requirements was not caught by swift-api-digester.

2017-04-21 13:11 UTC, airspeedswift commented
@swift-ci Please test

2017-04-21 17:53 UTC, nkcsgexi commented on stdlib/public/core/SequenceAlgorithms.swift.gyb
>      OtherSequence.${GElement} == ${GElement} {
Right, the diff tool is not comparing generic requirements now.

2017-04-21 23:45 UTC, airspeedswift requested changes
Could you add some changes to test some comparisons of different element types using a closure? (for example, comparing `["0","1","2"]` to `0..<4`)

2017-05-12 05:25 UTC, Cbieniak commented
@airspeedswift I've written a couple comparing the string version of ints being converted. Is this appropriate?

2017-06-05 04:47 UTC, Cbieniak commented
@swift-ci Please test

2017-06-05 16:44 UTC, jrose-apple commented
@swift-ci Please test

2017-06-05 16:44 UTC, jrose-apple commented
@swift-ci Please test source compatibility

2017-06-06 07:54 UTC, Cbieniak commented
@jrose-apple thanks for the review. The only error I could see in the linux build was 

```TestFoundation/TestNSURLSession.swift:245: error: TestURLSession.test_downloadTaskWithURLAndHandler : XCTAssertEqual failed: ("cannotConnectToHost") is not equal to ("timedOut") - Unexpected error code```

my best guess would be that its an issue with the linux instance rather than the pr, Should we just rerun the tests or did you have advice on how id go about fixing this?

2017-06-07 20:51 UTC, jrose-apple commented
Ah, yeah, seems unlikely. Let's try again.

(This still isn't a review, though. @airspeedswift needs to accept the new version.)

@swift-ci Please test Linux platform

2017-10-02 22:28 UTC, airspeedswift approved these changes

2017-10-02 22:28 UTC, airspeedswift commented
@swift-ci please test and merge

2017-10-02 22:33 UTC, jrose-apple commented
@swift-ci Please test source compatibility

2017-10-02 23:08 UTC, airspeedswift commented
Oops, thanks @jrose. Tho it'd be pretty weird if this caused anything to fail.

2017-10-02 23:08 UTC, airspeedswift commented
@swift-ci please clean test linux platform

2017-10-02 23:57 UTC, jrose-apple commented
The compat suite failures are in AsyncNinja, which we think is due to Pavel's recent change. Not related to this commit.

2017-10-03 22:42 UTC, airspeedswift commented
Hi @Cbieniak – sorry, looks like I just caused a conflict with another commit. Could you rebase and hopefully we can land this? Thanks!

2017-10-04 10:51 UTC, Cbieniak commented
@airspeedswift No worries at all mate.

2017-10-05 19:53 UTC, airspeedswift commented
@swift-ci please test

2017-10-05 19:53 UTC, airspeedswift commented
@swift-ci please smoke test compiler performance

2017-10-05 19:53 UTC, airspeedswift commented
@swift-ci please test source compatibility

2017-10-06 18:55 UTC, airspeedswift commented
Ah. Looks like one of the hardcoded tests that check completion needs tweaking.

2017-11-07 18:47 UTC, airspeedswift commented
@swift-ci please test

2017-11-08 02:36 UTC, Cbieniak commented
Looks like an issue with the complete_from_stdlib.swift. Ill fix it when I get a chance

2017-11-08 21:04 UTC, airspeedswift commented
Thanks @Cbieniak!

2017-11-28 09:29 UTC, Cbieniak commented
Should be all sorted now

2017-11-29 21:45 UTC, airspeedswift commented
@swift-ci please test

2017-11-30 01:05 UTC, airspeedswift commented
@swift-ci please test macOS platform

2017-11-30 01:06 UTC, merged