[WIP] [Syntax] Refactor Tuple Type Syntax
swiftlang/swift pull request #8254
Opened 2017-03-21 22:48 UTC by harlanhaskins

This patch:

- Refactors `TypeArgumentListSyntax` and
  `TypeArgumentListSyntaxData` to use the `SyntaxCollection` and
  `SyntaxCollectionData` APIs.
- Refactors `TupleTypeElementSyntax` to own its trailing comma and
  updates the tests accordingly.
- Provides an infrastructure for promoting types to use
  the `SyntaxCollection` APIs

Still needs to be done:

- Rework `TypeArgumentList` as `TupleTypeElementList`
- Update `LegacyASTTransformer` and ensure those round-trip tests work.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

2017-03-21 22:50 UTC, harlanhaskins commented
@swift-ci please smoke test

2017-03-21 22:58 UTC, bitjammer requested changes
Fantastic, well done. Just a couple of small suggestions above.

2017-03-21 22:58 UTC, bitjammer commented on include/swift/Syntax/SyntaxFactory.h
> +  makeTupleTypeElement(RC<TokenSyntax> Name, TypeSyntax ElementType,
I think we'll need a colon argument here won't we?

2017-03-21 22:58 UTC, bitjammer commented on include/swift/Syntax/SyntaxFactory.h
> +  makeTupleType(llvm::ArrayRef<TupleTypeElementSyntax> Types);
I think we'll need paren arguments here to, so folks can customize leading and trailing trivia on the left and right paren, respectively.

2017-03-21 22:58 UTC, bitjammer commented on include/swift/Syntax/SyntaxKinds.def
> +SYNTAX_COLLECTION(TypeArgumentList, TupleTypeElementSyntax)
s/TypeArgumentList/TupleTypeElementList/g, if you don't mind!

2017-03-21 22:58 UTC, bitjammer commented on include/swift/Syntax/SyntaxKinds.def
> +SYNTAX_COLLECTION(TypeArgumentList, TupleTypeElementSyntax)
(This is to match TSPL's terminology)

2017-03-21 22:58 UTC, bitjammer commented
Are you planning to look at LegacyASTTransformer visitor methods for `TupleTypeRepr`?

2017-03-21 22:59 UTC, harlanhaskins commented on include/swift/Syntax/SyntaxFactory.h
> +  makeTupleType(llvm::ArrayRef<TupleTypeElementSyntax> Types);
👍

2017-03-21 23:10 UTC, harlanhaskins commented on include/swift/Syntax/SyntaxFactory.h
> +  makeTupleTypeElement(RC<TokenSyntax> Name, TypeSyntax ElementType,
👍

2017-03-21 23:11 UTC, harlanhaskins commented on include/swift/Syntax/SyntaxKinds.def
> +SYNTAX_COLLECTION(TypeArgumentList, TupleTypeElementSyntax)
👍 This reveals an issue with the `FunctionTypeSyntax` that means it'll need its own `ElementSyntax` and collection.

2017-03-21 23:11 UTC, harlanhaskins commented
Yep! I'm going to address that after addressing these comments.

2017-03-21 23:12 UTC, harlanhaskins commented
@swift-ci please smoke test

2017-03-21 23:49 UTC, harlanhaskins commented
@swift-ci please test

2017-03-22 02:12 UTC, harlanhaskins commented
@swift-ci please smoke test

2017-03-22 02:16 UTC, harlanhaskins commented
@swift-ci please smoke test

2017-03-22 02:40 UTC, harlanhaskins commented
@swift-ci please smoke test

2017-03-22 08:21 UTC, bitjammer approved these changes

2017-03-22 08:23 UTC, bitjammer commented
Just amazing. Thanks!

2017-03-22 12:02 UTC, merged