Enable The Optional Sanitizer (by default)
swiftlang/swift pull request #8481
Opened 2017-04-01 17:01 UTC by CodaFi

Suffer no longer under the silent tyranny of the force-unwrap!

The Optional Sanitizer is a revolutionary new tool that allows
developers to gain enhanced insight into the inner workings of their
programs.  Traditional debugging techniques rely on a boring terminal
with text scrolling by, and a thousand commands that you need to
remember.  Instead, we have simplified the process of debugging down
to, what we see as, the most unused sense when programming: The ears.

That’s right, now you can hear your program as it executes! No longer
will you have to struggle with the debugger, now every optional
force-unwrap can grate on your senses with the ease and simplicity that
only Apple can provide.

Tooling is also highly accessible.  To those that wish to get all the
benefits of OSan, but may not be able to experience the aural sensation to its
fullest extent, we provide a visual OSan that is enabled by passing
`-Xfrontend -visual-osan-unwrap-instrumentation`

*A future patch will enable the ability to disable OSan.

2017-04-01 17:19 UTC, CodaFi commented
`<unfools>` (For the love of god, don't trigger CI) `</unfools>`

2017-04-01 19:31 UTC, dabrahams commented
+1, but the standard alert sound is insufficiently annoying. Please provide a custom nails-on-chalkboard sound

2017-04-01 19:39 UTC, CodaFi commented
@gparker42 Would it be alright if I embedded the nails-on-chalkboard m4a into the runtime and shell out to iTunes?

2017-04-01 21:30 UTC, harlanhaskins commented
[libc shells out to perl](https://github.com/Apple-FOSS-Mirror/Libc/blob/2ca2ae74647714acfc18674c3114b1a5d3325d7d/gen/wordexp.c#L192), so I think that's fair.

2017-04-01 22:24 UTC, zisko commented
I'm keeping this patch around in case @shahmishal gets locked in the lab

2017-04-02 02:44 UTC, devincoughlin commented
This is awesome. Made my day.

2017-04-02 10:04 UTC, hughbe requested changes

2017-04-02 10:04 UTC, hughbe commented on stdlib/public/runtime/Errors.cpp
> +      Swift_Framework_Token = dlopen("/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox", RTLD_FIRST);
I'd love to bring such an important feature to Windows. This is too platform specific :'(

2017-04-02 17:20 UTC, closed without merging