[sil-function-signature-opt] Support FSO for generic functions
swiftlang/swift pull request #8489
Opened 2017-04-02 22:44 UTC by swiftix

In particular, support the following optimizations:
- owned-to-guaranteed
- dead argument elimination

Argument explosion is disabled for generics at the moment as it usually leads to a slower code.

rdar://26268241

2017-04-02 22:44 UTC, swiftix commented
@swift-ci please test

2017-04-02 22:45 UTC, swiftix commented
@swift-ci please benchmark

2017-04-03 06:02 UTC, swiftix commented
@swift-ci please test

2017-04-03 06:03 UTC, swiftix commented
@swift-ci please test

2017-04-03 06:04 UTC, swiftix commented
@swift-ci please benchmark

2017-04-03 06:05 UTC, swiftix commented
@swift-ci please benchmark

2017-04-03 16:48 UTC, swiftix commented
@eeckstein Since it touches the FSO, could you have a look?
@gottesmm It touches ARCAnalysis. I'm pretty confident about the change, but may be you want to have a quick look?

2017-04-03 17:37 UTC, eeckstein requested changes
I'm not sure I understood all the FSO changes, but overall it looks good.
The only thing is that you really need to add tests for all the new features you added to FSO.

2017-04-03 17:37 UTC, eeckstein commented on lib/SILOptimizer/Analysis/ARCAnalysis.cpp
> +    else if (!isa<ReleaseValueInst>(*II) && !isa<StrongReleaseInst>(*II)) {
"else" is not needed after continue

2017-04-03 17:37 UTC, eeckstein commented on test/SILOptimizer/functionsigopts.sil
> +
FSO needs much more tests. You should test everything you support in the new FSO. As I understood this includes
*) @in -> @in_guaranteed conversion
*) completely eliminating all generic args, making the function non-generic

2017-04-04 18:12 UTC, swiftix commented on test/SILOptimizer/functionsigopts.sil
> +
I pushed a new version with more tests. Looks better now?

2017-04-04 18:12 UTC, swiftix commented
@swift-ci please test

2017-04-04 18:12 UTC, swiftix commented
@swift-ci please test

2017-04-04 18:19 UTC, eeckstein commented on test/SILOptimizer/functionsigopts.sil
> +// CHECK-LABEL: sil hidden [noinline] @_T027generic_owned_to_guaranteedTf4g_n : $@convention(thin) <T where T : KlassFoo> (@guaranteed T) -> Int64
Can you also check the body of the specialized functions? E.g. check that the destroy_value was eliminated?

Otherwise LGTM!

2017-04-04 18:22 UTC, swiftix commented on test/SILOptimizer/functionsigopts.sil
> +// CHECK-LABEL: sil hidden [noinline] @_T027generic_owned_to_guaranteedTf4g_n : $@convention(thin) <T where T : KlassFoo> (@guaranteed T) -> Int64
Sure. Will do!

2017-04-04 19:33 UTC, swiftix commented on test/SILOptimizer/functionsigopts.sil
> +// CHECK-LABEL: sil hidden [noinline] @_T027generic_owned_to_guaranteedTf4g_n : $@convention(thin) <T where T : KlassFoo> (@guaranteed T) -> Int64
I added the required checks

2017-04-04 19:40 UTC, eeckstein approved these changes

2017-04-04 19:40 UTC, swiftix commented
@swift-ci please test

2017-04-04 19:41 UTC, swiftix commented
@swift-ci please benchmark

2017-04-04 19:43 UTC, swiftix commented
@swift-ci please benchmark

2017-04-04 19:45 UTC, gottesmm commented
@swiftix Just confirming, I am going to review your changes post-commit

2017-04-05 00:05 UTC, swiftix commented
@swift-ci please test Linux

2017-04-05 00:47 UTC, merged

2017-04-05 01:41 UTC, slavapestov commented
Nice performance wins here.