Bump Swift version to 4.0
swiftlang/swift pull request #8861
Opened 2017-04-19 18:48 UTC by tkremenek

2017-04-19 18:48 UTC, tkremenek commented
@swift-ci clean test

2017-04-19 19:18 UTC, tkremenek commented
@swift-ci clean test

2017-04-19 19:24 UTC, erg commented
@tkremenek The other place to change is in ``build-script``:

```python
    parser.add_argument(
        "--swift-user-visible-version",
        help="User-visible version of the embedded Swift compiler",
        type=arguments.type.swift_compiler_version,
        default="3.1", # change to 4.0
        metavar="MAJOR.MINOR")
```

Note: The ``build-script-impl`` version flag was made into dead code by a refactoring to python by someone else months ago, but I only removed it last week upon discovering it was dead.

2017-04-19 20:02 UTC, tkremenek commented
@swift-ci clean test

2017-04-19 20:13 UTC, jrose-apple requested changes
For now, we need to continue building the standard library and overlays with Swift 3 as well.

2017-04-20 04:28 UTC, dabrahams commented
on Wed Apr 19 2017, Jordan Rose <notifications-AT-github.com> wrote:

> For now, we need to continue building the standard library and
> overlays with Swift 3 as well.

That's a little alarming to hear; we've been under the impression that
we could switch to building the standard library in Swift 4 mode
whenever we want.  Please explain why not, and when we can expect to be
able to flip the switch.

Thanks,
-Dave

2017-04-20 04:38 UTC, tkremenek commented
@dabrahams makes a good point.  The intent is we want the Standard Library and overlays building in Swift 4 mode.

2017-04-20 04:46 UTC, tkremenek commented
@DougGregor reminded me offline that the Standard Library/overlays can vend Swift 4 changes with `@available` markup.  Let's review outside this PR whether we need to build these libraries in Swift 4 mode.

2017-04-20 04:58 UTC, tkremenek commented
@swift-ci clean test

2017-04-20 05:36 UTC, tkremenek commented
@swift-ci test linux

2017-04-20 06:34 UTC, tkremenek commented
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/956

@swift-ci test linux

2017-04-20 07:17 UTC, tkremenek commented
Please test with following pull request:
apple/swift-corelibs-xctest#188
apple/swift-corelibs-foundation#956

@swift-ci test linux

2017-04-20 07:35 UTC, tkremenek commented
Build failure is now in SwiftPM.  I've reached out to @ddunbar to see how to force SwiftPM to build with `-swift-version 3` for now.

2017-04-20 07:35 UTC, tkremenek commented
@swift-ci smoke test macOS

2017-04-20 08:11 UTC, tkremenek commented
@aciidb0mb3r provided a PR for SwiftPM:

https://github.com/apple/swift-package-manager/pull/1109

2017-04-20 08:11 UTC, tkremenek commented
Please test with following pull request:
apple/swift-corelibs-xctest#188
apple/swift-corelibs-foundation#956
apple/swift-package-manager#1109

@swift-ci test linux

2017-04-20 08:12 UTC, tkremenek commented
Failing tests on macOS that probably need `-swift-version 3`:

~~~
Failing Tests (15):
    Swift(macosx-x86_64) :: attr/attr_dynamic_infer.swift
    Swift(macosx-x86_64) :: attr/attr_objc_clang.swift
    Swift(macosx-x86_64) :: Serialization/Recovery/crash-recovery.swift
    Swift(macosx-x86_64) :: IDE/crashers_2/0010-reference-to-self-in-extension-init.swift
    Swift(macosx-x86_64) :: IDE/crashers_2/0011-complete-protocol-with-initializer.swift
    Swift(macosx-x86_64) :: Serialization/rdar29694978.swift
    Swift(macosx-x86_64) :: Driver/swift-version-default.swift
    Swift(macosx-x86_64) :: IDE/complete_crashes.swift
    Swift(macosx-x86_64) :: IDE/complete_dynamic_lookup.swift
    Swift(macosx-x86_64) :: IDE/complete_func_reference.swift
    Swift(macosx-x86_64) :: IDE/complete_stdlib_optional.swift
    Swift(macosx-x86_64) :: IDE/local_types.swift
    Swift(macosx-x86_64) :: IDE/merge_local_types.swift
    Swift(macosx-x86_64) :: IDE/print_usrs.swift
    Swift(macosx-x86_64) :: IDE/range_info_basics.swift
~~~

2017-04-20 08:26 UTC, tkremenek commented
Failing tests on Linux:

~~~
01:24:23 Failing Tests (55):
01:24:23     Swift(linux-x86_64) :: compiler_crashers_2_fixed/0041-walkToDeclPost-crash.swift
01:24:23     Swift(linux-x86_64) :: stdlib/Renames.swift
01:24:23     Swift(linux-x86_64) :: SILGen/properties.swift
01:24:23     Swift(linux-x86_64) :: Sema/complex_expressions.swift
01:24:23     Swift(linux-x86_64) :: Serialization/class-roundtrip-module.swift
01:24:23     Swift(linux-x86_64) :: Serialization/class.swift
01:24:23     Swift(linux-x86_64) :: SILGen/guaranteed_self.swift
01:24:23     Swift(linux-x86_64) :: SILGen/closures.swift
01:24:23     Swift(linux-x86_64) :: IDE/complete_stdlib_optional.swift
01:24:23     Swift(linux-x86_64) :: Constraints/diagnostics.swift
01:24:23     Swift(linux-x86_64) :: Constraints/closures.swift
01:24:23     Swift(linux-x86_64) :: compiler_crashers_fixed/26813-generic-enum-tuple-optional-payload.swift
01:24:23     Swift(linux-x86_64) :: compiler_crashers_2_fixed/0034-rdar21982453.swift
01:24:23     Swift(linux-x86_64) :: Sema/type_checker_crashers_fixed/rdar27261929.swift
01:24:23     Swift(linux-x86_64) :: IDE/crashers_2/0010-reference-to-self-in-extension-init.swift
01:24:23     Swift(linux-x86_64) :: IDE/crashers_2/0011-complete-protocol-with-initializer.swift
01:24:23     Swift(linux-x86_64) :: expr/postfix/dot/init_ref_delegation.swift
01:24:23     Swift(linux-x86_64) :: decl/subscript/subscripting.swift
01:24:23     Swift(linux-x86_64) :: decl/protocol/req/optional.swift
01:24:23     Swift(linux-x86_64) :: expr/closure/single_expr.swift
01:24:23     Swift(linux-x86_64) :: expr/closure/closures.swift
01:24:23     Swift(linux-x86_64) :: expr/closure/anonymous.swift
01:24:23     Swift(linux-x86_64) :: decl/func/default-values.swift
01:24:23     Swift(linux-x86_64) :: decl/class/override.swift
01:24:23     Swift(linux-x86_64) :: attr/attr_dynamic_infer.swift
01:24:23     Swift(linux-x86_64) :: attr/attr_dynamic.swift
01:24:23     Swift(linux-x86_64) :: Serialization/struct.swift
01:24:23     Swift(linux-x86_64) :: Serialization/objc.swift
01:24:23     Swift(linux-x86_64) :: SILGen/tuples.swift
01:24:23     Swift(linux-x86_64) :: SILGen/property_abstraction.swift
01:24:23     Swift(linux-x86_64) :: SILGen/partial_apply_generic.swift
01:24:23     Swift(linux-x86_64) :: SILGen/nested_types_referencing_nested_functions.swift
01:24:23     Swift(linux-x86_64) :: SILGen/metatype_abstraction.swift
01:24:23     Swift(linux-x86_64) :: SILGen/existential_metatypes.swift
01:24:23     Swift(linux-x86_64) :: SILGen/function_conversion.swift
01:24:23     Swift(linux-x86_64) :: SILGen/generic_closures.swift
01:24:23     Swift(linux-x86_64) :: SILGen/dynamic_self.swift
01:24:23     Swift(linux-x86_64) :: SILGen/apply_abstraction_nested.swift
01:24:23     Swift(linux-x86_64) :: Misc/expression_too_complex.swift
01:24:23     Swift(linux-x86_64) :: IRGen/existential_nested_type.swift
01:24:23     Swift(linux-x86_64) :: IDE/range_info_basics.swift
01:24:23     Swift(linux-x86_64) :: IDE/print_usrs.swift
01:24:23     Swift(linux-x86_64) :: IDE/local_types.swift
01:24:23     Swift(linux-x86_64) :: IDE/merge_local_types.swift
01:24:23     Swift(linux-x86_64) :: IDE/complete_func_reference.swift
01:24:23     Swift(linux-x86_64) :: IDE/complete_crashes.swift
01:24:23     Swift(linux-x86_64) :: Generics/deduction.swift
01:24:23     Swift(linux-x86_64) :: Driver/swift-version-default.swift
01:24:23     Swift(linux-x86_64) :: DebugInfo/WeakCapture.swift
01:24:23     Swift(linux-x86_64) :: DebugInfo/closure-arg-linetable.swift
01:24:23     Swift(linux-x86_64) :: DebugInfo/nostorage.swift
01:24:23     Swift(linux-x86_64) :: Constraints/diag_ambiguities.swift
01:24:23     Swift(linux-x86_64) :: Constraints/tuple.swift
01:24:23     Swift(linux-x86_64) :: Compatibility/attr_escaping.swift
01:24:23     Swift(linux-x86_64) :: ClangImporter/ctypes_parse.swift
01:24:23 
~~~

2017-04-20 15:45 UTC, jrose-apple commented
Hm. lit is supposed to be passing -swift-version explicitly to any test using most of the standard substitutions. A few of these might be deliberately bypassing that, and Driver/swift-version-default.swift is deliberately trying to test the very thing being changed.

2017-04-20 15:46 UTC, jrose-apple commented on cmake/modules/SwiftSource.cmake
> +  if (SWIFTFILE_IS_STDLIB OR SWIFTFILE_IS_SDK_OVERLAY)
Which files don't fit into either of these categories? Things like StdlibUnittest?

2017-04-20 16:47 UTC, tkremenek commented
Some of the tests that are failing use  `%target-swift-ide-test`.  I do not believe that lit passing `-swift-version 3` to those.

2017-04-20 16:53 UTC, jrose-apple commented
Ah, good catch. It probably should.

2017-04-20 21:06 UTC, slavapestov commented
@dabrahams The standard library needs some minor updates to build in Swift 4 mode, due to the tuple argument changes.

@tkremenek Can you file a bug with the compiler crashers that regressed in Swift 4 mode? They should be rice instead of just passing -swift-version 3.

2017-04-20 21:09 UTC, jrose-apple commented
@slavapestov We're supposed to be running all the tests under Swift 3 unless the test opts out of that. You can pass "--param swift_version=4" to lit.py to see them running under Swift 4.

2017-04-23 05:21 UTC, tkremenek commented
@swift-ci clean test

2017-04-23 06:37 UTC, tkremenek commented
Please test with following pull request:
https://github.com/apple/swift-xcode-playground-support/pull/14

@swift-ci test macOS

2017-04-24 05:28 UTC, tkremenek commented
Please test with following pull request:
apple/swift-xcode-playground-support#14

@swift-ci test macOS

2017-04-24 16:13 UTC, jrose-apple commented on test/IDE/complete_crashes.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -code-completion -source-filename %s -code-completion-token=BAD_MEMBERS_1 | %FileCheck %s -check-prefix=BAD_MEMBERS_1
Instead of doing this, can you put `-swift-version 3` into the substitution for %target-swift-ide-test like it is for %target-build-swift?

2017-04-24 16:20 UTC, tkremenek commented on test/IDE/complete_crashes.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -code-completion -source-filename %s -code-completion-token=BAD_MEMBERS_1 | %FileCheck %s -check-prefix=BAD_MEMBERS_1
I tried that and it felt a bit wrong.  Some of these tests will simply not work in both language modes.   I only updated the tests that would not build with the new language default.   That said, I can see the reason why we would want to do it the way you propose so we have the option to run all tests in one mode or the other.

2017-04-24 17:09 UTC, jrose-apple commented on test/IDE/complete_crashes.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -code-completion -source-filename %s -code-completion-token=BAD_MEMBERS_1 | %FileCheck %s -check-prefix=BAD_MEMBERS_1
Whatever we do should be consistent, I think. As long as the swiftc tests are building with -swift-version 3, the swift-ide-test ones should too. Later on we can split up tests that actually should behave differently in Swift 4 mode.

2017-04-24 17:53 UTC, tkremenek commented on test/IDE/complete_crashes.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -code-completion -source-filename %s -code-completion-token=BAD_MEMBERS_1 | %FileCheck %s -check-prefix=BAD_MEMBERS_1
Makes sense to me.

2017-04-25 23:22 UTC, tkremenek commented
@swift-ci clean test

2017-04-25 23:33 UTC, jrose-apple approved these changes
Looks pretty good (assuming all our other projects build successfully). Only minor test changes left.

2017-04-25 23:33 UTC, jrose-apple commented on validation-test/IDE/crashers_2/0010-reference-to-self-in-extension-init.swift
> +// RUN: not --crash %target-swift-ide-test -swift-version 3 -code-completion -code-completion-token=A -source-filename=%s
This should be implicit now.

2017-04-25 23:33 UTC, jrose-apple commented on validation-test/IDE/crashers_2/0011-complete-protocol-with-initializer.swift
> +// RUN: not --crash %target-swift-ide-test -swift-version 3 -code-completion -code-completion-token=A -source-filename=%s
This should be implicit now. (Thank you!)

2017-04-25 23:33 UTC, jrose-apple commented on validation-test/Serialization/rdar29694978.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -print-module -module-to-print=Library -source-filename=x -I %S/Inputs/ -I %t | %FileCheck %s
These should be implicit now.

2017-04-25 23:41 UTC, tkremenek commented on validation-test/Serialization/rdar29694978.swift
> +// RUN: %target-swift-ide-test -swift-version 3 -print-module -module-to-print=Library -source-filename=x -I %S/Inputs/ -I %t | %FileCheck %s
@jrose-apple good catch; forgot those.  I'm re-running my tests locally with those reverted.

2017-04-26 14:40 UTC, tkremenek commented
@swift-ci test macOS

2017-04-26 14:41 UTC, tkremenek commented
Linux still has a bunch of failures that do not show up on macOS:

~~~
17:01:16 Failing Tests (46):
17:01:16     Swift(linux-x86_64) :: Serialization/Recovery/typedefs.swift
17:01:16     Swift(linux-x86_64) :: Constraints/diagnostics.swift
17:01:16     Swift(linux-x86_64) :: ClangImporter/ctypes_parse.swift
17:01:16     Swift(linux-x86_64) :: compiler_crashers_fixed/26813-generic-enum-tuple-optional-payload.swift
17:01:16     Swift(linux-x86_64) :: compiler_crashers_2_fixed/0041-walkToDeclPost-crash.swift
17:01:16     Swift(linux-x86_64) :: compiler_crashers_2_fixed/0034-rdar21982453.swift
17:01:16     Swift(linux-x86_64) :: Sema/type_checker_crashers_fixed/rdar27261929.swift
17:01:16     Swift(linux-x86_64) :: stdlib/Renames.swift
17:01:16     Swift(linux-x86_64) :: expr/postfix/dot/init_ref_delegation.swift
17:01:16     Swift(linux-x86_64) :: expr/closure/single_expr.swift
17:01:16     Swift(linux-x86_64) :: expr/closure/closures.swift
17:01:16     Swift(linux-x86_64) :: expr/closure/anonymous.swift
17:01:16     Swift(linux-x86_64) :: decl/subscript/subscripting.swift
17:01:16     Swift(linux-x86_64) :: decl/protocol/req/optional.swift
17:01:16     Swift(linux-x86_64) :: decl/func/default-values.swift
17:01:16     Swift(linux-x86_64) :: decl/class/override.swift
17:01:16     Swift(linux-x86_64) :: attr/attr_final.swift
17:01:16     Swift(linux-x86_64) :: attr/attr_dynamic.swift
17:01:16     Swift(linux-x86_64) :: Serialization/class-roundtrip-module.swift
17:01:16     Swift(linux-x86_64) :: Serialization/struct.swift
17:01:16     Swift(linux-x86_64) :: Serialization/class.swift
17:01:16     Swift(linux-x86_64) :: Serialization/objc.swift
17:01:16     Swift(linux-x86_64) :: Sema/complex_expressions.swift
17:01:16     Swift(linux-x86_64) :: SILGen/property_abstraction.swift
17:01:16     Swift(linux-x86_64) :: SILGen/properties.swift
17:01:16     Swift(linux-x86_64) :: SILGen/tuples.swift
17:01:16     Swift(linux-x86_64) :: SILGen/partial_apply_generic.swift
17:01:16     Swift(linux-x86_64) :: SILGen/nested_types_referencing_nested_functions.swift
17:01:16     Swift(linux-x86_64) :: SILGen/metatype_abstraction.swift
17:01:16     Swift(linux-x86_64) :: SILGen/function_conversion.swift
17:01:16     Swift(linux-x86_64) :: SILGen/generic_closures.swift
17:01:16     Swift(linux-x86_64) :: SILGen/guaranteed_self.swift
17:01:16     Swift(linux-x86_64) :: SILGen/existential_metatypes.swift
17:01:16     Swift(linux-x86_64) :: SILGen/closures.swift
17:01:16     Swift(linux-x86_64) :: SILGen/dynamic_self.swift
17:01:16     Swift(linux-x86_64) :: SILGen/apply_abstraction_nested.swift
17:01:16     Swift(linux-x86_64) :: Misc/expression_too_complex.swift
17:01:16     Swift(linux-x86_64) :: IRGen/existential_nested_type.swift
17:01:16     Swift(linux-x86_64) :: Generics/deduction.swift
17:01:16     Swift(linux-x86_64) :: DebugInfo/nostorage.swift
17:01:16     Swift(linux-x86_64) :: DebugInfo/WeakCapture.swift
17:01:16     Swift(linux-x86_64) :: DebugInfo/closure-arg-linetable.swift
17:01:16     Swift(linux-x86_64) :: Constraints/tuple.swift
17:01:16     Swift(linux-x86_64) :: Compatibility/attr_escaping.swift
17:01:16     Swift(linux-x86_64) :: Constraints/diag_ambiguities.swift
17:01:16     Swift(linux-x86_64) :: Constraints/closures.swift
~~~

2017-04-28 06:14 UTC, tkremenek commented
@swift-ci test

2017-04-28 06:20 UTC, tkremenek commented
@swift-ci clean test

2017-04-28 07:17 UTC, tkremenek commented
@swift-ci test

2017-04-28 13:10 UTC, tkremenek commented
On Linux it looks like we are down to a test failure in swift-corelibs-Foundation:

~~~
TestFoundation/HTTPServer.swift:101:20: error: 'subscript' is unavailable
00:31:25             return str[startIndex..<endIndex]
00:31:25                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
00:31:25 Swift.String:3:12: note: 'subscript' was obsoleted in Swift 4
00:31:25     public subscript(bounds: Range<String.Index>) -> String { get }
00:31:25            ^
00:31:25 
TestFoundation/HTTPServer.swift:101:20: error: 'subscript' is unavailable
00:31:25             return str[startIndex..<endIndex]
00:31:25                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
00:31:25 Swift.String:3:12: note: 'subscript' was obsoleted in Swift 4
00:31:25     public subscript(bounds: Range<String.Index>) -> String { get }
00:31:25            ^
~~~

2017-04-28 13:18 UTC, tkremenek commented
Please test with following pull request:
https://github.com/apple/swift-corelibs-foundation/pull/972

@swift-ci test linux

2017-04-28 13:22 UTC, tkremenek commented
Also seeing on iphoneSimulator:

~~~
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/DebugInfo/ErrorVar.swift:19:12: error: expected string not found in input
01:05:25  // CHECK: ![[ERRTY]] = !DICompositeType({{.*}}identifier: "_T0s5Error_pD"
01:05:25            ^
01:05:25 <stdin>:768:1: note: scanning from here
01:05:25 !90 = !DIExpression(DW_OP_deref)
01:05:25 ^
01:05:25 <stdin>:768:1: note: with variable "ERRTY" equal to "85"
01:05:25 !90 = !DIExpression(DW_OP_deref)
01:05:25 ^
01:05:25 <stdin>:773:3: note: possible intended match here
01:05:25 !95 = !DISubroutineType(types: !96)
01:05:25   ^
01:05:25 
~~~

but this looks like a new, unrelated failure.

2017-04-28 13:56 UTC, tkremenek commented
With:

apple/swift-corelibs-foundation#972

the swift-corelibs-foundation tests pass.  Now I am seeing the following test failure for swift-corelibs-xctest:

~~~
error: expression type 'XCTestCaseEntry' (aka '(testCaseClass: XCTestCase.Type, allTests: Array<(String, (XCTestCase) throws -> ())>)') is ambiguous without more context
06:52:46 XCTMain([testCase(MisuseTestCase.allTests)])
06:52:46          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
06:52:46 
~~~

2017-04-28 14:00 UTC, tkremenek commented
Please test with following pull request:
apple/swift-corelibs-foundation#972
https://github.com/apple/swift-corelibs-xctest/pull/189

@swift-ci test linux

2017-04-28 14:35 UTC, tkremenek commented
@swift-ci clean test

2017-04-28 19:51 UTC, tkremenek commented
I think @adrian-prantl address the `ErrorVar.swift` failure in:

https://github.com/apple/swift/pull/9105

2017-04-28 19:51 UTC, tkremenek commented
@swift-ci test macOS

2017-04-28 21:03 UTC, tkremenek commented
I am seeing new test failures that appear unrelated.  Looks like new breakage on `master`.  Merging.

2017-04-28 21:03 UTC, merged

2017-04-28 23:39 UTC, shajrawi commented
All the linux bots are failing with `static_assert(SWIFT_VERSION_MAJOR == 4` in `swift/lib/Basic/Version.cpp:329`
looking at the build logs I see `  -DSWIFT_VERSION=3.1 -DSWIFT_VERSION_MAJOR=3 -DSWIFT_VERSION_MINOR=1 `

2017-04-28 23:41 UTC, swiftix commented
@shajrawi You need a clean build to get rid of it

2017-04-29 00:00 UTC, tkremenek commented
@shajrawi yeah sorry about that; apparently changing the version in the build-script doesn't reflect as a build dependency.  I've triggered the bots to clean their workspaces.

2017-04-29 03:33 UTC, adrian-prantl commented
AFAIK, this is an inherent limitation of CMake. Once configuration parameters are cached, they can only be reset by removing the CMake cache.

2017-05-02 16:00 UTC, jrose-apple commented
Maybe we *shouldn't* be marking that variable as "CACHE"?