[4.0] Diagnostics for Minimal and Complete Patterns
swiftlang/swift pull request #9151
Opened 2017-05-01 15:26 UTC by CodaFi

Redoes a phase of type checking to validate patterns for minimality and completeness.

Cherry-picked from #8908 and #9121.

2017-05-01 15:26 UTC, CodaFi commented
@swift-ci please test

2017-05-01 16:23 UTC, CodaFi commented
Wow, this cherry-pick was pretty bad.  I'm gonna rebase and try again.

2017-05-01 16:29 UTC, CodaFi commented
@swift-ci please test

2017-05-01 16:29 UTC, CodaFi commented
@swift-ci please test

2017-05-01 17:20 UTC, CodaFi commented
@swift-ci please test source compatibility

2017-05-01 17:20 UTC, CodaFi commented
@swift-ci please test source compatibility

2017-05-01 18:38 UTC, CodaFi commented
@swift-ci please test

2017-05-01 18:38 UTC, CodaFi commented
@swift-ci please test

2017-05-01 19:04 UTC, nkcsgexi requested changes

2017-05-01 19:04 UTC, nkcsgexi commented on include/swift/AST/DiagnosticsSema.def
> +      "%select{:|?}0 %2", (bool, bool, StringRef))
Could you drop the last StringRef? we don't need to duplicate the fixit content.

2017-05-01 19:10 UTC, CodaFi commented on include/swift/AST/DiagnosticsSema.def
> +      "%select{:|?}0 %2", (bool, bool, StringRef))
Ah yeah.  That was leftover from when I thought I could combine these diagnostics.  

Thanks for catching this, I'll shoot a quick pull request over and cherry pick that into here.

2017-05-01 19:12 UTC, nkcsgexi commented on include/swift/AST/DiagnosticsSema.def
> +      "%select{:|?}0 %2", (bool, bool, StringRef))
Fixing on master first will be awesome. Thank you!

2017-05-01 19:14 UTC, CodaFi commented on include/swift/AST/DiagnosticsSema.def
> +      "%select{:|?}0 %2", (bool, bool, StringRef))
Ah yeah.  That was leftover from when I thought I could combine this fixit with the other one. 

Thanks!  I'll shoot a quick pull request over and cherry-pick that in here.

2017-05-03 00:35 UTC, CodaFi commented
Weird: If you force-push at a branch that becomes even with the one you're targeting a pull request at, it closes it.

2017-05-03 00:41 UTC, CodaFi commented
@nkcsgexi These commits are going to be auto-merged anyways, right?  I don't think this PR is necessary.

2017-05-03 00:41 UTC, closed without merging

2017-05-04 00:24 UTC, nkcsgexi commented
@CodaFi it seems they won't be auto-merged to swift-4.0-branch, shall we revive the pull request?